-------------------------------------------------------
-- All items (Leatherworking) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Leatherworking"] then RR_DATA["items"]["Leatherworking"] = {} end
local tbc_items = 
{
	{
		["expansion"] = 2,
		["id"] = 25720,
		["name"] = {
			["Chinese"] = "图样：重结缔皮",
			["English"] = "Pattern: Heavy Knothide Leather",
			["French"] = "Patron : Cuir granuleux lourd",
			["German"] = "Muster: Schweres Knotenhautleder",
			["Korean"] = "도안: 질긴 톱니매듭 가죽",
			["Mexican"] = "Patrón: cuero de pellejo nudoso grueso",
			["Portuguese"] = "Molde: Couro Nodoso Pesado",
			["Russian"] = "Выкройка: толстая узловатая кожа",
			["Spanish"] = "Patrón: cuero de pellejo nudoso grueso",
			["Taiwanese"] = "圖樣:厚重境外皮革",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				16689,
				16748,
				19196,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25721,
		["name"] = {
			["Chinese"] = "图样：守备官的护甲片",
			["English"] = "Pattern: Vindicator's Armor Kit",
			["French"] = "Patron : Renfort d'armure de redresseur de torts",
			["German"] = "Muster: Rüstungsset des Verteidigers",
			["Korean"] = "도안: 구원자의 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura de vindicador",
			["Portuguese"] = "Molde: Kit de Armadura do Vindicante",
			["Russian"] = "Выкройка: накладки для брони воздаятеля",
			["Spanish"] = "Patrón: refuerzo para armadura de vindicador",
			["Taiwanese"] = "圖樣:復仇者護甲片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25722,
		["name"] = {
			["Chinese"] = "图样：魔导师的护甲片",
			["English"] = "Pattern: Magister's Armor Kit",
			["French"] = "Patron : Renfort d'armure de magistère",
			["German"] = "Muster: Rüstungsset des Magisters",
			["Korean"] = "도안: 마법학자의 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura de magister",
			["Portuguese"] = "Molde: Kit de Armadura do Magíster",
			["Russian"] = "Выкройка: накладки для брони магистра",
			["Spanish"] = "Patrón: refuerzo para armadura de magister",
			["Taiwanese"] = "圖樣:博學者護甲片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25725,
		["name"] = {
			["Chinese"] = "图样：马鞭",
			["English"] = "Pattern: Riding Crop",
			["French"] = "Patron : Cravache d'équitation",
			["German"] = "Muster: Reitgerte",
			["Korean"] = "도안: 말채찍",
			["Mexican"] = "Patrón: fusta",
			["Portuguese"] = "Molde: Rebenque",
			["Russian"] = "Выкройка: ездовой хлыст",
			["Spanish"] = "Patrón: fusta",
			["Taiwanese"] = "圖樣:騎乘馬鞭",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				18672,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25726,
		["name"] = {
			["Chinese"] = "图样：鞋垫",
			["English"] = "Pattern: Comfortable Insoles",
			["French"] = "Patron : Semelles confortables",
			["German"] = "Muster: Bequeme Einlegesohlen",
			["Korean"] = "도안: 편안한 깔창",
			["Mexican"] = "Patrón: plantillas cómodas",
			["Portuguese"] = "Molde: Solas Confortáveis",
			["Russian"] = "Выкройка: удобные стельки",
			["Spanish"] = "Patrón: plantillas cómodas",
			["Taiwanese"] = "圖樣:舒適的鞋墊",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 10000,
			["sources"] = {
				16689,
				16748,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				18667,
			},
		},
		["expansion"] = 2,
		["id"] = 25728,
		["name"] = {
			["Chinese"] = "图样：斯蒂林的紫皮帽",
			["English"] = "Pattern: Stylin' Purple Hat",
			["French"] = "Patron : Chapeau violet stylé",
			["German"] = "Muster: Schicker lilafarbener Hut",
			["Korean"] = "도안: 근사한 보라색 모자",
			["Mexican"] = "Patrón: sombrero morado a la moda",
			["Portuguese"] = "Molde: Chapéu Estiloso Roxo",
			["Russian"] = "Выкройка: вычурная лиловая шляпа",
			["Spanish"] = "Patrón: sombrero morado a la moda",
			["Taiwanese"] = "圖樣:造型紫色帽",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				28132,
				17820,
			},
		},
		["expansion"] = 2,
		["id"] = 25729,
		["name"] = {
			["Chinese"] = "图样：斯蒂林的冒险帽",
			["English"] = "Pattern: Stylin' Adventure Hat",
			["French"] = "Patron : Chapeau d'aventurier stylé",
			["German"] = "Muster: Schicker Abenteurerhut",
			["Korean"] = "도안: 근사한 모험가 모자",
			["Mexican"] = "Patrón: sombrero de aventurero a la moda",
			["Portuguese"] = "Molde: Chapéu Estiloso de Aventuras",
			["Russian"] = "Выкройка: вычурная походная шляпа",
			["Spanish"] = "Patrón: sombrero de aventurero a la moda",
			["Taiwanese"] = "圖樣:造型冒險帽",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				17839,
				21104,
			},
		},
		["expansion"] = 2,
		["id"] = 25730,
		["name"] = {
			["Chinese"] = "图样：斯蒂林的丛林帽",
			["English"] = "Pattern: Stylin' Jungle Hat",
			["French"] = "Patron : Chapeau de jungle stylé",
			["German"] = "Muster: Schicker Dschungelhut",
			["Korean"] = "도안: 근사한 밀림 모자",
			["Mexican"] = "Patrón: sombrero de la jungla a la moda",
			["Portuguese"] = "Molde: Chapéu Estiloso de Safári",
			["Russian"] = "Выкройка: вычурная тропическая шляпа",
			["Spanish"] = "Patrón: sombrero de la jungla a la moda",
			["Taiwanese"] = "圖樣:造型叢林帽",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18322,
			},
		},
		["expansion"] = 2,
		["id"] = 25731,
		["name"] = {
			["Chinese"] = "图样：斯蒂林的赤链帽",
			["English"] = "Pattern: Stylin' Crimson Hat",
			["French"] = "Patron : Chapeau cramoisi stylé",
			["German"] = "Muster: Schicker purpurfarbener Hut",
			["Korean"] = "도안: 근사한 진홍색 모자",
			["Mexican"] = "Patrón: sombrero carmesí a la moda",
			["Portuguese"] = "Molde: Chapéu Estiloso Carmesim",
			["Russian"] = "Выкройка: вычурная багровая шляпа",
			["Spanish"] = "Patrón: sombrero carmesí a la moda",
			["Taiwanese"] = "圖樣:造型紅色帽",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 25732,
		["name"] = {
			["Chinese"] = "图样：魔能皮甲手套",
			["English"] = "Pattern: Fel Leather Gloves",
			["French"] = "Patron : Gants en gangrecuir",
			["German"] = "Muster: Teufelslederhandschuhe",
			["Korean"] = "도안: 지옥 가죽 장갑",
			["Mexican"] = "Patrón: guantes de cuero vil",
			["Portuguese"] = "Molde: Luvas de Couro Vil",
			["Russian"] = "Выкройка: перчатки из сквернокожи",
			["Spanish"] = "Patrón: guantes de cuero vil",
			["Taiwanese"] = "圖樣:惡魔皮手套",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25733,
		["name"] = {
			["Chinese"] = "图样：魔能皮甲长靴",
			["English"] = "Pattern: Fel Leather Boots",
			["French"] = "Patron : Bottes en gangrecuir",
			["German"] = "Muster: Teufelslederstiefel",
			["Korean"] = "도안: 지옥 가죽 장화",
			["Mexican"] = "Patrón: botas de cuero vil",
			["Portuguese"] = "Molde: Botas de Couro Vil",
			["Russian"] = "Выкройка: сапоги из сквернокожи",
			["Spanish"] = "Patrón: botas de cuero vil",
			["Taiwanese"] = "圖樣:惡魔皮靴",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 140000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25734,
		["name"] = {
			["Chinese"] = "图样：魔能皮甲护腿",
			["English"] = "Pattern: Fel Leather Leggings",
			["French"] = "Patron : Jambières en gangrecuir",
			["German"] = "Muster: Teufelsledergamaschen",
			["Korean"] = "도안: 지옥 가죽 다리보호구",
			["Mexican"] = "Patrón: leotardos de cuero vil",
			["Portuguese"] = "Molde: Perneiras de Couro Vil",
			["Russian"] = "Выкройка: поножи из сквернокожи",
			["Spanish"] = "Patrón: leotardos de cuero vil",
			["Taiwanese"] = "圖樣:惡魔皮護腿",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 140000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25735,
		["name"] = {
			["Chinese"] = "图样：厚重裂蹄外套",
			["English"] = "Pattern: Heavy Clefthoof Vest",
			["French"] = "Patron : Gilet du sabot-fourchu épais",
			["German"] = "Muster: Schwere Grollhufweste",
			["Korean"] = "도안: 질긴 갈래발굽 조끼",
			["Mexican"] = "Patrón: jubón de uñagrieta pesado",
			["Portuguese"] = "Molde: Colete Pesado de Fenoceronte",
			["Russian"] = "Выкройка: тяжелый панцирь из шкуры копытня",
			["Spanish"] = "Patrón: jubón de uñagrieta grueso",
			["Taiwanese"] = "圖樣:重型裂蹄外衣",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25736,
		["name"] = {
			["Chinese"] = "图样：厚重裂蹄护腿",
			["English"] = "Pattern: Heavy Clefthoof Leggings",
			["French"] = "Patron : Jambières du sabot-fourchu épaisses",
			["German"] = "Muster: Schwere Grollhufgamaschen",
			["Korean"] = "도안: 질긴 갈래발굽 다리보호구",
			["Mexican"] = "Patrón: leotardos de uñagrieta pesados",
			["Portuguese"] = "Molde: Perneiras Pesadas de Fenoceronte",
			["Russian"] = "Выкройка: тяжелые поножи из шкуры копытня",
			["Spanish"] = "Patrón: leotardos uñagrieta pesados",
			["Taiwanese"] = "圖樣:重型裂蹄護腿",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 140000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25737,
		["name"] = {
			["Chinese"] = "图样：厚重裂蹄长靴",
			["English"] = "Pattern: Heavy Clefthoof Boots",
			["French"] = "Patron : Bottes du sabot-fourchu épaisses",
			["German"] = "Muster: Schwere Grollhufstiefel",
			["Korean"] = "도안: 질긴 갈래발굽 장화",
			["Mexican"] = "Patrón: botas de uñagrieta pesadas",
			["Portuguese"] = "Molde: Botas Pesadas de Fenoceronte",
			["Russian"] = "Выкройка: тяжелые сапоги из шкуры копытня",
			["Spanish"] = "Patrón: botas uñagrieta pesadas",
			["Taiwanese"] = "圖樣:重型裂蹄長靴",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 140000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25738,
		["name"] = {
			["Chinese"] = "图样：魔能猎手腰带",
			["English"] = "Pattern: Felstalker Belt",
			["French"] = "Patron : Ceinture de traqueur gangrené",
			["German"] = "Muster: Gürtel des Teufelspirschers",
			["Korean"] = "도안: 지옥추적자 허리띠",
			["Mexican"] = "Patrón: cinturón de acechador vil",
			["Portuguese"] = "Molde: Cinto do Espreitador Vil",
			["Russian"] = "Выкройка: пояс ловца Скверны",
			["Spanish"] = "Patrón: cinturón de acechador vil",
			["Taiwanese"] = "圖樣:惡魔捕獵者腰帶",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25739,
		["name"] = {
			["Chinese"] = "图样：魔能猎手护腕",
			["English"] = "Pattern: Felstalker Bracers",
			["French"] = "Patron : Brassards de traqueur gangrené",
			["German"] = "Muster: Armschienen des Teufelspirschers",
			["Korean"] = "도안: 지옥추적자 팔보호구",
			["Mexican"] = "Patrón: brazales de acechador vil",
			["Portuguese"] = "Molde: Braçadeiras do Espreitador Vil",
			["Russian"] = "Выкройка: наручи ловца Скверны",
			["Spanish"] = "Patrón: brazales de acechador vil",
			["Taiwanese"] = "圖樣:惡魔捕獵者護腕",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25740,
		["name"] = {
			["Chinese"] = "图样：魔能猎手胸甲",
			["English"] = "Pattern: Felstalker Breastplate",
			["French"] = "Patron : Cuirasse de traqueur gangrené",
			["German"] = "Muster: Brustplatte des Teufelspirschers",
			["Korean"] = "도안: 지옥추적자 흉갑",
			["Mexican"] = "Patrón: coraza de acechador vil",
			["Portuguese"] = "Molde: Peitoral do Espreitador Vil",
			["Russian"] = "Выкройка: кираса ловца Скверны",
			["Spanish"] = "Patrón: coraza de acechador vil",
			["Taiwanese"] = "圖樣:惡魔捕獵者胸甲",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25741,
		["name"] = {
			["Chinese"] = "图样：虚空之怒腰带",
			["English"] = "Pattern: Netherfury Belt",
			["French"] = "Patron : Ceinture de la Furie du Néant",
			["German"] = "Muster: Netherzorngürtel",
			["Korean"] = "도안: 황천의 격노 허리띠",
			["Mexican"] = "Patrón: cinturón de furia abisal",
			["Portuguese"] = "Molde: Cinto da Fúria Etérea",
			["Russian"] = "Выкройка: пояс неистовства пустоты",
			["Spanish"] = "Patrón: cinturón de furia abisal",
			["Taiwanese"] = "圖樣:虛空之怒腰帶",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25742,
		["name"] = {
			["Chinese"] = "图样：虚空之怒护腿",
			["English"] = "Pattern: Netherfury Leggings",
			["French"] = "Patron : Jambières de la Furie du Néant",
			["German"] = "Muster: Netherzorngamaschen",
			["Korean"] = "도안: 황천의 격노 다리보호구",
			["Mexican"] = "Patrón: leotardos de furia abisal",
			["Portuguese"] = "Molde: Perneiras da Fúria Etérea",
			["Russian"] = "Выкройка: поножи неистовства пустоты",
			["Spanish"] = "Patrón: leotardos de furia abisal",
			["Taiwanese"] = "圖樣:虛空之怒護腿",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25743,
		["name"] = {
			["Chinese"] = "图样：虚空之怒长靴",
			["English"] = "Pattern: Netherfury Boots",
			["French"] = "Patron : Bottes de la Furie du Néant",
			["German"] = "Muster: Netherzornstiefel",
			["Korean"] = "도안: 황천의 격노 장화",
			["Mexican"] = "Patrón: botas de furia abisal",
			["Portuguese"] = "Molde: Botas da Fúria Etérea",
			["Russian"] = "Выкройка: сапоги неистовства пустоты",
			["Spanish"] = "Patrón: botas de furia abisal",
			["Taiwanese"] = "圖樣:虛空之怒長靴",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29213,
		["name"] = {
			["Chinese"] = "图样：魔能猎手腰带",
			["English"] = "Pattern: Felstalker Belt",
			["French"] = "Patron : Ceinture de traqueur gangrené",
			["German"] = "Muster: Gürtel des Teufelspirschers",
			["Korean"] = "도안: 지옥추적자 허리띠",
			["Mexican"] = "Patrón: cinturón de acechador vil",
			["Portuguese"] = "Molde: Cinto do Espreitador Vil",
			["Russian"] = "Выкройка: пояс ловца Скверны",
			["Spanish"] = "Patrón: cinturón de acechador vil",
			["Taiwanese"] = "圖樣:惡魔捕獵者腰帶",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29214,
		["name"] = {
			["Chinese"] = "图样：魔能猎手护腕",
			["English"] = "Pattern: Felstalker Bracers",
			["French"] = "Patron : Brassards de traqueur gangrené",
			["German"] = "Muster: Armschienen des Teufelspirschers",
			["Korean"] = "도안: 지옥추적자 팔보호구",
			["Mexican"] = "Patrón: brazales de acechador vil",
			["Portuguese"] = "Molde: Braçadeiras do Espreitador Vil",
			["Russian"] = "Выкройка: наручи ловца Скверны",
			["Spanish"] = "Patrón: brazales de acechador vil",
			["Taiwanese"] = "圖樣:惡魔捕獵者護腕",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29215,
		["name"] = {
			["Chinese"] = "图样：魔能猎手胸甲",
			["English"] = "Pattern: Felstalker Breastplate",
			["French"] = "Patron : Cuirasse de traqueur gangrené",
			["German"] = "Muster: Brustplatte des Teufelspirschers",
			["Korean"] = "도안: 지옥추적자 흉갑",
			["Mexican"] = "Patrón: coraza de acechador vil",
			["Portuguese"] = "Molde: Peitoral do Espreitador Vil",
			["Russian"] = "Выкройка: кираса ловца Скверны",
			["Spanish"] = "Patrón: coraza de acechador vil",
			["Taiwanese"] = "圖樣:惡魔捕獵者胸甲",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29217,
		["name"] = {
			["Chinese"] = "图样：虚空之怒腰带",
			["English"] = "Pattern: Netherfury Belt",
			["French"] = "Patron : Ceinture de la Furie du Néant",
			["German"] = "Muster: Netherzorngürtel",
			["Korean"] = "도안: 황천의 격노 허리띠",
			["Mexican"] = "Patrón: cinturón de furia abisal",
			["Portuguese"] = "Molde: Cinto da Fúria Etérea",
			["Russian"] = "Выкройка: пояс неистовства пустоты",
			["Spanish"] = "Patrón: cinturón de furia abisal",
			["Taiwanese"] = "圖樣:虛空之怒腰帶",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29218,
		["name"] = {
			["Chinese"] = "图样：虚空之怒长靴",
			["English"] = "Pattern: Netherfury Boots",
			["French"] = "Patron : Bottes de la Furie du Néant",
			["German"] = "Muster: Netherzornstiefel",
			["Korean"] = "도안: 황천의 격노 장화",
			["Mexican"] = "Patrón: botas de furia abisal",
			["Portuguese"] = "Molde: Botas da Fúria Etérea",
			["Russian"] = "Выкройка: сапоги неистовства пустоты",
			["Spanish"] = "Patrón: botas de furia abisal",
			["Taiwanese"] = "圖樣:虛空之怒長靴",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29219,
		["name"] = {
			["Chinese"] = "图样：虚空之怒护腿",
			["English"] = "Pattern: Netherfury Leggings",
			["French"] = "Patron : Jambières de la Furie du Néant",
			["German"] = "Muster: Netherzorngamaschen",
			["Korean"] = "도안: 황천의 격노 다리보호구",
			["Mexican"] = "Patrón: leotardos de furia abisal",
			["Portuguese"] = "Molde: Perneiras da Fúria Etérea",
			["Russian"] = "Выкройка: поножи неистовства пустоты",
			["Spanish"] = "Patrón: leotardos de furia abisal",
			["Taiwanese"] = "圖樣:虛空之怒護腿",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29664,
		["name"] = {
			["Chinese"] = "图样：加固矿工袋",
			["English"] = "Pattern: Reinforced Mining Bag",
			["French"] = "Patron : Sac de mineur renforcé",
			["German"] = "Muster: Verstärkte Bergbautasche",
			["Korean"] = "도안: 강화된 채광용 자루",
			["Mexican"] = "Patrón: bolsa de minero reforzada",
			["Portuguese"] = "Molde: Bolsa de Mineração Reforçada",
			["Russian"] = "Выкройка: укрепленная шахтерская сумка",
			["Spanish"] = "Patrón: bolsa de minero reforzada",
			["Taiwanese"] = "圖樣:強化礦石包",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				18320,
			},
		},
		["expansion"] = 2,
		["id"] = 29669,
		["name"] = {
			["Chinese"] = "图样：暗影护甲片",
			["English"] = "Pattern: Shadow Armor Kit",
			["French"] = "Patron : Renfort d'armure de l'Ombre",
			["German"] = "Muster: Schattenrüstungsset",
			["Korean"] = "도안: 암흑 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura contra las Sombras",
			["Portuguese"] = "Molde: Kit de Armadura Sombria",
			["Russian"] = "Выкройка: накладки сопротивления темной магии",
			["Spanish"] = "Patrón: refuerzo para armadura de las Sombras",
			["Taiwanese"] = "圖樣:暗影護甲片",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				20898,
			},
		},
		["expansion"] = 2,
		["id"] = 29672,
		["name"] = {
			["Chinese"] = "图样：烈焰护甲片",
			["English"] = "Pattern: Flame Armor Kit",
			["French"] = "Patron : Renfort d'armure des Flammes",
			["German"] = "Muster: Flammenrüstungsset",
			["Korean"] = "도안: 화염 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura contra las llamas",
			["Portuguese"] = "Molde: Kit de Armadura Ígnea",
			["Russian"] = "Выкройка: накладки сопротивления огню",
			["Spanish"] = "Patrón: refuerzo para armadura contra las llamas",
			["Taiwanese"] = "圖樣:烈焰護甲片",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				17797,
			},
		},
		["expansion"] = 2,
		["id"] = 29673,
		["name"] = {
			["Chinese"] = "图样：冰霜护甲片",
			["English"] = "Pattern: Frost Armor Kit",
			["French"] = "Patron : Renfort d'armure de Givre",
			["German"] = "Muster: Frostrüstungsset",
			["Korean"] = "도안: 냉기 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura contra Escarcha",
			["Portuguese"] = "Molde: Kit de Armadura Gélida",
			["Russian"] = "Выкройка: накладки сопротивления магии льда",
			["Spanish"] = "Patrón: refuerzo para armadura contra escarcha",
			["Taiwanese"] = "圖樣:寒冰護甲片",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				17941,
			},
		},
		["expansion"] = 2,
		["id"] = 29674,
		["name"] = {
			["Chinese"] = "图样：自然护甲片",
			["English"] = "Pattern: Nature Armor Kit",
			["French"] = "Patron : Renfort d'armure de la Nature",
			["German"] = "Muster: Naturrüstungsset",
			["Korean"] = "도안: 자연 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura contra la Naturaleza",
			["Portuguese"] = "Molde: Kit de Armadura Natural",
			["Russian"] = "Выкройка: накладки сопротивления силам природы",
			["Spanish"] = "Patrón: refuerzo para armadura contra la Naturaleza",
			["Taiwanese"] = "圖樣:自然護甲片",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				17879,
			},
		},
		["expansion"] = 2,
		["id"] = 29675,
		["name"] = {
			["Chinese"] = "图样：奥术护甲片",
			["English"] = "Pattern: Arcane Armor Kit",
			["French"] = "Patron : Renfort d'armure des Arcanes",
			["German"] = "Muster: Arkanrüstungsset",
			["Korean"] = "도안: 비전 방어구 키트",
			["Mexican"] = "Patrón: refuerzo para armadura Arcano",
			["Portuguese"] = "Molde: Kit de Armadura Arcana",
			["Russian"] = "Выкройка: накладки сопротивления тайной магии",
			["Spanish"] = "Patrón: refuerzo para armadura Arcano",
			["Taiwanese"] = "圖樣:秘法護甲片",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 29677,
		["name"] = {
			["Chinese"] = "图样：魔化邪鳞护腿",
			["English"] = "Pattern: Enchanted Felscale Leggings",
			["French"] = "Patron : Jambières enchantées en gangrécailles",
			["German"] = "Muster: Verzauberte Teufelsschuppengamaschen",
			["Korean"] = "도안: 마력 깃든 지옥껍질 다리보호구",
			["Mexican"] = "Patrón: leotardos de escamas viles encantados",
			["Portuguese"] = "Molde: Perneiras Encantadas de Escamavil",
			["Russian"] = "Выкройка: зачарованные скверночешуйчатые поножи",
			["Spanish"] = "Patrón: leotardos de escamas viles encantados",
			["Taiwanese"] = "圖樣:附魔魔鱗護腿",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29682,
		["name"] = {
			["Chinese"] = "图样：魔化邪鳞手套",
			["English"] = "Pattern: Enchanted Felscale Gloves",
			["French"] = "Patron : Gants enchantés en gangrécailles",
			["German"] = "Muster: Verzauberte Teufelsschuppenhandschuhe",
			["Korean"] = "도안: 마력 깃든 지옥껍질 장갑",
			["Mexican"] = "Patrón: guantes de escamas viles encantados",
			["Portuguese"] = "Molde: Luvas Encantadas de Escamavil",
			["Russian"] = "Выкройка: зачарованные скверночешуйчатые перчатки",
			["Spanish"] = "Patrón: guantes de escamas viles encantados",
			["Taiwanese"] = "圖樣:附魔魔鱗手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29684,
		["name"] = {
			["Chinese"] = "图样：魔化邪鳞长靴",
			["English"] = "Pattern: Enchanted Felscale Boots",
			["French"] = "Patron : Bottes enchantées en gangrécailles",
			["German"] = "Muster: Verzauberte Teufelsschuppenstiefel",
			["Korean"] = "도안: 마력 깃든 지옥껍질 장화",
			["Mexican"] = "Patrón: botas de escamas viles encantadas",
			["Portuguese"] = "Molde: Botas Encantadas de Escamavil",
			["Russian"] = "Выкройка: зачарованные скверночешуйчатые сапоги",
			["Spanish"] = "Patrón: botas de escamas viles encantadas",
			["Taiwanese"] = "圖樣:附魔魔鱗長靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29689,
		["name"] = {
			["Chinese"] = "图样：焰鳞护腿",
			["English"] = "Pattern: Flamescale Leggings",
			["French"] = "Patron : Jambières en flamécaille",
			["German"] = "Muster: Flammenschuppengamaschen",
			["Korean"] = "도안: 화염비늘 다리보호구",
			["Mexican"] = "Patrón: leotardos de flamaescama",
			["Portuguese"] = "Molde: Perneiras de Flamescama",
			["Russian"] = "Выкройка: огнечешуйчатые поножи",
			["Spanish"] = "Patrón: leotardos de flamaescama",
			["Taiwanese"] = "圖樣:火鱗護腿",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29691,
		["name"] = {
			["Chinese"] = "图样：焰鳞长靴",
			["English"] = "Pattern: Flamescale Boots",
			["French"] = "Patron : Bottes en flamécaille",
			["German"] = "Muster: Flammenschuppenstiefel",
			["Korean"] = "도안: 화염비늘 장화",
			["Mexican"] = "Patrón: botas de flamaescama",
			["Portuguese"] = "Molde: Botas de Flamescama",
			["Russian"] = "Выкройка: огнечешуйчатые сапоги",
			["Spanish"] = "Patrón: botas de flamaescama",
			["Taiwanese"] = "圖樣:火鱗長靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29693,
		["name"] = {
			["Chinese"] = "图样：焰鳞腰带",
			["English"] = "Pattern: Flamescale Belt",
			["French"] = "Patron : Ceinture en flamécaille",
			["German"] = "Muster: Flammenschuppengürtel",
			["Korean"] = "도안: 화염비늘 허리띠",
			["Mexican"] = "Patrón: cinturón de flamaescama",
			["Portuguese"] = "Molde: Cinto de Flamescama",
			["Russian"] = "Выкройка: огнечешуйчатый пояс",
			["Spanish"] = "Patrón: cinturón de flamaescama",
			["Taiwanese"] = "圖樣:火鱗腰帶",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29698,
		["name"] = {
			["Chinese"] = "图样：魔化裂蹄护腿",
			["English"] = "Pattern: Enchanted Clefthoof Leggings",
			["French"] = "Patron : Jambières enchantées en sabot-fourchu",
			["German"] = "Muster: Verzauberte Grollhufgamaschen",
			["Korean"] = "도안: 마력 깃든 갈래발굽 다리보호구",
			["Mexican"] = "Patrón: leotardos de uñagrieta encantados",
			["Portuguese"] = "Molde: Perneiras Encantadas de Fenoceronte",
			["Russian"] = "Выкройка: зачарованные поножи из шкуры копытня",
			["Spanish"] = "Patrón: leotardos de uñagrieta encantados",
			["Taiwanese"] = "圖樣:附魔裂蹄護腿",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29700,
		["name"] = {
			["Chinese"] = "图样：魔化裂蹄手套",
			["English"] = "Pattern: Enchanted Clefthoof Gloves",
			["French"] = "Patron : Gants enchantés en sabot-fourchu",
			["German"] = "Muster: Verzauberte Grollhufhandschuhe",
			["Korean"] = "도안: 마력 깃든 갈래발굽 장갑",
			["Mexican"] = "Patrón: guantes de uñagrieta encantados",
			["Portuguese"] = "Molde: Luvas Encantadas de Fenoceronte",
			["Russian"] = "Выкройка: зачарованные перчатки из шкуры копытня",
			["Spanish"] = "Patrón: guantes uñagrieta encantados",
			["Taiwanese"] = "圖樣:附魔裂蹄手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29701,
		["name"] = {
			["Chinese"] = "图样：魔化裂蹄长靴",
			["English"] = "Pattern: Enchanted Clefthoof Boots",
			["French"] = "Patron : Bottes enchantées en sabot-fourchu",
			["German"] = "Muster: Verzauberte Grollhufstiefel",
			["Korean"] = "도안: 마력 깃든 갈래발굽 장화",
			["Mexican"] = "Patrón: botas de uñagrieta encantadas",
			["Portuguese"] = "Molde: Botas Encantadas de Fenoceronte",
			["Russian"] = "Выкройка: зачарованные сапоги из шкуры копытня",
			["Spanish"] = "Patrón: botas uñagrieta encantadas",
			["Taiwanese"] = "圖樣:附魔裂蹄長靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29702,
		["name"] = {
			["Chinese"] = "图样：爆炸防护短裤",
			["English"] = "Pattern: Blastguard Pants",
			["French"] = "Patron : Pantalon de déminage",
			["German"] = "Muster: Lohenschildhose",
			["Korean"] = "도안: 폭풍막이 바지",
			["Mexican"] = "Patrón: pantalones antiexplosión",
			["Portuguese"] = "Molde: Calças Antibombas",
			["Russian"] = "Выкройка: взрывостойкие штаны",
			["Spanish"] = "Patrón: pantalones antiexplosión",
			["Taiwanese"] = "圖樣:爆烈守衛便褲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29703,
		["name"] = {
			["Chinese"] = "图样：爆炸防护长靴",
			["English"] = "Pattern: Blastguard Boots",
			["French"] = "Patron : Bottes de déminage",
			["German"] = "Muster: Lohenschildstiefel",
			["Korean"] = "도안: 폭풍막이 장화",
			["Mexican"] = "Patrón: botas antiexplosión",
			["Portuguese"] = "Molde: Botas Antibombas",
			["Russian"] = "Выкройка: взрывостойкие сапоги",
			["Spanish"] = "Patrón: botas antiexplosión",
			["Taiwanese"] = "圖樣:爆烈守衛長靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29704,
		["name"] = {
			["Chinese"] = "图样：爆炸防护腰带",
			["English"] = "Pattern: Blastguard Belt",
			["French"] = "Patron : Ceinture de déminage",
			["German"] = "Muster: Lohenschildgürtel",
			["Korean"] = "도안: 폭풍막이 허리띠",
			["Mexican"] = "Patrón: cinturón antiexplosión",
			["Portuguese"] = "Molde: Cinto Antibombas",
			["Russian"] = "Выкройка: взрывостойкий пояс",
			["Spanish"] = "Patrón: cinturón antiexplosión",
			["Taiwanese"] = "圖樣:爆烈守衛腰帶",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29713,
		["name"] = {
			["Chinese"] = "图样：恐慌之鼓",
			["English"] = "Pattern: Drums of Panic",
			["French"] = "Patron : Tambours de panique",
			["German"] = "Muster: Trommeln der Panik",
			["Korean"] = "도안: 공황의 북소리",
			["Mexican"] = "Patrón: tambores de pánico",
			["Portuguese"] = "Molde: Tambores do Pânico",
			["Russian"] = "Выкройка: барабаны паники",
			["Spanish"] = "Patrón: tambores de pánico",
			["Taiwanese"] = "圖樣:驚慌之鼓",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 989,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				21643,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29714,
		["name"] = {
			["Chinese"] = "图样：恢复之鼓",
			["English"] = "Pattern: Drums of Restoration",
			["French"] = "Patron : Tambours de restauration",
			["German"] = "Muster: Trommeln der Wiederherstellung",
			["Korean"] = "도안: 회복의 북소리",
			["Mexican"] = "Patrón: tambores de restauración",
			["Portuguese"] = "Molde: Tambores de Restauração",
			["Russian"] = "Выкройка: барабаны восстановления",
			["Spanish"] = "Patrón: tambores de restauración",
			["Taiwanese"] = "圖樣:恢復之鼓",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 29717,
		["name"] = {
			["Chinese"] = "图样：战斗之鼓",
			["English"] = "Pattern: Drums of Battle",
			["French"] = "Patron : Tambours de bataille",
			["German"] = "Muster: Trommeln der Schlacht",
			["Korean"] = "도안: 전투의 북소리",
			["Mexican"] = "Patrón: tambores de batalla",
			["Portuguese"] = "Molde: Tambores de Batalha",
			["Russian"] = "Выкройка: барабаны битвы",
			["Spanish"] = "Patrón: tambores de batalla",
			["Taiwanese"] = "圖樣:戰鬥之鼓",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29718,
		["name"] = {
			["Chinese"] = "图样：速度之鼓",
			["English"] = "Pattern: Drums of Speed",
			["French"] = "Patron : Tambours de vitesse",
			["German"] = "Muster: Trommeln des Tempos",
			["Korean"] = "도안: 신속의 북소리",
			["Mexican"] = "Patrón: tambores de velocidad",
			["Portuguese"] = "Molde: Tambores de Velocidade",
			["Russian"] = "Выкройка: барабаны скорости",
			["Spanish"] = "Patrón: tambores de velocidad",
			["Taiwanese"] = "圖樣:速度之鼓",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 29719,
		["name"] = {
			["Chinese"] = "图样：眼镜蛇皮腿甲片",
			["English"] = "Pattern: Cobrahide Leg Armor",
			["French"] = "Patron : Armure de jambe en peau de cobra",
			["German"] = "Muster: Kobrahautbeinrüstung",
			["Korean"] = "도안: 코브라가죽 다리 방어구 강화 키트",
			["Mexican"] = "Patrón: armadura para pierna de pellejo de cobra",
			["Portuguese"] = "Molde: Armadura de Perna de Pelego de Naja",
			["Russian"] = "Выкройка: накладки для поножей из кожи кобры",
			["Spanish"] = "Patrón: armadura para pierna de pellejo de cobra",
			["Taiwanese"] = "圖樣:眼鏡蛇皮護腿片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29720,
		["name"] = {
			["Chinese"] = "图样：裂蹄腿甲片",
			["English"] = "Pattern: Clefthide Leg Armor",
			["French"] = "Patron : Armure de jambe en cuir-fourchu",
			["German"] = "Muster: Grollbalgbeinrüstung",
			["Korean"] = "도안: 갈래가죽 다리 방어구 강화 키트",
			["Mexican"] = "Patrón: armadura para pierna de pellejo grieta",
			["Portuguese"] = "Molde: Armadura de Perna de Pelego de Fenoceronte",
			["Russian"] = "Выкройка: накладки для поножей из шкуры копытня",
			["Spanish"] = "Patrón: armadura para pierna de pellejo grieta",
			["Taiwanese"] = "圖樣:裂蹄皮護腿片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29721,
		["name"] = {
			["Chinese"] = "图样：虚空裂蹄腿甲片",
			["English"] = "Pattern: Nethercleft Leg Armor",
			["French"] = "Patron : Armure de jambe de faille du Néant",
			["German"] = "Muster: Netherkluftbeinrüstung",
			["Korean"] = "도안: 황천의 갈래 다리 방어구 강화 키트",
			["Mexican"] = "Patrón: armadura para pierna grieta abisal",
			["Portuguese"] = "Molde: Armadura de Perna de Fenoceréter",
			["Russian"] = "Выкройка: накладки для поножей из кожи копытня",
			["Spanish"] = "Patrón: armadura para pierna grieta abisal",
			["Taiwanese"] = "圖樣:虛空裂蹄護腿片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29722,
		["name"] = {
			["Chinese"] = "图样：虚空毒蛇腿甲片",
			["English"] = "Pattern: Nethercobra Leg Armor",
			["French"] = "Patron : Armure de jambe en cobra du Néant",
			["German"] = "Muster: Netherkobrabeinrüstung",
			["Korean"] = "도안: 황천의 코브라 다리 방어구 강화 키트",
			["Mexican"] = "Patrón: armadura para pierna cobra abisal",
			["Portuguese"] = "Molde: Armadura de Perna de Eternaja",
			["Russian"] = "Выкройка: накладки для поножей из чешуи кобры",
			["Spanish"] = "Patrón: armadura para pierna cobra abisal",
			["Taiwanese"] = "圖樣:虛空眼鏡蛇護腿片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29723,
		["name"] = {
			["Chinese"] = "图样：眼镜蛇鳞片兜帽",
			["English"] = "Pattern: Cobrascale Hood",
			["French"] = "Patron : Capuche en écailles de cobra",
			["German"] = "Muster: Kobraschuppenkapuze",
			["Korean"] = "도안: 코브라 비늘 두건",
			["Mexican"] = "Patrón: caperuza de escamas de cobra",
			["Portuguese"] = "Molde: Capuz de Escama de Naja",
			["Russian"] = "Выкройка: капюшон из чешуи кобры",
			["Spanish"] = "Patrón: caperuza de escamas de cobra",
			["Taiwanese"] = "圖樣:眼鏡蛇鱗兜帽",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29724,
		["name"] = {
			["Chinese"] = "图样：眼镜蛇鳞片手套",
			["English"] = "Pattern: Cobrascale Gloves",
			["French"] = "Patron : Gants en écailles de cobra",
			["German"] = "Muster: Kobraschuppenhandschuhe",
			["Korean"] = "도안: 코브라 비늘 장갑",
			["Mexican"] = "Patrón: guantes de escamas de cobra",
			["Portuguese"] = "Molde: Luvas de Escama de Naja",
			["Russian"] = "Выкройка: перчатки из чешуи кобры",
			["Spanish"] = "Patrón: guantes de escamas de cobra",
			["Taiwanese"] = "圖樣:眼鏡蛇鱗手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29725,
		["name"] = {
			["Chinese"] = "图样：风鳞兜帽",
			["English"] = "Pattern: Windscale Hood",
			["French"] = "Patron : Capuche en écailles du vent",
			["German"] = "Muster: Windschuppenkapuze",
			["Korean"] = "도안: 바람비늘 두건",
			["Mexican"] = "Patrón: caperuza de escamas de viento",
			["Portuguese"] = "Molde: Capuz de Escamas de Vento",
			["Russian"] = "Выкройка: ветрочешуйчатый капюшон",
			["Spanish"] = "Patrón: caperuza de escamas de viento",
			["Taiwanese"] = "圖樣:風鱗兜帽",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29726,
		["name"] = {
			["Chinese"] = "图样：源生生命罩帽",
			["English"] = "Pattern: Hood of Primal Life",
			["French"] = "Patron : Chaperon de vie primordiale",
			["German"] = "Muster: Kapuze des Urlebens",
			["Korean"] = "도안: 근원 생명의 두건",
			["Mexican"] = "Patrón: caperuza de vida primigenia",
			["Portuguese"] = "Molde: Capuz da Vida Primeva",
			["Russian"] = "Выкройка: капюшон изначальной жизни",
			["Spanish"] = "Patrón: caperuza de vida primigenia",
			["Taiwanese"] = "圖樣:原始生命兜帽",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29727,
		["name"] = {
			["Chinese"] = "图样：生命之触手套",
			["English"] = "Pattern: Gloves of the Living Touch",
			["French"] = "Patron : Gants du toucher de vie",
			["German"] = "Muster: Handschuhe der lebendigen Berührung",
			["Korean"] = "도안: 생명이 넘치는 손길의 장갑",
			["Mexican"] = "Patrón: guantes del toque viviente",
			["Portuguese"] = "Molde: Luvas do Toque Vivo",
			["Russian"] = "Выкройка: перчатки живого прикосновения",
			["Spanish"] = "Patrón: guantes del toque viviente",
			["Taiwanese"] = "圖樣:生命之觸手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29728,
		["name"] = {
			["Chinese"] = "图样：风斩裹手",
			["English"] = "Pattern: Windslayer Wraps",
			["French"] = "Patron : Protège-mains de tueur du vent",
			["German"] = "Muster: Windtöterwickel",
			["Korean"] = "도안: 바람의 학살자 장갑",
			["Mexican"] = "Patrón: guantes destripaviento",
			["Portuguese"] = "Molde: Braçadeiras do Mataventos",
			["Russian"] = "Выкройка: напульсники ветроубийцы",
			["Spanish"] = "Patrón: guantes destripaviento",
			["Taiwanese"] = "圖樣:屠風者裹帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29729,
		["name"] = {
			["Chinese"] = "图样：生命龙鳞头盔",
			["English"] = "Pattern: Living Dragonscale Helm",
			["French"] = "Patron : Casque vivant en écailles de dragon",
			["German"] = "Muster: Lebendiger Drachenschuppenhelm",
			["Korean"] = "도안: 생명의 용비늘 투구",
			["Mexican"] = "Patrón: yelmo de dragontina viviente",
			["Portuguese"] = "Molde: Elmo Vivo de Escama de Dragão",
			["Russian"] = "Выкройка: животворный шлем из чешуи дракона",
			["Spanish"] = "Patrón: yelmo de escamas de dragón viviente",
			["Taiwanese"] = "圖樣:生命龍鱗頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29730,
		["name"] = {
			["Chinese"] = "图样：土灵虚鳞长靴",
			["English"] = "Pattern: Earthen Netherscale Boots",
			["French"] = "Patron : Bottes terrestres en écailles du Néant",
			["German"] = "Muster: Irdene Netherschuppenstiefel",
			["Korean"] = "도안: 대지의 황천비늘 장화",
			["Mexican"] = "Patrón: botas de escamas abisales de terráneo",
			["Portuguese"] = "Molde: Botas Terranas de Escama Etérea",
			["Russian"] = "Выкройка: сапоги земли из чешуи дракона Пустоты",
			["Spanish"] = "Patrón: botas de escamas abisales de terráneo",
			["Taiwanese"] = "圖樣:土靈虛空鱗長靴",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				18635,
			},
		},
		["expansion"] = 2,
		["id"] = 29731,
		["name"] = {
			["Chinese"] = "图样：风击手套",
			["English"] = "Pattern: Windstrike Gloves",
			["French"] = "Patron : Gants du Frappevent",
			["German"] = "Muster: Windstoßhandschuhe",
			["Korean"] = "도안: 바람쐐기 장갑",
			["Mexican"] = "Patrón: guantes de golpe de viento",
			["Portuguese"] = "Molde: Luvas do Golpe de Vento",
			["Russian"] = "Выкройка: перчатки налетевшего ветра",
			["Spanish"] = "Patrón: guantes de golpe de viento",
			["Taiwanese"] = "圖樣:風擊手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				18203,
			},
		},
		["expansion"] = 2,
		["id"] = 29732,
		["name"] = {
			["Chinese"] = "图样：虚空幼龙头盔",
			["English"] = "Pattern: Netherdrake Helm",
			["French"] = "Patron : Casque de drake du Néant",
			["German"] = "Muster: Netherdrachenhelm",
			["Korean"] = "도안: 황천의 비룡 투구",
			["Mexican"] = "Patrón: yelmo de draco abisal",
			["Portuguese"] = "Molde: Elmo de Draco Etéreo",
			["Russian"] = "Выкройка: шлем дракона Пустоты",
			["Spanish"] = "Patrón: yelmo de draco abisal",
			["Taiwanese"] = "圖樣:虛空龍頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29733,
		["name"] = {
			["Chinese"] = "图样：虚空幼龙手套",
			["English"] = "Pattern: Netherdrake Gloves",
			["French"] = "Patron : Gants de drake du Néant",
			["German"] = "Muster: Netherdrachenhandschuhe",
			["Korean"] = "도안: 황천의 비룡 장갑",
			["Mexican"] = "Patrón: guantes de draco abisal",
			["Portuguese"] = "Molde: Luvas de Draco Etéreo",
			["Russian"] = "Выкройка: перчатки дракона Пустоты",
			["Spanish"] = "Patrón: guantes de draco abisal",
			["Taiwanese"] = "圖樣:虛空龍手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 29734,
		["name"] = {
			["Chinese"] = "图样：厚重虚空鳞片胸甲",
			["English"] = "Pattern: Thick Netherscale Breastplate",
			["French"] = "Patron : Cuirasse épaisse en écailles du Néant",
			["German"] = "Muster: Dicke Netherschuppenbrustplatte",
			["Korean"] = "도안: 두꺼운 황천비늘 흉갑",
			["Mexican"] = "Patrón: coraza de escamas abisales gruesa",
			["Portuguese"] = "Molde: Peitoral Grosso de Escama Etérea",
			["Russian"] = "Выкройка: плотная кираса из чешуи дракона Пустоты",
			["Spanish"] = "Patrón: coraza de escamas abisales gruesa",
			["Taiwanese"] = "圖樣:厚虛空鱗胸甲",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				19514,
				20046,
				21212,
				21216,
				23054,
			},
		},
		["expansion"] = 2,
		["id"] = 30301,
		["name"] = {
			["Chinese"] = "图样：自然力量腰带",
			["English"] = "Pattern: Belt of Natural Power",
			["French"] = "Patron : Ceinture de puissance naturelle",
			["German"] = "Muster: Gürtel der naturgleichen Kraft",
			["Korean"] = "도안: 자연이 품은 힘의 허리띠",
			["Mexican"] = "Patrón: cinturón de poder natural",
			["Portuguese"] = "Molde: Cinto do Poder Natural",
			["Russian"] = "Выкройка: пояс природной силы",
			["Spanish"] = "Patrón: cinturón de poder natural",
			["Taiwanese"] = "圖樣:自然之力腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30302,
		["name"] = {
			["Chinese"] = "图样：深邃暗影腰带",
			["English"] = "Pattern: Belt of Deep Shadow",
			["French"] = "Patron : Ceinture des ombres profondes",
			["German"] = "Muster: Gürtel der tiefen Schatten",
			["Korean"] = "도안: 깊은 어둠의 허리띠",
			["Mexican"] = "Patrón: cinturón de sombra profunda",
			["Portuguese"] = "Molde: Cinto da Sombra Profunda",
			["Russian"] = "Выкройка: пояс глубокой тени",
			["Spanish"] = "Patrón: cinturón de sombra profunda",
			["Taiwanese"] = "圖樣:暗影深淵腰帶",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				20046,
				21212,
				21224,
				23054,
			},
		},
		["expansion"] = 2,
		["id"] = 30303,
		["name"] = {
			["Chinese"] = "图样：黑鹰腰带",
			["English"] = "Pattern: Belt of the Black Eagle",
			["French"] = "Patron : Ceinture de l'aigle noir",
			["German"] = "Muster: Gürtel des schwarzen Adlers",
			["Korean"] = "도안: 검은 독수리 허리띠",
			["Mexican"] = "Patrón: cinturón del águila negra",
			["Portuguese"] = "Molde: Cinto da Águia Negra",
			["Russian"] = "Выкройка: пояс черного орла",
			["Spanish"] = "Patrón: cinturón del águila negra",
			["Taiwanese"] = "圖樣:黑鷹腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				20045,
				20046,
				21214,
				21217,
				23054,
			},
		},
		["expansion"] = 2,
		["id"] = 30304,
		["name"] = {
			["Chinese"] = "图样：季风腰带",
			["English"] = "Pattern: Monsoon Belt",
			["French"] = "Patron : Ceinture de la mousson",
			["German"] = "Muster: Gürtel des Monsuns",
			["Korean"] = "도안: 계절풍 허리띠",
			["Mexican"] = "Patrón: cinturón de monzón",
			["Portuguese"] = "Molde: Cinto da Monção",
			["Russian"] = "Выкройка: пояс сезона дождей",
			["Spanish"] = "Patrón: cinturón de monzón",
			["Taiwanese"] = "圖樣:季風腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30305,
		["name"] = {
			["Chinese"] = "图样：自然优雅之靴",
			["English"] = "Pattern: Boots of Natural Grace",
			["French"] = "Patron : Bottes de grâce naturelle",
			["German"] = "Muster: Stiefel der naturgleichen Anmut",
			["Korean"] = "도안: 자연이 내린 은총의 장화",
			["Mexican"] = "Patrón: botas de gracia natural",
			["Portuguese"] = "Molde: Botas do Encanto Natural",
			["Russian"] = "Выкройка: сапоги природной милости",
			["Spanish"] = "Patrón: botas de gracia natural",
			["Taiwanese"] = "圖樣:自然之擁之靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30306,
		["name"] = {
			["Chinese"] = "图样：无边黑暗之靴",
			["English"] = "Pattern: Boots of Utter Darkness",
			["French"] = "Patron : Bottes de l'obscurité totale",
			["German"] = "Muster: Stiefel der totalen Finsternis",
			["Korean"] = "도안: 철저한 암흑의 장화",
			["Mexican"] = "Patrón: botas de oscuridad absoluta",
			["Portuguese"] = "Molde: Botas da Escuridão Absoluta",
			["Russian"] = "Выкройка: сапоги непроглядной тьмы",
			["Spanish"] = "Patrón: botas de oscuridad absoluta",
			["Taiwanese"] = "圖樣:絕對黑暗之靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30307,
		["name"] = {
			["Chinese"] = "图样：赤鹰之靴",
			["English"] = "Pattern: Boots of the Crimson Hawk",
			["French"] = "Patron : Bottes du faucon écarlate",
			["German"] = "Muster: Stiefel des Purpurfalken",
			["Korean"] = "도안: 붉은매 장화",
			["Mexican"] = "Patrón: botas de halcón carmesí",
			["Portuguese"] = "Molde: Botas do Falcão Carmesim",
			["Russian"] = "Выкройка: сапоги багрового ястреба",
			["Spanish"] = "Patrón: botas de halcón carmesí",
			["Taiwanese"] = "圖樣:紅鷹之靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30308,
		["name"] = {
			["Chinese"] = "图样：飓风长靴",
			["English"] = "Pattern: Hurricane Boots",
			["French"] = "Patron : Bottes de l'ouragan",
			["German"] = "Muster: Stiefel des Wirbelsturms",
			["Korean"] = "도안: 폭풍우 장화",
			["Mexican"] = "Patrón: botas de huracán",
			["Portuguese"] = "Molde: Botas Furacão",
			["Russian"] = "Выкройка: сапоги урагана",
			["Spanish"] = "Patrón: botas de huracán",
			["Taiwanese"] = "圖樣:颶風長靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 30444,
		["name"] = {
			["Chinese"] = "图样：加固矿工袋",
			["English"] = "Pattern: Reinforced Mining Bag",
			["French"] = "Patron : Sac de mineur renforcé",
			["German"] = "Muster: Verstärkte Bergbautasche",
			["Korean"] = "도안: 강화된 채광용 자루",
			["Mexican"] = "Patrón: bolsa de minero reforzada",
			["Portuguese"] = "Molde: Bolsa de Mineração Reforçada",
			["Russian"] = "Выкройка: укрепленная шахтерская сумка",
			["Spanish"] = "Patrón: bolsa de minero reforzada",
			["Taiwanese"] = "圖樣:強化礦石包",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31361,
		["name"] = {
			["Chinese"] = "图样：眼镜蛇皮腿甲片",
			["English"] = "Pattern: Cobrahide Leg Armor",
			["French"] = "Patron : Armure de jambe en peau de cobra",
			["German"] = "Muster: Kobrahautbeinrüstung",
			["Korean"] = "도안: 코브라가죽 다리 방어구 강화 키트",
			["Mexican"] = "Patrón: armadura para pierna de pellejo de cobra",
			["Portuguese"] = "Molde: Armadura de Perna de Pelego de Naja",
			["Russian"] = "Выкройка: накладки для поножей из кожи кобры",
			["Spanish"] = "Patrón: armadura para pierna de pellejo de cobra",
			["Taiwanese"] = "圖樣:眼鏡蛇皮護腿片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31362,
		["name"] = {
			["Chinese"] = "图样：虚空毒蛇腿甲片",
			["English"] = "Pattern: Nethercobra Leg Armor",
			["French"] = "Patron : Armure de jambe en cobra du Néant",
			["German"] = "Muster: Netherkobrabeinrüstung",
			["Korean"] = "도안: 황천의 코브라 다리 방어구 강화 키트",
			["Mexican"] = "Patrón: armadura para pierna cobra abisal",
			["Portuguese"] = "Molde: Armadura de Perna de Eternaja",
			["Russian"] = "Выкройка: накладки для поножей из чешуи кобры",
			["Spanish"] = "Patrón: armadura para pierna cobra abisal",
			["Taiwanese"] = "圖樣:虛空眼鏡蛇護腿片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32429,
		["name"] = {
			["Chinese"] = "图样：束缚灵魂长靴",
			["English"] = "Pattern: Boots of Shackled Souls",
			["French"] = "Dessin : Bottes des âmes entravées",
			["German"] = "Muster: Stiefel der gefangenen Seelen",
			["Korean"] = "도안: 구속된 영혼의 장화",
			["Mexican"] = "Patrón: botas de almas encadenadas",
			["Portuguese"] = "Molde: Botas das Almas Acorrentadas",
			["Russian"] = "Выкройка: сапоги скованных душ",
			["Spanish"] = "Patrón: botas de almas encadenadas",
			["Taiwanese"] = "圖樣:束縛之魂長靴",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32430,
		["name"] = {
			["Chinese"] = "图样：束缚灵魂护腕",
			["English"] = "Pattern: Bracers of Shackled Souls",
			["French"] = "Dessin : Brassards des âmes entravées",
			["German"] = "Muster: Armschienen der gefangenen Seelen",
			["Korean"] = "도안: 구속된 영혼의 팔보호구",
			["Mexican"] = "Patrón: brazales de almas encadenadas",
			["Portuguese"] = "Molde: Braçadeiras das Almas Acorrentadas",
			["Russian"] = "Выкройка: наручи скованных душ",
			["Spanish"] = "Patrón: brazales de almas encadenadas",
			["Taiwanese"] = "圖樣:束縛之魂護腕",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32431,
		["name"] = {
			["Chinese"] = "图样：束缚灵魂护腿",
			["English"] = "Pattern: Greaves of Shackled Souls",
			["French"] = "Dessin : Grèves des âmes entravées",
			["German"] = "Muster: Schienbeinschützer der gefangenen Seelen",
			["Korean"] = "도안: 구속된 영혼의 경갑",
			["Mexican"] = "Patrón: grebas de almas encadenadas",
			["Portuguese"] = "Molde: Grevas das Almas Acorrentadas",
			["Russian"] = "Выкройка: наголенники скованных душ",
			["Spanish"] = "Patrón: grebas de almas encadenadas",
			["Taiwanese"] = "圖樣:束縛之魂護脛",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32432,
		["name"] = {
			["Chinese"] = "图样：束缚灵魂腰带",
			["English"] = "Pattern: Waistguard of Shackled Souls",
			["French"] = "Dessin : Sangle des âmes entravées",
			["German"] = "Muster: Taillenschutz der gefangenen Seelen",
			["Korean"] = "도안: 구속된 영혼의 허리보호대",
			["Mexican"] = "Patrón: guardarrenes de almas encadenadas",
			["Portuguese"] = "Molde: Cinta das Almas Acorrentadas",
			["Russian"] = "Выкройка: воинский пояс скованных душ",
			["Spanish"] = "Patrón: guardarrenes de almas encadenadas",
			["Taiwanese"] = "圖樣:束縛之魂護腰",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32433,
		["name"] = {
			["Chinese"] = "图样：救赎灵魂长靴",
			["English"] = "Pattern: Redeemed Soul Moccasins",
			["French"] = "Patron : Mocassins d'âme rachetée",
			["German"] = "Muster: Mokassins der erlösten Seele",
			["Korean"] = "도안: 구원된 영혼의 장화",
			["Mexican"] = "Patrón: mocasines de alma redimida",
			["Portuguese"] = "Molde: Mocassins da Alma Redimida",
			["Russian"] = "Выкройка: мокасины искупленной души",
			["Spanish"] = "Patrón: mocasines de alma redimida",
			["Taiwanese"] = "圖樣:救贖之魂底鞋",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32434,
		["name"] = {
			["Chinese"] = "图样：救赎灵魂腕甲",
			["English"] = "Pattern: Redeemed Soul Wristguards",
			["French"] = "Patron : Garde-poignets d'âme rachetée",
			["German"] = "Muster: Handgelenksschutz der erlösten Seele",
			["Korean"] = "도안: 구원된 영혼의 손목보호구",
			["Mexican"] = "Patrón: guardamuñecas de alma redimida",
			["Portuguese"] = "Molde: Munhequeiras da Alma Redimida",
			["Russian"] = "Выкройка: нарукавники искупленной души",
			["Spanish"] = "Patrón: guardamuñecas de alma redimida",
			["Taiwanese"] = "圖樣:救贖之魂腕甲",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32435,
		["name"] = {
			["Chinese"] = "图样：救赎灵魂腿甲",
			["English"] = "Pattern: Redeemed Soul Legguards",
			["French"] = "Patron : Garde-jambes d'âme rachetée",
			["German"] = "Muster: Beinschützer der erlösten Seele",
			["Korean"] = "도안: 구원된 영혼의 다리보호대",
			["Mexican"] = "Patrón: musleras de alma redimida",
			["Portuguese"] = "Molde: Guarda-pernas da Alma Redimida",
			["Russian"] = "Выкройка: набедренники искупленной души",
			["Spanish"] = "Patrón: musleras de alma redimida",
			["Taiwanese"] = "圖樣:救贖之魂腿甲",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32436,
		["name"] = {
			["Chinese"] = "图样：救赎灵魂束带",
			["English"] = "Pattern: Redeemed Soul Cinch",
			["French"] = "Patron : Cordelière d'âme rachetée",
			["German"] = "Muster: Sattelgurt der erlösten Seele",
			["Korean"] = "도안: 구원된 영혼의 허리띠",
			["Mexican"] = "Patrón: cincho de alma redimida",
			["Portuguese"] = "Molde: Cilha da Alma Redimida",
			["Russian"] = "Выкройка: кушак искупленной души",
			["Spanish"] = "Patrón: cincho de alma redimida",
			["Taiwanese"] = "圖樣:救贖之魂繫腰",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32744,
		["name"] = {
			["Chinese"] = "图样：新生护腕",
			["English"] = "Pattern: Bracers of Renewed Life",
			["French"] = "Patron : Brassards du regain de vie",
			["German"] = "Muster: Armschienen des erneuerten Lebens",
			["Korean"] = "도안: 새로운 삶의 팔보호구",
			["Mexican"] = "Patrón: brazales de vida renovada",
			["Portuguese"] = "Molde: Braçadeiras da Vida Renovada",
			["Russian"] = "Выкройка: наручи обновленной жизни",
			["Spanish"] = "Patrón: brazales de vida renovada",
			["Taiwanese"] = "圖樣:生命再生護腕",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
			},
		},
		["expansion"] = 2,
		["id"] = 32745,
		["name"] = {
			["Chinese"] = "图样：新生护肩",
			["English"] = "Pattern: Shoulderpads of Renewed Life",
			["French"] = "Patron : Protège-épaules du regain de vie",
			["German"] = "Muster: Schulterpolster des erneuerten Lebens",
			["Korean"] = "도안: 새로운 삶의 어깨보호구",
			["Mexican"] = "Patrón: hombreras de vida renovada",
			["Portuguese"] = "Molde: Ombreiras da Vida Renovada",
			["Russian"] = "Выкройка: наплечные пластины обновленной жизни",
			["Spanish"] = "Patrón: hombreras de vida renovada",
			["Taiwanese"] = "圖樣:生命再生肩墊",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32746,
		["name"] = {
			["Chinese"] = "图样：迅捷打击护腕",
			["English"] = "Pattern: Swiftstrike Bracers",
			["French"] = "Patron : Brassards de frappe rapide",
			["German"] = "Muster: Flinkschlagarmschienen",
			["Korean"] = "도안: 재빠른 일격의 팔보호구",
			["Mexican"] = "Patrón: brazales Golpepresto",
			["Portuguese"] = "Molde: Braçadeiras do Golpepresto",
			["Russian"] = "Выкройка: наручи молниеносного удара",
			["Spanish"] = "Patrón: brazales Golpeveloz",
			["Taiwanese"] = "圖樣:迅擊護腕",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32747,
		["name"] = {
			["Chinese"] = "图样：迅捷打击护肩",
			["English"] = "Pattern: Swiftstrike Shoulders",
			["French"] = "Patron : Epaulières de frappe rapide",
			["German"] = "Muster: Flinkschlagschultern",
			["Korean"] = "도안: 재빠른 일격의 어깨보호구",
			["Mexican"] = "Patrón: sobrehombros Golpepresto",
			["Portuguese"] = "Molde: Omoplatas do Golpepresto",
			["Russian"] = "Выкройка: наплечники молниеносного удара",
			["Spanish"] = "Patrón: sobrehombros Golpeveloz",
			["Taiwanese"] = "圖樣:迅擊護肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32748,
		["name"] = {
			["Chinese"] = "图样：闪电反射护腕",
			["English"] = "Pattern: Bindings of Lightning Reflexes",
			["French"] = "Patron : Manchettes des réflexes éclairs",
			["German"] = "Muster: Bindungen der blitzartigen Reflexe",
			["Korean"] = "도안: 번개같은 반사 신경의 손목띠",
			["Mexican"] = "Patrón: ataduras de reflejos de relámpago",
			["Portuguese"] = "Molde: Braçadeiras do Reflexo Relâmpago",
			["Russian"] = "Выкройка: наручники молниеносной реакции",
			["Spanish"] = "Patrón: ataduras de reflejos de relámpago",
			["Taiwanese"] = "圖樣:電光反射束腕",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32749,
		["name"] = {
			["Chinese"] = "图样：闪电反射护肩",
			["English"] = "Pattern: Shoulders of Lightning Reflexes",
			["French"] = "Patron : Epaulières des réflexes éclairs",
			["German"] = "Muster: Schultern der blitzartigen Reflexe",
			["Korean"] = "도안: 번개같은 반사 신경의 어깨보호구",
			["Mexican"] = "Patrón: sobrehombros de reflejos de relámpago",
			["Portuguese"] = "Molde: Omoplatas do Reflexo Relâmpago",
			["Russian"] = "Выкройка: наплечники молниеносной реакции",
			["Spanish"] = "Patrón: sobrehombros de reflejos de relámpago",
			["Taiwanese"] = "圖樣:電光反射護肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32750,
		["name"] = {
			["Chinese"] = "图样：生命之地护腕",
			["English"] = "Pattern: Living Earth Bindings",
			["French"] = "Patron : Manchettes de la terre vivante",
			["German"] = "Muster: Lebendige Erdbindungen",
			["Korean"] = "도안: 살아있는 대지의 손목띠",
			["Mexican"] = "Patrón: ataduras Tierra Viva",
			["Portuguese"] = "Molde: Braceletes da Terra Viva",
			["Russian"] = "Выкройка: наручники живой земли",
			["Spanish"] = "Patrón: ataduras Tierra Viva",
			["Taiwanese"] = "圖樣:大地生命束腕",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32751,
		["name"] = {
			["Chinese"] = "图样：生命之地护肩",
			["English"] = "Pattern: Living Earth Shoulders",
			["French"] = "Patron : Epaulières de la terre vivante",
			["German"] = "Muster: Lebendige Erdschultern",
			["Korean"] = "도안: 살아있는 대지의 어깨보호구",
			["Mexican"] = "Patrón: sobrehombros Tierra Viva",
			["Portuguese"] = "Molde: Omoplatas da Terra Viva",
			["Russian"] = "Выкройка: наплечники живой земли",
			["Spanish"] = "Patrón: sobrehombros Tierra Viva",
			["Taiwanese"] = "圖樣:大地生命護肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 33124,
		["name"] = {
			["Chinese"] = "图样：黑暗披风",
			["English"] = "Pattern: Cloak of Darkness",
			["French"] = "Patron : Cape des ténèbres",
			["German"] = "Muster: Umhang der Dunkelheit",
			["Korean"] = "도안: 암흑의 망토",
			["Mexican"] = "Patrón: capa de oscuridad",
			["Portuguese"] = "Molde: Manto de Trevas",
			["Russian"] = "Выкройка: плащ Тьмы",
			["Spanish"] = "Patrón: capa de oscuridad",
			["Taiwanese"] = "圖樣:黑暗披風",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				18255,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33205,
		["name"] = {
			["Chinese"] = "图样：阴影徘徊者胸甲",
			["English"] = "Pattern: Shadowprowler's Chestguard",
			["French"] = "Patron : Corselet de rôdeur des ombres",
			["German"] = "Muster: Brustschutz des Schattenschleichers",
			["Korean"] = "도안: 그림자늑대의 가슴보호구",
			["Mexican"] = "Patrón: coselete de merodeador de las Sombras",
			["Portuguese"] = "Molde: Couraça do Predador das Sombras",
			["Russian"] = "Выкройка: нагрудный доспех сумеречного проныры",
			["Spanish"] = "Patrón: coselete de merodeador de las Sombras",
			["Taiwanese"] = "圖樣:暗影徘徊者護胸",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				18255,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34172,
		["name"] = {
			["Chinese"] = "图样：速度之鼓",
			["English"] = "Pattern: Drums of Speed",
			["French"] = "Patron : Tambours de vitesse",
			["German"] = "Muster: Trommeln des Tempos",
			["Korean"] = "도안: 신속의 북소리",
			["Mexican"] = "Patrón: tambores de velocidad",
			["Portuguese"] = "Molde: Tambores de Velocidade",
			["Russian"] = "Выкройка: барабаны скорости",
			["Spanish"] = "Patrón: tambores de velocidad",
			["Taiwanese"] = "圖樣:速度之鼓",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34173,
		["name"] = {
			["Chinese"] = "图样：速度之鼓",
			["English"] = "Pattern: Drums of Speed",
			["French"] = "Patron : Tambours de vitesse",
			["German"] = "Muster: Trommeln des Tempos",
			["Korean"] = "도안: 신속의 북소리",
			["Mexican"] = "Patrón: tambores de velocidad",
			["Portuguese"] = "Molde: Tambores de Velocidade",
			["Russian"] = "Выкройка: барабаны скорости",
			["Spanish"] = "Patrón: tambores de velocidad",
			["Taiwanese"] = "圖樣:速度之鼓",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34174,
		["name"] = {
			["Chinese"] = "图样：恢复之鼓",
			["English"] = "Pattern: Drums of Restoration",
			["French"] = "Patron : Tambours de restauration",
			["German"] = "Muster: Trommeln der Wiederherstellung",
			["Korean"] = "도안: 회복의 북소리",
			["Mexican"] = "Patrón: tambores de restauración",
			["Portuguese"] = "Molde: Tambores de Restauração",
			["Russian"] = "Выкройка: барабаны восстановления",
			["Spanish"] = "Patrón: tambores de restauración",
			["Taiwanese"] = "圖樣:恢復之鼓",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34175,
		["name"] = {
			["Chinese"] = "图样：恢复之鼓",
			["English"] = "Pattern: Drums of Restoration",
			["French"] = "Patron : Tambours de restauration",
			["German"] = "Muster: Trommeln der Wiederherstellung",
			["Korean"] = "도안: 회복의 북소리",
			["Mexican"] = "Patrón: tambores de restauración",
			["Portuguese"] = "Molde: Tambores de Restauração",
			["Russian"] = "Выкройка: барабаны восстановления",
			["Spanish"] = "Patrón: tambores de restauración",
			["Taiwanese"] = "圖樣:恢復之鼓",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34200,
		["name"] = {
			["Chinese"] = "图样：千羽箭袋",
			["English"] = "Pattern: Quiver of a Thousand Feathers",
			["French"] = "Patron : Carquois des mille plumes",
			["German"] = "Muster: Köcher der tausend Federn",
			["Korean"] = "도안: 천 개의 깃털 화살통",
			["Mexican"] = "Patrón: carcaj de mil plumas",
			["Portuguese"] = "Molde: Aljava de Mil Penas",
			["Russian"] = "Выкройка: колчан тысячи перьев",
			["Spanish"] = "Patrón: carcaj de mil plumas",
			["Taiwanese"] = "圖樣:千羽箭袋",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1011,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				21655,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34201,
		["name"] = {
			["Chinese"] = "图样：虚空鳞片弹药包",
			["English"] = "Pattern: Netherscale Ammo Pouch",
			["French"] = "Patron : Giberne en écailles du Néant",
			["German"] = "Muster: Munitionsbeutel aus Netherschuppen",
			["Korean"] = "도안: 황천비늘 탄약주머니",
			["Mexican"] = "Patrón: faltriquera de munición de escamas abisales",
			["Portuguese"] = "Molde: Bornal de Munição de Escama Etérea",
			["Russian"] = "Выкройка: подсумок из чешуи дракона Пустоты",
			["Spanish"] = "Patrón: faltriquera de munición de escamas abisales",
			["Taiwanese"] = "圖樣:虛空鱗彈藥袋",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34218,
		["name"] = {
			["Chinese"] = "图样：虚空鳞片弹药包",
			["English"] = "Pattern: Netherscale Ammo Pouch",
			["French"] = "Patron : Giberne en écailles du Néant",
			["German"] = "Muster: Munitionsbeutel aus Netherschuppen",
			["Korean"] = "도안: 황천비늘 탄약주머니",
			["Mexican"] = "Patrón: faltriquera de munición de escamas abisales",
			["Portuguese"] = "Molde: Bornal de Munição de Escama Etérea",
			["Russian"] = "Выкройка: подсумок из чешуи дракона Пустоты",
			["Spanish"] = "Patrón: faltriquera de munición de escamas abisales",
			["Taiwanese"] = "圖樣:虛空鱗彈藥袋",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 160000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34262,
		["holiday"] = 141,
		["name"] = {
			["Chinese"] = "图样：寒冬长靴",
			["English"] = "Pattern: Winter Boots",
			["French"] = "Patron : Bottes d'hiver",
			["German"] = "Muster: Winterstiefel",
			["Korean"] = "도안: 겨울 장화",
			["Mexican"] = "Patrón: botas de invierno",
			["Portuguese"] = "Molde: Botas de Inverno",
			["Russian"] = "Выкройка: зимние сапоги",
			["Spanish"] = "Patrón: botas de invierno",
			["Taiwanese"] = "圖樣:冬靴",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["price"] = 5000,
			["sources"] = {
				13420,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				22143,
				22144,
				22148,
				23022,
			}
		},
		["expansion"] = 2,
		["id"] = 34491,
		["name"] = {
			["Chinese"] = "图样：大皮袋",
			["English"] = "Pattern: Bag of Many Hides",
			["French"] = "Patron : Sac des nombreuses peaux",
			["German"] = "Muster: Tasche für alle Felle",
			["Korean"] = "도안: 가죽 덧댄 가방",
			["Mexican"] = "Patrón: bolsa de muchos pellejos",
			["Portuguese"] = "Molde: Bolsa de Muitos Pelegos",
			["Russian"] = "Выкройка: сумка множества шкур",
			["Spanish"] = "Patrón: bolsa de muchos pellejos",
			["Taiwanese"] = "圖樣:拼接皮包",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35212,
		["name"] = {
			["Chinese"] = "图样：骄阳之皮革护手",
			["English"] = "Pattern: Leather Gauntlets of the Sun",
			["French"] = "Patron : Gantelets du soleil en cuir",
			["German"] = "Muster: Lederstulpen der Sonne",
			["Korean"] = "도안: 태양의 가죽 건틀릿",
			["Mexican"] = "Patrón: guanteletes de cuero del sol",
			["Portuguese"] = "Molde: Manoplas Solares de Couro",
			["Russian"] = "Выкройка: кожаные рукавицы Солнца",
			["Spanish"] = "Patrón: guanteletes de cuero del sol",
			["Taiwanese"] = "圖樣:太陽皮甲護手",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35213,
		["name"] = {
			["Chinese"] = "图样：凤凰飞羽手套",
			["English"] = "Pattern: Fletcher's Gloves of the Phoenix",
			["French"] = "Patron : Gants de fléchier du phénix",
			["German"] = "Muster: Pfeilmacherhandschuhe des Phönix",
			["Korean"] = "도안: 불사조의 활장이 장갑",
			["Mexican"] = "Patrón: guantes del Fénix de flechero",
			["Portuguese"] = "Molde: Luvas-fênix do Seteiro",
			["Russian"] = "Выкройка: стрелецкие перчатки Феникса",
			["Spanish"] = "Patrón: guantes del Fénix de flechero",
			["Taiwanese"] = "圖樣:鳳凰弓匠手套",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35214,
		["name"] = {
			["Chinese"] = "图样：永生幽暗手套",
			["English"] = "Pattern: Gloves of Immortal Dusk",
			["French"] = "Patron : Gants de la pénombre immortelle",
			["German"] = "Muster: Handschuhe der unsterblichen Dämmerung",
			["Korean"] = "도안: 불멸의 황혼 장갑",
			["Mexican"] = "Patrón: guantes de anochecer inmortal",
			["Portuguese"] = "Molde: Luvas do Crepúsculo Imortal",
			["Russian"] = "Выкройка: перчатки вечного сумрака",
			["Spanish"] = "Patrón: guantes de anochecer inmortal",
			["Taiwanese"] = "圖樣:不朽之暮手套",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35215,
		["name"] = {
			["Chinese"] = "图样：炙日鳞片手套",
			["English"] = "Pattern: Sun-Drenched Scale Gloves",
			["French"] = "Patron : Gantelets d'écailles inondés de soleil",
			["German"] = "Muster: Sonnengetränkte Schuppenhandschuhe",
			["Korean"] = "도안: 태양빛에 물든 미늘 장갑",
			["Mexican"] = "Patrón: guantes de escamas caladas de sol",
			["Portuguese"] = "Molde: Luvas de Escama Banhada de Sol",
			["Russian"] = "Выкройка: пронизанные солнцем чешуйчатые перчатки",
			["Spanish"] = "Patrón: guantes de escamas caladas de sol",
			["Taiwanese"] = "圖樣:沁日鱗甲手套",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35216,
		["name"] = {
			["Chinese"] = "图样：骄阳之皮革胸甲",
			["English"] = "Pattern: Leather Chestguard of the Sun",
			["French"] = "Patron : Corselet du soleil en cuir",
			["German"] = "Muster: Lederbrustschutz der Sonne",
			["Korean"] = "도안: 태양의 가죽 흉갑",
			["Mexican"] = "Patrón: coselete de cuero del sol",
			["Portuguese"] = "Molde: Couraça Solar de Couro",
			["Russian"] = "Выкройка: кожаный нагрудный доспех солнца",
			["Spanish"] = "Patrón: coselete de cuero del sol",
			["Taiwanese"] = "圖樣:太陽皮甲護胸",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35217,
		["name"] = {
			["Chinese"] = "图样：凤凰的拥抱",
			["English"] = "Pattern: Embrace of the Phoenix",
			["French"] = "Patron : Etreinte du phénix",
			["German"] = "Muster: Umarmung des Phönix",
			["Korean"] = "도안: 불사조의 은총",
			["Mexican"] = "Patrón: abrazo del Fénix",
			["Portuguese"] = "Molde: Abraço da Fênix",
			["Russian"] = "Выкройка: облачение Феникса",
			["Spanish"] = "Patrón: abrazo del Fénix",
			["Taiwanese"] = "圖樣:鳳凰之擁",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35218,
		["name"] = {
			["Chinese"] = "图样：烈日暗影甲胄",
			["English"] = "Pattern: Carapace of Sun and Shadow",
			["French"] = "Patron : Carapace du soleil et de l'ombre",
			["German"] = "Muster: Panzerung von Sonne und Schatten",
			["Korean"] = "도안: 해그림자 갑옷",
			["Mexican"] = "Patrón: caparazón de sol y sombra",
			["Portuguese"] = "Molde: Carapaça de Sol e Sombra",
			["Russian"] = "Выкройка: панцирь Солнца и Тени",
			["Spanish"] = "Patrón: caparazón de sol y sombra",
			["Taiwanese"] = "圖樣:日與影之殼",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35219,
		["name"] = {
			["Chinese"] = "图样：炙日鳞片胸甲",
			["English"] = "Pattern: Sun-Drenched Scale Chestguard",
			["French"] = "Patron : Corselet d'écailles inondé de soleil",
			["German"] = "Muster: Sonnengetränkter Schuppenbrustschutz",
			["Korean"] = "도안: 태양빛에 물든 흉갑",
			["Mexican"] = "Patrón: coselete de escamas caladas de sol",
			["Portuguese"] = "Molde: Couraça de Escama Banhada de Sol",
			["Russian"] = "Выкройка: пронизанный солнцем нагрудный доспех",
			["Spanish"] = "Patrón: coselete de escamas caladas de sol",
			["Taiwanese"] = "圖樣:沁日鱗甲護胸",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 35300,
		["name"] = {
			["Chinese"] = "图样：风击手套",
			["English"] = "Pattern: Windstrike Gloves",
			["French"] = "Patron : Gants du Frappevent",
			["German"] = "Muster: Windstoßhandschuhe",
			["Korean"] = "도안: 바람쐐기 장갑",
			["Mexican"] = "Patrón: guantes de golpe de viento",
			["Portuguese"] = "Molde: Luvas do Golpe de Vento",
			["Russian"] = "Выкройка: перчатки налетевшего ветра",
			["Spanish"] = "Patrón: guantes de golpe de viento",
			["Taiwanese"] = "圖樣:風擊手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 35301,
		["name"] = {
			["Chinese"] = "图样：虚空幼龙手套",
			["English"] = "Pattern: Netherdrake Gloves",
			["French"] = "Patron : Gants de drake du Néant",
			["German"] = "Muster: Netherdrachenhandschuhe",
			["Korean"] = "도안: 황천의 비룡 장갑",
			["Mexican"] = "Patrón: guantes de draco abisal",
			["Portuguese"] = "Molde: Luvas de Draco Etéreo",
			["Russian"] = "Выкройка: перчатки дракона Пустоты",
			["Spanish"] = "Patrón: guantes de draco abisal",
			["Taiwanese"] = "圖樣:虛空龍手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 35302,
		["name"] = {
			["Chinese"] = "图样：眼镜蛇鳞片手套",
			["English"] = "Pattern: Cobrascale Gloves",
			["French"] = "Patron : Gants en écailles de cobra",
			["German"] = "Muster: Kobraschuppenhandschuhe",
			["Korean"] = "도안: 코브라 비늘 장갑",
			["Mexican"] = "Patrón: guantes de escamas de cobra",
			["Portuguese"] = "Molde: Luvas de Escama de Naja",
			["Russian"] = "Выкройка: перчатки из чешуи кобры",
			["Spanish"] = "Patrón: guantes de escamas de cobra",
			["Taiwanese"] = "圖樣:眼鏡蛇鱗手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 35303,
		["name"] = {
			["Chinese"] = "图样：生命之触手套",
			["English"] = "Pattern: Gloves of the Living Touch",
			["French"] = "Patron : Gants du toucher de vie",
			["German"] = "Muster: Handschuhe der lebendigen Berührung",
			["Korean"] = "도안: 생명이 넘치는 손길의 장갑",
			["Mexican"] = "Patrón: guantes del toque viviente",
			["Portuguese"] = "Molde: Luvas do Toque Vivo",
			["Russian"] = "Выкройка: перчатки живого прикосновения",
			["Spanish"] = "Patrón: guantes del toque viviente",
			["Taiwanese"] = "圖樣:生命之觸手套",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Leatherworking"], item)
end
