-------------------------------------------------------
-- All skills (Leatherworking) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Leatherworking"] then RR_DATA["skills"]["Leatherworking"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 32454,
		["item_id"] = 21887,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "结缔皮",
			["English"] = "Knothide Leather",
			["French"] = "Cuir granuleux",
			["German"] = "Knotenhautleder",
			["Korean"] = "톱니매듭 가죽",
			["Mexican"] = "Cuero de pellejo nudoso",
			["Portuguese"] = "Couro Nodoso",
			["Russian"] = "Узловатая кожа",
			["Spanish"] = "Cuero de pellejo nudoso",
			["Taiwanese"] = "境外皮革",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32455,
		["item_id"] = 23793,
		["items"] = {
			25720,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "重结缔皮",
			["English"] = "Heavy Knothide Leather",
			["French"] = "Cuir granuleux lourd",
			["German"] = "Schweres Knotenhautleder",
			["Korean"] = "질긴 톱니매듭 가죽",
			["Mexican"] = "Cuero de pellejo nudoso grueso",
			["Portuguese"] = "Couro Nodoso Pesado",
			["Russian"] = "Толстая узловатая кожа",
			["Spanish"] = "Cuero de pellejo nudoso grueso",
			["Taiwanese"] = "厚重境外皮革",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32456,
		["item_id"] = 25650,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "结缔皮护甲片",
			["English"] = "Knothide Armor Kit",
			["French"] = "Renfort d'armure granuleux",
			["German"] = "Knotenhautrüstungsset",
			["Korean"] = "톱니매듭 방어구 키트",
			["Mexican"] = "Refuerzo para armadura de pellejo nudoso",
			["Portuguese"] = "Kit de Armadura de Couro Nodoso",
			["Russian"] = "Накладки из узловатой кожи",
			["Spanish"] = "Refuerzo para armadura de pellejo nudoso",
			["Taiwanese"] = "境外護甲片",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32457,
		["item_id"] = 25651,
		["items"] = {
			25721,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "守备官的护甲片",
			["English"] = "Vindicator's Armor Kit",
			["French"] = "Renfort d'armure de redresseur de torts",
			["German"] = "Rüstungsset des Verteidigers",
			["Korean"] = "구원자의 방어구 키트",
			["Mexican"] = "Refuerzo para armadura de vindicador",
			["Portuguese"] = "Kit de Armadura do Vindicante",
			["Russian"] = "Накладки для брони воздаятеля",
			["Spanish"] = "Refuerzo para armadura de vindicador",
			["Taiwanese"] = "復仇者護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32458,
		["item_id"] = 25652,
		["items"] = {
			25722,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "魔导师的护甲片",
			["English"] = "Magister's Armor Kit",
			["French"] = "Renfort d'armure de magistère",
			["German"] = "Rüstungsset des Magisters",
			["Korean"] = "마법학자의 방어구 키트",
			["Mexican"] = "Refuerzo para armadura de magister",
			["Portuguese"] = "Kit de Armadura do Magíster",
			["Russian"] = "Накладки для брони магистра",
			["Spanish"] = "Refuerzo para armadura de magister",
			["Taiwanese"] = "博學者護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32461,
		["item_id"] = 25653,
		["items"] = {
			25725,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "马鞭",
			["English"] = "Riding Crop",
			["French"] = "Cravache d'équitation",
			["German"] = "Reitgerte",
			["Korean"] = "말채찍",
			["Mexican"] = "Fusta",
			["Portuguese"] = "Rebenque",
			["Russian"] = "Ездовой хлыст",
			["Spanish"] = "Fusta",
			["Taiwanese"] = "騎乘馬鞭",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32462,
		["item_id"] = 25654,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔鳞手套",
			["English"] = "Felscale Gloves",
			["French"] = "Gants en gangrécailles",
			["German"] = "Teufelsschuppenhandschuhe",
			["Korean"] = "지옥껍질 장갑",
			["Mexican"] = "Guantes de escamas viles",
			["Portuguese"] = "Luvas de Escamavil",
			["Russian"] = "Скверночешуйчатые перчатки",
			["Spanish"] = "Guantes de escamas viles",
			["Taiwanese"] = "魔鱗手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32463,
		["item_id"] = 25655,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "魔鳞长靴",
			["English"] = "Felscale Boots",
			["French"] = "Bottes en gangrécailles",
			["German"] = "Teufelsschuppenstiefel",
			["Korean"] = "지옥껍질 장화",
			["Mexican"] = "Botas de escamas viles",
			["Portuguese"] = "Botas de Escamavil",
			["Russian"] = "Скверночешуйчатые сапоги",
			["Spanish"] = "Botas de escamas viles",
			["Taiwanese"] = "魔鱗長靴",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 18000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32464,
		["item_id"] = 25656,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "魔鳞短裤",
			["English"] = "Felscale Pants",
			["French"] = "Pantalon en gangrécailles",
			["German"] = "Teufelsschuppenhose",
			["Korean"] = "지옥껍질 바지",
			["Mexican"] = "Pantalones de escamas viles",
			["Portuguese"] = "Calças de Escamavil",
			["Russian"] = "Скверночешуйчатые штаны",
			["Spanish"] = "Pantalones de escamas viles",
			["Taiwanese"] = "魔鱗便褲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32465,
		["item_id"] = 25657,
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "魔鳞胸甲",
			["English"] = "Felscale Breastplate",
			["French"] = "Cuirasse en gangrécailles",
			["German"] = "Teufelsschuppenbrustplatte",
			["Korean"] = "지옥껍질 흉갑",
			["Mexican"] = "Coraza de escamas viles",
			["Portuguese"] = "Peitoral de Escamavil",
			["Russian"] = "Скверночешуйчатая кираса",
			["Spanish"] = "Coraza de escamas viles",
			["Taiwanese"] = "魔鱗胸甲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32466,
		["item_id"] = 25662,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "缀鳞德拉诺短裤",
			["English"] = "Scaled Draenic Pants",
			["French"] = "Pantalon draenique en écailles",
			["German"] = "Geschuppte draenische Hose",
			["Korean"] = "드레나이 미늘 바지",
			["Mexican"] = "Pantalones draénicos escamados",
			["Portuguese"] = "Calças Draeneicas em Escamas",
			["Russian"] = "Чешуйчатые дренорские штаны",
			["Spanish"] = "Pantalones draénicos escamados",
			["Taiwanese"] = "德萊尼綴鱗便褲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32467,
		["item_id"] = 25661,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "缀鳞德拉诺手套",
			["English"] = "Scaled Draenic Gloves",
			["French"] = "Gants draeniques en écailles",
			["German"] = "Geschuppte draenische Handschuhe",
			["Korean"] = "드레나이 미늘 장갑",
			["Mexican"] = "Guantes draénicos escamados",
			["Portuguese"] = "Luvas Draeneicas em Escamas",
			["Russian"] = "Чешуйчатые дренорские перчатки",
			["Spanish"] = "Guantes draénicos escamados",
			["Taiwanese"] = "德萊尼綴鱗手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 18000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32468,
		["item_id"] = 25660,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "缀鳞德拉诺外套",
			["English"] = "Scaled Draenic Vest",
			["French"] = "Broigne draenique",
			["German"] = "Geschuppte draenische Weste",
			["Korean"] = "드레나이 미늘 조끼",
			["Mexican"] = "Jubón draénico escamado",
			["Portuguese"] = "Colete Draeneico em Escamas",
			["Russian"] = "Чешуйчатая дренорская безрукавка",
			["Spanish"] = "Jubón draénico escamado",
			["Taiwanese"] = "德萊尼綴鱗外衣",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32469,
		["item_id"] = 25659,
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "缀鳞德拉诺长靴",
			["English"] = "Scaled Draenic Boots",
			["French"] = "Bottes draeniques en écailles",
			["German"] = "Geschuppte draenische Stiefel",
			["Korean"] = "드레나이 미늘 장화",
			["Mexican"] = "Botas draénicas escamadas",
			["Portuguese"] = "Botas Draeneicas em Escamas",
			["Russian"] = "Чешуйчатые дренорские сапоги",
			["Spanish"] = "Botas draénicas escamadas",
			["Taiwanese"] = "德萊尼綴鱗長靴",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32470,
		["item_id"] = 25669,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "厚重德莱尼手套",
			["English"] = "Thick Draenic Gloves",
			["French"] = "Gants draeniques épais",
			["German"] = "Dicke draenische Handschuhe",
			["Korean"] = "두꺼운 드레나이 장갑",
			["Mexican"] = "Guantes draénicos gruesos",
			["Portuguese"] = "Luvas Draeneicas Grossas",
			["Russian"] = "Утолщенные дренорские перчатки",
			["Spanish"] = "Guantes draénicos gruesos",
			["Taiwanese"] = "厚德萊尼手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32471,
		["item_id"] = 25670,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "厚重德莱尼短裤",
			["English"] = "Thick Draenic Pants",
			["French"] = "Pantalon draenique épais",
			["German"] = "Dicke draenische Hose",
			["Korean"] = "두꺼운 드레나이 바지",
			["Mexican"] = "Pantalones draénicos gruesos",
			["Portuguese"] = "Calças Draeneicas Grossas",
			["Russian"] = "Утолщенные дренорские штаны",
			["Spanish"] = "Pantalones draénicos gruesos",
			["Taiwanese"] = "厚德萊尼便褲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 18000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32472,
		["item_id"] = 25668,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "厚重德莱尼长靴",
			["English"] = "Thick Draenic Boots",
			["French"] = "Bottes draeniques épaisses",
			["German"] = "Dicke draenische Stiefel",
			["Korean"] = "두꺼운 드레나이 장화",
			["Mexican"] = "Botas draénicas gruesas",
			["Portuguese"] = "Botas Draeneicas Grossas",
			["Russian"] = "Утолщенные дренорские сапоги",
			["Spanish"] = "Botas draénicas gruesas",
			["Taiwanese"] = "厚德萊尼長靴",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32473,
		["item_id"] = 25671,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "厚重德莱尼外套",
			["English"] = "Thick Draenic Vest",
			["French"] = "Gilet draenique épais",
			["German"] = "Dicke draenische Weste",
			["Korean"] = "두꺼운 드레나이 조끼",
			["Mexican"] = "Jubón draénico grueso",
			["Portuguese"] = "Colete Draeneico Grosso",
			["Russian"] = "Утолщенная дренорская безрукавка",
			["Spanish"] = "Jubón draénico grueso",
			["Taiwanese"] = "厚德萊尼外衣",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32478,
		["item_id"] = 25673,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "野性德莱尼长靴",
			["English"] = "Wild Draenish Boots",
			["French"] = "Bottes draeniques sauvages",
			["German"] = "Wilde draenische Stiefel",
			["Korean"] = "야생의 드레나이 장화",
			["Mexican"] = "Botas draenianas salvajes",
			["Portuguese"] = "Botas Draeneicas Selvagens",
			["Russian"] = "Сапоги дренейского дикаря",
			["Spanish"] = "Botas draenianas salvajes",
			["Taiwanese"] = "狂野德萊尼長靴",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32479,
		["item_id"] = 25674,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "野性德莱尼手套",
			["English"] = "Wild Draenish Gloves",
			["French"] = "Gants draeniques sauvages",
			["German"] = "Wilde draenische Handschuhe",
			["Korean"] = "야생의 드레나이 장갑",
			["Mexican"] = "Guantes draenianos salvajes",
			["Portuguese"] = "Luvas Draeneicas Selvagens",
			["Russian"] = "Перчатки дренейского дикаря",
			["Spanish"] = "Guantes draenianos salvajes",
			["Taiwanese"] = "狂野德萊尼手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 18000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32480,
		["item_id"] = 25675,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "野性德莱尼护腿",
			["English"] = "Wild Draenish Leggings",
			["French"] = "Jambières draeniques sauvages",
			["German"] = "Wilde draenische Gamaschen",
			["Korean"] = "야생의 드레나이 다리보호구",
			["Mexican"] = "Leotardos draenianos salvajes",
			["Portuguese"] = "Perneiras Draeneicas Selvagens",
			["Russian"] = "Поножи дренейского дикаря",
			["Spanish"] = "Leotardos draenianos salvajes",
			["Taiwanese"] = "狂野德萊尼護腿",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32481,
		["item_id"] = 25676,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "野性德莱尼外套",
			["English"] = "Wild Draenish Vest",
			["French"] = "Gilet draenique sauvage",
			["German"] = "Wilde draenische Weste",
			["Korean"] = "야생의 드레나이 조끼",
			["Mexican"] = "Jubón draeniano salvaje",
			["Portuguese"] = "Colete Draeneico Selvagem",
			["Russian"] = "Жилет дренейского дикаря",
			["Spanish"] = "Jubón draeniano salvaje",
			["Taiwanese"] = "狂野德萊尼外衣",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32482,
		["item_id"] = 25679,
		["items"] = {
			25726,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "鞋垫",
			["English"] = "Comfortable Insoles",
			["French"] = "Semelles confortables",
			["German"] = "Bequeme Einlegesohlen",
			["Korean"] = "편안한 깔창",
			["Mexican"] = "Plantillas cómodas",
			["Portuguese"] = "Solas Confortáveis",
			["Russian"] = "Удобные стельки",
			["Spanish"] = "Plantillas cómodas",
			["Taiwanese"] = "舒適的鞋墊",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32485,
		["item_id"] = 25680,
		["items"] = {
			25728,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "斯蒂林的紫皮帽",
			["English"] = "Stylin' Purple Hat",
			["French"] = "Chapeau violet stylé",
			["German"] = "Schicker lilafarbener Hut",
			["Korean"] = "근사한 보라색 모자",
			["Mexican"] = "Sombrero morado a la moda",
			["Portuguese"] = "Chapéu Estiloso Roxo",
			["Russian"] = "Вычурная лиловая шляпа",
			["Spanish"] = "Sombrero morado a la moda",
			["Taiwanese"] = "造型紫色帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32487,
		["item_id"] = 25681,
		["items"] = {
			25729,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "斯蒂林的冒险帽",
			["English"] = "Stylin' Adventure Hat",
			["French"] = "Chapeau d'aventurier stylé",
			["German"] = "Schicker Abenteurerhut",
			["Korean"] = "근사한 모험가 모자",
			["Mexican"] = "Sombrero de aventurero a la moda",
			["Portuguese"] = "Chapéu Estiloso de Aventuras",
			["Russian"] = "Вычурная походная шляпа",
			["Spanish"] = "Sombrero de aventurero a la moda",
			["Taiwanese"] = "造型冒險帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32488,
		["item_id"] = 25683,
		["items"] = {
			25731,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "斯蒂林的赤链帽",
			["English"] = "Stylin' Crimson Hat",
			["French"] = "Chapeau cramoisi stylé",
			["German"] = "Schicker purpurfarbener Hut",
			["Korean"] = "근사한 진홍색 모자",
			["Mexican"] = "Sombrero carmesí a la moda",
			["Portuguese"] = "Chapéu Estiloso Carmesim",
			["Russian"] = "Вычурная багровая шляпа",
			["Spanish"] = "Sombrero carmesí a la moda",
			["Taiwanese"] = "造型紅色帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32489,
		["item_id"] = 25682,
		["items"] = {
			25730,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "斯蒂林的丛林帽",
			["English"] = "Stylin' Jungle Hat",
			["French"] = "Chapeau de jungle stylé",
			["German"] = "Schicker Dschungelhut",
			["Korean"] = "근사한 밀림 모자",
			["Mexican"] = "Sombrero de la jungla a la moda",
			["Portuguese"] = "Chapéu Estiloso de Safári",
			["Russian"] = "Вычурная тропическая шляпа",
			["Spanish"] = "Sombrero de la jungla a la moda",
			["Taiwanese"] = "造型叢林帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32490,
		["item_id"] = 25685,
		["items"] = {
			25732,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "魔能皮甲手套",
			["English"] = "Fel Leather Gloves",
			["French"] = "Gants en gangrecuir",
			["German"] = "Teufelslederhandschuhe",
			["Korean"] = "지옥 가죽 장갑",
			["Mexican"] = "Guantes de cuero vil",
			["Portuguese"] = "Luvas de Couro Vil",
			["Russian"] = "Перчатки из сквернокожи",
			["Spanish"] = "Guantes de cuero vil",
			["Taiwanese"] = "惡魔皮手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32493,
		["item_id"] = 25686,
		["items"] = {
			25733,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔能皮甲长靴",
			["English"] = "Fel Leather Boots",
			["French"] = "Bottes en gangrecuir",
			["German"] = "Teufelslederstiefel",
			["Korean"] = "지옥 가죽 장화",
			["Mexican"] = "Botas de cuero vil",
			["Portuguese"] = "Botas de Couro Vil",
			["Russian"] = "Сапоги из сквернокожи",
			["Spanish"] = "Botas de cuero vil",
			["Taiwanese"] = "惡魔皮靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32494,
		["item_id"] = 25687,
		["items"] = {
			25734,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔能皮甲护腿",
			["English"] = "Fel Leather Leggings",
			["French"] = "Jambières en gangrecuir",
			["German"] = "Teufelsledergamaschen",
			["Korean"] = "지옥 가죽 다리보호구",
			["Mexican"] = "Leotardos de cuero vil",
			["Portuguese"] = "Perneiras de Couro Vil",
			["Russian"] = "Поножи из сквернокожи",
			["Spanish"] = "Leotardos de cuero vil",
			["Taiwanese"] = "惡魔皮護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32495,
		["item_id"] = 25689,
		["items"] = {
			25735,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "厚重裂蹄外套",
			["English"] = "Heavy Clefthoof Vest",
			["French"] = "Gilet du sabot-fourchu épais",
			["German"] = "Schwere Grollhufweste",
			["Korean"] = "질긴 갈래발굽 조끼",
			["Mexican"] = "Jubón de uñagrieta pesado",
			["Portuguese"] = "Colete Pesado de Fenoceronte",
			["Russian"] = "Тяжелый панцирь из шкуры копытня",
			["Spanish"] = "Jubón uñagrieta pesado",
			["Taiwanese"] = "重型裂蹄外衣",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32496,
		["item_id"] = 25690,
		["items"] = {
			25736,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "厚重裂蹄护腿",
			["English"] = "Heavy Clefthoof Leggings",
			["French"] = "Jambières du sabot-fourchu épaisses",
			["German"] = "Schwere Grollhufgamaschen",
			["Korean"] = "질긴 갈래발굽 다리보호구",
			["Mexican"] = "Leotardos de uñagrieta pesados",
			["Portuguese"] = "Perneiras Pesadas de Fenoceronte",
			["Russian"] = "Тяжелые поножи из шкуры копытня",
			["Spanish"] = "Leotardos uñagrieta pesados",
			["Taiwanese"] = "重型裂蹄護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32497,
		["item_id"] = 25691,
		["items"] = {
			25737,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "厚重裂蹄长靴",
			["English"] = "Heavy Clefthoof Boots",
			["French"] = "Bottes du sabot-fourchu épaisses",
			["German"] = "Schwere Grollhufstiefel",
			["Korean"] = "질긴 갈래발굽 장화",
			["Mexican"] = "Botas de uñagrieta pesadas",
			["Portuguese"] = "Botas Pesadas de Fenoceronte",
			["Russian"] = "Тяжелые сапоги из шкуры копытня",
			["Spanish"] = "Botas uñagrieta pesadas",
			["Taiwanese"] = "重型裂蹄長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32498,
		["item_id"] = 25695,
		["items"] = {
			25738,
			29213,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔能猎手腰带",
			["English"] = "Felstalker Belt",
			["French"] = "Ceinture de traqueur gangrené",
			["German"] = "Gürtel des Teufelspirschers",
			["Korean"] = "지옥추적자 허리띠",
			["Mexican"] = "Cinturón de acechador vil",
			["Portuguese"] = "Cinto do Espreitador Vil",
			["Russian"] = "Пояс ловца Скверны",
			["Spanish"] = "Cinturón de acechador vil",
			["Taiwanese"] = "惡魔捕獵者腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32499,
		["item_id"] = 25697,
		["items"] = {
			25739,
			29214,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔能猎手护腕",
			["English"] = "Felstalker Bracer",
			["French"] = "Brassards de traqueur gangrené",
			["German"] = "Armschienen des Teufelspirschers",
			["Korean"] = "지옥추적자 팔보호구",
			["Mexican"] = "Brazal de acechador vil",
			["Portuguese"] = "Braçadeira do Espreitador Vil",
			["Russian"] = "Наручи ловца Скверны",
			["Spanish"] = "Brazal de acechador vil",
			["Taiwanese"] = "惡魔捕獵者護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32500,
		["item_id"] = 25696,
		["items"] = {
			25740,
			29215,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔能猎手胸甲",
			["English"] = "Felstalker Breastplate",
			["French"] = "Cuirasse de traqueur gangrené",
			["German"] = "Brustplatte des Teufelspirschers",
			["Korean"] = "지옥추적자 흉갑",
			["Mexican"] = "Coraza de acechador vil",
			["Portuguese"] = "Peitoral do Espreitador Vil",
			["Russian"] = "Кираса ловца Скверны",
			["Spanish"] = "Coraza de acechador vil",
			["Taiwanese"] = "惡魔捕獵者胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32501,
		["item_id"] = 25694,
		["items"] = {
			25741,
			29217,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "虚空之怒腰带",
			["English"] = "Netherfury Belt",
			["French"] = "Ceinture de la Furie du Néant",
			["German"] = "Netherzorngürtel",
			["Korean"] = "황천의 격노 허리띠",
			["Mexican"] = "Cinturón de furia abisal",
			["Portuguese"] = "Cinto da Fúria Etérea",
			["Russian"] = "Пояс неистовства пустоты",
			["Spanish"] = "Cinturón de furia abisal",
			["Taiwanese"] = "虛空之怒腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32502,
		["item_id"] = 25692,
		["items"] = {
			25742,
			29219,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "虚空之怒护腿",
			["English"] = "Netherfury Leggings",
			["French"] = "Jambières de la Furie du Néant",
			["German"] = "Netherzorngamaschen",
			["Korean"] = "황천의 격노 다리보호구",
			["Mexican"] = "Leotardos de furia abisal",
			["Portuguese"] = "Perneiras da Fúria Etérea",
			["Russian"] = "Поножи неистовства пустоты",
			["Spanish"] = "Leotardos de furia abisal",
			["Taiwanese"] = "虛空之怒護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32503,
		["item_id"] = 25693,
		["items"] = {
			25743,
			29218,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "虚空之怒长靴",
			["English"] = "Netherfury Boots",
			["French"] = "Bottes de la Furie du Néant",
			["German"] = "Netherzornstiefel",
			["Korean"] = "황천의 격노 장화",
			["Mexican"] = "Botas de furia abisal",
			["Portuguese"] = "Botas da Fúria Etérea",
			["Russian"] = "Сапоги неистовства пустоты",
			["Spanish"] = "Botas de furia abisal",
			["Taiwanese"] = "虛空之怒長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35520,
		["item_id"] = 29483,
		["items"] = {
			29669,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "暗影护甲片",
			["English"] = "Shadow Armor Kit",
			["French"] = "Renfort d'armure de l'Ombre",
			["German"] = "Schattenrüstungsset",
			["Korean"] = "암흑 방어구 키트",
			["Mexican"] = "Refuerzo para armadura contra las Sombras",
			["Portuguese"] = "Kit de Armadura Sombria",
			["Russian"] = "Накладки сопротивления темной магии",
			["Spanish"] = "Refuerzo para armadura de las Sombras",
			["Taiwanese"] = "暗影護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35521,
		["item_id"] = 29485,
		["items"] = {
			29672,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "烈焰护甲片",
			["English"] = "Flame Armor Kit",
			["French"] = "Renfort d'armure des Flammes",
			["German"] = "Flammenrüstungsset",
			["Korean"] = "화염 방어구 키트",
			["Mexican"] = "Refuerzo para armadura contra las llamas",
			["Portuguese"] = "Kit de Armadura Ígnea",
			["Russian"] = "Накладки сопротивления огню",
			["Spanish"] = "Refuerzo para armadura contra las llamas",
			["Taiwanese"] = "烈焰護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35522,
		["item_id"] = 29486,
		["items"] = {
			29673,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "冰霜护甲片",
			["English"] = "Frost Armor Kit",
			["French"] = "Renfort d'armure de Givre",
			["German"] = "Frostrüstungsset",
			["Korean"] = "냉기 방어구 키트",
			["Mexican"] = "Refuerzo para armadura contra Escarcha",
			["Portuguese"] = "Kit de Armadura Gélida",
			["Russian"] = "Накладки сопротивления магии льда",
			["Spanish"] = "Refuerzo para armadura contra Escarcha",
			["Taiwanese"] = "寒冰護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35523,
		["item_id"] = 29487,
		["items"] = {
			29674,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "自然护甲片",
			["English"] = "Nature Armor Kit",
			["French"] = "Renfort d'armure de la Nature",
			["German"] = "Naturrüstungsset",
			["Korean"] = "자연 방어구 키트",
			["Mexican"] = "Refuerzo para armadura contra la Naturaleza",
			["Portuguese"] = "Kit de Armadura Natural",
			["Russian"] = "Накладки сопротивления силам природы",
			["Spanish"] = "Refuerzo para armadura contra la Naturaleza",
			["Taiwanese"] = "自然護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35524,
		["item_id"] = 29488,
		["items"] = {
			29675,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "奥术护甲片",
			["English"] = "Arcane Armor Kit",
			["French"] = "Renfort d'armure des Arcanes",
			["German"] = "Arkanrüstungsset",
			["Korean"] = "비전 방어구 키트",
			["Mexican"] = "Refuerzo para armadura Arcano",
			["Portuguese"] = "Kit de Armadura Arcana",
			["Russian"] = "Накладки сопротивления тайной магии",
			["Spanish"] = "Refuerzo para armadura Arcano",
			["Taiwanese"] = "秘法護甲片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35525,
		["item_id"] = 29489,
		["items"] = {
			29677,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化邪鳞护腿",
			["English"] = "Enchanted Felscale Leggings",
			["French"] = "Jambières enchantées en gangrécailles",
			["German"] = "Verzauberte Teufelsschuppengamaschen",
			["Korean"] = "마력 깃든 지옥껍질 다리보호구",
			["Mexican"] = "Leotardos de escamas viles encantados",
			["Portuguese"] = "Perneiras Encantadas de Escamavil",
			["Russian"] = "Зачарованные скверночешуйчатые поножи",
			["Spanish"] = "Leotardos de escamas viles encantados",
			["Taiwanese"] = "附魔魔鱗護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35526,
		["item_id"] = 29490,
		["items"] = {
			29682,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化邪鳞手套",
			["English"] = "Enchanted Felscale Gloves",
			["French"] = "Gants enchantés en gangrécailles",
			["German"] = "Verzauberte Teufelsschuppenhandschuhe",
			["Korean"] = "마력 깃든 지옥껍질 장갑",
			["Mexican"] = "Guantes de escamas viles encantados",
			["Portuguese"] = "Luvas Encantadas de Escamavil",
			["Russian"] = "Зачарованные скверночешуйчатые перчатки",
			["Spanish"] = "Guantes de escamas viles encantados",
			["Taiwanese"] = "附魔魔鱗手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35527,
		["item_id"] = 29491,
		["items"] = {
			29684,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化邪鳞长靴",
			["English"] = "Enchanted Felscale Boots",
			["French"] = "Bottes enchantées en gangrécailles",
			["German"] = "Verzauberte Teufelsschuppenstiefel",
			["Korean"] = "마력 깃든 지옥껍질 장화",
			["Mexican"] = "Botas de escamas viles encantadas",
			["Portuguese"] = "Botas Encantadas de Escamavil",
			["Russian"] = "Зачарованные скверночешуйчатые сапоги",
			["Spanish"] = "Botas de escamas viles encantadas",
			["Taiwanese"] = "附魔魔鱗長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35528,
		["item_id"] = 29493,
		["items"] = {
			29691,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "焰鳞长靴",
			["English"] = "Flamescale Boots",
			["French"] = "Bottes en flamécaille",
			["German"] = "Flammenschuppenstiefel",
			["Korean"] = "화염비늘 장화",
			["Mexican"] = "Botas de flamaescama",
			["Portuguese"] = "Botas de Flamescama",
			["Russian"] = "Огнечешуйчатые сапоги",
			["Spanish"] = "Botas de flamaescama",
			["Taiwanese"] = "火鱗長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35529,
		["item_id"] = 29492,
		["items"] = {
			29689,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "焰鳞护腿",
			["English"] = "Flamescale Leggings",
			["French"] = "Jambières en flamécaille",
			["German"] = "Flammenschuppengamaschen",
			["Korean"] = "화염비늘 다리보호구",
			["Mexican"] = "Leotardos de flamaescama",
			["Portuguese"] = "Perneiras de Flamescama",
			["Russian"] = "Огнечешуйчатые поножи",
			["Spanish"] = "Leotardos de flamaescama",
			["Taiwanese"] = "火鱗護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35530,
		["item_id"] = 29540,
		["items"] = {
			29664,
			30444,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "加固矿工袋",
			["English"] = "Reinforced Mining Bag",
			["French"] = "Sac de mineur renforcé",
			["German"] = "Verstärkte Bergbautasche",
			["Korean"] = "강화된 채광용 자루",
			["Mexican"] = "Bolsa de minero reforzada",
			["Portuguese"] = "Bolsa de Mineração Reforçada",
			["Russian"] = "Укрепленная шахтерская сумка",
			["Spanish"] = "Bolsa de minero reforzada",
			["Taiwanese"] = "強化礦石包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35531,
		["item_id"] = 29494,
		["items"] = {
			29693,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "焰鳞腰带",
			["English"] = "Flamescale Belt",
			["French"] = "Ceinture en flamécaille",
			["German"] = "Flammenschuppengürtel",
			["Korean"] = "화염비늘 허리띠",
			["Mexican"] = "Cinturón de flamaescama",
			["Portuguese"] = "Cinto de Flamescama",
			["Russian"] = "Огнечешуйчатый пояс",
			["Spanish"] = "Cinturón de flamaescama",
			["Taiwanese"] = "火鱗腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35532,
		["item_id"] = 29495,
		["items"] = {
			29698,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化裂蹄护腿",
			["English"] = "Enchanted Clefthoof Leggings",
			["French"] = "Jambières enchantées en sabot-fourchu",
			["German"] = "Verzauberte Grollhufgamaschen",
			["Korean"] = "마력 깃든 갈래발굽 다리보호구",
			["Mexican"] = "Leotardos de uñagrieta encantados",
			["Portuguese"] = "Perneiras Encantadas de Fenoceronte",
			["Russian"] = "Зачарованные поножи из шкуры копытня",
			["Spanish"] = "Leotardos uñagrieta encantados",
			["Taiwanese"] = "附魔裂蹄護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35533,
		["item_id"] = 29496,
		["items"] = {
			29700,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化裂蹄手套",
			["English"] = "Enchanted Clefthoof Gloves",
			["French"] = "Gants enchantés en sabot-fourchu",
			["German"] = "Verzauberte Grollhufhandschuhe",
			["Korean"] = "마력 깃든 갈래발굽 장갑",
			["Mexican"] = "Guantes de uñagrieta encantados",
			["Portuguese"] = "Luvas Encantadas de Fenoceronte",
			["Russian"] = "Зачарованные перчатки из шкуры копытня",
			["Spanish"] = "Guantes uñagrieta encantados",
			["Taiwanese"] = "附魔裂蹄手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35534,
		["item_id"] = 29497,
		["items"] = {
			29701,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化裂蹄长靴",
			["English"] = "Enchanted Clefthoof Boots",
			["French"] = "Bottes enchantées en sabot-fourchu",
			["German"] = "Verzauberte Grollhufstiefel",
			["Korean"] = "마력 깃든 갈래발굽 장화",
			["Mexican"] = "Botas de uñagrieta encantadas",
			["Portuguese"] = "Botas Encantadas de Fenoceronte",
			["Russian"] = "Зачарованные сапоги из шкуры копытня",
			["Spanish"] = "Botas uñagrieta encantadas",
			["Taiwanese"] = "附魔裂蹄長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35535,
		["item_id"] = 29498,
		["items"] = {
			29702,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "爆炸防护短裤",
			["English"] = "Blastguard Pants",
			["French"] = "Pantalon de déminage",
			["German"] = "Lohenschildhose",
			["Korean"] = "폭풍막이 바지",
			["Mexican"] = "Pantalones antiexplosión",
			["Portuguese"] = "Calças Antibombas",
			["Russian"] = "Взрывостойкие штаны",
			["Spanish"] = "Pantalones antiexplosión",
			["Taiwanese"] = "爆烈守衛便褲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35536,
		["item_id"] = 29499,
		["items"] = {
			29703,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "爆炸防护长靴",
			["English"] = "Blastguard Boots",
			["French"] = "Bottes de déminage",
			["German"] = "Lohenschildstiefel",
			["Korean"] = "폭풍막이 장화",
			["Mexican"] = "Botas antiexplosión",
			["Portuguese"] = "Botas Antibombas",
			["Russian"] = "Взрывостойкие сапоги",
			["Spanish"] = "Botas antiexplosión",
			["Taiwanese"] = "爆烈守衛長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35537,
		["item_id"] = 29500,
		["items"] = {
			29704,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "爆炸防护腰带",
			["English"] = "Blastguard Belt",
			["French"] = "Ceinture de déminage",
			["German"] = "Lohenschildgürtel",
			["Korean"] = "폭풍막이 허리띠",
			["Mexican"] = "Cinturón antiexplosión",
			["Portuguese"] = "Cinto Antibombas",
			["Russian"] = "Взрывостойкий пояс",
			["Spanish"] = "Cinturón antiexplosión",
			["Taiwanese"] = "爆烈守衛腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35538,
		["item_id"] = 29532,
		["items"] = {
			29713,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "恐慌之鼓",
			["English"] = "Drums of Panic",
			["French"] = "Tambours de panique",
			["German"] = "Trommeln der Panik",
			["Korean"] = "공황의 북소리",
			["Mexican"] = "Tambores de pánico",
			["Portuguese"] = "Tambores do Pânico",
			["Russian"] = "Барабаны паники",
			["Spanish"] = "Tambores de pánico",
			["Taiwanese"] = "驚慌之鼓",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35539,
		["item_id"] = 29531,
		["items"] = {
			29714,
			34174,
			34175,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "恢复之鼓",
			["English"] = "Drums of Restoration",
			["French"] = "Tambours de restauration",
			["German"] = "Trommeln der Wiederherstellung",
			["Korean"] = "회복의 북소리",
			["Mexican"] = "Tambores de restauración",
			["Portuguese"] = "Tambores de Restauração",
			["Russian"] = "Барабаны восстановления",
			["Spanish"] = "Tambores de restauración",
			["Taiwanese"] = "恢復之鼓",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35540,
		["item_id"] = 29528,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "战争之鼓",
			["English"] = "Drums of War",
			["French"] = "Tambours de guerre",
			["German"] = "Trommeln des Krieges",
			["Korean"] = "전쟁의 북소리",
			["Mexican"] = "Tambores de guerra",
			["Portuguese"] = "Tambores da Guerra",
			["Russian"] = "Барабаны войны",
			["Spanish"] = "Tambores de guerra",
			["Taiwanese"] = "戰爭之鼓",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35543,
		["item_id"] = 29529,
		["items"] = {
			29717,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "战斗之鼓",
			["English"] = "Drums of Battle",
			["French"] = "Tambours de bataille",
			["German"] = "Trommeln der Schlacht",
			["Korean"] = "전투의 북소리",
			["Mexican"] = "Tambores de batalla",
			["Portuguese"] = "Tambores de Batalha",
			["Russian"] = "Барабаны битвы",
			["Spanish"] = "Tambores de batalla",
			["Taiwanese"] = "戰鬥之鼓",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35544,
		["item_id"] = 29530,
		["items"] = {
			29718,
			34172,
			34173,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "速度之鼓",
			["English"] = "Drums of Speed",
			["French"] = "Tambours de vitesse",
			["German"] = "Trommeln des Tempos",
			["Korean"] = "신속의 북소리",
			["Mexican"] = "Tambores de velocidad",
			["Portuguese"] = "Tambores de Velocidade",
			["Russian"] = "Барабаны скорости",
			["Spanish"] = "Tambores de velocidad",
			["Taiwanese"] = "速度之鼓",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35549,
		["item_id"] = 29533,
		["items"] = {
			29719,
			31361,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "眼镜蛇皮腿甲片",
			["English"] = "Cobrahide Leg Armor",
			["French"] = "Armure de jambe en peau de cobra",
			["German"] = "Kobrahautbeinrüstung",
			["Korean"] = "코브라가죽 다리 방어구 강화 키트",
			["Mexican"] = "Armadura para pierna de pellejo de cobra",
			["Portuguese"] = "Armadura de Perna de Pelego de Naja",
			["Russian"] = "Накладки для поножей из кожи кобры",
			["Spanish"] = "Armadura para pierna de pellejo de cobra",
			["Taiwanese"] = "眼鏡蛇皮護腿片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35554,
		["item_id"] = 29535,
		["items"] = {
			29722,
			31362,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "虚空毒蛇腿甲片",
			["English"] = "Nethercobra Leg Armor",
			["French"] = "Armure de jambe en cobra du Néant",
			["German"] = "Netherkobrabeinrüstung",
			["Korean"] = "황천의 코브라 다리 방어구 강화 키트",
			["Mexican"] = "Armadura para pierna cobra abisal",
			["Portuguese"] = "Armadura de Perna de Eternaja",
			["Russian"] = "Накладки для поножей из чешуи кобры",
			["Spanish"] = "Armadura para pierna cobra abisal",
			["Taiwanese"] = "虛空眼鏡蛇護腿片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35555,
		["item_id"] = 29534,
		["items"] = {
			29720,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "裂蹄腿甲片",
			["English"] = "Clefthide Leg Armor",
			["French"] = "Armure de jambe en cuir-fourchu",
			["German"] = "Grollbalgbeinrüstung",
			["Korean"] = "갈래가죽 다리 방어구 강화 키트",
			["Mexican"] = "Armadura para pierna de pellejo grieta",
			["Portuguese"] = "Armadura de Perna de Pelego de Fenoceronte",
			["Russian"] = "Накладки для поножей из шкуры копытня",
			["Spanish"] = "Armadura para pierna de pellejo grieta",
			["Taiwanese"] = "裂蹄皮護腿片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35557,
		["item_id"] = 29536,
		["items"] = {
			29721,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "虚空裂蹄腿甲片",
			["English"] = "Nethercleft Leg Armor",
			["French"] = "Armure de jambe de faille du Néant",
			["German"] = "Netherkluftbeinrüstung",
			["Korean"] = "황천의 갈래 다리 방어구 강화 키트",
			["Mexican"] = "Armadura para pierna grieta abisal",
			["Portuguese"] = "Armadura de Perna de Fenoceréter",
			["Russian"] = "Накладки для поножей из кожи копытня",
			["Spanish"] = "Armadura para pierna grieta abisal",
			["Taiwanese"] = "虛空裂蹄護腿片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35558,
		["item_id"] = 29502,
		["items"] = {
			29723,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "眼镜蛇鳞片兜帽",
			["English"] = "Cobrascale Hood",
			["French"] = "Capuche en écailles de cobra",
			["German"] = "Kobraschuppenkapuze",
			["Korean"] = "코브라 비늘 두건",
			["Mexican"] = "Caperuza de escamas de cobra",
			["Portuguese"] = "Capuz de Escama de Naja",
			["Russian"] = "Капюшон из чешуи кобры",
			["Spanish"] = "Caperuza de escamas de cobra",
			["Taiwanese"] = "眼鏡蛇鱗頭套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35559,
		["item_id"] = 29503,
		["items"] = {
			29724,
			35302,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "眼镜蛇鳞片手套",
			["English"] = "Cobrascale Gloves",
			["French"] = "Gants en écailles de cobra",
			["German"] = "Kobraschuppenhandschuhe",
			["Korean"] = "코브라 비늘 장갑",
			["Mexican"] = "Guantes de escamas de cobra",
			["Portuguese"] = "Luvas de Escama de Naja",
			["Russian"] = "Перчатки из чешуи кобры",
			["Spanish"] = "Guantes de escamas de cobra",
			["Taiwanese"] = "眼鏡蛇鱗手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35560,
		["item_id"] = 29504,
		["items"] = {
			29725,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "风鳞兜帽",
			["English"] = "Windscale Hood",
			["French"] = "Capuche en écailles du vent",
			["German"] = "Windschuppenkapuze",
			["Korean"] = "바람비늘 두건",
			["Mexican"] = "Caperuza de escamas de viento",
			["Portuguese"] = "Capuz de Escamas de Vento",
			["Russian"] = "Ветрочешуйчатый капюшон",
			["Spanish"] = "Caperuza de escamas de viento",
			["Taiwanese"] = "風鱗兜帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35561,
		["item_id"] = 29505,
		["items"] = {
			29726,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "源生生命罩帽",
			["English"] = "Hood of Primal Life",
			["French"] = "Chaperon de vie primordiale",
			["German"] = "Kapuze des Urlebens",
			["Korean"] = "근원 생명의 두건",
			["Mexican"] = "Caperuza de vida primigenia",
			["Portuguese"] = "Capuz da Vida Primeva",
			["Russian"] = "Капюшон изначальной жизни",
			["Spanish"] = "Caperuza de vida primigenia",
			["Taiwanese"] = "原始生命兜帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35562,
		["item_id"] = 29506,
		["items"] = {
			29727,
			35303,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "生命之触手套",
			["English"] = "Gloves of the Living Touch",
			["French"] = "Gants du toucher de vie",
			["German"] = "Handschuhe der lebendigen Berührung",
			["Korean"] = "생명이 넘치는 손길의 장갑",
			["Mexican"] = "Guantes del toque viviente",
			["Portuguese"] = "Luvas do Toque Vivo",
			["Russian"] = "Перчатки живого прикосновения",
			["Spanish"] = "Guantes del toque viviente",
			["Taiwanese"] = "生命之觸手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35563,
		["item_id"] = 29507,
		["items"] = {
			29728,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "风斩裹手",
			["English"] = "Windslayer Wraps",
			["French"] = "Protège-mains de tueur du vent",
			["German"] = "Windtöterwickel",
			["Korean"] = "바람의 학살자 장갑",
			["Mexican"] = "Guantes destripaviento",
			["Portuguese"] = "Braçadeiras do Mataventos",
			["Russian"] = "Напульсники ветроубийцы",
			["Spanish"] = "Guantes destripaviento",
			["Taiwanese"] = "屠風者裹帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35564,
		["item_id"] = 29508,
		["items"] = {
			29729,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "生命龙鳞头盔",
			["English"] = "Living Dragonscale Helm",
			["French"] = "Casque vivant en écailles de dragon",
			["German"] = "Lebendiger Drachenschuppenhelm",
			["Korean"] = "생명의 용비늘 투구",
			["Mexican"] = "Yelmo de dragontina viviente",
			["Portuguese"] = "Elmo Vivo de Escama de Dragão",
			["Russian"] = "Животворный шлем из чешуи дракона",
			["Spanish"] = "Yelmo de escamas de dragón viviente",
			["Taiwanese"] = "生命龍鱗頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35567,
		["item_id"] = 29512,
		["items"] = {
			29730,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "土灵虚鳞长靴",
			["English"] = "Earthen Netherscale Boots",
			["French"] = "Bottes terrestres en écailles du Néant",
			["German"] = "Irdene Netherschuppenstiefel",
			["Korean"] = "대지의 황천비늘 장화",
			["Mexican"] = "Botas de escamas abisales terráneas",
			["Portuguese"] = "Botas Terrenas de Escama Etérea",
			["Russian"] = "Сапоги земли из чешуи дракона Пустоты",
			["Spanish"] = "Botas de escamas abisales terráneas",
			["Taiwanese"] = "土靈虛空鱗長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35568,
		["item_id"] = 29509,
		["items"] = {
			29731,
			35300,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "风击手套",
			["English"] = "Windstrike Gloves",
			["French"] = "Gants du Frappevent",
			["German"] = "Windstoßhandschuhe",
			["Korean"] = "바람쐐기 장갑",
			["Mexican"] = "Guantes de golpe de viento",
			["Portuguese"] = "Luvas do Golpe de Vento",
			["Russian"] = "Перчатки налетевшего ветра",
			["Spanish"] = "Guantes de golpe de viento",
			["Taiwanese"] = "風擊手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35572,
		["item_id"] = 29510,
		["items"] = {
			29732,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "虚空幼龙头盔",
			["English"] = "Netherdrake Helm",
			["French"] = "Casque de drake du Néant",
			["German"] = "Netherdrachenhelm",
			["Korean"] = "황천의 비룡 투구",
			["Mexican"] = "Yelmo de draco abisal",
			["Portuguese"] = "Elmo de Draco Etéreo",
			["Russian"] = "Шлем дракона Пустоты",
			["Spanish"] = "Yelmo de draco abisal",
			["Taiwanese"] = "虛空龍頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35573,
		["item_id"] = 29511,
		["items"] = {
			29733,
			35301,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "虚空幼龙手套",
			["English"] = "Netherdrake Gloves",
			["French"] = "Gants de drake du Néant",
			["German"] = "Netherdrachenhandschuhe",
			["Korean"] = "황천의 비룡 장갑",
			["Mexican"] = "Guantes de draco abisal",
			["Portuguese"] = "Luvas de Draco Etéreo",
			["Russian"] = "Перчатки дракона Пустоты",
			["Spanish"] = "Guantes de draco abisal",
			["Taiwanese"] = "虛空龍手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35574,
		["item_id"] = 29514,
		["items"] = {
			29734,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "厚重虚空鳞片胸甲",
			["English"] = "Thick Netherscale Breastplate",
			["French"] = "Cuirasse épaisse en écailles du Néant",
			["German"] = "Dicke Netherschuppenbrustplatte",
			["Korean"] = "두꺼운 황천비늘 흉갑",
			["Mexican"] = "Coraza de escamas abisales gruesa",
			["Portuguese"] = "Peitoral Grosso de Escama Etérea",
			["Russian"] = "Плотная кираса из чешуи дракона Пустоты",
			["Spanish"] = "Coraza de escamas abisales gruesa",
			["Taiwanese"] = "厚虛空鱗胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 35575,
		["item_id"] = 29515,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "黑色虚鳞胸甲",
			["English"] = "Ebon Netherscale Breastplate",
			["French"] = "Cuirasse d'ébène en écailles du Néant",
			["German"] = "Ebenholzfarbene Netherschuppenbrustplatte",
			["Korean"] = "칠흑의 황천비늘 흉갑",
			["Mexican"] = "Coraza de escamas abisales de ébano",
			["Portuguese"] = "Peitoral de Ébano de Escama Etérea",
			["Russian"] = "Черная кираса из чешуи дракона Пустоты",
			["Spanish"] = "Coraza de escamas abisales de ébano",
			["Taiwanese"] = "黑虛空鱗胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35576,
		["item_id"] = 29516,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "黑色虚鳞腰带",
			["English"] = "Ebon Netherscale Belt",
			["French"] = "Ceinture d'ébène en écailles du Néant",
			["German"] = "Ebenholzfarbener Netherschuppengürtel",
			["Korean"] = "칠흑의 황천비늘 허리띠",
			["Mexican"] = "Cinturón de escamas abisales de ébano",
			["Portuguese"] = "Cinto de Ébano de Escama Etérea",
			["Russian"] = "Черный пояс из чешуи дракона Пустоты",
			["Spanish"] = "Cinturón de escamas abisales de ébano",
			["Taiwanese"] = "黑虛空鱗腰帶",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35577,
		["item_id"] = 29517,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "黑色虚鳞护腕",
			["English"] = "Ebon Netherscale Bracers",
			["French"] = "Brassards d'ébène en écailles du Néant",
			["German"] = "Ebenholzfarbene Netherschuppenarmschienen",
			["Korean"] = "칠흑의 황천비늘 팔보호구",
			["Mexican"] = "Brazales de escamas abisales de ébano",
			["Portuguese"] = "Braçadeiras de Ébano de Escama Etérea",
			["Russian"] = "Черные наручи из чешуи дракона Пустоты",
			["Spanish"] = "Brazales de escamas abisales de ébano",
			["Taiwanese"] = "黑虛空鱗護腕",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35580,
		["item_id"] = 29519,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "虚空打击胸甲",
			["English"] = "Netherstrike Breastplate",
			["French"] = "Cuirasse Coup-de-Néant",
			["German"] = "Netherstoßbrustplatte",
			["Korean"] = "황천쐐기 흉갑",
			["Mexican"] = "Coraza de golpe abisal",
			["Portuguese"] = "Peitoral do Golpe Etéreo",
			["Russian"] = "Кираса удара Пустоты",
			["Spanish"] = "Coraza de golpe abisal",
			["Taiwanese"] = "地擊胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35582,
		["item_id"] = 29520,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "虚空打击腰带",
			["English"] = "Netherstrike Belt",
			["French"] = "Ceinture Coup-de-Néant",
			["German"] = "Netherstoßgürtel",
			["Korean"] = "황천쐐기 허리띠",
			["Mexican"] = "Cinturón de golpe abisal",
			["Portuguese"] = "Cinto do Golpe Etéreo",
			["Russian"] = "Пояс удара Пустоты",
			["Spanish"] = "Cinturón de golpe abisal",
			["Taiwanese"] = "地擊腰帶",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35584,
		["item_id"] = 29521,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "虚空打击护腕",
			["English"] = "Netherstrike Bracers",
			["French"] = "Brassards Coup-de-Néant",
			["German"] = "Netherstoßarmschienen",
			["Korean"] = "황천쐐기 팔보호구",
			["Mexican"] = "Brazales de golpe abisal",
			["Portuguese"] = "Braçadeiras do Golpe Etéreo",
			["Russian"] = "Наручи удара Пустоты",
			["Spanish"] = "Brazales de golpe abisal",
			["Taiwanese"] = "地擊護腕",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35585,
		["item_id"] = 29522,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "风鹰胸甲",
			["English"] = "Windhawk Hauberk",
			["French"] = "Haubert Faucon-du-vent",
			["German"] = "Windfalkenhalsberge",
			["Korean"] = "바람매 갑옷",
			["Mexican"] = "Camisote de halcón del viento",
			["Portuguese"] = "Cota do Falcão do Vento",
			["Russian"] = "Хауберк легкокрылого ястреба",
			["Spanish"] = "Camisote de halcón del viento",
			["Taiwanese"] = "風之隼鍊衫",
		},
		["phase"] = 1,
		["specialisation"] = 10660,
		["trainers"] = {
			["price"] = 85000,
			["sources"] = {
				7870,
				7871,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35587,
		["item_id"] = 29524,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "风鹰腰带",
			["English"] = "Windhawk Belt",
			["French"] = "Ceinture Faucon-du-vent",
			["German"] = "Windfalkengürtel",
			["Korean"] = "바람매 허리띠",
			["Mexican"] = "Cinturón de halcón del viento",
			["Portuguese"] = "Cinto do Falcão do Vento",
			["Russian"] = "Пояс легкокрылого ястреба",
			["Spanish"] = "Cinturón de halcón del viento",
			["Taiwanese"] = "風之隼腰帶",
		},
		["phase"] = 1,
		["specialisation"] = 10660,
		["trainers"] = {
			["price"] = 85000,
			["sources"] = {
				7870,
				7871,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35588,
		["item_id"] = 29523,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "风鹰护腕",
			["English"] = "Windhawk Bracers",
			["French"] = "Brassards Faucon-du-vent",
			["German"] = "Windfalkenarmschienen",
			["Korean"] = "바람매 팔보호구",
			["Mexican"] = "Brazales de halcón del viento",
			["Portuguese"] = "Braçadeiras do Falcão do Vento",
			["Russian"] = "Наручи легкокрылого ястреба",
			["Spanish"] = "Brazales de halcón del viento",
			["Taiwanese"] = "風之隼護腕",
		},
		["phase"] = 1,
		["specialisation"] = 10660,
		["trainers"] = {
			["price"] = 85000,
			["sources"] = {
				7870,
				7871,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35589,
		["item_id"] = 29525,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "原始打击外衣",
			["English"] = "Primalstrike Vest",
			["French"] = "Gilet de frappe primordiale",
			["German"] = "Erstschlagweste",
			["Korean"] = "원소쐐기 조끼",
			["Mexican"] = "Jubón de golpe primigenio",
			["Portuguese"] = "Colete do Golpe Primevo",
			["Russian"] = "Жилет упреждающего удара",
			["Spanish"] = "Jubón de golpe primigenio",
			["Taiwanese"] = "原始之擊外衣",
		},
		["phase"] = 1,
		["specialisation"] = 10658,
		["trainers"] = {
			["price"] = 90000,
			["sources"] = {
				7869,
				7868,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35590,
		["item_id"] = 29526,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "原始打击腰带",
			["English"] = "Primalstrike Belt",
			["French"] = "Ceinture de frappe primordiale",
			["German"] = "Erstschlaggürtel",
			["Korean"] = "원소쐐기 허리띠",
			["Mexican"] = "Cinturón de golpe primigenio",
			["Portuguese"] = "Cinto do Golpe Primevo",
			["Russian"] = "Пояс упреждающего удара",
			["Spanish"] = "Cinturón de golpe primigenio",
			["Taiwanese"] = "原始之擊腰帶",
		},
		["phase"] = 1,
		["specialisation"] = 10658,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7869,
				7868,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35591,
		["item_id"] = 29527,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "原始打击护腕",
			["English"] = "Primalstrike Bracers",
			["French"] = "Brassards de frappe primordiale",
			["German"] = "Erstschlagarmschienen",
			["Korean"] = "원소쐐기 팔보호구",
			["Mexican"] = "Brazales de golpe primigenio",
			["Portuguese"] = "Braçadeiras do Golpe Primevo",
			["Russian"] = "Наручи упреждающего удара",
			["Spanish"] = "Brazales de golpe primigenio",
			["Taiwanese"] = "原始之擊護腕",
		},
		["phase"] = 1,
		["specialisation"] = 10658,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7869,
				7868,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36074,
		["item_id"] = 29964,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "黑色风暴护腿",
			["English"] = "Blackstorm Leggings",
			["French"] = "Jambières de Noir-orage",
			["German"] = "Gamaschen des schwarzen Sturms",
			["Korean"] = "검은폭풍 다리보호구",
			["Mexican"] = "Leotardos de tormenta negra",
			["Portuguese"] = "Perneiras da Tempestade Negra",
			["Russian"] = "Поножи Черной бури",
			["Spanish"] = "Leotardos de tormenta negra",
			["Taiwanese"] = "黑色風暴護腿",
		},
		["phase"] = 1,
		["specialisation"] = 10658,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				7869,
				7868,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36075,
		["item_id"] = 29970,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "野羽护腿",
			["English"] = "Wildfeather Leggings",
			["French"] = "Jambières de plumes sauvages",
			["German"] = "Wildfedergamaschen",
			["Korean"] = "바람깃털 다리보호구",
			["Mexican"] = "Leotardos plumasalvaje",
			["Portuguese"] = "Perneiras de Penagreste",
			["Russian"] = "Поножи Дикого Пера",
			["Spanish"] = "Leotardos plumasalvaje",
			["Taiwanese"] = "野性之皮護腿",
		},
		["phase"] = 1,
		["specialisation"] = 10660,
		["trainers"] = {
			["price"] = 8500,
			["sources"] = {
				7870,
				7871,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36076,
		["item_id"] = 29971,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "龙击护腿",
			["English"] = "Dragonstrike Leggings",
			["French"] = "Jambières de frappe de dragon",
			["German"] = "Gamaschen des Drachenschlags",
			["Korean"] = "용쐐기 다리보호구",
			["Mexican"] = "Leotardos de golpe de dragón",
			["Portuguese"] = "Perneiras do Golpe de Dragão",
			["Russian"] = "Поножи Драконоборца",
			["Spanish"] = "Leotardos de golpe de dragón",
			["Taiwanese"] = "龍擊護腿",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36077,
		["item_id"] = 29973,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "原始风暴胸甲",
			["English"] = "Primalstorm Breastplate",
			["French"] = "Cuirasse de tempête primordiale",
			["German"] = "Brustplatte des Ursturms",
			["Korean"] = "원소폭풍 흉갑",
			["Mexican"] = "Coraza de tormenta primigenia",
			["Portuguese"] = "Peitoral da Tempestade Primeva",
			["Russian"] = "Кираса извечного шторма",
			["Spanish"] = "Coraza de tormenta primigenia",
			["Taiwanese"] = "原始風暴胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 10658,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				7869,
				7868,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36078,
		["item_id"] = 29974,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "生命水晶胸甲",
			["English"] = "Living Crystal Breastplate",
			["French"] = "Cuirasse vivante en cristal",
			["German"] = "Lebendige Kristallbrustplatte",
			["Korean"] = "생명의 수정 흉갑",
			["Mexican"] = "Coraza de cristal viviente",
			["Portuguese"] = "Peitoral de Cristal Vivo",
			["Russian"] = "Кираса живых кристаллов",
			["Spanish"] = "Coraza de cristal viviente",
			["Taiwanese"] = "生命水晶胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 10660,
		["trainers"] = {
			["price"] = 17000,
			["sources"] = {
				7870,
				7871,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36079,
		["item_id"] = 29975,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "金色龙击胸甲",
			["English"] = "Golden Dragonstrike Breastplate",
			["French"] = "Cuirasse dorée de frappe de dragon",
			["German"] = "Goldene Brustplatte des Drachenschlags",
			["Korean"] = "황금 용쐐기 흉갑",
			["Mexican"] = "Coraza de golpe de dragón dorada",
			["Portuguese"] = "Peitoral Dourado do Golpe de Dragão",
			["Russian"] = "Золотая кираса Драконоборца",
			["Spanish"] = "Coraza de golpe de dragón dorada",
			["Taiwanese"] = "黃金龍擊胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 10656,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				7866,
				7867,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36349,
		["item_id"] = 30042,
		["items"] = {
			30301,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "自然力量腰带",
			["English"] = "Belt of Natural Power",
			["French"] = "Ceinture de puissance naturelle",
			["German"] = "Gürtel der naturgleichen Kraft",
			["Korean"] = "자연이 품은 힘의 허리띠",
			["Mexican"] = "Cinturón de poder natural",
			["Portuguese"] = "Cinto do Poder Natural",
			["Russian"] = "Пояс природной силы",
			["Spanish"] = "Cinturón de poder natural",
			["Taiwanese"] = "自然之力腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36351,
		["item_id"] = 30040,
		["items"] = {
			30302,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "深邃暗影腰带",
			["English"] = "Belt of Deep Shadow",
			["French"] = "Ceinture des ombres profondes",
			["German"] = "Gürtel der tiefen Schatten",
			["Korean"] = "깊은 어둠의 허리띠",
			["Mexican"] = "Cinturón de sombra profunda",
			["Portuguese"] = "Cinto da Sombra Profunda",
			["Russian"] = "Пояс глубокой тени",
			["Spanish"] = "Cinturón de sombra profunda",
			["Taiwanese"] = "暗影深淵腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36352,
		["item_id"] = 30046,
		["items"] = {
			30303,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "黑鹰腰带",
			["English"] = "Belt of the Black Eagle",
			["French"] = "Ceinture de l'aigle noir",
			["German"] = "Gürtel des schwarzen Adlers",
			["Korean"] = "검은 독수리 허리띠",
			["Mexican"] = "Cinturón del águila negra",
			["Portuguese"] = "Cinto da Águia Negra",
			["Russian"] = "Пояс черного орла",
			["Spanish"] = "Cinturón del águila negra",
			["Taiwanese"] = "黑鷹腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36353,
		["item_id"] = 30044,
		["items"] = {
			30304,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "季风腰带",
			["English"] = "Monsoon Belt",
			["French"] = "Ceinture de la mousson",
			["German"] = "Gürtel des Monsuns",
			["Korean"] = "계절풍 허리띠",
			["Mexican"] = "Cinturón de monzón",
			["Portuguese"] = "Cinto da Monção",
			["Russian"] = "Пояс сезона дождей",
			["Spanish"] = "Cinturón de monzón",
			["Taiwanese"] = "季風腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36355,
		["item_id"] = 30041,
		["items"] = {
			30305,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "自然优雅之靴",
			["English"] = "Boots of Natural Grace",
			["French"] = "Bottes de grâce naturelle",
			["German"] = "Stiefel der naturgleichen Anmut",
			["Korean"] = "자연이 내린 은총의 장화",
			["Mexican"] = "Botas de gracia natural",
			["Portuguese"] = "Botas do Encanto Natural",
			["Russian"] = "Сапоги природной милости",
			["Spanish"] = "Botas de gracia natural",
			["Taiwanese"] = "自然之擁長靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36357,
		["item_id"] = 30039,
		["items"] = {
			30306,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "绝对黑暗之靴",
			["English"] = "Boots of Utter Darkness",
			["French"] = "Bottes de l'obscurité totale",
			["German"] = "Stiefel der totalen Finsternis",
			["Korean"] = "철저한 암흑의 장화",
			["Mexican"] = "Botas de oscuridad absoluta",
			["Portuguese"] = "Botas da Escuridão Absoluta",
			["Russian"] = "Сапоги непроглядной тьмы",
			["Spanish"] = "Botas de oscuridad absoluta",
			["Taiwanese"] = "絕對黑暗之靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36358,
		["item_id"] = 30045,
		["items"] = {
			30307,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "赤鹰之靴",
			["English"] = "Boots of the Crimson Hawk",
			["French"] = "Bottes du faucon écarlate",
			["German"] = "Stiefel des Purpurfalken",
			["Korean"] = "붉은매 장화",
			["Mexican"] = "Botas del halcón carmesí",
			["Portuguese"] = "Botas do Falcão Carmesim",
			["Russian"] = "Сапоги багрового ястреба",
			["Spanish"] = "Botas del halcón carmesí",
			["Taiwanese"] = "紅鷹之靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36359,
		["item_id"] = 30043,
		["items"] = {
			30308,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "飓风长靴",
			["English"] = "Hurricane Boots",
			["French"] = "Bottes de l'ouragan",
			["German"] = "Stiefel des Wirbelsturms",
			["Korean"] = "폭풍우 장화",
			["Mexican"] = "Botas de huracán",
			["Portuguese"] = "Botas Furacão",
			["Russian"] = "Сапоги урагана",
			["Spanish"] = "Botas de huracán",
			["Taiwanese"] = "颶風長靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 39997,
		["item_id"] = 32398,
		["items"] = {
			32429,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "束缚灵魂长靴",
			["English"] = "Boots of Shackled Souls",
			["French"] = "Bottes des âmes entravées",
			["German"] = "Stiefel der gefangenen Seelen",
			["Korean"] = "구속된 영혼의 장화",
			["Mexican"] = "Botas de almas encadenadas",
			["Portuguese"] = "Botas das Almas Acorrentadas",
			["Russian"] = "Сапоги скованных душ",
			["Spanish"] = "Botas de almas encadenadas",
			["Taiwanese"] = "束縛之魂長靴",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40000,
		["item_id"] = 32399,
		["items"] = {
			32430,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "束缚灵魂护腕",
			["English"] = "Bracers of Shackled Souls",
			["French"] = "Brassards des âmes entravées",
			["German"] = "Armschienen der gefangenen Seelen",
			["Korean"] = "구속된 영혼의 팔보호구",
			["Mexican"] = "Brazales de almas encadenadas",
			["Portuguese"] = "Braçadeiras das Almas Acorrentadas",
			["Russian"] = "Наручи скованных душ",
			["Spanish"] = "Brazales de almas encadenadas",
			["Taiwanese"] = "束縛之魂護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40001,
		["item_id"] = 32400,
		["items"] = {
			32431,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "束缚灵魂护腿",
			["English"] = "Greaves of Shackled Souls",
			["French"] = "Grèves des âmes entravées",
			["German"] = "Schienbeinschützer der gefangenen Seelen",
			["Korean"] = "구속된 영혼의 경갑",
			["Mexican"] = "Grebas de almas encadenadas",
			["Portuguese"] = "Grevas das Almas Acorrentadas",
			["Russian"] = "Наголенники скованных душ",
			["Spanish"] = "Grebas de almas encadenadas",
			["Taiwanese"] = "束縛之魂護脛",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40002,
		["item_id"] = 32397,
		["items"] = {
			32432,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "束缚灵魂腰带",
			["English"] = "Waistguard of Shackled Souls",
			["French"] = "Sangle des âmes entravées",
			["German"] = "Taillenschutz der gefangenen Seelen",
			["Korean"] = "구속된 영혼의 허리보호대",
			["Mexican"] = "Guardarrenes de almas encadenadas",
			["Portuguese"] = "Cinta das Almas Acorrentadas",
			["Russian"] = "Воинский пояс скованных душ",
			["Spanish"] = "Guardarrenes de almas encadenadas",
			["Taiwanese"] = "束縛之魂護腰",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40003,
		["item_id"] = 32394,
		["items"] = {
			32433,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "救赎灵魂长靴",
			["English"] = "Redeemed Soul Moccasins",
			["French"] = "Mocassins d'âme rachetée",
			["German"] = "Mokassins der erlösten Seele",
			["Korean"] = "구원된 영혼의 장화",
			["Mexican"] = "Mocasines de alma redimida",
			["Portuguese"] = "Mocassins da Alma Redimida",
			["Russian"] = "Мокасины искупленной души",
			["Spanish"] = "Mocasines de alma redimida",
			["Taiwanese"] = "救贖之魂底鞋",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40004,
		["item_id"] = 32395,
		["items"] = {
			32434,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "救赎灵魂腕甲",
			["English"] = "Redeemed Soul Wristguards",
			["French"] = "Garde-poignets d'âme rachetée",
			["German"] = "Handgelenksschützer der erlösten Seele",
			["Korean"] = "구원된 영혼의 손목보호구",
			["Mexican"] = "Guardamuñecas de alma redimida",
			["Portuguese"] = "Munhequeiras da Alma Redimida",
			["Russian"] = "Нарукавники искупленной души",
			["Spanish"] = "Guardamuñecas de alma redimida",
			["Taiwanese"] = "救贖之魂腕甲",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40005,
		["item_id"] = 32396,
		["items"] = {
			32435,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "救赎灵魂腿甲",
			["English"] = "Redeemed Soul Legguards",
			["French"] = "Garde-jambes d'âme rachetée",
			["German"] = "Beinschützer der erlösten Seele",
			["Korean"] = "구원된 영혼의 다리보호대",
			["Mexican"] = "Musleras de alma redimida",
			["Portuguese"] = "Guarda-pernas da Alma Redimida",
			["Russian"] = "Набедренники искупленной души",
			["Spanish"] = "Musleras de alma redimida",
			["Taiwanese"] = "救贖之魂腿甲",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40006,
		["item_id"] = 32393,
		["items"] = {
			32436,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "救赎灵魂束带",
			["English"] = "Redeemed Soul Cinch",
			["French"] = "Cordelière d'âme rachetée",
			["German"] = "Sattelgurt der erlösten Seele",
			["Korean"] = "구원된 영혼의 허리띠",
			["Mexican"] = "Cincho de alma redimida",
			["Portuguese"] = "Cilha da Alma Redimida",
			["Russian"] = "Кушак искупленной души",
			["Spanish"] = "Cincho de alma redimida",
			["Taiwanese"] = "救贖之魂繫腰",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41156,
		["item_id"] = 32582,
		["items"] = {
			32744,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "新生护腕",
			["English"] = "Bracers of Renewed Life",
			["French"] = "Brassards du regain de vie",
			["German"] = "Armschienen des neuen Lebens",
			["Korean"] = "새로운 삶의 팔보호구",
			["Mexican"] = "Brazales de Vida renovada",
			["Portuguese"] = "Braçadeiras da Vida Renovada",
			["Russian"] = "Наручи обновленной жизни",
			["Spanish"] = "Brazales de vida renovada",
			["Taiwanese"] = "生命再生護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41157,
		["item_id"] = 32583,
		["items"] = {
			32745,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "新生护肩",
			["English"] = "Shoulderpads of Renewed Life",
			["French"] = "Protège-épaules du regain de vie",
			["German"] = "Schulterpolster des neuen Lebens",
			["Korean"] = "새로운 삶의 어깨보호구",
			["Mexican"] = "Hombreras de vida renovada",
			["Portuguese"] = "Ombreiras da Vida Renovada",
			["Russian"] = "Наплечные пластины обновленной жизни",
			["Spanish"] = "Hombreras de vida renovada",
			["Taiwanese"] = "生命再生肩墊",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41158,
		["item_id"] = 32580,
		["items"] = {
			32746,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "迅捷打击护腕",
			["English"] = "Swiftstrike Bracers",
			["French"] = "Brassards de frappe rapide",
			["German"] = "Flinkschlagarmschienen",
			["Korean"] = "재빠른 일격의 팔보호구",
			["Mexican"] = "Brazales Golpepresto",
			["Portuguese"] = "Braçadeiras do Golpepresto",
			["Russian"] = "Наручи молниеносного удара",
			["Spanish"] = "Brazales Golpeveloz",
			["Taiwanese"] = "迅擊護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41160,
		["item_id"] = 32581,
		["items"] = {
			32747,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "迅捷打击护肩",
			["English"] = "Swiftstrike Shoulders",
			["French"] = "Epaulières de frappe rapide",
			["German"] = "Flinkschlagschultern",
			["Korean"] = "재빠른 일격의 어깨보호구",
			["Mexican"] = "Sobrehombros Golpepresto",
			["Portuguese"] = "Omoplatas do Golpepresto",
			["Russian"] = "Наплечники молниеносного удара",
			["Spanish"] = "Sobrehombros Golpeveloz",
			["Taiwanese"] = "迅擊護肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41161,
		["item_id"] = 32574,
		["items"] = {
			32748,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "闪电反射护腕",
			["English"] = "Bindings of Lightning Reflexes",
			["French"] = "Manchettes des réflexes éclairs",
			["German"] = "Bindungen der blitzartigen Reflexe",
			["Korean"] = "번개같은 반사 신경의 손목띠",
			["Mexican"] = "Ataduras de reflejos de relámpago",
			["Portuguese"] = "Braçadeiras do Reflexo Relâmpago",
			["Russian"] = "Наручники молниеносной реакции",
			["Spanish"] = "Ataduras de reflejos de relámpago",
			["Taiwanese"] = "電光反射束腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41162,
		["item_id"] = 32575,
		["items"] = {
			32749,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "闪电反射护肩",
			["English"] = "Shoulders of Lightning Reflexes",
			["French"] = "Epaulières des réflexes éclairs",
			["German"] = "Schultern der blitzartigen Reflexe",
			["Korean"] = "번개같은 반사 신경의 어깨보호구",
			["Mexican"] = "Sobrehombros de reflejos de relámpago",
			["Portuguese"] = "Omoplatas do Reflexo Relâmpago",
			["Russian"] = "Наплечники молниеносной реакции",
			["Spanish"] = "Sobrehombros de reflejos de relámpago",
			["Taiwanese"] = "電光反射護肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41163,
		["item_id"] = 32577,
		["items"] = {
			32750,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "生命之地护腕",
			["English"] = "Living Earth Bindings",
			["French"] = "Manchettes de la terre vivante",
			["German"] = "Lebendige Erdbindungen",
			["Korean"] = "살아있는 대지의 손목띠",
			["Mexican"] = "Ataduras Tierra Viva",
			["Portuguese"] = "Braceletes da Terra Viva",
			["Russian"] = "Наручники живой земли",
			["Spanish"] = "Ataduras Tierra Viva",
			["Taiwanese"] = "大地生命束腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41164,
		["item_id"] = 32579,
		["items"] = {
			32751,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "生命之地护肩",
			["English"] = "Living Earth Shoulders",
			["French"] = "Epaulières de la terre vivante",
			["German"] = "Lebendige Erdschultern",
			["Korean"] = "살아있는 대지의 어깨보호구",
			["Mexican"] = "Sobrehombros Tierra Viva",
			["Portuguese"] = "Omoplatas da Terra Viva",
			["Russian"] = "Наплечники живой земли",
			["Spanish"] = "Sobrehombros Tierra Viva",
			["Taiwanese"] = "大地生命護肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 42546,
		["item_id"] = 33122,
		["items"] = {
			33124,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "黑暗披风",
			["English"] = "Cloak of Darkness",
			["French"] = "Cape des ténèbres",
			["German"] = "Umhang der Dunkelheit",
			["Korean"] = "암흑의 망토",
			["Mexican"] = "Capa de oscuridad",
			["Portuguese"] = "Manto de Trevas",
			["Russian"] = "Плащ Тьмы",
			["Spanish"] = "Capa de oscuridad",
			["Taiwanese"] = "黑暗披風",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 42731,
		["item_id"] = 33204,
		["items"] = {
			33205,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "阴影徘徊者胸甲",
			["English"] = "Shadowprowler's Chestguard",
			["French"] = "Corselet de rôdeur des ombres",
			["German"] = "Brustschutz des Schattenschleichers",
			["Korean"] = "그림자늑대의 가슴보호구",
			["Mexican"] = "Coselete de merodeador de las Sombras",
			["Portuguese"] = "Couraça do Predador das Sombras",
			["Russian"] = "Нагрудный доспех сумеречного проныры",
			["Spanish"] = "Coselete de merodeador de las Sombras",
			["Taiwanese"] = "暗影徘徊者護胸",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 44343,
		["item_id"] = 34099,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "结缔皮弹药包",
			["English"] = "Knothide Ammo Pouch",
			["French"] = "Giberne en cuir granuleux",
			["German"] = "Munitionsbeutel aus Knotenhautleder",
			["Korean"] = "코도가죽 탄약주머니",
			["Mexican"] = "Faltriquera para munición de pellejo nudoso",
			["Portuguese"] = "Bornal de Munição de Couro Nodoso",
			["Russian"] = "Подсумок из узловатой кожи",
			["Spanish"] = "Faltriquera para munición de pellejo nudoso",
			["Taiwanese"] = "境外皮彈藥包",
		},
		["phase"] = 4,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 44344,
		["item_id"] = 34100,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "结缔皮箭袋",
			["English"] = "Knothide Quiver",
			["French"] = "Carquois en cuir granuleux",
			["German"] = "Köcher aus Knotenhautleder",
			["Korean"] = "코도가죽 화살통",
			["Mexican"] = "Carcaj de pellejo nudoso",
			["Portuguese"] = "Aljava de Couro Nodoso",
			["Russian"] = "Колчан из узловатой кожи",
			["Spanish"] = "Carcaj de pellejo nudoso",
			["Taiwanese"] = "境外皮箭袋",
		},
		["phase"] = 4,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 44359,
		["item_id"] = 34105,
		["items"] = {
			34200,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "千羽箭袋",
			["English"] = "Quiver of a Thousand Feathers",
			["French"] = "Carquois des mille plumes",
			["German"] = "Köcher der tausend Federn",
			["Korean"] = "천 개의 깃털 화살통",
			["Mexican"] = "Carcaj de mil plumas",
			["Portuguese"] = "Aljava de Mil Penas",
			["Russian"] = "Колчан тысячи перьев",
			["Spanish"] = "Carcaj de mil plumas",
			["Taiwanese"] = "千羽箭袋",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 44768,
		["item_id"] = 34106,
		["items"] = {
			34201,
			34218,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "虚空鳞片弹药包",
			["English"] = "Netherscale Ammo Pouch",
			["French"] = "Giberne en écailles du Néant",
			["German"] = "Munitionsbeutel aus Netherschuppen",
			["Korean"] = "황천비늘 탄약주머니",
			["Mexican"] = "Faltriquera de munición de escamas abisales",
			["Portuguese"] = "Bornal de Munição de Escama Etérea",
			["Russian"] = "Подсумок из чешуи дракона Пустоты",
			["Spanish"] = "Faltriquera de munición de escamas abisales",
			["Taiwanese"] = "虛空鱗彈藥袋",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 44770,
		["item_id"] = 34207,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "手套强固",
			["English"] = "Glove Reinforcements",
			["French"] = "Renforts de gants",
			["German"] = "Handschuhverstärkung",
			["Korean"] = "장갑 강화도구",
			["Mexican"] = "Refuerzos de guantes",
			["Portuguese"] = "Reforço para Luvas",
			["Russian"] = "Упрочнения для перчаток",
			["Spanish"] = "Refuerzos de guantes",
			["Taiwanese"] = "手套強化片",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 44953,
		["item_id"] = 34086,
		["items"] = {
			34262,
		},
		["min_skill"] = 285,
		["name"] = {
			["Chinese"] = "寒冬长靴",
			["English"] = "Winter Boots",
			["French"] = "Bottes d'hiver",
			["German"] = "Winterstiefel",
			["Korean"] = "겨울 장화",
			["Mexican"] = "Botas de invierno",
			["Portuguese"] = "Botas de Inverno",
			["Russian"] = "Зимние сапоги",
			["Spanish"] = "Botas de invierno",
			["Taiwanese"] = "冬靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 44970,
		["item_id"] = 34330,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "厚重结缔皮护甲片",
			["English"] = "Heavy Knothide Armor Kit",
			["French"] = "Renfort d'armure en cuir granuleux lourd",
			["German"] = "Schweres Knotenhautlederset",
			["Korean"] = "질긴 톱니매듭 가죽 방어구 키트",
			["Mexican"] = "Refuerzo para armadura de pellejo nudoso grueso",
			["Portuguese"] = "Kit de Armadura de Couro Nodoso Pesado",
			["Russian"] = "Накладки из толстой узловатой кожи",
			["Spanish"] = "Refuerzo para armadura de pellejo nudoso grueso",
			["Taiwanese"] = "厚重境外皮護甲片",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 45100,
		["item_id"] = 34482,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "制皮匠的背包",
			["English"] = "Leatherworker's Satchel",
			["French"] = "Sacoche de travailleur du cuir",
			["German"] = "Ranzen des Lederers",
			["Korean"] = "가죽세공인의 가방",
			["Mexican"] = "Cartera de peletero",
			["Portuguese"] = "Algibeira do Coureiro",
			["Russian"] = "Сумка кожевника",
			["Spanish"] = "Cartera de peletero",
			["Taiwanese"] = "製皮師的背包",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18754,
				18771,
				19187,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 45117,
		["item_id"] = 34490,
		["items"] = {
			34491,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "大皮袋",
			["English"] = "Bag of Many Hides",
			["French"] = "Sac des nombreuses peaux",
			["German"] = "Tasche für alle Felle",
			["Korean"] = "가죽 덧댄 가방",
			["Mexican"] = "Bolsa de muchos pellejos",
			["Portuguese"] = "Bolsa de Muitos Pelegos",
			["Russian"] = "Сумка множества шкур",
			["Spanish"] = "Bolsa de muchos pellejos",
			["Taiwanese"] = "拼接皮包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 46132,
		["item_id"] = 34372,
		["items"] = {
			35212,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "骄阳之皮革护手",
			["English"] = "Leather Gauntlets of the Sun",
			["French"] = "Gantelets du soleil en cuir",
			["German"] = "Lederhandschuhe der Sonne",
			["Korean"] = "태양의 가죽 건틀릿",
			["Mexican"] = "Guanteletes de cuero del sol",
			["Portuguese"] = "Manoplas Solares de Couro",
			["Russian"] = "Кожаные рукавицы Солнца",
			["Spanish"] = "Guanteletes de cuero del sol",
			["Taiwanese"] = "太陽皮甲護手",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46133,
		["item_id"] = 34374,
		["items"] = {
			35213,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "凤凰飞羽手套",
			["English"] = "Fletcher's Gloves of the Phoenix",
			["French"] = "Gants de fléchier du phénix",
			["German"] = "Pfeilmacherhandschuhe des Phönix",
			["Korean"] = "불사조의 활장이 장갑",
			["Mexican"] = "Guantes del Fénix de flechero",
			["Portuguese"] = "Luvas-fênix do Seteiro",
			["Russian"] = "Стрелецкие перчатки Феникса",
			["Spanish"] = "Guantes del Fénix de flechero",
			["Taiwanese"] = "鳳凰弓匠手套",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46134,
		["item_id"] = 34370,
		["items"] = {
			35214,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "永生幽暗手套",
			["English"] = "Gloves of Immortal Dusk",
			["French"] = "Gants de la pénombre immortelle",
			["German"] = "Handschuhe der unsterblichen Dämmerung",
			["Korean"] = "불멸의 황혼 장갑",
			["Mexican"] = "Guantes de anochecer inmortal",
			["Portuguese"] = "Luvas do Crepúsculo Imortal",
			["Russian"] = "Перчатки вечного сумрака",
			["Spanish"] = "Guantes de anochecer inmortal",
			["Taiwanese"] = "不朽之暮手套",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46135,
		["item_id"] = 34376,
		["items"] = {
			35215,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "炙日鳞片手套",
			["English"] = "Sun-Drenched Scale Gloves",
			["French"] = "Gantelets d'écailles inondés de soleil",
			["German"] = "Sonnengetränkte Schuppenhandschuhe",
			["Korean"] = "태양빛에 물든 미늘 장갑",
			["Mexican"] = "Guantes de escamas caladas de sol",
			["Portuguese"] = "Luvas de Escama Banhada de Sol",
			["Russian"] = "Пронизанные солнцем чешуйчатые перчатки",
			["Spanish"] = "Guantes de escamas caladas de sol",
			["Taiwanese"] = "沁日鱗甲手套",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46136,
		["item_id"] = 34371,
		["items"] = {
			35216,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "骄阳之皮革胸甲",
			["English"] = "Leather Chestguard of the Sun",
			["French"] = "Corselet du soleil en cuir",
			["German"] = "Lederbrustschutz der Sonne",
			["Korean"] = "태양의 가죽 흉갑",
			["Mexican"] = "Coselete de cuero del sol",
			["Portuguese"] = "Couraça Solar de Couro",
			["Russian"] = "Кожаный нагрудный доспех солнца",
			["Spanish"] = "Coselete de cuero del sol",
			["Taiwanese"] = "太陽皮甲護胸",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46137,
		["item_id"] = 34373,
		["items"] = {
			35217,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "凤凰的拥抱",
			["English"] = "Embrace of the Phoenix",
			["French"] = "Etreinte du phénix",
			["German"] = "Umarmung des Phönix",
			["Korean"] = "불사조의 은총",
			["Mexican"] = "Abrazo del Fénix",
			["Portuguese"] = "Abraço da Fênix",
			["Russian"] = "Облачение Феникса",
			["Spanish"] = "Abrazo del Fénix",
			["Taiwanese"] = "鳳凰之擁",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46138,
		["item_id"] = 34369,
		["items"] = {
			35218,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "烈日暗影甲胄",
			["English"] = "Carapace of Sun and Shadow",
			["French"] = "Carapace du soleil et de l'ombre",
			["German"] = "Panzerung von Sonne und Schatten",
			["Korean"] = "해그림자 갑옷",
			["Mexican"] = "Caparazón de sol y sombra",
			["Portuguese"] = "Carapaça de Sol e Sombra",
			["Russian"] = "Панцирь Солнца и Тени",
			["Spanish"] = "Caparazón de sol y sombra",
			["Taiwanese"] = "日與影之殼",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46139,
		["item_id"] = 34375,
		["items"] = {
			35219,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "炙日鳞片胸甲",
			["English"] = "Sun-Drenched Scale Chestguard",
			["French"] = "Corselet d'écailles inondé de soleil",
			["German"] = "Sonnengetränkter Schuppenbrustschutz",
			["Korean"] = "태양빛에 물든 흉갑",
			["Mexican"] = "Coselete de escamas caladas de sol",
			["Portuguese"] = "Couraça de Escama Banhada de Sol",
			["Russian"] = "Пронизанный солнцем нагрудный доспех",
			["Spanish"] = "Coselete de escamas caladas de sol",
			["Taiwanese"] = "沁日鱗甲護胸",
		},
		["phase"] = 5,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Leatherworking"], skill)
end
