-------------------------------------------------------
-- All factions - The Burning Crusade Delta
-------------------------------------------------------
local tbc_factions = 
{
	{
        ["id"] = 911,
        ["name"] = {
            ["Chinese"] = "银月城",
            ["English"] = "Silvermoon City",
            ["French"] = "Lune-d'argent",
            ["German"] = "Silbermond",
            ["Korean"] = "실버문",
            ["Mexican"] = "Ciudad de Lunargenta",
            ["Portuguese"] = "Luaprata",
            ["Russian"] = "Луносвет",
            ["Spanish"] = "Ciudad de Lunargenta",
            ["Taiwanese"] = "銀月城",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 922,
        ["name"] = {
            ["Chinese"] = "塔奎林",
            ["English"] = "Tranquillien",
            ["French"] = "Tranquillien",
            ["German"] = "Tristessa",
            ["Korean"] = "트랜퀼리엔",
            ["Mexican"] = "Tranquillien",
            ["Portuguese"] = "Tranquillien",
            ["Russian"] = "Транквиллион",
            ["Spanish"] = "Tranquillien",
            ["Taiwanese"] = "塔奎林",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 930,
        ["name"] = {
            ["Chinese"] = "埃索达",
            ["English"] = "Exodar",
            ["French"] = "Exodar",
            ["German"] = "Die Exodar",
            ["Korean"] = "엑소다르",
            ["Mexican"] = "El Exodar",
            ["Portuguese"] = "Exodar",
            ["Russian"] = "Экзодар",
            ["Spanish"] = "El Exodar",
            ["Taiwanese"] = "埃索達",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 932,
        ["name"] = {
            ["Chinese"] = "奥尔多",
            ["English"] = "The Aldor",
            ["French"] = "L'Aldor",
            ["German"] = "Die Aldor",
            ["Korean"] = "알도르 사제회",
            ["Mexican"] = "Los Aldor",
            ["Portuguese"] = "Os Aldor",
            ["Russian"] = "Алдоры",
            ["Spanish"] = "Los Aldor",
            ["Taiwanese"] = "奧爾多",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 933,
        ["name"] = {
            ["Chinese"] = "星界财团",
            ["English"] = "The Consortium",
            ["French"] = "Le Consortium",
            ["German"] = "Das Konsortium",
            ["Korean"] = "무역연합",
            ["Mexican"] = "El Consorcio",
            ["Portuguese"] = "O Consórcio",
            ["Russian"] = "Консорциум",
            ["Spanish"] = "El Consorcio",
            ["Taiwanese"] = "星界財團",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 934,
        ["name"] = {
            ["Chinese"] = "占星者",
            ["English"] = "The Scryers",
            ["French"] = "Les Clairvoyants",
            ["German"] = "Die Seher",
            ["Korean"] = "점술가 길드",
            ["Mexican"] = "Los Arúspices",
            ["Portuguese"] = "Os Áugures",
            ["Russian"] = "Провидцы",
            ["Spanish"] = "Los Arúspices",
            ["Taiwanese"] = "占星者",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 935,
        ["name"] = {
            ["Chinese"] = "沙塔尔",
            ["English"] = "The Sha'tar",
            ["French"] = "Les Sha'tar",
            ["German"] = "Die Sha'tar",
            ["Korean"] = "샤타르",
            ["Mexican"] = "Los Sha'tar",
            ["Portuguese"] = "Os Sha'tar",
            ["Russian"] = "Ша'тар",
            ["Spanish"] = "Los Sha'tar",
            ["Taiwanese"] = "沙塔爾",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 936,
        ["name"] = {
            ["Chinese"] = "沙塔斯城",
            ["English"] = "Shattrath City",
            ["French"] = "Shattrath",
            ["German"] = "Shattrath",
            ["Korean"] = "샤트라스",
            ["Mexican"] = "Ciudad de Shattrath",
            ["Portuguese"] = "Shattrath",
            ["Russian"] = "Шаттрат",
            ["Spanish"] = "Ciudad de Shattrath",
            ["Taiwanese"] = "沙塔斯城",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 941,
        ["name"] = {
            ["Chinese"] = "玛格汉",
            ["English"] = "The Mag'har",
            ["French"] = "Mag'har",
            ["German"] = "Die Mag'har",
            ["Korean"] = "마그하르",
            ["Mexican"] = "Los Mag'har",
            ["Portuguese"] = "Os Mag'har",
            ["Russian"] = "Маг'хары",
            ["Spanish"] = "Los Mag'har",
            ["Taiwanese"] = "瑪格漢",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 942,
        ["name"] = {
            ["Chinese"] = "塞纳里奥远征队",
            ["English"] = "Cenarion Expedition",
            ["French"] = "Expédition cénarienne",
            ["German"] = "Expedition des Cenarius",
            ["Korean"] = "세나리온 원정대",
            ["Mexican"] = "Expedición Cenarion",
            ["Portuguese"] = "Expedição Cenariana",
            ["Russian"] = "Кенарийская экспедиция",
            ["Spanish"] = "Expedición Cenarion",
            ["Taiwanese"] = "塞納裏奧遠征隊",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 946,
        ["name"] = {
            ["Chinese"] = "荣耀堡",
            ["English"] = "Honor Hold",
            ["French"] = "Bastion de l'Honneur",
            ["German"] = "Ehrenfeste",
            ["Korean"] = "명예의 요새",
            ["Mexican"] = "Bastión del Honor",
            ["Portuguese"] = "Fortaleza da Honra",
            ["Russian"] = "Оплот Чести",
            ["Spanish"] = "Bastión del Honor",
            ["Taiwanese"] = "榮耀堡",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 947,
        ["name"] = {
            ["Chinese"] = "萨尔玛",
            ["English"] = "Thrallmar",
            ["French"] = "Thrallmar",
            ["German"] = "Thrallmar",
            ["Korean"] = "스랄마",
            ["Mexican"] = "Thrallmar",
            ["Portuguese"] = "Thrallmar",
            ["Russian"] = "Траллмар",
            ["Spanish"] = "Thrallmar",
            ["Taiwanese"] = "薩爾瑪",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 967,
        ["name"] = {
            ["Chinese"] = "紫罗兰之眼",
            ["English"] = "The Violet Eye",
            ["French"] = "L'Œil pourpre",
            ["German"] = "Das Violette Auge",
            ["Korean"] = "보랏빛 눈의 감시자",
            ["Mexican"] = "El Ojo Violeta",
            ["Portuguese"] = "O Olho Violeta",
            ["Russian"] = "Аметистовое Око",
            ["Spanish"] = "El Ojo Violeta",
            ["Taiwanese"] = "紫羅蘭之眼",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 970,
        ["name"] = {
            ["Chinese"] = "孢子村",
            ["English"] = "Sporeggar",
            ["French"] = "Sporeggar",
            ["German"] = "Sporeggar",
            ["Korean"] = "스포어가르",
            ["Mexican"] = "Esporaggar",
            ["Portuguese"] = "Sporeggar",
            ["Russian"] = "Спореггар",
            ["Spanish"] = "Esporaggar",
            ["Taiwanese"] = "孢子村",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 978,
        ["name"] = {
            ["Chinese"] = "库雷尼",
            ["English"] = "Kurenai",
            ["French"] = "Kurenaï",
            ["German"] = "Kurenai",
            ["Korean"] = "쿠레나이",
            ["Mexican"] = "Kurenai",
            ["Portuguese"] = "Kurenai",
            ["Russian"] = "Куренай",
            ["Spanish"] = "Kurenai",
            ["Taiwanese"] = "庫雷尼",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 989,
        ["name"] = {
            ["Chinese"] = "时光守护者",
            ["English"] = "Keepers of Time",
            ["French"] = "Gardiens du Temps",
            ["German"] = "Hüter der Zeit",
            ["Korean"] = "시간의 수호자",
            ["Mexican"] = "Vigilantes del Tiempo",
            ["Portuguese"] = "Defensores do Tempo",
            ["Russian"] = "Хранители Времени",
            ["Spanish"] = "Vigilantes del Tiempo",
            ["Taiwanese"] = "時光守護者",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 990,
        ["name"] = {
            ["Chinese"] = "流沙之鳞",
            ["English"] = "The Scale of the Sands",
            ["French"] = "La Balance des sables",
            ["German"] = "Die Wächter der Sande",
            ["Korean"] = "시간의 중재자",
            ["Mexican"] = "La Escama de las Arenas",
            ["Portuguese"] = "A Escama das Areias",
            ["Russian"] = "Песчаная Чешуя",
            ["Spanish"] = "La Escama de las Arenas",
            ["Taiwanese"] = "流沙之鱗",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 1011,
        ["name"] = {
            ["Chinese"] = "贫民窟",
            ["English"] = "Lower City",
            ["French"] = "Ville basse",
            ["German"] = "Unteres Viertel",
            ["Korean"] = "고난의 거리",
            ["Mexican"] = "Bajo Arrabal",
            ["Portuguese"] = "Bairro Inferior",
            ["Russian"] = "Нижний город",
            ["Spanish"] = "Bajo Arrabal",
            ["Taiwanese"] = "貧民窟",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 1012,
        ["name"] = {
            ["Chinese"] = "灰舌死誓者",
            ["English"] = "Ashtongue Deathsworn",
            ["French"] = "Ligemort cendrelangue",
            ["German"] = "Die Todeshörigen",
            ["Korean"] = "잿빛혓바닥 결사단",
            ["Mexican"] = "Juramorte Lengua de ceniza",
            ["Portuguese"] = "Devotos da Morte Grislíngua",
            ["Russian"] = "Пеплоусты-служители",
            ["Spanish"] = "Juramorte Lengua de ceniza",
            ["Taiwanese"] = "灰舌死誓者",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 1015,
        ["name"] = {
            ["Chinese"] = "灵翼之龙",
            ["English"] = "Netherwing",
            ["French"] = "Aile-du-Néant",
            ["German"] = "Netherschwingen",
            ["Korean"] = "황천의 용군단",
            ["Mexican"] = "Ala Abisal",
            ["Portuguese"] = "Asa Etérea",
            ["Russian"] = "Крылья Пустоты",
            ["Spanish"] = "Ala Abisal",
            ["Taiwanese"] = "靈翼之龍",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 1031,
        ["name"] = {
            ["Chinese"] = "沙塔尔天空卫队",
            ["English"] = "Sha'tari Skyguard",
            ["French"] = "Garde-ciel sha'tari",
            ["German"] = "Himmelswache der Sha'tari",
            ["Korean"] = "샤타리 하늘경비대",
            ["Mexican"] = "Guardia del cielo Sha'tari",
            ["Portuguese"] = "Guarda Aérea Sha'tari",
            ["Russian"] = "Стражи небес Ша'тар",
            ["Spanish"] = "Guardia del cielo Sha'tari",
            ["Taiwanese"] = "沙塔爾天空衛隊",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 1038,
        ["name"] = {
            ["Chinese"] = "奥格瑞拉",
            ["English"] = "Ogri'la",
            ["French"] = "Ogri'la",
            ["German"] = "Ogri'la",
            ["Korean"] = "오그릴라",
            ["Mexican"] = "Ogri'la",
            ["Portuguese"] = "Ogri'la",
            ["Russian"] = "Огри'ла",
            ["Spanish"] = "Ogri'la",
            ["Taiwanese"] = "奧格瑞拉",
        },
        ["phase"] = 1,
    },
	{
        ["id"] = 1077,
        ["name"] = {
            ["Chinese"] = "破碎残阳",
            ["English"] = "Shattered Sun Offensive",
            ["French"] = "Opération Soleil brisé",
            ["German"] = "Offensive der Zerschmetterten Sonne",
            ["Korean"] = "무너진 태양 공격대",
            ["Mexican"] = "Ofensiva Sol Devastado",
            ["Portuguese"] = "Ofensiva Sol Partido",
            ["Russian"] = "Армия Расколотого Солнца",
            ["Spanish"] = "Ofensiva Sol Devastado",
            ["Taiwanese"] = "破碎殘陽",
        },
        ["phase"] = 1,
    },
}

for _, entry in ipairs(tbc_factions) do
	table.insert(RR_DATA["factions"], entry)
end
