-------------------------------------------------------
-- All quests - The Burning Crusade Delta
-------------------------------------------------------
local tbc_quests = 
{
	{
		["expansion"] = 1,
		["id"] = 1578,
		["min_xp_level"] = 1,
		["name"] = {
			["Chinese"] = "前线的补给",
			["English"] = "Supplying the Front",
			["French"] = "Rééquiper le front",
			["German"] = "Nachschub für die Front",
			["Korean"] = "전방 보급품 조달",
			["Mexican"] = "Abastecer al frente",
			["Portuguese"] = "Suprimentos para o front",
			["Russian"] = "Помощь фронту",
			["Spanish"] = "Abastecer al frente",
			["Taiwanese"] = "前線的補給",
		},
		["npcs"] = {
			6031,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 1,
		["id"] = 9171,
		["min_xp_level"] = 12,
		["name"] = {
			["Chinese"] = "松脆蜘蛛腿",
			["English"] = "Culinary Crunch",
			["French"] = "Il faut que ça croustille !",
			["German"] = "Knusperkost",
			["Korean"] = "오독오독 씹히는 요리",
			["Mexican"] = "Texturas crujientes",
			["Portuguese"] = "Comida crocante",
			["Russian"] = "Хрустящий деликатес",
			["Spanish"] = "Texturas crujientes",
			["Taiwanese"] = "松脆蜘蛛腿",
		},
		["npcs"] = {
			16253,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 9356,
		["min_xp_level"] = 58,
		["name"] = {
			["Chinese"] = "万无一失",
			["English"] = "Smooth as Butter",
			["French"] = "Les doigts dans le nez",
			["German"] = "So weich wie Butter",
			["Korean"] = "버터처럼 부드러운...",
			["Mexican"] = "Suave como una pluma",
			["Portuguese"] = "Fadinha furada",
			["Russian"] = "Летать как птица",
			["Spanish"] = "Suave como una pluma",
			["Taiwanese"] = "萬無一失",
		},
		["npcs"] = {
			19344,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 9454,
		["min_xp_level"] = 4,
		["name"] = {
			["Chinese"] = "狩猎月痕鹿",
			["English"] = "The Great Moongraze Hunt",
			["French"] = "La grande chasse aux frôle-lune",
			["German"] = "Die große Mondweidenjagd",
			["Korean"] = "달새김 사슴 사냥",
			["Mexican"] = "La caza de venados lunares",
			["Portuguese"] = "A grande caçada de pastolunas",
			["Russian"] = "Великая охота на лунных оленей",
			["Spanish"] = "La caza de venados lunares",
			["Taiwanese"] = "狩獵月痕鹿",
		},
		["npcs"] = {
			17110,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 9635,
		["min_xp_level"] = 58,
		["name"] = {
			["Chinese"] = "气阀微粒提取器！",
			["English"] = "The Zapthrottle Mote Extractor!",
			["French"] = "L'extracteur de granules Zappeur-Gazier !",
			["German"] = "Der schockdrosselnde Partikelextraktor!",
			["Korean"] = "기압조절 가스 추출기!",
			["Mexican"] = "¡El extractor de motas Zapacelerador!",
			["Portuguese"] = "O Extrator de Partículas Zapeacelera!",
			["Russian"] = "Удаленный конденсатор выхлопов!",
			["Spanish"] = "¡El extractor de motas Zapacelerador!",
			["Taiwanese"] = "氣閥微粒提取器！",
		},
		["npcs"] = {
			17634,
			17637,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 10831,
		["min_skill"] = 350,
		["min_xp_level"] = 60,
		["name"] = {
			["Chinese"] = "成为月布裁缝",
			["English"] = "Becoming a Mooncloth Tailor",
			["French"] = "Devenir un tailleur d'étoffe lunaire",
			["German"] = "Wie man ein Mondstoffschneider wird",
			["Korean"] = "[Becoming a Mooncloth Tailor]",
			["Mexican"] = "Convertirse en un sastre de tela lunar",
			["Portuguese"] = "Como se tornar um alfaiate de lunatrama",
			["Russian"] = "Обучение шитью из луноткани",
			["Spanish"] = "Convertirse en un sastre de tela lunar",
			["Taiwanese"] = "成為月布裁縫",
		},
		["npcs"] = {
			22208,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 10832,
		["min_skill"] = 350,
		["min_xp_level"] = 60,
		["name"] = {
			["Chinese"] = "成为魔焰裁缝",
			["English"] = "Becoming a Spellfire Tailor",
			["French"] = "Devenir un tailleur de feu-sorcier",
			["German"] = "Wie man ein Zauberfeuerschneider wird",
			["Korean"] = "[Becoming a Spellfire Tailor]",
			["Mexican"] = "Convertirse en sastre fuego de hechizo",
			["Portuguese"] = "Como se tornar um alfaiate de fogo místico",
			["Russian"] = "Обучение шитью из чароткани",
			["Spanish"] = "Convertirse en sastre fuego de hechizo",
			["Taiwanese"] = "成為魔焰裁縫",
		},
		["npcs"] = {
			22213,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 10833,
		["min_skill"] = 350,
		["min_xp_level"] = 60,
		["name"] = {
			["Chinese"] = "成为暗纹裁缝",
			["English"] = "Becoming a Shadoweave Tailor",
			["French"] = "Devenir un tailleur de tisse-ombre",
			["German"] = "Wie man ein Schattenzwirnschneider wird",
			["Korean"] = "[Becoming a Shadoweave Tailor]",
			["Mexican"] = "Convertirse en un sastre de tejido de sombra",
			["Portuguese"] = "Como se tornar um alfaiate de umbratrama",
			["Russian"] = "Обучение шитью из тенеткани",
			["Spanish"] = "Convertirse en un sastre de tejido de sombra",
			["Taiwanese"] = "成為暗紋裁縫",
		},
		["npcs"] = {
			22212,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 10897,
		["min_skill"] = 325,
		["min_xp_level"] = 68,
		["name"] = {
			["Chinese"] = "药水大师",
			["English"] = "Master of Potions",
			["French"] = "Maître des potions",
			["German"] = "Meister der Tränke",
			["Korean"] = "물약의 대가",
			["Mexican"] = "Maestro en pociones",
			["Portuguese"] = "[Master of Potions]",
			["Russian"] = "Мастер-изготовитель зелий",
			["Spanish"] = "Maestro en pociones",
			["Taiwanese"] = "藥水大師",
		},
		["npcs"] = {
			17909,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 10899,
		["min_skill"] = 325,
		["min_xp_level"] = 68,
		["name"] = {
			["Chinese"] = "转化大师",
			["English"] = "Master of Transmutation",
			["French"] = "Maître de la transmutation",
			["German"] = "Meister der Transmutation",
			["Korean"] = "[Master of Transmutation]",
			["Mexican"] = "Maestro de transmutación",
			["Portuguese"] = "[Master of Transmutation]",
			["Russian"] = "Мастер трансмутации",
			["Spanish"] = "Maestro de transmutación",
			["Taiwanese"] = "轉化大師",
		},
		["npcs"] = {
			22427,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 10902,
		["min_skill"] = 325,
		["min_xp_level"] = 68,
		["name"] = {
			["Chinese"] = "药剂大师",
			["English"] = "Master of Elixirs",
			["French"] = "Maître des élixirs",
			["German"] = "Meister der Elixiere",
			["Korean"] = "비약의 대가",
			["Mexican"] = "Maestro en elixires",
			["Portuguese"] = "[Master of Elixirs]",
			["Russian"] = "Мастер эликсиров",
			["Spanish"] = "Maestro en elixires",
			["Taiwanese"] = "藥劑大師",
		},
		["npcs"] = {
			19052,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 11379,
		["min_xp_level"] = 70,
		["name"] = {
			["Chinese"] = "每日烹饪任务",
			["English"] = "Daily cooking quest",
			["French"] = "Quête de cuisine quotidienne",
			["German"] = "Tägliche Kochquest",
			["Korean"] = "일일 요리 퀘스트",
			["Mexican"] = "Búsqueda de cocina diaria",
			["Portuguese"] = "Busca de culinária diária",
			["Russian"] = "Ежедневный кулинарный квест",
			["Spanish"] = "Búsqueda de cocina diaria",
			["Taiwanese"] = "每日烹飪任務",
		},
		["npcs"] = {
			24393,
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 11665,
		["min_xp_level"] = 70,
		["name"] = {
			["Chinese"] = "每日钓鱼任务",
			["English"] = "Daily fishing quest",
			["French"] = "Quête de pêche quotidienne",
			["German"] = "Tägliche Angelquest",
			["Korean"] = "일일 퀘스트 낚시",
			["Mexican"] = "Búsqueda de pesca diaria",
			["Portuguese"] = "Busca de pesca diária",
			["Russian"] = "Ежедневный квест на рыбалку",
			["Spanish"] = "Búsqueda de pesca diaria",
			["Taiwanese"] = "每日釣魚任務",
		},
		["npcs"] = {
			25580,
		},
		["phase"] = 1,
	},
}

for _, entry in ipairs(tbc_quests) do
	table.insert(RR_DATA["quests"], entry)
end
