-------------------------------------------------------
-- All zones - The Burning Crusade Delta
-------------------------------------------------------
local tbc_zones = 
{
	{
		["expansion"] = 1,
		["id"] = 0,
		["levels"] = {
			["max"] = 70,
			["min"] = 1,
		},
		["name"] = {
			["Chinese"] = "未知",
			["English"] = "Unknown",
			["French"] = "Inconnu",
			["German"] = "Unbekannt",
			["Korean"] = "알 수 없는",
			["Mexican"] = "Desconocido",
			["Portuguese"] = "Desconhecido",
			["Russian"] = "Неизвестный",
			["Spanish"] = "Desconocido",
			["Taiwanese"] = "未知",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 2366,
		["levels"] = {
			["max"] = 70,
			["min"] = 68,
		},
		["name"] = {
			["Chinese"] = "黑色沼泽",
			["English"] = "The Black Morass",
			["French"] = "Le Noir Marécage",
			["German"] = "Der schwarze Morast",
			["Korean"] = "검은늪",
			["Mexican"] = "La Ciénaga Negra",
			["Portuguese"] = "Lamaçal Negro",
			["Russian"] = "Черные топи",
			["Spanish"] = "La Ciénaga Negra",
			["Taiwanese"] = "黑色沼澤",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 2367,
		["levels"] = {
			["max"] = 70,
			["min"] = 66,
		},
		["name"] = {
			["Chinese"] = "旧希尔斯布莱德丘陵",
			["English"] = "Old Hillsbrad Foothills",
			["French"] = "Contreforts de Hautebrande d'antan",
			["German"] = "Vorgebirge des Alten Hügellands",
			["Korean"] = "옛 힐스브래드 구릉지",
			["Mexican"] = "Antiguas Laderas de Trabalomas",
			["Portuguese"] = "Antigo Contraforte de Eira dos Montes",
			["Russian"] = "Старые предгорья Хилсбрада",
			["Spanish"] = "Antiguas Laderas de Trabalomas",
			["Taiwanese"] = "舊希爾斯布萊德丘陵",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 2,
		["expansion"] = 2,
		["id"] = 3430,
		["levels"] = {
			["max"] = 10,
			["min"] = 1,
		},
		["name"] = {
			["Chinese"] = "永歌森林",
			["English"] = "Eversong Woods",
			["French"] = "Bois des Chants éternels",
			["German"] = "Immersangwald",
			["Korean"] = "영원노래 숲",
			["Mexican"] = "Bosque Canción Eterna",
			["Portuguese"] = "Floresta do Canto Eterno",
			["Russian"] = "Леса Вечной Песни",
			["Spanish"] = "Bosque Canción Eterna",
			["Taiwanese"] = "永歌森林",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 2,
		["expansion"] = 2,
		["id"] = 3433,
		["levels"] = {
			["max"] = 20,
			["min"] = 10,
		},
		["name"] = {
			["Chinese"] = "幽魂之地",
			["English"] = "Ghostlands",
			["French"] = "Les Terres fantômes",
			["German"] = "Geisterlande",
			["Korean"] = "유령의 땅",
			["Mexican"] = "Tierras Fantasma",
			["Portuguese"] = "Terra Fantasma",
			["Russian"] = "Призрачные земли",
			["Spanish"] = "Tierras Fantasma",
			["Taiwanese"] = "幽魂之地",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3457,
		["name"] = {
			["Chinese"] = "卡拉赞",
			["English"] = "Karazhan",
			["French"] = "Karazhan",
			["German"] = "Karazhan",
			["Korean"] = "카라잔",
			["Mexican"] = "Karazhan",
			["Portuguese"] = "Karazhan",
			["Russian"] = "Каражан",
			["Spanish"] = "Karazhan",
			["Taiwanese"] = "卡拉贊",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3483,
		["levels"] = {
			["max"] = 70,
			["min"] = 58,
		},
		["name"] = {
			["Chinese"] = "地狱火半岛",
			["English"] = "Hellfire Peninsula",
			["French"] = "Péninsule des Flammes infernales",
			["German"] = "Höllenfeuerhalbinsel",
			["Korean"] = "지옥불 반도",
			["Mexican"] = "Península del Fuego Infernal",
			["Portuguese"] = "Península Fogo do Inferno",
			["Russian"] = "Полуостров Адского Пламени",
			["Spanish"] = "Península del Fuego Infernal",
			["Taiwanese"] = "地獄火半島",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 2,
		["expansion"] = 2,
		["id"] = 3487,
		["name"] = {
			["Chinese"] = "银月城",
			["English"] = "Silvermoon City",
			["French"] = "Lune-d'argent",
			["German"] = "Silbermond",
			["Korean"] = "실버문",
			["Mexican"] = "Ciudad de Lunargenta",
			["Portuguese"] = "Luaprata",
			["Russian"] = "Луносвет",
			["Spanish"] = "Ciudad de Lunargenta",
			["Taiwanese"] = "銀月城",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3518,
		["levels"] = {
			["max"] = 70,
			["min"] = 64,
		},
		["name"] = {
			["Chinese"] = "纳格兰",
			["English"] = "Nagrand",
			["French"] = "Nagrand",
			["German"] = "Nagrand",
			["Korean"] = "나그란드",
			["Mexican"] = "Nagrand",
			["Portuguese"] = "Nagrand",
			["Russian"] = "Награнд",
			["Spanish"] = "Nagrand",
			["Taiwanese"] = "納格蘭",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3519,
		["levels"] = {
			["max"] = 70,
			["min"] = 62,
		},
		["name"] = {
			["Chinese"] = "泰罗卡森林",
			["English"] = "Terokkar Forest",
			["French"] = "Forêt de Terokkar",
			["German"] = "Wälder von Terokkar",
			["Korean"] = "테로카르 숲",
			["Mexican"] = "Bosque de Terokkar",
			["Portuguese"] = "Mata Terokkar",
			["Russian"] = "Лес Тероккар",
			["Spanish"] = "Bosque de Terokkar",
			["Taiwanese"] = "泰羅卡森林",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3520,
		["levels"] = {
			["max"] = 70,
			["min"] = 67,
		},
		["name"] = {
			["Chinese"] = "影月谷",
			["English"] = "Shadowmoon Valley",
			["French"] = "Vallée d'Ombrelune",
			["German"] = "Schattenmondtal",
			["Korean"] = "어둠달 골짜기",
			["Mexican"] = "Valle Sombraluna",
			["Portuguese"] = "Vale da Lua Negra",
			["Russian"] = "Долина Призрачной Луны",
			["Spanish"] = "Valle Sombraluna",
			["Taiwanese"] = "影月谷",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3521,
		["levels"] = {
			["max"] = 63,
			["min"] = 60,
		},
		["name"] = {
			["Chinese"] = "赞加沼泽",
			["English"] = "Zangarmarsh",
			["French"] = "Marécage de Zangar",
			["German"] = "Zangarmarschen",
			["Korean"] = "장가르 습지대",
			["Mexican"] = "Marisma de Zangar",
			["Portuguese"] = "Pântano Zíngaro",
			["Russian"] = "Зангартопь",
			["Spanish"] = "Marisma de Zangar",
			["Taiwanese"] = "贊加沼澤",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3522,
		["levels"] = {
			["max"] = 70,
			["min"] = 65,
		},
		["name"] = {
			["Chinese"] = "刀锋山",
			["English"] = "Blade's Edge Mountains",
			["French"] = "Les Tranchantes",
			["German"] = "Schergrat",
			["Korean"] = "칼날 산맥",
			["Mexican"] = "Montañas Filospada",
			["Portuguese"] = "Montanhas da Lâmina Afiada",
			["Russian"] = "Острогорье",
			["Spanish"] = "Montañas Filospada",
			["Taiwanese"] = "刀鋒山",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3523,
		["levels"] = {
			["max"] = 70,
			["min"] = 66,
		},
		["name"] = {
			["Chinese"] = "虚空风暴",
			["English"] = "Netherstorm",
			["French"] = "Raz-de-Néant",
			["German"] = "Nethersturm",
			["Korean"] = "황천의 폭풍",
			["Mexican"] = "Tormenta Abisal",
			["Portuguese"] = "Eternévoa",
			["Russian"] = "Пустоверть",
			["Spanish"] = "Tormenta Abisal",
			["Taiwanese"] = "虚空风暴",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 1,
		["expansion"] = 2,
		["id"] = 3524,
		["levels"] = {
			["max"] = 10,
			["min"] = 1,
		},
		["name"] = {
			["Chinese"] = "秘蓝岛",
			["English"] = "Azuremyst Isle",
			["French"] = "Ile de Brume-azur",
			["German"] = "Azurmythosinsel",
			["Korean"] = "하늘안개 섬",
			["Mexican"] = "Isla Bruma Azur",
			["Portuguese"] = "Ilha Névoa Lazúli",
			["Russian"] = "Остров Лазурной Дымки",
			["Spanish"] = "Isla Bruma Azur",
			["Taiwanese"] = "秘藍島",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 1,
		["expansion"] = 2,
		["id"] = 3525,
		["levels"] = {
			["max"] = 19,
			["min"] = 9,
		},
		["name"] = {
			["Chinese"] = "秘血岛",
			["English"] = "Bloodmyst Isle",
			["French"] = "Ile de Brume-sang",
			["German"] = "Blutmythosinsel",
			["Korean"] = "핏빛안개 섬",
			["Mexican"] = "Isla Bruma de Sangre",
			["Portuguese"] = "Ilha Névoa Rubra",
			["Russian"] = "Остров Кровавой Дымки",
			["Spanish"] = "Isla Bruma de Sangre",
			["Taiwanese"] = "秘血島",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 1,
		["expansion"] = 2,
		["id"] = 3557,
		["name"] = {
			["Chinese"] = "埃索达",
			["English"] = "The Exodar",
			["French"] = "L'Exodar",
			["German"] = "Die Exodar",
			["Korean"] = "엑소다르",
			["Mexican"] = "El Exodar",
			["Portuguese"] = "Exodar",
			["Russian"] = "Экзодар",
			["Spanish"] = "El Exodar",
			["Taiwanese"] = "埃索達",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3562,
		["levels"] = {
			["max"] = 67,
			["min"] = 59,
		},
		["name"] = {
			["Chinese"] = "地狱火城墙",
			["English"] = "Hellfire Ramparts",
			["French"] = "Remparts des Flammes infernales",
			["German"] = "Höllenfeuerbollwerk",
			["Korean"] = "지옥불 성루",
			["Mexican"] = "Murallas del Fuego Infernal",
			["Portuguese"] = "Muralha Fogo do Inferno",
			["Russian"] = "Бастионы Адского Пламени",
			["Spanish"] = "Murallas del Fuego Infernal",
			["Taiwanese"] = "地獄火城牆",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3606,
		["name"] = {
			["Chinese"] = "海加尔峰",
			["English"] = "Hyjal Summit",
			["French"] = "Sommet d'Hyjal",
			["German"] = "Hyjalgipfel",
			["Korean"] = "하이잘 정상",
			["Mexican"] = "La Cima Hyjal",
			["Portuguese"] = "Pico Hyjal",
			["Russian"] = "Вершина Хиджала",
			["Spanish"] = "La Cima Hyjal",
			["Taiwanese"] = "海加爾峰",
		},
		["phase"] = 3,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3607,
		["name"] = {
			["Chinese"] = "毒蛇神殿",
			["English"] = "Serpentshrine Cavern",
			["French"] = "Caverne du sanctuaire du Serpent",
			["German"] = "Höhle des Schlangenschreins",
			["Korean"] = "불뱀 제단",
			["Mexican"] = "Caverna Santuario Serpiente",
			["Portuguese"] = "Caverna do Serpentário",
			["Russian"] = "Змеиное святилище",
			["Spanish"] = "Caverna Santuario Serpiente",
			["Taiwanese"] = "毒蛇神殿",
		},
		["phase"] = 2,
	},
	{
		["continent_id"] = 3,
		["expansion"] = 2,
		["id"] = 3703,
		["name"] = {
			["Chinese"] = "沙塔斯城",
			["English"] = "Shattrath City",
			["French"] = "Shattrath",
			["German"] = "Shattrath",
			["Korean"] = "샤트라스",
			["Mexican"] = "Ciudad de Shattrath",
			["Portuguese"] = "Shattrath",
			["Russian"] = "Шаттрат",
			["Spanish"] = "Ciudad de Shattrath",
			["Taiwanese"] = "沙塔斯城",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3713,
		["levels"] = {
			["max"] = 68,
			["min"] = 60,
		},
		["name"] = {
			["Chinese"] = "鲜血熔炉",
			["English"] = "The Blood Furnace",
			["French"] = "La Fournaise du sang",
			["German"] = "Der Blutkessel",
			["Korean"] = "피의 용광로",
			["Mexican"] = "El Horno de Sangre",
			["Portuguese"] = "Fornalha de Sangue",
			["Russian"] = "Кузня Крови",
			["Spanish"] = "El Horno de Sangre",
			["Taiwanese"] = "鮮血熔爐",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3714,
		["levels"] = {
			["max"] = 70,
			["min"] = 69,
		},
		["name"] = {
			["Chinese"] = "破碎大厅",
			["English"] = "The Shattered Halls",
			["French"] = "Les Salles brisées",
			["German"] = "Die Zerschmetterten Hallen",
			["Korean"] = "으스러진 손의 전당",
			["Mexican"] = "Las Salas Arrasadas",
			["Portuguese"] = "Salões Despedaçados",
			["Russian"] = "Разрушенные залы",
			["Spanish"] = "Las Salas Arrasadas",
			["Taiwanese"] = "破碎大廳",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3715,
		["levels"] = {
			["max"] = 70,
			["min"] = 69,
		},
		["name"] = {
			["Chinese"] = "蒸汽地窟",
			["English"] = "The Steamvault",
			["French"] = "Le Caveau de la vapeur",
			["German"] = "Die Dampfkammer",
			["Korean"] = "증기 저장고",
			["Mexican"] = "La Cámara de Vapor",
			["Portuguese"] = "Câmara dos Vapores",
			["Russian"] = "Паровое подземелье",
			["Spanish"] = "La Cámara de Vapor",
			["Taiwanese"] = "蒸汽地窟",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3716,
		["levels"] = {
			["max"] = 70,
			["min"] = 62,
		},
		["name"] = {
			["Chinese"] = "幽暗沼泽",
			["English"] = "The Underbog",
			["French"] = "La Basse-tourbière",
			["German"] = "Der Tiefensumpf",
			["Korean"] = "지하수렁",
			["Mexican"] = "La Sotiénaga",
			["Portuguese"] = "Brejo Oculto",
			["Russian"] = "Нижетопь",
			["Spanish"] = "La Sotiénaga",
			["Taiwanese"] = "幽暗沼澤",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3717,
		["levels"] = {
			["max"] = 69,
			["min"] = 61,
		},
		["name"] = {
			["Chinese"] = "奴隶围栏",
			["English"] = "The Slave Pens",
			["French"] = "Les enclos aux esclaves",
			["German"] = "Die Sklavenunterkünfte",
			["Korean"] = "강제 노역소",
			["Mexican"] = "Recinto de los Esclavos",
			["Portuguese"] = "Pátio dos Escravos",
			["Russian"] = "Узилище",
			["Spanish"] = "Recinto de los Esclavos",
			["Taiwanese"] = "奴隸圍欄",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3789,
		["levels"] = {
			["max"] = 70,
			["min"] = 69,
		},
		["name"] = {
			["Chinese"] = "暗影迷宫",
			["English"] = "Shadow Labyrinth",
			["French"] = "Labyrinthe des ombres",
			["German"] = "Schattenlabyrinth",
			["Korean"] = "어둠의 미궁",
			["Mexican"] = "Laberinto de las Sombras",
			["Portuguese"] = "Labirinto Soturno",
			["Russian"] = "Темный лабиринт",
			["Spanish"] = "Laberinto de las Sombras",
			["Taiwanese"] = "暗影迷宮",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3790,
		["levels"] = {
			["max"] = 70,
			["min"] = 64,
		},
		["name"] = {
			["Chinese"] = "奥金尼地穴",
			["English"] = "Auchenai Crypts",
			["French"] = "Cryptes Auchenaï",
			["German"] = "Auchenaikrypta",
			["Korean"] = "아키나이 납골당",
			["Mexican"] = "Criptas Auchenai",
			["Portuguese"] = "Catacumbas Auchenai",
			["Russian"] = "Аукенайские гробницы",
			["Spanish"] = "Criptas Auchenai",
			["Taiwanese"] = "奧金尼地穴",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3791,
		["levels"] = {
			["max"] = 70,
			["min"] = 66,
		},
		["name"] = {
			["Chinese"] = "塞泰克大厅",
			["English"] = "Sethekk Halls",
			["French"] = "Les salles des Sethekk",
			["German"] = "Sethekkhallen",
			["Korean"] = "세데크 전당",
			["Mexican"] = "Salas Sethekk",
			["Portuguese"] = "Salões dos Sethekk",
			["Russian"] = "Сетеккские залы",
			["Spanish"] = "Salas Sethekk",
			["Taiwanese"] = "塞泰克大廳",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3792,
		["levels"] = {
			["max"] = 70,
			["min"] = 63,
		},
		["name"] = {
			["Chinese"] = "法力陵墓",
			["English"] = "Mana-Tombs",
			["French"] = "Tombes-mana",
			["German"] = "Managruft",
			["Korean"] = "마나 무덤",
			["Mexican"] = "Tumbas de Maná",
			["Portuguese"] = "Tumbas de Mana",
			["Russian"] = "Гробницы маны",
			["Spanish"] = "Tumbas de Maná",
			["Taiwanese"] = "法力陵墓",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3805,
		["name"] = {
			["Chinese"] = "祖阿曼",
			["English"] = "Zul'Aman",
			["French"] = "Zul'Aman",
			["German"] = "Zul'Aman",
			["Korean"] = "줄아만",
			["Mexican"] = "Zul'Aman",
			["Portuguese"] = "Zul'Aman",
			["Russian"] = "Зул'Аман",
			["Spanish"] = "Zul'Aman",
			["Taiwanese"] = "祖阿曼",
		},
		["phase"] = 4,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3836,
		["name"] = {
			["Chinese"] = "玛瑟里顿的巢穴",
			["English"] = "Magtheridon's Lair",
			["French"] = "Le repaire de Magtheridon",
			["German"] = "Magtheridons Kammer",
			["Korean"] = "마그테리돈의 둥지",
			["Mexican"] = "Guarida de Magtheridon",
			["Portuguese"] = "Covil de Magtheridon",
			["Russian"] = "Логово Магтеридона",
			["Spanish"] = "Guarida de Magtheridon",
			["Taiwanese"] = "瑪瑟裏頓的巢穴",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3845,
		["name"] = {
			["Chinese"] = "风暴要塞",
			["English"] = "Tempest Keep",
			["French"] = "Donjon de la Tempête",
			["German"] = "Festung der Stürme",
			["Korean"] = "폭풍우 요새",
			["Mexican"] = "El Castillo de la Tempestad",
			["Portuguese"] = "Bastilha da Tormenta",
			["Russian"] = "Крепость Бурь",
			["Spanish"] = "El Castillo de la Tempestad",
			["Taiwanese"] = "風暴要塞",
		},
		["phase"] = 2,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3847,
		["levels"] = {
			["max"] = 70,
			["min"] = 69,
		},
		["name"] = {
			["Chinese"] = "生态船",
			["English"] = "The Botanica",
			["French"] = "La Botanica",
			["German"] = "Die Botanika",
			["Korean"] = "신록의 정원",
			["Mexican"] = "El Invernáculo",
			["Portuguese"] = "Jardim Botânico",
			["Russian"] = "Ботаника",
			["Spanish"] = "El Invernáculo",
			["Taiwanese"] = "生態船",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3848,
		["levels"] = {
			["max"] = 70,
			["min"] = 69,
		},
		["name"] = {
			["Chinese"] = "禁魔监狱",
			["English"] = "The Arcatraz",
			["French"] = "L'Arcatraz",
			["German"] = "Die Arkatraz",
			["Korean"] = "알카트라즈",
			["Mexican"] = "El Arcatraz",
			["Portuguese"] = "Arcatraz",
			["Russian"] = "The Arcatraz",
			["Spanish"] = "El Arcatraz",
			["Taiwanese"] = "禁魔監獄",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 3849,
		["levels"] = {
			["max"] = 70,
			["min"] = 68,
		},
		["name"] = {
			["Chinese"] = "能源舰",
			["English"] = "The Mechanar",
			["French"] = "Le Méchanar",
			["German"] = "Die Mechanar",
			["Korean"] = "메카나르",
			["Mexican"] = "El Mechanar",
			["Portuguese"] = "Mecanar",
			["Russian"] = "Механар",
			["Spanish"] = "El Mechanar",
			["Taiwanese"] = "能源艦",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3923,
		["name"] = {
			["Chinese"] = "格鲁尔的巢穴",
			["English"] = "Gruul's Lair",
			["French"] = "Repaire de Gruul",
			["German"] = "Gruuls Unterschlupf",
			["Korean"] = "그룰의 둥지",
			["Mexican"] = "Guarida de Gruul",
			["Portuguese"] = "Covil de Gruul",
			["Russian"] = "Логово Груула",
			["Spanish"] = "Guarida de Gruul",
			["Taiwanese"] = "格魯爾的巢穴",
		},
		["phase"] = 1,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 3959,
		["name"] = {
			["Chinese"] = "黑暗神殿",
			["English"] = "Black Temple",
			["French"] = "Temple noir",
			["German"] = "Der Schwarze Tempel",
			["Korean"] = "검은 사원",
			["Mexican"] = "Templo Oscuro",
			["Portuguese"] = "Templo Negro",
			["Russian"] = "Черный храм",
			["Spanish"] = "Templo Oscuro",
			["Taiwanese"] = "黑暗神殿",
		},
		["phase"] = 3,
	},
	{
		["continent_id"] = 6,
		["expansion"] = 2,
		["id"] = 4075,
		["name"] = {
			["Chinese"] = "太阳之井高地",
			["English"] = "Sunwell Plateau",
			["French"] = "Plateau du Puits de soleil",
			["German"] = "Sonnenbrunnenplateau",
			["Korean"] = "태양샘 고원",
			["Mexican"] = "Meseta de La Fuente del Sol",
			["Portuguese"] = "Platô da Nascente do Sol",
			["Russian"] = "Плато Солнечного Колодца",
			["Spanish"] = "Meseta de La Fuente del Sol",
			["Taiwanese"] = "太陽之井高地",
		},
		["phase"] = 5,
	},
	{
		["continent_id"] = 2,
		["expansion"] = 2,
		["id"] = 4080,
		["levels"] = {
			["max"] = 70,
			["min"] = 70,
		},
		["name"] = {
			["Chinese"] = "奎尔丹纳斯岛",
			["English"] = "Isle of Quel'Danas",
			["French"] = "Île de Quel'Danas",
			["German"] = "Insel von Quel'Danas",
			["Korean"] = "쿠엘다나스 섬",
			["Mexican"] = "Isla de Quel'Danas",
			["Portuguese"] = "Ilha de Quel'Danas",
			["Russian"] = "Остров Кель'Данас",
			["Spanish"] = "Isla de Quel'Danas",
			["Taiwanese"] = "奎爾丹納斯島",
		},
		["phase"] = 5,
	},
	{
		["continent_id"] = 5,
		["expansion"] = 2,
		["id"] = 4131,
		["levels"] = {
			["max"] = 70,
			["min"] = 69,
		},
		["name"] = {
			["Chinese"] = "魔导师平台",
			["English"] = "Magisters' Terrace",
			["French"] = "Terrasse des Magistères",
			["German"] = "Terrasse der Magister",
			["Korean"] = "마법학자의 정원",
			["Mexican"] = "Bancal del Magister",
			["Portuguese"] = "Terraço dos Magísteres",
			["Russian"] = "Терраса Магистров",
			["Spanish"] = "Bancal del Magister",
			["Taiwanese"] = "魔導師平台",
		},
		["phase"] = 5,
	},
}

for _, entry in ipairs(tbc_zones) do
	table.insert(RR_DATA["zones"], entry)
end
