-------------------------------------------------------
-- All items (Alchemy) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Alchemy"] then RR_DATA["items"]["Alchemy"] = {} end
local tbc_items = 
{
	{
		["expansion"] = 2,
		["id"] = 13517,
		["name"] = {
			["Chinese"] = "炼金石",
			["English"] = "Alchemist's Stone",
			["French"] = "Pierre d'alchimiste",
			["German"] = "Alchimistenstein",
			["Korean"] = "연금술사의 돌",
			["Mexican"] = "Piedra de alquimista",
			["Portuguese"] = "Pedra do Alquimista",
			["Russian"] = "Алхимический камень",
			["Spanish"] = "Piedra de alquimista",
			["Taiwanese"] = "煉金石",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22900,
		["name"] = {
			["Chinese"] = "配方：伪装药剂",
			["English"] = "Recipe: Elixir of Camouflage",
			["French"] = "Recette : Elixir de dissimulation",
			["German"] = "Rezept: Elixier der Tarnung",
			["Korean"] = "조제법: 위장의 비약",
			["Mexican"] = "Receta: elixir de camuflaje",
			["Portuguese"] = "Receita: Elixir de Camuflagem",
			["Russian"] = "Рецепт: эликсир маскировки",
			["Spanish"] = "Receta: elixir de camuflaje",
			["Taiwanese"] = "配方:隱身藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				16588,
				16641,
				16705,
				18802,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22901,
		["name"] = {
			["Chinese"] = "配方：潜行药水",
			["English"] = "Recipe: Sneaking Potion",
			["French"] = "Recette : Potion furtive",
			["German"] = "Rezept: Schleichtrank",
			["Korean"] = "조제법: 은신의 물약",
			["Mexican"] = "Receta: poción de Escabullida",
			["Portuguese"] = "Receita: Poção Furtiva",
			["Russian"] = "Рецепт: зелье лазутчика",
			["Spanish"] = "Receta: poción de Escabullida",
			["Taiwanese"] = "配方:潛行藥水",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				18017,
				19042,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22902,
		["name"] = {
			["Chinese"] = "配方：特效冰霜能量药剂",
			["English"] = "Recipe: Elixir of Major Frost Power",
			["French"] = "Recette : Elixir de puissance du Givre majeure",
			["German"] = "Rezept: Elixier der erheblichen Frostmacht",
			["Korean"] = "조제법: 최상급 냉기 강화의 비약",
			["Mexican"] = "Receta: elixir de poder de Escarcha sublime",
			["Portuguese"] = "Receita: Elixir de Poder Gélido Elevado",
			["Russian"] = "Рецепт: улучшенный эликсир силы льда",
			["Spanish"] = "Receta: elixir de poder de Escarcha sublime",
			["Taiwanese"] = "配方:極效冰霜之力藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				18005,
				18017,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				16507,
				18493,
			},
		},
		["expansion"] = 2,
		["id"] = 22903,
		["name"] = {
			["Chinese"] = "配方：疯狂力量药水",
			["English"] = "Recipe: Insane Strength Potion",
			["French"] = "Recette : Potion de Force démente",
			["German"] = "Rezept: Trank der Wahnsinnsstärke",
			["Korean"] = "조제법: 광기어린 힘의 물약",
			["Mexican"] = "Receta: poción de fuerza demente",
			["Portuguese"] = "Receita: Poção de Força Insana",
			["Russian"] = "Рецепт: зелье безумной силы",
			["Spanish"] = "Receta: poción de fuerza demente",
			["Taiwanese"] = "配方:瘋狂力量藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				18313,
			},
		},
		["expansion"] = 2,
		["id"] = 22904,
		["name"] = {
			["Chinese"] = "配方：搜寻之眼药剂",
			["English"] = "Recipe: Elixir of the Searching Eye",
			["French"] = "Recette : Elixir de l'oeil inquisiteur",
			["German"] = "Rezept: Elixier des suchenden Auges",
			["Korean"] = "조제법: 탐색의 비약",
			["Mexican"] = "Receta: elixir del ojo escrutador",
			["Portuguese"] = "Receita: Elixir do Olhar Inquiridor",
			["Russian"] = "Рецепт: эликсир \"Зоркий глаз\"",
			["Spanish"] = "Receta: elixir del ojo escrutador",
			["Taiwanese"] = "配方:搜尋之眼藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22905,
		["name"] = {
			["Chinese"] = "配方：特效敏捷药剂",
			["English"] = "Recipe: Elixir of Major Agility",
			["French"] = "Recette : Elixir d'agilité majeure",
			["German"] = "Rezept: Elixier der erheblichen Beweglichkeit",
			["Korean"] = "조제법: 최상급 민첩의 비약",
			["Mexican"] = "Receta: elixir de agilidad sublime",
			["Portuguese"] = "Receita: Elixir de Agilidade Elevada",
			["Russian"] = "Рецепт: большой эликсир ловкости",
			["Spanish"] = "Receta: elixir de agilidad sublime",
			["Taiwanese"] = "配方:極效敏捷藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22906,
		["name"] = {
			["Chinese"] = "配方：遮罩药水",
			["English"] = "Recipe: Shrouding Potion",
			["French"] = "Recette : Potion de voilage",
			["German"] = "Rezept: Verschleierungstrank",
			["Korean"] = "조제법: 장막의 물약",
			["Mexican"] = "Receta: poción de velo",
			["Portuguese"] = "Receita: Poção de Esconderijo",
			["Russian"] = "Рецепт: зелье покровов",
			["Spanish"] = "Receta: poción de velo",
			["Taiwanese"] = "配方:漸隱藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["currency"] = 24245,
			["price"] = 30,
			["sources"] = {
				18382,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22907,
		["name"] = {
			["Chinese"] = "配方：超级法力药水",
			["English"] = "Recipe: Super Mana Potion",
			["French"] = "Recette : Potion de super-mana",
			["German"] = "Rezept: Erstklassiger Manatrank",
			["Korean"] = "조제법: 특급 마나 물약",
			["Mexican"] = "Receta: superpoción de maná",
			["Portuguese"] = "Receita: Super Poção de Mana",
			["Russian"] = "Рецепт: гигантский флакон с зельем маны",
			["Spanish"] = "Receta: superpoción de maná",
			["Taiwanese"] = "配方:超強效法力藥水",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				18005,
				19837,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22908,
		["name"] = {
			["Chinese"] = "配方：特效火力药剂",
			["English"] = "Recipe: Elixir of Major Firepower",
			["French"] = "Recette : Elixir de maîtrise du Feu majeure",
			["German"] = "Rezept: Elixier der erheblichen Feuermacht",
			["Korean"] = "조제법: 최상급 화염 강화의 비약",
			["Mexican"] = "Receta: elixir de poder de Fuego sublime",
			["Portuguese"] = "Receita: Elixir de Poder de Fogo Elevado",
			["Russian"] = "Рецепт: большой эликсир огневой мощи",
			["Spanish"] = "Receta: elixir de poder de Fuego sublime",
			["Taiwanese"] = "配方:極效火焰之力藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22909,
		["name"] = {
			["Chinese"] = "配方：特效防御药剂",
			["English"] = "Recipe: Elixir of Major Defense",
			["French"] = "Recette : Elixir de défense majeure",
			["German"] = "Rezept: Elixier der erheblichen Verteidigung",
			["Korean"] = "조제법: 일급 방어의 비약",
			["Mexican"] = "Receta: elixir de defensa sublime",
			["Portuguese"] = "Receita: Elixir de Defesa Elevada",
			["Russian"] = "Рецепт: большой эликсир защиты",
			["Spanish"] = "Receta: elixir de defensa sublime",
			["Taiwanese"] = "配方:極效防禦藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				18005,
				19837,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22910,
		["name"] = {
			["Chinese"] = "配方：特效暗影能量药剂",
			["English"] = "Recipe: Elixir of Major Shadow Power",
			["French"] = "Recette : Elixir de puissance de l'Ombre majeure",
			["German"] = "Rezept: Elixier der erheblichen Schattenmacht",
			["Korean"] = "조제법: 최상급 암흑 강화의 비약",
			["Mexican"] = "Receta: elixir de poder de las Sombras sublime",
			["Portuguese"] = "Receita: Elixir de Poder Sombrio Elevado",
			["Russian"] = "Рецепт: большой эликсир энергии Тьмы",
			["Spanish"] = "Receta: elixir de poder de las Sombras sublime",
			["Taiwanese"] = "配方:極效暗影之力藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 1011,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				21655,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22911,
		["name"] = {
			["Chinese"] = "配方：特效无梦睡眠药水",
			["English"] = "Recipe: Major Dreamless Sleep Potion",
			["French"] = "Recette : Potion de sommeil sans rêve majeure",
			["German"] = "Rezept: Erheblicher Trank des traumlosen Schlafs",
			["Korean"] = "조제법: 최상급 숙면의 물약",
			["Mexican"] = "Receta: poción de letargo sin sueños sublime",
			["Portuguese"] = "Receita: Poção Elevada de Sono sem Sonhos",
			["Russian"] = "Рецепт: большое зелье спокойного сна",
			["Spanish"] = "Receta: poción de letargo sin sueños sublime",
			["Taiwanese"] = "配方:極效昏睡藥水",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				19042,
				19837,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22912,
		["name"] = {
			["Chinese"] = "配方：英雄药水",
			["English"] = "Recipe: Heroic Potion",
			["French"] = "Recette : Potion héroïque",
			["German"] = "Rezept: Heldentrank",
			["Korean"] = "조제법: 영웅의 물약",
			["Mexican"] = "Receta: poción de heroicidad",
			["Portuguese"] = "Receita: Poção de Heroísmo",
			["Russian"] = "Рецепт: зелье героизма",
			["Spanish"] = "Receta: poción de heroicidad",
			["Taiwanese"] = "配方:英勇藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22913,
		["name"] = {
			["Chinese"] = "配方：加速药水",
			["English"] = "Recipe: Haste Potion",
			["French"] = "Recette : Potion de hâte",
			["German"] = "Rezept: Hasttrank",
			["Korean"] = "조제법: 가속의 물약",
			["Mexican"] = "Receta: poción de celeridad",
			["Portuguese"] = "Receita: Poção de Aceleração",
			["Russian"] = "Рецепт: зелье ускорения",
			["Spanish"] = "Receta: poción de celeridad",
			["Taiwanese"] = "配方:急速藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				18328,
			},
		},
		["expansion"] = 2,
		["id"] = 22914,
		["name"] = {
			["Chinese"] = "配方：毁灭药水",
			["English"] = "Recipe: Destruction Potion",
			["French"] = "Recette : Potion de destruction",
			["German"] = "Rezept: Zerstörungstrank",
			["Korean"] = "조제법: 파괴의 물약",
			["Mexican"] = "Receta: poción de destrucción",
			["Portuguese"] = "Receita: Poção de Destruição",
			["Russian"] = "Рецепт: зелье разрушения",
			["Spanish"] = "Receta: poción de destrucción",
			["Taiwanese"] = "配方:毀滅藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22915,
		["name"] = {
			["Chinese"] = "配方：源气转火",
			["English"] = "Recipe: Transmute Primal Air to Fire",
			["French"] = "Recette : Transmutation primordiale (Air en Feu)",
			["German"] = "Rezept: Urluft zu Urfeuer transmutieren",
			["Korean"] = "조제법: 바람의 근원을 불로 변환",
			["Mexican"] = "Receta: transmutar aire primigenio en fuego",
			["Portuguese"] = "Receita: Transmutar Ar Primevo em Fogo Primevo",
			["Russian"] = "Рецепт: трансмутация изначального воздуха в огонь",
			["Spanish"] = "Receta: transmutar aire primigenio en fuego",
			["Taiwanese"] = "配方:原始空氣轉化原始之火",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22916,
		["name"] = {
			["Chinese"] = "配方：源土转水",
			["English"] = "Recipe: Transmute Primal Earth to Water",
			["French"] = "Recette : Transmutation primordiale (Terre en Eau)",
			["German"] = "Rezept: Urerde zu Urwasser transmutieren",
			["Korean"] = "조제법: 대지의 근원을 물로 변환",
			["Mexican"] = "Receta: transmutar tierra primigenia a agua",
			["Portuguese"] = "Receita: Transmutar Terra Primeva em Água Primeva",
			["Russian"] = "Рецепт: трансмутация изначальной земли в воду",
			["Spanish"] = "Receta: transmutar tierra primigenia a agua",
			["Taiwanese"] = "配方:原始大地轉化原始之水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["currency"] = 24245,
			["price"] = 25,
			["sources"] = {
				18382,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22917,
		["name"] = {
			["Chinese"] = "配方：源火转土",
			["English"] = "Recipe: Transmute Primal Fire to Earth",
			["French"] = "Recette : Transmutation primordiale (Feu en Terre)",
			["German"] = "Rezept: Urfeuer zu Urerde transmutieren",
			["Korean"] = "조제법: 불의 근원을 대지로 변환",
			["Mexican"] = "Receta: transmutar fuego primigenio a tierra",
			["Portuguese"] = "Receita: Transmutar Fogo Primevo em Terra Primeva",
			["Russian"] = "Рецепт: трансмутация изначального огня в землю",
			["Spanish"] = "Receta: transmutar fuego primigenio a tierra",
			["Taiwanese"] = "配方:原始之火轉化原始大地",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 941,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				20241,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22918,
		["name"] = {
			["Chinese"] = "配方：源水转气",
			["English"] = "Recipe: Transmute Primal Water to Air",
			["French"] = "Recette : Transmutation primordiale (Eau en Air)",
			["German"] = "Rezept: Urwasser zu Urluft transmutieren",
			["Korean"] = "조제법: 물의 근원을 바람으로 변환",
			["Mexican"] = "Receta: transmutar agua primigenia a aire",
			["Portuguese"] = "Receita: Transmutar Água Primeva em Ar",
			["Russian"] = "Рецепт: трансмутация изначальной воды в воздух",
			["Spanish"] = "Receta: transmutar agua primigenia a aire",
			["Taiwanese"] = "配方:原始之水轉化原始空氣",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22919,
		["name"] = {
			["Chinese"] = "配方：特效魔血药剂",
			["English"] = "Recipe: Elixir of Major Mageblood",
			["French"] = "Recette : Elixir magesang majeur",
			["German"] = "Rezept: Elixier des erheblichen Magierbluts",
			["Korean"] = "조제법: 최상급 마력의 비약",
			["Mexican"] = "Receta: elixir de sangre de mago sublime",
			["Portuguese"] = "Receita: Elixir de Sangue de Mago Elevado",
			["Russian"] = "Рецепт: мощный эликсир крови волшебника",
			["Spanish"] = "Receta: elixir de sangre de mago sublime",
			["Taiwanese"] = "配方:極效魔血藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				19221,
			},
		},
		["expansion"] = 2,
		["id"] = 22920,
		["name"] = {
			["Chinese"] = "配方：特效火焰防护药水",
			["English"] = "Recipe: Major Fire Protection Potion",
			["French"] = "Recette : Potion de protection contre le Feu majeure",
			["German"] = "Rezept: Erheblicher Feuerschutztrank",
			["Korean"] = "조제법: 최상급 화염 보호 물약",
			["Mexican"] = "Receta: poción de Protección contra el Fuego sublime",
			["Portuguese"] = "Receita: Poção Elevada de Proteção contra o Fogo",
			["Russian"] = "Рецепт: сильное зелье защиты от огня",
			["Spanish"] = "Receta: poción de Protección contra el Fuego sublime",
			["Taiwanese"] = "配方:極效火焰防護藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				18344,
			},
		},
		["expansion"] = 2,
		["id"] = 22921,
		["name"] = {
			["Chinese"] = "配方：特效冰霜防护药水",
			["English"] = "Recipe: Major Frost Protection Potion",
			["French"] = "Recette : Potion de protection contre le Givre majeure",
			["German"] = "Rezept: Erheblicher Frostschutztrank",
			["Korean"] = "조제법: 최상급 냉기 보호 물약",
			["Mexican"] = "Receta: poción de Protección contra la Escarcha sublime",
			["Portuguese"] = "Receita: Poção Elevada de Proteção contra o Gelo",
			["Russian"] = "Рецепт: сильное зелье защиты от магии льда",
			["Spanish"] = "Receta: poción de Protección contra la Escarcha sublime",
			["Taiwanese"] = "配方:極效冰霜防護藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22922,
		["name"] = {
			["Chinese"] = "配方：特效自然防护药水",
			["English"] = "Recipe: Major Nature Protection Potion",
			["French"] = "Recette : Potion de protection contre la Nature majeure",
			["German"] = "Rezept: Erheblicher Naturschutztrank",
			["Korean"] = "조제법: 최상급 자연 보호 물약",
			["Mexican"] = "Receta: poción de Protección contra la Naturaleza sublime",
			["Portuguese"] = "Receita: Poção Elevada de Proteção contra a Natureza",
			["Russian"] = "Рецепт: сильное зелье защиты от сил природы",
			["Spanish"] = "Receta: poción de Protección contra la Naturaleza sublime",
			["Taiwanese"] = "配方:極效自然防護藥水",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				17150,
			},
		},
		["expansion"] = 2,
		["id"] = 22923,
		["name"] = {
			["Chinese"] = "配方：特效奥术防护药水",
			["English"] = "Recipe: Major Arcane Protection Potion",
			["French"] = "Recette : Potion de protection contre les Arcanes majeure",
			["German"] = "Rezept: Erheblicher Arkanschutztrank",
			["Korean"] = "조제법: 최상급 비전 보호 물약",
			["Mexican"] = "Receta: poción de Protección contra lo Arcano sublime",
			["Portuguese"] = "Receita: Poção Elevada de Proteção contra o Arcano",
			["Russian"] = "Рецепт: большое зелье защиты от тайной магии",
			["Spanish"] = "Receta: poción de Protección contra lo Arcano sublime",
			["Taiwanese"] = "配方:極效秘法防護藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				21302,
			},
		},
		["expansion"] = 2,
		["id"] = 22924,
		["name"] = {
			["Chinese"] = "配方：特效暗影防护药水",
			["English"] = "Recipe: Major Shadow Protection Potion",
			["French"] = "Recette : Potion de protection contre l'Ombre majeure",
			["German"] = "Rezept: Erheblicher Schattenschutztrank",
			["Korean"] = "조제법: 최상급 암흑 보호 물약",
			["Mexican"] = "Receta: poción de Protección contra las Sombras sublime",
			["Portuguese"] = "Receita: Poção Elevada de Proteção contra a Sombra",
			["Russian"] = "Рецепт: сильное зелье защиты от темной магии",
			["Spanish"] = "Receta: poción de Protección contra las Sombras sublime",
			["Taiwanese"] = "配方:極效暗影防護藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				19973,
			},
		},
		["expansion"] = 2,
		["id"] = 22925,
		["name"] = {
			["Chinese"] = "配方：特效神圣防护药水",
			["English"] = "Recipe: Major Holy Protection Potion",
			["French"] = "Recette : Potion de protection contre le Sacré majeure",
			["German"] = "Rezept: Erheblicher Heiligschutztrank",
			["Korean"] = "조제법: 최상급 신성 보호 물약",
			["Mexican"] = "Receta: poción de Protección contra lo Sagrado sublime",
			["Portuguese"] = "Receita: Poção Elevada de Proteção contra o Sagrado",
			["Russian"] = "Рецепт: сильное зелье защиты от светлой магии",
			["Spanish"] = "Receta: poción de Protección contra lo Sagrado sublime",
			["Taiwanese"] = "配方:極效神聖防護藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22926,
		["name"] = {
			["Chinese"] = "配方：强化药剂",
			["English"] = "Recipe: Elixir of Empowerment",
			["French"] = "Recette : Elixir de renforcement",
			["German"] = "Rezept: Elixier der Schwächung",
			["Korean"] = "조제법: 권능의 비약",
			["Mexican"] = "Receta: elixir de potenciación",
			["Portuguese"] = "Receita: Elixir de Potencialização",
			["Russian"] = "Рецепт: эликсир подавления",
			["Spanish"] = "Receta: elixir de empoderación",
			["Taiwanese"] = "配方:活效藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				17862,
			},
		},
		["expansion"] = 2,
		["id"] = 22927,
		["name"] = {
			["Chinese"] = "配方：铁盾药水",
			["English"] = "Recipe: Ironshield Potion",
			["French"] = "Recette : Potion de bouclier de fer",
			["German"] = "Rezept: Eisenschildtrank",
			["Korean"] = "조제법: 무쇠방패 물약",
			["Mexican"] = "Receta: poción de escudo de hierro",
			["Portuguese"] = "Receita: Poção de Escudo Férreo",
			["Russian"] = "Рецепт: зелье железного щита",
			["Spanish"] = "Receta: poción de escudo de hierro",
			["Taiwanese"] = "配方:鐵盾藥水",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 23574,
		["name"] = {
			["Chinese"] = "配方：源生之能",
			["English"] = "Recipe: Transmute Primal Might",
			["French"] = "Recette : Transmutation primordiale (Pouvoir)",
			["German"] = "Rezept: Urmacht transmutieren",
			["Korean"] = "조제법: 힘의 근원 변환식",
			["Mexican"] = "Receta: transmutar poderío primigenio",
			["Portuguese"] = "Receita: Transmutar Poder Primevo",
			["Russian"] = "Рецепт: трансмутация изначальной мощи",
			["Spanish"] = "Receta: transmutar poderío primigenio",
			["Taiwanese"] = "配方:轉化原始力量",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				16641,
				16705,
				19074,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24001,
		["name"] = {
			["Chinese"] = "配方：特效敏捷药剂",
			["English"] = "Recipe: Elixir of Major Agility",
			["French"] = "Recette : Elixir d'agilité majeure",
			["German"] = "Rezept: Elixier der erheblichen Beweglichkeit",
			["Korean"] = "조제법: 최상급 민첩의 비약",
			["Mexican"] = "Receta: elixir de agilidad sublime",
			["Portuguese"] = "Receita: Elixir de Agilidade Elevada",
			["Russian"] = "Рецепт: большой эликсир ловкости",
			["Spanish"] = "Receta: elixir de agilidad sublime",
			["Taiwanese"] = "配方:極效敏捷藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25869,
		["name"] = {
			["Chinese"] = "配方：合成大地风暴钻石",
			["English"] = "Recipe: Transmute Earthstorm Diamond",
			["French"] = "Recette : Transmutation de diamant tonneterre",
			["German"] = "Rezept: Erdsturmdiamanten transmutieren",
			["Korean"] = "조제법: 대지폭풍 다이아몬드 변환식",
			["Mexican"] = "Receta: transmutar diamante de tormenta de tierra",
			["Portuguese"] = "Receita: Transmutar Diamante Tempesterra",
			["Russian"] = "Рецепт: трансмутация алмаза земной бури",
			["Spanish"] = "Receta: transmutar diamante de tormenta de tierra",
			["Taiwanese"] = "配方:轉化大地風暴鑽石",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25870,
		["name"] = {
			["Chinese"] = "配方：合成天火钻石",
			["English"] = "Recipe: Transmute Skyfire Diamond",
			["French"] = "Recette : Transmutation de diamant brûleciel",
			["German"] = "Rezept: Himmelsfeuerdiamanten transmutieren",
			["Korean"] = "조제법: 하늘불꽃 다이아몬드 변환식",
			["Mexican"] = "Receta: transmutar diamante de fuego celeste",
			["Portuguese"] = "Receita: Transmutar Diamante Fogocéu",
			["Russian"] = "Рецепт: трансмутация алмаза небесного огня",
			["Spanish"] = "Receta: transmutar diamante de fuego celeste",
			["Taiwanese"] = "配方:轉化天火鑽石",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29232,
		["name"] = {
			["Chinese"] = "配方：合成天火钻石",
			["English"] = "Recipe: Transmute Skyfire Diamond",
			["French"] = "Recette : Transmutation de diamant brûleciel",
			["German"] = "Rezept: Himmelsfeuerdiamanten transmutieren",
			["Korean"] = "조제법: 하늘불꽃 다이아몬드 변환식",
			["Mexican"] = "Receta: transmutar diamante de fuego celeste",
			["Portuguese"] = "Receita: Transmutar Diamante Fogocéu",
			["Russian"] = "Рецепт: трансмутация алмаза небесного огня",
			["Spanish"] = "Receta: transmutar diamante de fuego celeste",
			["Taiwanese"] = "配方:轉化天火鑽石",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30443,
		["name"] = {
			["Chinese"] = "配方：源火转土",
			["English"] = "Recipe: Transmute Primal Fire to Earth",
			["French"] = "Recette : Transmutation primordiale (Feu en Terre)",
			["German"] = "Rezept: Urfeuer zu Urerde transmutieren",
			["Korean"] = "조제법: 불의 근원을 대지로 변환",
			["Mexican"] = "Receta: transmutar fuego primigenio a tierra",
			["Portuguese"] = "Receita: Transmutar Fogo Primevo em Terra Primeva",
			["Russian"] = "Рецепт: трансмутация изначального огня в землю",
			["Spanish"] = "Receta: transmutar fuego primigenio a tierra",
			["Taiwanese"] = "配方:原始之火轉化原始大地",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 978,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				20240,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31354,
		["name"] = {
			["Chinese"] = "配方：泰坦合剂",
			["English"] = "Recipe: Flask of the Titans",
			["French"] = "Recette : Flacon des Titans",
			["German"] = "Rezept: Fläschchen der Titanen",
			["Korean"] = "조제법: 티탄의 영약",
			["Mexican"] = "Receta: frasco de los titanes",
			["Portuguese"] = "Receita: Frasco dos Titãs",
			["Russian"] = "Рецепт: настой титанов",
			["Spanish"] = "Receta: frasco de los Titanes",
			["Taiwanese"] = "配方:泰坦精煉藥劑",
		},
		["phase"] = 2,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31355,
		["name"] = {
			["Chinese"] = "配方：超级能量合剂",
			["English"] = "Recipe: Flask of Supreme Power",
			["French"] = "Recette : Flacon de pouvoir suprême",
			["German"] = "Rezept: Fläschchen der obersten Macht",
			["Korean"] = "조제법: 강력한 마력의 영약",
			["Mexican"] = "Receta: frasco de poder supremo",
			["Portuguese"] = "Receita: Frasco de Poder Supremo",
			["Russian"] = "Рецепт: настой великой силы",
			["Spanish"] = "Receta: frasco de poder supremo",
			["Taiwanese"] = "配方:超級能量精煉藥劑",
		},
		["phase"] = 2,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 989,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				21643,
			},
		},
	},
	{
		["expansion"] = 1,
		["id"] = 31356,
		["name"] = {
			["Chinese"] = "配方：精炼智慧合剂",
			["English"] = "Recipe: Flask of Distilled Wisdom",
			["French"] = "Recette : Flacon de sagesse distillée",
			["German"] = "Rezept: Fläschchen der destillierten Weisheit",
			["Korean"] = "조제법: 순수한 지혜의 영약",
			["Mexican"] = "Receta: frasco de sabiduría destilada",
			["Portuguese"] = "Receita: Frasco de Sabedoria Destilada",
			["Russian"] = "Рецепт: настой чистой мудрости",
			["Spanish"] = "Receta: frasco de sabiduría destilada",
			["Taiwanese"] = "配方:智慧精煉藥劑",
		},
		["phase"] = 2,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31357,
		["name"] = {
			["Chinese"] = "配方：多重抗性合剂",
			["English"] = "Recipe: Flask of Chromatic Resistance",
			["French"] = "Recette : Flacon de résistance chromatique",
			["German"] = "Rezept: Fläschchen des chromatischen Widerstands",
			["Korean"] = "조제법: 마력 저항의 영약",
			["Mexican"] = "Receta: frasco de resistencia cromática",
			["Portuguese"] = "Receita: Frasco de Resistência Cromática",
			["Russian"] = "Рецепт: настой разноцветного сопротивления",
			["Spanish"] = "Receta: frasco de resistencia cromática",
			["Taiwanese"] = "配方:多重抗性精煉藥劑",
		},
		["phase"] = 4,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 1011,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				21655,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				19740,
				19755,
				21302,
				21314,
			},
		},
		["expansion"] = 2,
		["id"] = 31680,
		["name"] = {
			["Chinese"] = "配方：魔能力量药剂",
			["English"] = "Recipe: Fel Strength Elixir",
			["French"] = "Recette : Elixir de force gangrené",
			["German"] = "Rezept: Elixier der Teufelsstärke",
			["Korean"] = "조제법: 타락한 힘의 비약",
			["Mexican"] = "Receta: elixir de fuerza vil",
			["Portuguese"] = "Receita: Elixir de Força Vil",
			["Russian"] = "Рецепт: оскверненный эликсир силы",
			["Spanish"] = "Receta: elixir de fuerza vil",
			["Taiwanese"] = "配方:魔化力量藥劑",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				19754,
				19756,
				20878,
				20887,
			},
		},
		["expansion"] = 2,
		["id"] = 31681,
		["name"] = {
			["Chinese"] = "配方：魔能回复药水",
			["English"] = "Recipe: Fel Regeneration Potion",
			["French"] = "Recette : Potion de régénération gangrenée",
			["German"] = "Rezept: Teufelsregenerationstrank",
			["Korean"] = "조제법: 타락의 회복 물약",
			["Mexican"] = "Receta: poción de regeneración vil",
			["Portuguese"] = "Receita: Poção Vil de Regeneração",
			["Russian"] = "Рецепт: оскверненное зелье регенерации",
			["Spanish"] = "Receta: poción de regeneración vil",
			["Taiwanese"] = "配方:魔化再生藥水",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				19797,
			},
		},
		["expansion"] = 2,
		["id"] = 31682,
		["name"] = {
			["Chinese"] = "配方：魔能法力药水",
			["English"] = "Recipe: Fel Mana Potion",
			["French"] = "Recette : Potion de mana gangrenée",
			["German"] = "Rezept: Teufelsmanatrank",
			["Korean"] = "조제법: 타락의 마나 물약",
			["Mexican"] = "Receta: poción de maná vil",
			["Portuguese"] = "Receita: Poção Vil de Mana",
			["Russian"] = "Рецепт: оскверненное зелье маны",
			["Spanish"] = "Receta: poción de maná vil",
			["Taiwanese"] = "配方:魔化法力藥水",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 32070,
		["name"] = {
			["Chinese"] = "配方：土灵药剂",
			["English"] = "Recipe: Earthen Elixir",
			["French"] = "Recette : Elixir terrestre",
			["German"] = "Rezept: Erdelixier",
			["Korean"] = "조제법: 대지의 비약",
			["Mexican"] = "Receta: elixir terráneo",
			["Portuguese"] = "Receita: Elixir Terrano",
			["Russian"] = "Рецепт: эликсир земли",
			["Spanish"] = "Receta: elixir terráneo",
			["Taiwanese"] = "配方:地化藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32071,
		["name"] = {
			["Chinese"] = "配方：铁皮药剂",
			["English"] = "Recipe: Elixir of Ironskin",
			["French"] = "Recette : Elixir peau-de-fer",
			["German"] = "Rezept: Elixier der Eisenhaut",
			["Korean"] = "조제법: 무쇠가죽 비약",
			["Mexican"] = "Receta: elixir de piel de hierro",
			["Portuguese"] = "Receita: Elixir de Pele de Ferro",
			["Russian"] = "Рецепт: эликсир железной шкуры",
			["Spanish"] = "Receta: elixir de piel de hierro",
			["Taiwanese"] = "配方:鐵膚藥劑",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["currency"] = 26044,
			["price"] = 2,
			["sources"] = {
				18821,
				18822,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33209,
		["name"] = {
			["Chinese"] = "配方：多彩奇迹合剂",
			["English"] = "Recipe: Flask of Chromatic Wonder",
			["French"] = "Recette : Flacon de merveille chromatique",
			["German"] = "Rezept: Fläschchen des chromatischen Wunders",
			["Korean"] = "조제법: 오색 신비의 영약",
			["Mexican"] = "Receta: frasco de Maravilla cromática",
			["Portuguese"] = "Receita: Frasco de Maravilha Cromática",
			["Russian"] = "Рецепт: настой всецветного чуда",
			["Spanish"] = "Receta: frasco de Maravilla cromática",
			["Taiwanese"] = "配方:炫彩驚奇精煉藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				18255,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35294,
		["name"] = {
			["Chinese"] = "配方：强化药剂",
			["English"] = "Recipe: Elixir of Empowerment",
			["French"] = "Recette : Elixir de renforcement",
			["German"] = "Rezept: Elixier der Schwächung",
			["Korean"] = "조제법: 권능의 비약",
			["Mexican"] = "Receta: elixir de potenciación",
			["Portuguese"] = "Receita: Elixir de Potencialização",
			["Russian"] = "Рецепт: эликсир подавления",
			["Spanish"] = "Receta: elixir de empoderación",
			["Taiwanese"] = "配方:活效藥劑",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35295,
		["name"] = {
			["Chinese"] = "配方：加速药水",
			["English"] = "Recipe: Haste Potion",
			["French"] = "Recette : Potion de hâte",
			["German"] = "Rezept: Hasttrank",
			["Korean"] = "조제법: 가속의 물약",
			["Mexican"] = "Receta: poción de celeridad",
			["Portuguese"] = "Receita: Poção de Aceleração",
			["Russian"] = "Рецепт: зелье ускорения",
			["Spanish"] = "Receta: poción de celeridad",
			["Taiwanese"] = "配方:急速藥水",
		},
		["phase"] = 5,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 35752,
		["name"] = {
			["Chinese"] = "配方：守护者的炼金石",
			["English"] = "Recipe: Guardian's Alchemist Stone",
			["French"] = "Recette : Pierre d'alchimiste de gardien",
			["German"] = "Rezept: Alchimistenstein des Wächters",
			["Korean"] = "조제법: 수호자의 연금술사 돌",
			["Mexican"] = "Receta: piedra de alquimista de guardián",
			["Portuguese"] = "Receita: Pedra do Alquimista do Guardião",
			["Russian"] = "Рецепт: алхимический камень стража",
			["Spanish"] = "Receta: piedra de alquimista de guardián",
			["Taiwanese"] = "配方:守護者鍊金石",
		},
		["phase"] = 5,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 250000,
			["sources"] = {
				25032,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35753,
		["name"] = {
			["Chinese"] = "配方：巫师的炼金石",
			["English"] = "Recipe: Sorcerer's Alchemist Stone",
			["French"] = "Recette : Pierre d'alchimiste d'ensorceleur",
			["German"] = "Rezept: Alchimistenstein des Zauberhexers",
			["Korean"] = "조제법: 마술사의 연금술사 돌",
			["Mexican"] = "Receta: piedra de alquimista de hechicero",
			["Portuguese"] = "Receita: Pedra do Alquimista do Feiticeiro",
			["Russian"] = "Рецепт: алхимический камень чародея",
			["Spanish"] = "Receta: piedra de alquimista de hechicero",
			["Taiwanese"] = "配方:巫士鍊金石",
		},
		["phase"] = 5,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 250000,
			["sources"] = {
				25032,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35754,
		["name"] = {
			["Chinese"] = "配方：救赎者的炼金石",
			["English"] = "Recipe: Redeemer's Alchemist Stone",
			["French"] = "Recette : Pierre d'alchimiste de rédempteur",
			["German"] = "Rezept: Alchimistenstein des Erlösers",
			["Korean"] = "조제법: 구원자의 연금술사 돌",
			["Mexican"] = "Receta: piedra de alquimista de redentor",
			["Portuguese"] = "Receita: Pedra do Alquimista do Redentor",
			["Russian"] = "Рецепт: алхимический камень искупителя",
			["Spanish"] = "Receta: piedra de alquimista de redentor",
			["Taiwanese"] = "配方:救贖者鍊金石",
		},
		["phase"] = 5,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 250000,
			["sources"] = {
				25032,
			},
		},
	},
	{
		["expansion"] = 2,
		["faction_id"] = 1077,
		["id"] = 35755,
		["name"] = {
			["Chinese"] = "配方：刺客的炼金石",
			["English"] = "Recipe: Assassin's Alchemist Stone",
			["French"] = "Recette : Pierre d'alchimiste d'assassin",
			["German"] = "Rezept: Alchimistenstein des Assassinen",
			["Korean"] = "조제법: 암살자의 연금술사 돌",
			["Mexican"] = "Receta: piedra de alquimista de asesino",
			["Portuguese"] = "Receita: Pedra do Alquimista do Assassino",
			["Russian"] = "Рецепт: алхимический камень убийцы",
			["Spanish"] = "Receta: piedra de alquimista de asesino",
			["Taiwanese"] = "配方:刺客鍊金石",
		},
		["phase"] = 5,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 250000,
			["sources"] = {
				25032,
			},
		},
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Alchemy"], item)
end
