-------------------------------------------------------
-- All skills (Alchemy) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Alchemy"] then RR_DATA["skills"]["Alchemy"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 17632,
		["item_id"] = 13503,
		["items"] = {
			13517,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "炼金石",
			["English"] = "Alchemist's Stone",
			["French"] = "Pierre d'alchimiste",
			["German"] = "Alchimistenstein",
			["Korean"] = "연금술사의 돌",
			["Mexican"] = "Piedra de alquimista",
			["Portuguese"] = "Pedra do Alquimista",
			["Russian"] = "Алхимический камень",
			["Spanish"] = "Piedra de alquimista",
			["Taiwanese"] = "煉金石",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28543,
		["item_id"] = 22823,
		["items"] = {
			22900,
		},
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "伪装药剂",
			["English"] = "Elixir of Camouflage",
			["French"] = "Elixir de dissimulation",
			["German"] = "Elixier der Tarnung",
			["Korean"] = "위장의 비약",
			["Mexican"] = "Elixir de camuflaje",
			["Portuguese"] = "Elixir de Camuflagem",
			["Russian"] = "Эликсир маскировки",
			["Spanish"] = "Elixir de camuflaje",
			["Taiwanese"] = "隱身藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28544,
		["item_id"] = 22824,
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "特效力量药剂",
			["English"] = "Elixir of Major Strength",
			["French"] = "Elixir de force majeure",
			["German"] = "Elixier der erheblichen Stärke",
			["Korean"] = "최상급 힘의 비약",
			["Mexican"] = "Elixir de fuerza sublime",
			["Portuguese"] = "Elixir de Força Elevada",
			["Russian"] = "Большой эликсир силы",
			["Spanish"] = "Elixir de fuerza sublime",
			["Taiwanese"] = "極效力量藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28545,
		["item_id"] = 22825,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "治疗能量药剂",
			["English"] = "Elixir of Healing Power",
			["French"] = "Elixir de pouvoir de guérison",
			["German"] = "Elixier der Heilkraft",
			["Korean"] = "치유력 강화의 비약",
			["Mexican"] = "Elixir de poder de sanación",
			["Portuguese"] = "Elixir de Poder Curativo",
			["Russian"] = "Эликсир целительной силы",
			["Spanish"] = "Elixir de poder de sanación",
			["Taiwanese"] = "治療能量藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28546,
		["item_id"] = 22826,
		["items"] = {
			22901,
		},
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "潜行药水",
			["English"] = "Sneaking Potion",
			["French"] = "Potion furtive",
			["German"] = "Schleichtrank",
			["Korean"] = "은신의 물약",
			["Mexican"] = "Poción de Escabullida",
			["Portuguese"] = "Poção Furtiva",
			["Russian"] = "Зелье лазутчика",
			["Spanish"] = "Poción de Escabullida",
			["Taiwanese"] = "潛行藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28549,
		["item_id"] = 22827,
		["items"] = {
			22902,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "特效冰霜能量药剂",
			["English"] = "Elixir of Major Frost Power",
			["French"] = "Elixir de puissance du Givre majeure",
			["German"] = "Elixier der erheblichen Frostmacht",
			["Korean"] = "최상급 냉기 강화의 비약",
			["Mexican"] = "Elixir de poder de Escarcha sublime",
			["Portuguese"] = "Elixir de Poder Gélido Elevado",
			["Russian"] = "Улучшенный эликсир силы льда",
			["Spanish"] = "Elixir de poder de Escarcha sublime",
			["Taiwanese"] = "極效冰霜之力藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28550,
		["item_id"] = 22828,
		["items"] = {
			22903,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "疯狂力量药水",
			["English"] = "Insane Strength Potion",
			["French"] = "Potion de Force démente",
			["German"] = "Trank der Wahnsinnsstärke",
			["Korean"] = "광기어린 힘의 물약",
			["Mexican"] = "Poción de fuerza demente",
			["Portuguese"] = "Poção de Força Insana",
			["Russian"] = "Зелье безумной силы",
			["Spanish"] = "Poción de fuerza demente",
			["Taiwanese"] = "瘋狂力量藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28551,
		["item_id"] = 22829,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "超级治疗药水",
			["English"] = "Super Healing Potion",
			["French"] = "Potion de super-soins",
			["German"] = "Erstklassiger Heiltrank",
			["Korean"] = "특급 치유 물약",
			["Mexican"] = "Superpoción de sanación",
			["Portuguese"] = "Super Poção de Cura",
			["Russian"] = "Гигантский флакон с лечебным зельем",
			["Spanish"] = "Superpoción de sanación",
			["Taiwanese"] = "超強效治療藥水",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28552,
		["item_id"] = 22830,
		["items"] = {
			22904,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "搜寻之眼药剂",
			["English"] = "Elixir of the Searching Eye",
			["French"] = "Elixir de l'oeil inquisiteur",
			["German"] = "Elixier des suchenden Auges",
			["Korean"] = "탐색의 비약",
			["Mexican"] = "Elixir del ojo escrutador",
			["Portuguese"] = "Elixir do Olhar Inquiridor",
			["Russian"] = "Эликсир \"Зоркий глаз\"",
			["Spanish"] = "Elixir del ojo escrutador",
			["Taiwanese"] = "搜尋之眼藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28553,
		["item_id"] = 22831,
		["items"] = {
			22905,
			24001,
		},
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "特效敏捷药剂",
			["English"] = "Elixir of Major Agility",
			["French"] = "Elixir d'agilité majeure",
			["German"] = "Elixier der erheblichen Beweglichkeit",
			["Korean"] = "최상급 민첩의 비약",
			["Mexican"] = "Elixir de agilidad sublime",
			["Portuguese"] = "Elixir de Agilidade Elevada",
			["Russian"] = "Большой эликсир ловкости",
			["Spanish"] = "Elixir de agilidad sublime",
			["Taiwanese"] = "極效敏捷藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28554,
		["item_id"] = 22871,
		["items"] = {
			22906,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "遮罩药水",
			["English"] = "Shrouding Potion",
			["French"] = "Potion de voilage",
			["German"] = "Verschleierungstrank",
			["Korean"] = "장막의 물약",
			["Mexican"] = "Poción de velo",
			["Portuguese"] = "Poção de Esconderijo",
			["Russian"] = "Зелье покровов",
			["Spanish"] = "Poción de velo",
			["Taiwanese"] = "漸隱藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28555,
		["item_id"] = 22832,
		["items"] = {
			22907,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "超级法力药水",
			["English"] = "Super Mana Potion",
			["French"] = "Potion de super-mana",
			["German"] = "Erstklassiger Manatrank",
			["Korean"] = "특급 마나 물약",
			["Mexican"] = "Superpoción de maná",
			["Portuguese"] = "Super Poção de Mana",
			["Russian"] = "Гигантский флакон с зельем маны",
			["Spanish"] = "Superpoción de maná",
			["Taiwanese"] = "超強效法力藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28556,
		["item_id"] = 22833,
		["items"] = {
			22908,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "特效火力药剂",
			["English"] = "Elixir of Major Firepower",
			["French"] = "Elixir de maîtrise du Feu majeure",
			["German"] = "Elixier der erheblichen Feuermacht",
			["Korean"] = "최상급 화염 강화의 비약",
			["Mexican"] = "Elixir de poder de Fuego sublime",
			["Portuguese"] = "Elixir de Poder de Fogo Elevado",
			["Russian"] = "Большой эликсир огневой мощи",
			["Spanish"] = "Elixir de poder de Fuego sublime",
			["Taiwanese"] = "極效火焰之力藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28557,
		["item_id"] = 22834,
		["items"] = {
			22909,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "特效防御药剂",
			["English"] = "Elixir of Major Defense",
			["French"] = "Elixir de défense majeure",
			["German"] = "Elixier der erheblichen Verteidigung",
			["Korean"] = "일급 방어의 비약",
			["Mexican"] = "Elixir de defensa sublime",
			["Portuguese"] = "Elixir de Defesa Elevada",
			["Russian"] = "Большой эликсир защиты",
			["Spanish"] = "Elixir de defensa sublime",
			["Taiwanese"] = "極效防禦藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28558,
		["item_id"] = 22835,
		["items"] = {
			22910,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "特效暗影能量药剂",
			["English"] = "Elixir of Major Shadow Power",
			["French"] = "Elixir de puissance de l'Ombre majeure",
			["German"] = "Elixier der erheblichen Schattenmacht",
			["Korean"] = "최상급 암흑 강화의 비약",
			["Mexican"] = "Elixir de poder de las Sombras sublime",
			["Portuguese"] = "Elixir de Poder Sombrio Elevado",
			["Russian"] = "Большой эликсир энергии Тьмы",
			["Spanish"] = "Elixir de poder de las Sombras sublime",
			["Taiwanese"] = "極效暗影之力藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28562,
		["item_id"] = 22836,
		["items"] = {
			22911,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "特效无梦睡眠药水",
			["English"] = "Major Dreamless Sleep Potion",
			["French"] = "Potion de sommeil sans rêve majeure",
			["German"] = "Erheblicher Trank des traumlosen Schlafs",
			["Korean"] = "최상급 숙면의 물약",
			["Mexican"] = "Poción de letargo sin sueños sublime",
			["Portuguese"] = "Poção Elevada de Sono sem Sonhos",
			["Russian"] = "Большое зелье спокойного сна",
			["Spanish"] = "Poción de letargo sin sueños sublime",
			["Taiwanese"] = "極效昏睡藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28563,
		["item_id"] = 22837,
		["items"] = {
			22912,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "英雄药水",
			["English"] = "Heroic Potion",
			["French"] = "Potion héroïque",
			["German"] = "Heldentrank",
			["Korean"] = "영웅의 물약",
			["Mexican"] = "Poción de heroicidad",
			["Portuguese"] = "Poção de Heroísmo",
			["Russian"] = "Зелье героизма",
			["Spanish"] = "Poción de heroicidad",
			["Taiwanese"] = "英勇藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28564,
		["item_id"] = 22838,
		["items"] = {
			22913,
			35295,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "加速药水",
			["English"] = "Haste Potion",
			["French"] = "Potion de hâte",
			["German"] = "Hasttrank",
			["Korean"] = "가속의 물약",
			["Mexican"] = "Poción de celeridad",
			["Portuguese"] = "Poção de Aceleração",
			["Russian"] = "Зелье ускорения",
			["Spanish"] = "Poción de celeridad",
			["Taiwanese"] = "急速藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28565,
		["item_id"] = 22839,
		["items"] = {
			22914,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "毁灭药水",
			["English"] = "Destruction Potion",
			["French"] = "Potion de destruction",
			["German"] = "Zerstörungstrank",
			["Korean"] = "파괴의 물약",
			["Mexican"] = "Poción de destrucción",
			["Portuguese"] = "Poção de Destruição",
			["Russian"] = "Зелье разрушения",
			["Spanish"] = "Poción de destrucción",
			["Taiwanese"] = "毀滅藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28566,
		["item_id"] = 21884,
		["items"] = {
			22915,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：源生空气至源生火焰",
			["English"] = "Transmute: Primal Air to Fire",
			["French"] = "Transmutation primordiale : Air en Feu",
			["German"] = "Transmutieren: Urluft zu Urfeuer",
			["Korean"] = "변환식: 바람의 근원을 불로",
			["Mexican"] = "Transmutar: aire primigenio a fuego primigenio",
			["Portuguese"] = "Transmutar: Ar Primevo em Fogo",
			["Russian"] = "Трансмутация изначального воздуха в огонь",
			["Spanish"] = "Transmutar: aire primigenio a fuego primigenio",
			["Taiwanese"] = "轉化:原始空氣轉原始之火",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28567,
		["item_id"] = 21885,
		["items"] = {
			22916,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：源生之土至源生之水",
			["English"] = "Transmute: Primal Earth to Water",
			["French"] = "Transmutation primordiale : Terre en Eau",
			["German"] = "Transmutieren: Urerde zu Urwasser",
			["Korean"] = "변환식: 대지의 근원을 물로",
			["Mexican"] = "Transmutar: tierra primigenia a agua primigenia",
			["Portuguese"] = "Transmutar: Terra Primeva em Água",
			["Russian"] = "Трансмутация изначальной земли в воду",
			["Spanish"] = "Transmutar: tierra primigenia a agua primigenia",
			["Taiwanese"] = "轉化:原始大地轉原始之水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28568,
		["item_id"] = 22452,
		["items"] = {
			22917,
			30443,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：源生火焰至源生之土",
			["English"] = "Transmute: Primal Fire to Earth",
			["French"] = "Transmutation primordiale : Feu en Terre",
			["German"] = "Transmutieren: Urfeuer zu Urerde",
			["Korean"] = "변환식: 불의 근원을 대지로",
			["Mexican"] = "Transmutar: fuego primigenio a tierra primigenia",
			["Portuguese"] = "Transmutar: Fogo Primevo em Terra",
			["Russian"] = "Трансмутация изначального огня в землю",
			["Spanish"] = "Transmutar: fuego primigenio a tierra primigenia",
			["Taiwanese"] = "轉化:原始之火轉原始大地",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28569,
		["item_id"] = 22451,
		["items"] = {
			22918,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：源生之水至源生空气",
			["English"] = "Transmute: Primal Water to Air",
			["French"] = "Transmutation primordiale : Eau en Air",
			["German"] = "Transmutieren: Urwasser zu Urluft",
			["Korean"] = "변환식: 물의 근원을 바람으로",
			["Mexican"] = "Transmutar: agua primigenia a aire primigenio",
			["Portuguese"] = "Transmutar: Água Primeva em Ar",
			["Russian"] = "Трансмутация изначальной воды в воздух",
			["Spanish"] = "Transmutar: agua primigenia a aire primigenio",
			["Taiwanese"] = "轉化:原始之水轉原始空氣",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28570,
		["item_id"] = 22840,
		["items"] = {
			22919,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "特效魔血药剂",
			["English"] = "Elixir of Major Mageblood",
			["French"] = "Elixir magesang majeur",
			["German"] = "Elixier des erheblichen Magierbluts",
			["Korean"] = "최상급 마력의 비약",
			["Mexican"] = "Elixir de sangre de mago sublime",
			["Portuguese"] = "Elixir de Sangue de Mago Elevado",
			["Russian"] = "Мощный эликсир крови волшебника",
			["Spanish"] = "Elixir de sangre de mago sublime",
			["Taiwanese"] = "極效魔血藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28571,
		["item_id"] = 22841,
		["items"] = {
			22920,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "特效火焰防护药水",
			["English"] = "Major Fire Protection Potion",
			["French"] = "Potion de protection contre le Feu majeure",
			["German"] = "Erheblicher Feuerschutztrank",
			["Korean"] = "최상급 화염 보호 물약",
			["Mexican"] = "Poción de Protección contra el Fuego sublime",
			["Portuguese"] = "Poção Elevada de Proteção contra o Fogo",
			["Russian"] = "Сильное зелье защиты от огня",
			["Spanish"] = "Poción de Protección contra el Fuego sublime",
			["Taiwanese"] = "極效火焰防護藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28572,
		["item_id"] = 22842,
		["items"] = {
			22921,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "特效冰霜防护药水",
			["English"] = "Major Frost Protection Potion",
			["French"] = "Potion de protection contre le Givre majeure",
			["German"] = "Erheblicher Frostschutztrank",
			["Korean"] = "최상급 냉기 보호 물약",
			["Mexican"] = "Poción de Protección contra la Escarcha sublime",
			["Portuguese"] = "Poção Elevada de Proteção contra o Gelo",
			["Russian"] = "Сильное зелье защиты от магии льда",
			["Spanish"] = "Poción de Protección contra la Escarcha sublime",
			["Taiwanese"] = "極效冰霜防護藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28573,
		["item_id"] = 22844,
		["items"] = {
			22922,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "特效自然防护药水",
			["English"] = "Major Nature Protection Potion",
			["French"] = "Potion de protection contre la Nature majeure",
			["German"] = "Erheblicher Naturschutztrank",
			["Korean"] = "최상급 자연 보호 물약",
			["Mexican"] = "Poción de Protección contra la Naturaleza sublime",
			["Portuguese"] = "Poção Elevada de Proteção contra a Natureza",
			["Russian"] = "Сильное зелье защиты от сил природы",
			["Spanish"] = "Poción de Protección contra la Naturaleza sublime",
			["Taiwanese"] = "極效自然防護藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28575,
		["item_id"] = 22845,
		["items"] = {
			22923,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "特效奥术防护药水",
			["English"] = "Major Arcane Protection Potion",
			["French"] = "Potion de protection contre les Arcanes majeure",
			["German"] = "Erheblicher Arkanschutztrank",
			["Korean"] = "최상급 비전 보호 물약",
			["Mexican"] = "Poción de Protección contra lo Arcano sublime",
			["Portuguese"] = "Poção Elevada de Proteção contra o Arcano",
			["Russian"] = "Большое зелье защиты от тайной магии",
			["Spanish"] = "Poción de Protección contra lo Arcano sublime",
			["Taiwanese"] = "極效秘法防護藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28576,
		["item_id"] = 22846,
		["items"] = {
			22924,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "特效暗影防护药水",
			["English"] = "Major Shadow Protection Potion",
			["French"] = "Potion de protection contre l'Ombre majeure",
			["German"] = "Erheblicher Schattenschutztrank",
			["Korean"] = "최상급 암흑 보호 물약",
			["Mexican"] = "Poción de Protección contra las Sombras sublime",
			["Portuguese"] = "Poção Elevada de Proteção contra a Sombra",
			["Russian"] = "Сильное зелье защиты от темной магии",
			["Spanish"] = "Poción de Protección contra las Sombras sublime",
			["Taiwanese"] = "極效暗影防護藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28577,
		["item_id"] = 22847,
		["items"] = {
			22925,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "特效神圣防护药水",
			["English"] = "Major Holy Protection Potion",
			["French"] = "Potion de protection contre le Sacré majeure",
			["German"] = "Erheblicher Heiligschutztrank",
			["Korean"] = "최상급 신성 보호 물약",
			["Mexican"] = "Poción de Protección contra lo Sagrado sublime",
			["Portuguese"] = "Poção Elevada de Proteção contra o Sagrado",
			["Russian"] = "Сильное зелье защиты от светлой магии",
			["Spanish"] = "Poción de Protección contra lo Sagrado sublime",
			["Taiwanese"] = "極效神聖防護藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28578,
		["item_id"] = 22848,
		["items"] = {
			22926,
			35294,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "强化药剂",
			["English"] = "Elixir of Empowerment",
			["French"] = "Elixir de renforcement",
			["German"] = "Elixier der Schwächung",
			["Korean"] = "권능의 비약",
			["Mexican"] = "Elixir de potenciación",
			["Portuguese"] = "Elixir de Potencialização",
			["Russian"] = "Эликсир подавления",
			["Spanish"] = "Elixir de empoderación",
			["Taiwanese"] = "活效藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28579,
		["item_id"] = 22849,
		["items"] = {
			22927,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "铁盾药水",
			["English"] = "Ironshield Potion",
			["French"] = "Potion de bouclier de fer",
			["German"] = "Eisenschildtrank",
			["Korean"] = "무쇠방패 물약",
			["Mexican"] = "Poción de escudo de hierro",
			["Portuguese"] = "Poção de Escudo Férreo",
			["Russian"] = "Зелье железного щита",
			["Spanish"] = "Poción de escudo de hierro",
			["Taiwanese"] = "鐵盾藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28580,
		["item_id"] = 21885,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "转化：源生暗影至源生之水",
			["English"] = "Transmute: Primal Shadow to Water",
			["French"] = "Transmutation primordiale : Ombre en Eau",
			["German"] = "Transmutieren: Urschatten zu Urwasser",
			["Korean"] = "변환식: 어둠의 근원을 물로",
			["Mexican"] = "Transmutar: sombra primigenia a agua primigenia",
			["Portuguese"] = "Transmutar: Sombra Primeva em Água",
			["Russian"] = "Трансмутация изначальной тени в воду",
			["Spanish"] = "Transmutar: sombra primigenia a agua primigenia",
			["Taiwanese"] = "轉化:原始暗影轉原始之水",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28581,
		["item_id"] = 22456,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "转化：源生之水至源生暗影",
			["English"] = "Transmute: Primal Water to Shadow",
			["French"] = "Transmutation primordiale : Eau en Ombre",
			["German"] = "Transmutieren: Urwasser zu Urschatten",
			["Korean"] = "변환식: 물의 근원을 어둠으로",
			["Mexican"] = "Transmutar: agua primigenia a sombra primigenia",
			["Portuguese"] = "Transmutar: Água Primeva em Sombra",
			["Russian"] = "Трансмутация изначальной воды в тьму",
			["Spanish"] = "Transmutar: agua primigenia a sombra primigenia",
			["Taiwanese"] = "轉化:原始之水轉原始暗影",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28582,
		["item_id"] = 21884,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "转化：源生法力至源生火焰",
			["English"] = "Transmute: Primal Mana to Fire",
			["French"] = "Transmutation primordiale : Mana en Feu",
			["German"] = "Transmutieren: Urmana zu Urfeuer",
			["Korean"] = "변환식: 마나의 근원을 불로",
			["Mexican"] = "Transmutar: maná primigenio a fuego primigenio",
			["Portuguese"] = "Transmutar: Mana Primevo em Fogo",
			["Russian"] = "Трансмутация изначальной маны в огонь",
			["Spanish"] = "Transmutar: maná primigenio a fuego primigenio",
			["Taiwanese"] = "轉化:原始法力轉原始之火",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28583,
		["item_id"] = 22457,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "转化：源生火焰至源生法力",
			["English"] = "Transmute: Primal Fire to Mana",
			["French"] = "Transmutation primordiale : Feu en Mana",
			["German"] = "Transmutieren: Urfeuer zu Urmana",
			["Korean"] = "변환식: 불의 근원을 마나로",
			["Mexican"] = "Transmutar: fuego primigenio a maná primigenio",
			["Portuguese"] = "Transmutar: Fogo Primevo em Mana",
			["Russian"] = "Трансмутация изначального огня в ману",
			["Spanish"] = "Transmutar: fuego primigenio a maná primigenio",
			["Taiwanese"] = "轉化:原始之火轉原始法力",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28584,
		["item_id"] = 22452,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "转化：源生生命至源生之土",
			["English"] = "Transmute: Primal Life to Earth",
			["French"] = "Transmutation primordiale : Vie en Terre",
			["German"] = "Transmutieren: Urleben zu Urerde",
			["Korean"] = "변환식: 생명의 근원을 대지로",
			["Mexican"] = "Transmutar: vida primigenia a tierra primigenia",
			["Portuguese"] = "Transmutar: Vida Primeva em Terra",
			["Russian"] = "Трансмутация изначальной жизни в землю",
			["Spanish"] = "Transmutar: vida primigenia a tierra primigenia",
			["Taiwanese"] = "轉化:原始生命轉原始大地",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28585,
		["item_id"] = 21886,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "转化：源生之土至源生生命",
			["English"] = "Transmute: Primal Earth to Life",
			["French"] = "Transmutation primordiale : Terre en Vie",
			["German"] = "Transmutieren: Urerde zu Urleben",
			["Korean"] = "변환식: 대지의 근원을 생명으로",
			["Mexican"] = "Transmutar: tierra primigenia a vida primigenia",
			["Portuguese"] = "Transmutar: Terra Primeva em Vida",
			["Russian"] = "Трансмутация изначальной земли в жизнь",
			["Spanish"] = "Transmutar: tierra primigenia a vida primigenia",
			["Taiwanese"] = "轉化:原始大地轉原始生命",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28586,
		["item_id"] = 22850,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "超级活力药水",
			["English"] = "Super Rejuvenation Potion",
			["French"] = "Potion de super-régénération",
			["German"] = "Erstklassiger Verjüngungstrank",
			["Korean"] = "특급 회복 물약",
			["Mexican"] = "Superpoción de rejuvenecimiento",
			["Portuguese"] = "Super Poção de Rejuvenescimento",
			["Russian"] = "Мощное зелье омоложения",
			["Spanish"] = "Superpoción de rejuvenecimiento",
			["Taiwanese"] = "超強效活力藥水",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28587,
		["item_id"] = 22851,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "强固合剂",
			["English"] = "Flask of Fortification",
			["French"] = "Flacon de fortifiant",
			["German"] = "Fläschchen der Stärkung",
			["Korean"] = "증강의 영약",
			["Mexican"] = "Frasco de fortificación",
			["Portuguese"] = "Frasco de Fortificação",
			["Russian"] = "Настой укрепления",
			["Spanish"] = "Frasco de fortificación",
			["Taiwanese"] = "防禦精煉藥劑",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28588,
		["item_id"] = 22853,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "强效回复合剂",
			["English"] = "Flask of Mighty Restoration",
			["French"] = "Flacon de puissante restauration",
			["German"] = "Fläschchen der mächtigen Wiederherstellung",
			["Korean"] = "강력한 마나 회복의 영약",
			["Mexican"] = "Frasco de restauración poderosa",
			["Portuguese"] = "Frasco de Restauração Potente",
			["Russian"] = "Настой могучего восстановления",
			["Spanish"] = "Frasco de restauración poderosa",
			["Taiwanese"] = "法力恢復精煉藥劑",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28589,
		["item_id"] = 22854,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "无情突袭合剂",
			["English"] = "Flask of Relentless Assault",
			["French"] = "Flacon d'attaque implacable",
			["German"] = "Fläschchen des unerbittlichen Angriffs",
			["Korean"] = "가혹한 공격의 영약",
			["Mexican"] = "Frasco de asalto incansable",
			["Portuguese"] = "Frasco do Ataque Implacável",
			["Russian"] = "Настой безжалостного убийцы",
			["Spanish"] = "Frasco de asalto incansable",
			["Taiwanese"] = "強襲精煉藥劑",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28590,
		["item_id"] = 22861,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "盲目光芒合剂",
			["English"] = "Flask of Blinding Light",
			["French"] = "Flacon de lumière aveuglante",
			["German"] = "Fläschchen des blendenden Lichts",
			["Korean"] = "눈부신 빛의 영약",
			["Mexican"] = "Frasco de Luz cegadora",
			["Portuguese"] = "Frasco de Luz Cegante",
			["Russian"] = "Настой Слепящего света",
			["Spanish"] = "Frasco de Luz cegadora",
			["Taiwanese"] = "盲目之光精煉藥劑",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 28591,
		["item_id"] = 22866,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "纯粹死亡合剂",
			["English"] = "Flask of Pure Death",
			["French"] = "Flacon de pure mort",
			["German"] = "Fläschchen des reinen Todes",
			["Korean"] = "순수한 죽음의 영약",
			["Mexican"] = "Frasco de muerte pura",
			["Portuguese"] = "Frasco de Pura Morte",
			["Russian"] = "Настой чистой смерти",
			["Spanish"] = "Frasco de muerte pura",
			["Taiwanese"] = "純淨死亡精煉藥劑",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 29688,
		["item_id"] = 23571,
		["items"] = {
			23574,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：源生之能",
			["English"] = "Transmute: Primal Might",
			["French"] = "Transmutation primordiale : Pouvoir",
			["German"] = "Transmutieren: Urmacht",
			["Korean"] = "변환식: 힘의 근원",
			["Mexican"] = "Transmutar: poderío primigenio",
			["Portuguese"] = "Transmutar: Poder Primevo",
			["Russian"] = "Трансмутация изначальной мощи",
			["Spanish"] = "Transmutar: poderío primigenio",
			["Taiwanese"] = "轉化:原始力量",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32765,
		["item_id"] = 25867,
		["items"] = {
			25869,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：大地风暴钻石",
			["English"] = "Transmute: Earthstorm Diamond",
			["French"] = "Transmutation : Diamant tonneterre",
			["German"] = "Transmutieren: Erdsturmdiamant",
			["Korean"] = "변환식: 대지폭풍 다이아몬드",
			["Mexican"] = "Transmutar: diamante de tormenta de tierra",
			["Portuguese"] = "Transmutar: Diamante Tempesterra",
			["Russian"] = "Трансмутация: алмаз земной бури",
			["Spanish"] = "Transmutar: diamante de tormenta de tierra",
			["Taiwanese"] = "轉化:大地風暴鑽石",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32766,
		["item_id"] = 25868,
		["items"] = {
			25870,
			29232,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "转化：天火钻石",
			["English"] = "Transmute: Skyfire Diamond",
			["French"] = "Transmutation : Diamant brûleciel",
			["German"] = "Transmutieren: Himmelsfeuerdiamant",
			["Korean"] = "변환식: 하늘불꽃 다이아몬드",
			["Mexican"] = "Transmutar: diamante de fuego celeste",
			["Portuguese"] = "Transmutar: Diamante Fogocéu",
			["Russian"] = "Трансмутация: алмаз небесного огня",
			["Spanish"] = "Transmutar: diamante de fuego celeste",
			["Taiwanese"] = "轉化:天火鑽石",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33732,
		["item_id"] = 28100,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "不稳定的治疗药水",
			["English"] = "Volatile Healing Potion",
			["French"] = "Potion de soins volatile",
			["German"] = "Flüchtiger Heiltrank",
			["Korean"] = "신속 치유 물약",
			["Mexican"] = "Poción de sanación volátil",
			["Portuguese"] = "Poção Volátil de Cura",
			["Russian"] = "Флакон с летучим лечебным зельем",
			["Spanish"] = "Poción de sanación volátil",
			["Taiwanese"] = "強烈治療藥水",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33733,
		["item_id"] = 28101,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "不稳定的法力药水",
			["English"] = "Unstable Mana Potion",
			["French"] = "Potion de mana instable",
			["German"] = "Instabiler Manatrank",
			["Korean"] = "불안정한 마나 물약",
			["Mexican"] = "Poción de maná inestable",
			["Portuguese"] = "Poção Instável de Mana",
			["Russian"] = "Флакон с нестойким зельем маны",
			["Spanish"] = "Poción de maná inestable",
			["Taiwanese"] = "不穩定法力藥水",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33738,
		["item_id"] = 28102,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "强攻药剂",
			["English"] = "Onslaught Elixir",
			["French"] = "Elixir d'assaut",
			["German"] = "Elixier des Ansturms",
			["Korean"] = "맹공의 비약",
			["Mexican"] = "Elixir de acometida",
			["Portuguese"] = "Elixir da Ofensiva",
			["Russian"] = "Эликсир натиска",
			["Spanish"] = "Elixir de acometida",
			["Taiwanese"] = "猛擊藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33740,
		["item_id"] = 28103,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "法能药剂",
			["English"] = "Adept's Elixir",
			["French"] = "Elixir d'adepte",
			["German"] = "Elixier des Adepten",
			["Korean"] = "숙련의 비약",
			["Mexican"] = "Elixir de adepto",
			["Portuguese"] = "Elixir do Adepto",
			["Russian"] = "Эликсир адепта",
			["Spanish"] = "Elixir de adepto",
			["Taiwanese"] = "內行藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33741,
		["item_id"] = 28104,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "掌控药剂",
			["English"] = "Elixir of Mastery",
			["French"] = "Elixir de maîtrise",
			["German"] = "Elixier des Meisters",
			["Korean"] = "정통의 비약",
			["Mexican"] = "Elixir de maestría",
			["Portuguese"] = "Elixir de Maestria",
			["Russian"] = "Эликсир власти",
			["Spanish"] = "Elixir de maestría",
			["Taiwanese"] = "精通藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 30000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 38070,
		["item_id"] = 31080,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "水银石",
			["English"] = "Mercurial Stone",
			["French"] = "Pierre mercurienne",
			["German"] = "Quecksilberstein",
			["Korean"] = "수은석",
			["Mexican"] = "Piedra mercúrica",
			["Portuguese"] = "Pedra Mercurial",
			["Russian"] = "Переменчивый камень",
			["Spanish"] = "Piedra mercúrica",
			["Taiwanese"] = "水銀石",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 38960,
		["item_id"] = 31679,
		["items"] = {
			31680,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "魔能力量药水",
			["English"] = "Fel Strength Elixir",
			["French"] = "Elixir de force gangrené",
			["German"] = "Elixier der Teufelsstärke",
			["Korean"] = "타락한 힘의 비약",
			["Mexican"] = "Elixir de fuerza vil",
			["Portuguese"] = "Elixir de Força Vil",
			["Russian"] = "Оскверненный эликсир силы",
			["Spanish"] = "Elixir de fuerza vil",
			["Taiwanese"] = "魔化力量藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38961,
		["item_id"] = 31677,
		["items"] = {
			31682,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔能法力药水",
			["English"] = "Fel Mana Potion",
			["French"] = "Potion de mana gangrenée",
			["German"] = "Teufelsmanatrank",
			["Korean"] = "타락의 마나 물약",
			["Mexican"] = "Poción de maná vil",
			["Portuguese"] = "Poção Vil de Mana",
			["Russian"] = "Оскверненное зелье маны",
			["Spanish"] = "Poción de maná vil",
			["Taiwanese"] = "魔化法力藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38962,
		["item_id"] = 31676,
		["items"] = {
			31681,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "魔能回复药水",
			["English"] = "Fel Regeneration Potion",
			["French"] = "Potion de régénération gangrenée",
			["German"] = "Teufelsregenerationstrank",
			["Korean"] = "타락의 회복 물약",
			["Mexican"] = "Poción de regeneración vil",
			["Portuguese"] = "Poção Vil de Regeneração",
			["Russian"] = "Оскверненное зелье регенерации",
			["Spanish"] = "Poción de regeneración vil",
			["Taiwanese"] = "魔化再生藥水",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 39636,
		["item_id"] = 32062,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "特效坚韧药剂",
			["English"] = "Elixir of Major Fortitude",
			["French"] = "Elixir de robustesse majeure",
			["German"] = "Elixier der erheblichen Seelenstärke",
			["Korean"] = "최상급 인내의 비약",
			["Mexican"] = "Elixir de entereza sublime",
			["Portuguese"] = "Elixir de Fortitude Elevada",
			["Russian"] = "Большой эликсир стойкости",
			["Spanish"] = "Elixir de entereza sublime",
			["Taiwanese"] = "極效堅韌藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 39637,
		["item_id"] = 32063,
		["items"] = {
			32070,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "土灵药剂",
			["English"] = "Earthen Elixir",
			["French"] = "Elixir terrestre",
			["German"] = "Erdelixier",
			["Korean"] = "대지의 비약",
			["Mexican"] = "Elixir terráneo",
			["Portuguese"] = "Elixir Terreno",
			["Russian"] = "Эликсир земли",
			["Spanish"] = "Elixir terráneo",
			["Taiwanese"] = "地化藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 39638,
		["item_id"] = 32067,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "德莱尼智慧药剂",
			["English"] = "Elixir of Draenic Wisdom",
			["French"] = "Elixir de sagesse draenique",
			["German"] = "Elixier der draenischen Weisheit",
			["Korean"] = "드레나이 지혜의 비약",
			["Mexican"] = "Elixir de sabiduría draénica",
			["Portuguese"] = "Elixir de Sabedoria Draeneica",
			["Russian"] = "Эликсир дренейской мудрости",
			["Spanish"] = "Elixir de sabiduría draénica",
			["Taiwanese"] = "德萊尼智慧藥劑",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 30000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 39639,
		["item_id"] = 32068,
		["items"] = {
			32071,
		},
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "铁皮药剂",
			["English"] = "Elixir of Ironskin",
			["French"] = "Elixir peau-de-fer",
			["German"] = "Elixier der Eisenhaut",
			["Korean"] = "무쇠가죽 비약",
			["Mexican"] = "Elixir de piel de hierro",
			["Portuguese"] = "Elixir de Pele de Ferro",
			["Russian"] = "Эликсир железной шкуры",
			["Spanish"] = "Elixir de piel de hierro",
			["Taiwanese"] = "鐵膚藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 41458,
		["item_id"] = 32839,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "特效奥术防护药锅",
			["English"] = "Cauldron of Major Arcane Protection",
			["French"] = "Chaudron de protection contre les Arcanes majeure",
			["German"] = "Kessel des erheblichen Arkanschutzes",
			["Korean"] = "최상급 비전 보호의 가마솥",
			["Mexican"] = "Caldera de Protección contra lo Arcano sublime",
			["Portuguese"] = "Caldeirão de Proteção Elevada Contra o Arcano",
			["Russian"] = "Котел великой защиты от тайной магии",
			["Spanish"] = "Caldera de Protección contra lo Arcano sublime",
			["Taiwanese"] = "極效秘法防護大鍋",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 41500,
		["item_id"] = 32849,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "特效火焰防护药锅",
			["English"] = "Cauldron of Major Fire Protection",
			["French"] = "Chaudron de protection contre le Feu majeure",
			["German"] = "Kessel des erheblichen Feuerschutzes",
			["Korean"] = "최상급 화염 보호의 가마솥",
			["Mexican"] = "Caldera de Protección contra el Fuego sublime",
			["Portuguese"] = "Caldeirão de Proteção Elevada Contra o Fogo",
			["Russian"] = "Котел сильной защиты от огня",
			["Spanish"] = "Caldera de Protección contra el Fuego sublime",
			["Taiwanese"] = "極效火焰防護大鍋",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 41501,
		["item_id"] = 32850,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "特效冰霜防护药锅",
			["English"] = "Cauldron of Major Frost Protection",
			["French"] = "Chaudron de protection contre le Givre majeure",
			["German"] = "Kessel des erheblichen Frostschutzes",
			["Korean"] = "최상급 냉기 보호의 가마솥",
			["Mexican"] = "Caldera de Protección contra la Escarcha sublime",
			["Portuguese"] = "Caldeirão de Proteção Elevada Contra o Gelo",
			["Russian"] = "Котел сильной защиты от магии льда",
			["Spanish"] = "Caldera de Protección contra la Escarcha sublime",
			["Taiwanese"] = "極效冰霜防護大鍋",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 41502,
		["item_id"] = 32851,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "特效自然防护药锅",
			["English"] = "Cauldron of Major Nature Protection",
			["French"] = "Chaudron de protection contre la Nature majeure",
			["German"] = "Kessel des erheblichen Naturschutzes",
			["Korean"] = "최상급 자연 보호의 가마솥",
			["Mexican"] = "Caldera de Protección contra la Naturaleza sublime",
			["Portuguese"] = "Caldeirão de Proteção Elevada Contra a Natureza",
			["Russian"] = "Котел сильной защиты от сил природы",
			["Spanish"] = "Caldera de Protección contra la Naturaleza sublime",
			["Taiwanese"] = "極效自然防護大鍋",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 41503,
		["item_id"] = 32852,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "特效暗影防护药锅",
			["English"] = "Cauldron of Major Shadow Protection",
			["French"] = "Chaudron de protection contre l'Ombre majeure",
			["German"] = "Kessel des erheblichen Schattenschutzes",
			["Korean"] = "최상급 암흑 보호의 가마솥",
			["Mexican"] = "Caldera de Protección contra las Sombras sublime",
			["Portuguese"] = "Caldeirão de Proteção Elevada Contra a Sombra",
			["Russian"] = "Котел сильной защиты от темной магии",
			["Spanish"] = "Caldera de Protección contra las Sombras sublime",
			["Taiwanese"] = "極效暗影防護大鍋",
		},
		["phase"] = 1,
		["special_action"] = "learned through discovery",
	},
	{
		["expansion"] = 2,
		["id"] = 42736,
		["item_id"] = 33208,
		["items"] = {
			33209,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "多彩奇迹合剂",
			["English"] = "Flask of Chromatic Wonder",
			["French"] = "Flacon de merveille chromatique",
			["German"] = "Fläschchen des chromatischen Wunders",
			["Korean"] = "오색 신비의 영약",
			["Mexican"] = "Frasco de Maravilla cromática",
			["Portuguese"] = "Frasco de Maravilha Cromática",
			["Russian"] = "Настой всецветного чуда",
			["Spanish"] = "Frasco de Maravilla cromática",
			["Taiwanese"] = "炫彩驚奇精煉藥劑",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 45061,
		["item_id"] = 34440,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "疯狂炼金师药水",
			["English"] = "Mad Alchemist's Potion",
			["French"] = "Potion de l'alchimiste fou",
			["German"] = "Trank des verrückten Alchimisten",
			["Korean"] = "미치광이 연금술사의 물약",
			["Mexican"] = "Poción de alquimista loco",
			["Portuguese"] = "Poção do Alquimista Louco",
			["Russian"] = "Зелье безумного алхимика",
			["Spanish"] = "Poción de alquimista loco",
			["Taiwanese"] = "瘋狂鍊金師藥水",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 35000,
			["sources"] = {
				18802,
				16588,
				19052,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 47046,
		["item_id"] = 35748,
		["items"] = {
			35752,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "守护者的炼金石",
			["English"] = "Guardian's Alchemist Stone",
			["French"] = "Pierre d'alchimiste de gardien",
			["German"] = "Alchimistenstein des Wächters",
			["Korean"] = "수호자의 연금술사 돌",
			["Mexican"] = "Piedra de alquimista de guardián",
			["Portuguese"] = "Pedra do Alquimista do Guardião",
			["Russian"] = "Алхимический камень стража",
			["Spanish"] = "Piedra de alquimista de guardián",
			["Taiwanese"] = "守護者鍊金石",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 47048,
		["item_id"] = 35749,
		["items"] = {
			35753,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "巫师的炼金石",
			["English"] = "Sorcerer's Alchemist Stone",
			["French"] = "Pierre d'alchimiste d'ensorceleur",
			["German"] = "Alchimistenstein des Zauberhexers",
			["Korean"] = "마술사의 연금술사 돌",
			["Mexican"] = "Piedra de alquimista de hechicero",
			["Portuguese"] = "Pedra do Alquimista do Feiticeiro",
			["Russian"] = "Алхимический камень чародея",
			["Spanish"] = "Piedra de alquimista de hechicero",
			["Taiwanese"] = "巫士鍊金石",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 47049,
		["item_id"] = 35750,
		["items"] = {
			35754,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "救赎者的炼金石",
			["English"] = "Redeemer's Alchemist Stone",
			["French"] = "Pierre d'alchimiste de rédempteur",
			["German"] = "Alchimistenstein des Erlösers",
			["Korean"] = "구원자의 연금술사 돌",
			["Mexican"] = "Piedra de alquimista de redentor",
			["Portuguese"] = "Pedra do Alquimista do Redentor",
			["Russian"] = "Алхимический камень искупителя",
			["Spanish"] = "Piedra de alquimista de redentor",
			["Taiwanese"] = "救贖者鍊金石",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 47050,
		["item_id"] = 35751,
		["items"] = {
			35755,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "刺客的炼金石",
			["English"] = "Assassin's Alchemist Stone",
			["French"] = "Pierre d'alchimiste d'assassin",
			["German"] = "Alchimistenstein des Assassinen",
			["Korean"] = "암살자의 연금술사 돌",
			["Mexican"] = "Piedra de alquimista de asesino",
			["Portuguese"] = "Pedra do Alquimista do Assassino",
			["Russian"] = "Алхимический камень убийцы",
			["Spanish"] = "Piedra de alquimista de asesino",
			["Taiwanese"] = "刺客鍊金石",
		},
		["phase"] = 5,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Alchemy"], skill)
end
