-------------------------------------------------------
-- All items (Engineering) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Engineering"] then RR_DATA["items"]["Engineering"] = {} end
local tbc_items = 
{
	{
		["expansion"] = 2,
		["id"] = 23799,
		["name"] = {
			["Chinese"] = "结构图：精金步枪",
			["English"] = "Schematic: Adamantite Rifle",
			["French"] = "Schéma : Carabine en adamantite",
			["German"] = "Bauplan: Adamantitgewehr",
			["Korean"] = "설계도: 아다만타이트 소총",
			["Mexican"] = "Esquema: rifle de adamantita",
			["Portuguese"] = "Diagrama: Rifle de Adamantita",
			["Russian"] = "Схема: адамантитовая винтовка",
			["Spanish"] = "Esquema: rifle de adamantita",
			["Taiwanese"] = "結構圖:堅鋼步槍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				16657,
				16782,
				19661,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				19960,
			},
		},
		["expansion"] = 2,
		["id"] = 23800,
		["name"] = {
			["Chinese"] = "结构图：魔钢火枪",
			["English"] = "Schematic: Felsteel Boomstick",
			["French"] = "Schéma : Espingole en gangracier",
			["German"] = "Bauplan: Teufelsstahlschießeisen",
			["Korean"] = "설계도: 지옥강철 붐스틱",
			["Mexican"] = "Esquema: bocarda de acero vil",
			["Portuguese"] = "Diagrama: Cano de Atirar de Açovil",
			["Russian"] = "Чертеж: огнестрел из оскверненной стали",
			["Spanish"] = "Esquema: bocarda de acero vil",
			["Taiwanese"] = "結構圖:魔鋼火槍",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				17940,
				18314,
			},
		},
		["expansion"] = 2,
		["id"] = 23802,
		["name"] = {
			["Chinese"] = "结构图：精制氪金步枪",
			["English"] = "Schematic: Ornate Khorium Rifle",
			["French"] = "Schéma : Carabine ornée en khorium",
			["German"] = "Bauplan: Verschnörkeltes Khoriumgewehr",
			["Korean"] = "설계도: 화려한 코륨 소총",
			["Mexican"] = "Esquema: rifle de korio ornamentado",
			["Portuguese"] = "Diagrama: Rifle de Kório Ornado",
			["Russian"] = "Схема: узорчатая кориевая винтовка",
			["Spanish"] = "Esquema: rifle de korio ornamentado",
			["Taiwanese"] = "結構圖:華麗克銀步槍",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 23803,
		["name"] = {
			["Chinese"] = "结构图：旋轮护目镜",
			["English"] = "Schematic: Cogspinner Goggles",
			["French"] = "Schéma : Lunettes de Tournepignon",
			["German"] = "Bauplan: Zahnradbrille",
			["Korean"] = "설계도: 톱니바퀴 고글",
			["Mexican"] = "Esquema: gafas Volopiñón",
			["Portuguese"] = "Diagrama: Óculos Rodagiros",
			["Russian"] = "Схема: очки прядильщика",
			["Spanish"] = "Esquema: gafas Volopiñón",
			["Taiwanese"] = "結構圖:考格斯賓護目鏡",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				18775,
				19836,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				18314,
				18327,
				18634,
				18331,
			},
		},
		["expansion"] = 2,
		["id"] = 23804,
		["name"] = {
			["Chinese"] = "结构图：能量放大护目镜",
			["English"] = "Schematic: Power Amplification Goggles",
			["French"] = "Schéma : Lunettes d'amplification de puissance",
			["German"] = "Bauplan: Energieverstärkungsbrille",
			["Korean"] = "설계도: 마력 증폭 고글",
			["Mexican"] = "Esquema: gafas de amplificación de poder",
			["Portuguese"] = "Diagrama: Lentes de Amplificação do Poder",
			["Russian"] = "Схема: умножающие силу очки",
			["Spanish"] = "Esquema: gafas de amplificación de poder",
			["Taiwanese"] = "結構圖:能量增強護目鏡",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 23805,
		["name"] = {
			["Chinese"] = "结构图：超光谱侦测护目镜",
			["English"] = "Schematic: Ultra-Spectropic Detection Goggles",
			["French"] = "Schéma : Lunettes de détection ultra-spectroscopique",
			["German"] = "Bauplan: Ultraspektropische Enthüllungsbrille",
			["Korean"] = "설계도: 초분광 감지 고글",
			["Mexican"] = "Esquema: gafas de detección ultraespectrópicas",
			["Portuguese"] = "Diagrama: Óculos de Detecção Ultra-espectrópicos",
			["Russian"] = "Схема: ультраскопические очки обнаружения",
			["Spanish"] = "Esquema: gafas de detección ultraespectrópicas",
			["Taiwanese"] = "結構圖:超光學偵測護目鏡",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				18775,
				19383,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				19755,
			},
		},
		["expansion"] = 2,
		["id"] = 23806,
		["name"] = {
			["Chinese"] = "结构图：超视距护目镜",
			["English"] = "Schematic: Hyper-Vision Goggles",
			["French"] = "Schéma : Lunettes d'hyper-vision",
			["German"] = "Bauplan: Extremsichtbrille",
			["Korean"] = "설계도: 고감도 고글",
			["Mexican"] = "Esquema: gafas de hipervisión",
			["Portuguese"] = "Diagrama: Óculos de Hipervisão",
			["Russian"] = "Схема: очки гиперзрения",
			["Spanish"] = "Esquema: gafas de hipervisión",
			["Taiwanese"] = "結構圖:超視覺護目鏡",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 23807,
		["name"] = {
			["Chinese"] = "结构图：精金瞄准镜",
			["English"] = "Schematic: Adamantite Scope",
			["French"] = "Schéma : Lunette en adamantite",
			["German"] = "Bauplan: Adamantitzielfernrohr",
			["Korean"] = "설계도: 아다만타이트 조준경",
			["Mexican"] = "Esquema: mira de adamantita",
			["Portuguese"] = "Diagrama: Mira de Adamantita",
			["Russian"] = "Схема: адамантитовый прицел",
			["Spanish"] = "Esquema: mira de adamantita",
			["Taiwanese"] = "結構圖:堅鋼瞄準鏡",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19351,
				19836,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				20207,
			},
		},
		["expansion"] = 2,
		["id"] = 23808,
		["name"] = {
			["Chinese"] = "结构图：氪金瞄准镜",
			["English"] = "Schematic: Khorium Scope",
			["French"] = "Schéma : Lunette en khorium",
			["German"] = "Bauplan: Khoriumzielfernrohr",
			["Korean"] = "설계도: 코륨 조준경",
			["Mexican"] = "Esquema: mira de korio",
			["Portuguese"] = "Diagrama: Mira de Kório",
			["Russian"] = "Схема: кориевый прицел",
			["Spanish"] = "Esquema: mira de korio",
			["Taiwanese"] = "結構圖:克銀瞄準鏡",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				16152,
			},
		},
		["expansion"] = 2,
		["id"] = 23809,
		["name"] = {
			["Chinese"] = "结构图：稳定恒金瞄准镜",
			["English"] = "Schematic: Stabilized Eternium Scope",
			["French"] = "Schéma : Lunette en éternium stabilisé",
			["German"] = "Bauplan: Geeichtes Eterniumzielfernrohr",
			["Korean"] = "설계도: 안정된 이터늄 조준경",
			["Mexican"] = "Esquema: mira de eternio estabilizada",
			["Portuguese"] = "Diagrama: Mira Estável de Etérnio",
			["Russian"] = "Схема: стабилизированный этерниевый прицел",
			["Spanish"] = "Esquema: mira de eternium estabilizada",
			["Taiwanese"] = "結構圖:穩固恆金瞄準鏡",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18312,
				18326,
				18315,
			},
		},
		["expansion"] = 2,
		["id"] = 23810,
		["name"] = {
			["Chinese"] = "结构图：打架机器人",
			["English"] = "Schematic: Crashin' Thrashin' Robot",
			["French"] = "Schéma : Robot Cogn'Baff",
			["German"] = "Bauplan: Krachbummroboter",
			["Korean"] = "설계도: 우당탕 쿠당탕 전투로봇",
			["Mexican"] = "Esquema: robot triturador",
			["Portuguese"] = "Diagrama: Robô Bate-bate",
			["Russian"] = "Схема: робот \"Бей-Молоти\"",
			["Spanish"] = "Esquema: robot triturador",
			["Taiwanese"] = "結構圖:暴力粉碎機器人",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 23811,
		["name"] = {
			["Chinese"] = "结构图：白色烟幕弹",
			["English"] = "Schematic: White Smoke Flare",
			["French"] = "Schéma : Fumigène blanc",
			["German"] = "Bauplan: Weißes Rauchsignal",
			["Korean"] = "설계도: 백색 조명탄",
			["Mexican"] = "Esquema: bengala de humo blanco",
			["Portuguese"] = "Diagrama: Sinalizador de Fumaça Branca",
			["Russian"] = "Схема: белая дымовая сигнальная ракета",
			["Spanish"] = "Esquema: bengala de humo blanco",
			["Taiwanese"] = "結構圖:白色煙霧照明彈",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				16657,
				16782,
				18484,
				19383,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23814,
		["name"] = {
			["Chinese"] = "结构图：绿色烟幕弹",
			["English"] = "Schematic: Green Smoke Flare",
			["French"] = "Schéma : Fumigène vert",
			["German"] = "Bauplan: Grünes Rauchsignal",
			["Korean"] = "설계도: 녹색 조명탄",
			["Mexican"] = "Esquema: bengala de humo verde",
			["Portuguese"] = "Diagrama: Sinalizador de Fumaça Verde",
			["Russian"] = "Схема: зеленая дымовая сигнальная ракета",
			["Spanish"] = "Esquema: bengala de humo verde",
			["Taiwanese"] = "結構圖:綠色煙霧照明彈",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23815,
		["name"] = {
			["Chinese"] = "结构图：精金制弹机",
			["English"] = "Schematic: Adamantite Shell Machine",
			["French"] = "Schéma : Presse à obus en adamantite",
			["German"] = "Bauplan: Maschine für Adamantitpatronen",
			["Korean"] = "설계도: 아다만타이트 탄환 제조기",
			["Mexican"] = "Esquema: máquina de balas de adamantita",
			["Portuguese"] = "Diagrama: Máquina de Cartuchos de Adamantita",
			["Russian"] = "Чертеж: станок для адамантитовых патронов",
			["Spanish"] = "Esquema: máquina de balas de adamantita",
			["Taiwanese"] = "結構圖:堅鋼彈藥製造器",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				18484,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23816,
		["name"] = {
			["Chinese"] = "结构图：魔铁工具箱",
			["English"] = "Schematic: Fel Iron Toolbox",
			["French"] = "Schéma : Boîte à outils en gangrefer",
			["German"] = "Bauplan: Werkzeugkasten aus Teufelseisen",
			["Korean"] = "설계도: 지옥무쇠 연장통",
			["Mexican"] = "Esquema: caja de herramientas de hierro vil",
			["Portuguese"] = "Diagrama: Caixa de Ferramentas de Ferrovil",
			["Russian"] = "Схема: ящик для инструментов из оскверненного железа",
			["Spanish"] = "Esquema: caja de herramientas de hierro vil",
			["Taiwanese"] = "結構圖:魔鐵工具箱",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16657,
				16782,
				18484,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23874,
		["name"] = {
			["Chinese"] = "结构图：元素爆盐炸弹",
			["English"] = "Schematic: Elemental Seaforium Charge",
			["French"] = "Schéma : Charge d'hydroglycérine élémentaire",
			["German"] = "Bauplan: Elementare Zephyriumladung",
			["Korean"] = "설계도: 원소 시포리움 폭약",
			["Mexican"] = "Esquema: carga de seforio elemental",
			["Portuguese"] = "Diagrama: Carga Elemental de Cequatrum",
			["Russian"] = "Чертеж: стихийный сефориевый заряд",
			["Spanish"] = "Esquema: carga de seforio elemental",
			["Taiwanese"] = "結構圖:元素爆鹽炸藥",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23883,
		["name"] = {
			["Chinese"] = "结构图：治疗药水注射器",
			["English"] = "Schematic: Healing Potion Injector",
			["French"] = "Schéma : Injecteur de potion de soins",
			["German"] = "Bauplan: Heiltrankeinspritzung",
			["Korean"] = "설계도: 치유 물약 주사기",
			["Mexican"] = "Esquema: inyector de poción de sanación",
			["Portuguese"] = "Diagrama: Injetor de Poção de Cura",
			["Russian"] = "Схема: набор для лечебных инъекций",
			["Spanish"] = "Esquema: inyector de poción de sanación",
			["Taiwanese"] = "結構圖:治療藥水注射器",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23884,
		["name"] = {
			["Chinese"] = "结构图：法力药水注射器",
			["English"] = "Schematic: Mana Potion Injector",
			["French"] = "Schéma : Injecteur de potion de mana",
			["German"] = "Bauplan: Manatrankeinspritzung",
			["Korean"] = "설계도: 마나 물약 주사기",
			["Mexican"] = "Esquema: inyector de poción de maná",
			["Portuguese"] = "Diagrama: Injetor de Poção de Mana",
			["Russian"] = "Схема: набор для инъекций маны",
			["Spanish"] = "Esquema: inyector de poción de maná",
			["Taiwanese"] = "結構圖:法力藥水注射器",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				17796,
			},
		},
		["expansion"] = 2,
		["id"] = 23887,
		["name"] = {
			["Chinese"] = "结构图：超级火箭靴",
			["English"] = "Schematic: Rocket Boots Xtreme",
			["French"] = "Schéma : Bottes-fusées extrêmes",
			["German"] = "Bauplan: Raketenstiefel Xtrem",
			["Korean"] = "설계도: 극한의 로켓 장화",
			["Mexican"] = "Esquema: botas cohete Xtremo",
			["Portuguese"] = "Diagrama: Botas-foguete Xtremas",
			["Russian"] = "Схема: экстремальные реактивные сапоги",
			["Spanish"] = "Esquema: botas cohete Xtremo",
			["Taiwanese"] = "結構圖:火箭靴極限版",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 23888,
		["name"] = {
			["Chinese"] = "结构图：气阀微粒提取器",
			["English"] = "Schematic: Zapthrottle Mote Extractor",
			["French"] = "Schéma : Extracteur de granules Zappeur-Gazier",
			["German"] = "Bauplan: Schockdrosselnder Partikelextraktor",
			["Korean"] = "설계도: 기압조절 가스 추출기",
			["Mexican"] = "Esquema: extractor de motas de zapacelerador",
			["Portuguese"] = "Diagrama: Extrator de Partículas Zapeacelera",
			["Russian"] = "Схема: удаленный конденсатор выхлопов",
			["Spanish"] = "Esquema: extractor de motas de zapacelerador",
			["Taiwanese"] = "結構圖:快速節流微粒吸取器",
		},
		["phase"] = 1,
		["quality"] = "common",
		["quests"] = {
			9635,
		}
	},
	{
		["drops"] = {
			["sources"] = {
				18319,
				18328,
			},
		},
		["expansion"] = 2,
		["id"] = 25887,
		["name"] = {
			["Chinese"] = "结构图：紫色烟幕弹",
			["English"] = "Schematic: Purple Smoke Flare",
			["French"] = "Schéma : Fumigène violet",
			["German"] = "Bauplan: Violettes Rauchsignal",
			["Korean"] = "설계도: 보라색 조명탄",
			["Mexican"] = "Esquema: bengala de humo morado",
			["Portuguese"] = "Diagrama: Sinalizador de Fumaça Roxa",
			["Russian"] = "Схема: лиловая дымовая сигнальная ракета",
			["Spanish"] = "Esquema: bengala de humo morado",
			["Taiwanese"] = "結構圖:紫色煙霧照明彈",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 32381,
		["name"] = {
			["Chinese"] = "结构图：保险丝",
			["English"] = "Schematic: Fused Wiring",
			["French"] = "Schéma : Câble avec fusible",
			["German"] = "Bauplan: Verschmorte Verkabelung",
			["Korean"] = "설계도: 신관 배선",
			["Mexican"] = "Esquema: cableado de fusibles",
			["Portuguese"] = "Diagrama: Fiação com Fusível",
			["Russian"] = "Схема: оплавленный провод",
			["Spanish"] = "Esquema: cableado de fusibles",
			["Taiwanese"] = "結構圖:保險絲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 16000,
			["sources"] = {
				11185,
				19661,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				23386
			}
		},
		["expansion"] = 2,
		["id"] = 34114,
		["name"] = {
			["Chinese"] = "结构图：战地修理机器人110G",
			["English"] = "Schematic: Field Repair Bot 110G",
			["French"] = "Schéma : Robot réparateur 110G",
			["German"] = "Bauplan: Feldreparaturbot 110G",
			["Korean"] = "설계도: 야전수리로봇 110G",
			["Mexican"] = "Esquema: robot de reparación de campo 110G",
			["Portuguese"] = "Diagrama: Robô de Reparos em Campo 110G",
			["Russian"] = "Чертеж: полевой ремонтный робот 110G",
			["Spanish"] = "Esquema: robot de reparación de campo 110G",
			["Taiwanese"] = "設計圖:修理機器人110G型",
		},
		["phase"] = 3,
		["quality"] = "uncommon"
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35186,
		["name"] = {
			["Chinese"] = "结构图：湮灭全视护目镜",
			["English"] = "Schematic: Annihilator Holo-Gogs",
			["French"] = "Schéma : Holo-binocles d'annihilateur",
			["German"] = "Schema: Holobrille des Vernichters",
			["Korean"] = "설계도: 파멸의 홀로그램 고글",
			["Mexican"] = "Esquema: hologafas de aniquilador",
			["Portuguese"] = "Diagrama: Holóculos do Aniquilador",
			["Russian"] = "Схема: голографические очки аннигиляции",
			["Spanish"] = "Esquema: hologafas de aniquilador",
			["Taiwanese"] = "結構圖:殲滅者環視鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35187,
		["name"] = {
			["Chinese"] = "结构图：审判者护目镜3000型",
			["English"] = "Schematic: Justicebringer 3000 Specs",
			["French"] = "Schéma : Bésicles Porte-justice 3000",
			["German"] = "Schema: Gerechtomatbrille 3000",
			["Korean"] = "설계도: 정의의 수호 반사경 3000",
			["Mexican"] = "Esquema: gafas de la Justiciera 3000",
			["Portuguese"] = "Diagrama: Lentes Justiceiras 3000",
			["Russian"] = "Схема: очки \"Воздаятель-3000\"",
			["Spanish"] = "Esquema: gafas de la Justiciera 3000",
			["Taiwanese"] = "結構圖:正義使者3000眼鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35189,
		["name"] = {
			["Chinese"] = "结构图：超级治疗射线9000型",
			["English"] = "Schematic: Powerheal 9000 Lens",
			["French"] = "Schéma : Lentilles fulgurosoin 9000",
			["German"] = "Schema: Superheillinse 9000",
			["Korean"] = "설계도: 강력한 치유 렌즈 9000",
			["Mexican"] = "Esquema: lente de supersanación 9000",
			["Portuguese"] = "Diagrama: Lentes de Supercura 9000",
			["Russian"] = "Схема: линза могущественного целителя-9000",
			["Spanish"] = "Esquema: lente de supersanación 9000",
			["Taiwanese"] = "結構圖:能量治癒9000鏡片",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35190,
		["name"] = {
			["Chinese"] = "结构图：超级月光放大护目镜",
			["English"] = "Schematic: Hyper-Magnified Moon Specs",
			["French"] = "Schéma : Bésicles lunaires hyper-amplifiées",
			["German"] = "Schema: Mondmikroskopbrille",
			["Korean"] = "설계도: 고도로 증폭된 달빛 반사경",
			["Mexican"] = "Esquema: gafas de la luna de hiperamplificación",
			["Portuguese"] = "Diagrama: Lunóculos de Hiper-aumento",
			["Russian"] = "Схема: гиперувеличивающие лунные очки",
			["Spanish"] = "Esquema: gafas de la luna de hiperamplificación",
			["Taiwanese"] = "結構圖:超放大月光眼鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35191,
		["name"] = {
			["Chinese"] = "结构图：奇迹治疗罩XT68型",
			["English"] = "Schematic: Wonderheal XT68 Shades",
			["French"] = "Schéma : Lunettes de soleil fabulosoin XT68",
			["German"] = "Schema: Wunderheilbinokel XT68",
			["Korean"] = "설계도: 기적의 치유 색안경 XT68",
			["Mexican"] = "Esquema: gafas de sol curamaravilla XT68",
			["Portuguese"] = "Diagrama: Óculos da Maravilha Curativa XT68",
			["Russian"] = "Схема: исцеляющий рассеиватель теней XT68",
			["Spanish"] = "Esquema: gafas de sol curamaravilla XT68",
			["Taiwanese"] = "結構圖:奇跡治癒XT68遮光鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35192,
		["name"] = {
			["Chinese"] = "结构图：源生同频护目镜",
			["English"] = "Schematic: Primal-Attuned Goggles",
			["French"] = "Schéma : Lunettes d'harmonisation primordiale",
			["German"] = "Schema: Urgestimmte Brille",
			["Korean"] = "설계도: 원소 조화의 고글",
			["Mexican"] = "Esquema: gafas armonizadas con primordial",
			["Portuguese"] = "Diagrama: Óculos Primajustados",
			["Russian"] = "Схема: очки изначальной гармонии",
			["Spanish"] = "Esquema: gafas armonizadas con primordial",
			["Taiwanese"] = "結構圖:原始調和護目鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35193,
		["name"] = {
			["Chinese"] = "结构图：闪电蚀刻护目镜",
			["English"] = "Schematic: Lightning Etched Specs",
			["French"] = "Schéma : Bésicles gravées aux éclairs",
			["German"] = "Schema: Blitzgeätzte Brille",
			["Korean"] = "설계도: 번개 깃든 반사경",
			["Mexican"] = "Esquema: gafas de grabados de relámpagos",
			["Portuguese"] = "Diagrama: Óculos Cinzelados com Raios",
			["Russian"] = "Схема: иссеченные молниями очки",
			["Spanish"] = "Esquema: gafas de grabados de relámpagos",
			["Taiwanese"] = "結構圖:閃電蝕刻眼鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35194,
		["name"] = {
			["Chinese"] = "结构图：必中护目镜V3.0",
			["English"] = "Schematic: Surestrike Goggles v3.0",
			["French"] = "Schéma : Lunettes vise-juste v3.0",
			["German"] = "Schema: Volltrefferbrille v3.0",
			["Korean"] = "설계도: 일격보증 고글 v3.0",
			["Mexican"] = "Esquema: gafas de golpe seguro v3.0",
			["Portuguese"] = "Diagrama: Óculos Golpe-certeiro v3.0",
			["Russian"] = "Схема: очки верного удара модель 3.0",
			["Spanish"] = "Esquema: gafas de golpe seguro v3.0",
			["Taiwanese"] = "結構圖:絕對打擊護目鏡v3.0",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35195,
		["name"] = {
			["Chinese"] = "结构图：伤害投射护目镜",
			["English"] = "Schematic: Mayhem Projection Goggles",
			["French"] = "Schéma : Lunettes de projection de désordre",
			["German"] = "Schema: Chaosprognosebrille",
			["Korean"] = "설계도: 파괴력 투영 고글",
			["Mexican"] = "Esquema: gafas de proyección de caos",
			["Portuguese"] = "Diagrama: Lentes de Projeção da Desordem",
			["Russian"] = "Схема: проекционные очки резни",
			["Spanish"] = "Esquema: gafas de proyección de caos",
			["Taiwanese"] = "結構圖:暴行投影護目鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35196,
		["name"] = {
			["Chinese"] = "结构图：硬化氪金护目镜",
			["English"] = "Schematic: Hard Khorium Goggles",
			["French"] = "Schéma : Lunettes en khorium durci",
			["German"] = "Schema: Brille aus Hartkhorium",
			["Korean"] = "설계도: 단단한 코륨 고글",
			["Mexican"] = "Esquema: gafas de korio duro",
			["Portuguese"] = "Diagrama: Óculos de Kório Duro",
			["Russian"] = "Схема: очки из закаленного кория",
			["Spanish"] = "Esquema: gafas de korio duro",
			["Taiwanese"] = "結構圖:特硬克銀護目鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35197,
		["name"] = {
			["Chinese"] = "结构图：四核死亡一击护目镜X44型",
			["English"] = "Schematic: Quad Deathblow X44 Goggles",
			["French"] = "Schéma : Quadrilunettes coup-de-grâce X44",
			["German"] = "Schema: Vieltotmacherbrille X44",
			["Korean"] = "설계도: 사중 죽음의 고글 X44",
			["Mexican"] = "Esquema: gafas de arremetida mortal cuádruple X44",
			["Portuguese"] = "Diagrama: Óculos Quad Golpe Mortal X44",
			["Russian"] = "Схема: очки квадрисмертельного удара X44",
			["Spanish"] = "Esquema: gafas de arremetida mortal cuádruple X44",
			["Taiwanese"] = "結構圖:四倍死亡打擊X44護目鏡",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35310,
		["name"] = {
			["Chinese"] = "结构图：治疗药水注射器",
			["English"] = "Schematic: Healing Potion Injector",
			["French"] = "Schéma : Injecteur de potion de soins",
			["German"] = "Bauplan: Heiltrankeinspritzung",
			["Korean"] = "설계도: 치유 물약 주사기",
			["Mexican"] = "Esquema: inyector de poción de sanación",
			["Portuguese"] = "Diagrama: Injetor de Poção de Cura",
			["Russian"] = "Схема: набор для лечебных инъекций",
			["Spanish"] = "Esquema: inyector de poción de sanación",
			["Taiwanese"] = "結構圖:治療藥水注射器",
		},
		["phase"] = 5,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35311,
		["name"] = {
			["Chinese"] = "结构图：法力药水注射器",
			["English"] = "Schematic: Mana Potion Injector",
			["French"] = "Schéma : Injecteur de potion de mana",
			["German"] = "Bauplan: Manatrankeinspritzung",
			["Korean"] = "설계도: 마나 물약 주사기",
			["Mexican"] = "Esquema: inyector de poción de maná",
			["Portuguese"] = "Diagrama: Injetor de Poção de Mana",
			["Russian"] = "Схема: набор для инъекций маны",
			["Spanish"] = "Esquema: inyector de poción de maná",
			["Taiwanese"] = "結構圖:法力藥水注射器",
		},
		["phase"] = 5,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				19219,
			},
		},
		["expansion"] = 2,
		["id"] = 35582,
		["name"] = {
			["Chinese"] = "结构图：轻便型超级火箭靴",
			["English"] = "Schematic: Rocket Boots Xtreme Lite",
			["French"] = "Schéma : Bottes-fusées extrêmes légères",
			["German"] = "Bauplan: Raketenstiefel Xtrem-Lite",
			["Korean"] = "설계도: 가벼운 극한의 로켓 장화",
			["Mexican"] = "Esquema: botas cohete Xtremo ligeras",
			["Portuguese"] = "Diagrama: Botas-foguete Xtremas Lite",
			["Russian"] = "Схема: облегченные экстремальные реактивные сапоги",
			["Spanish"] = "Esquema: botas cohete Xtremo ligeras",
			["Taiwanese"] = "結構圖:輕巧型火箭靴極限版",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Engineering"], item)
end
