-------------------------------------------------------
-- All skills (Engineering) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Engineering"] then RR_DATA["skills"]["Engineering"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 30303,
		["item_id"] = 23781,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "元素炸药粉",
			["English"] = "Elemental Blasting Powder",
			["French"] = "Poudre d'explosion élémentaire",
			["German"] = "Elementarsprengpulver",
			["Korean"] = "원소 화약",
			["Mexican"] = "Pólvora elemental",
			["Portuguese"] = "Pó Explosivo Elemental",
			["Russian"] = "Взрывчатое вещество стихий",
			["Spanish"] = "Pólvora elemental",
			["Taiwanese"] = "元素火藥粉",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30304,
		["item_id"] = 23782,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔铁外壳",
			["English"] = "Fel Iron Casing",
			["French"] = "Etui en gangrefer",
			["German"] = "Teufelseisengehäuse",
			["Korean"] = "지옥무쇠 형틀",
			["Mexican"] = "Envoltura de hierro vil",
			["Portuguese"] = "Carcaça de Ferrovil",
			["Russian"] = "Обшивка из оскверненного железа",
			["Spanish"] = "Envoltura de hierro vil",
			["Taiwanese"] = "魔鐵外殼",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30305,
		["item_id"] = 23783,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔铁螺丝",
			["English"] = "Handful of Fel Iron Bolts",
			["French"] = "Poignée de boulons en gangrefer",
			["German"] = "Eine Hand voll Teufelseisenbolzen",
			["Korean"] = "지옥무쇠 나사 한 줌",
			["Mexican"] = "Puñado de tornillos de hierro vil",
			["Portuguese"] = "Punhado de Parafusos de Ferrovil",
			["Russian"] = "Горсть винтов из оскверненного железа",
			["Spanish"] = "Puñado de tornillos de hierro vil",
			["Taiwanese"] = "一把魔鐵螺栓",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30306,
		["item_id"] = 23784,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "精金框架",
			["English"] = "Adamantite Frame",
			["French"] = "Structure en adamantite",
			["German"] = "Adamantitrahmen",
			["Korean"] = "아다만타이트 형틀",
			["Mexican"] = "Marco de adamantita",
			["Portuguese"] = "Estrutura de Adamantita",
			["Russian"] = "Адамантитовая рамка",
			["Spanish"] = "Marco de adamantita",
			["Taiwanese"] = "堅鋼骨架",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30307,
		["item_id"] = 23785,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "硬化精金管",
			["English"] = "Hardened Adamantite Tube",
			["French"] = "Tube en adamantite trempé",
			["German"] = "Gehärtetes Adamantitrohr",
			["Korean"] = "강화된 아다만타이트관",
			["Mexican"] = "Tubo de adamantita endurecida",
			["Portuguese"] = "Tubo de Adamantita Temperada",
			["Russian"] = "Труба из закаленного адамантита",
			["Spanish"] = "Tubo de adamantita endurecida",
			["Taiwanese"] = "特堅鋼管",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30308,
		["item_id"] = 23786,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "氪金能量核心",
			["English"] = "Khorium Power Core",
			["French"] = "Batterie en khorium",
			["German"] = "Khoriumkraftkern",
			["Korean"] = "코륨 동력핵",
			["Mexican"] = "Batería de korio",
			["Portuguese"] = "Núcleo de Força de Kório",
			["Russian"] = "Кориевое силовое ядро",
			["Spanish"] = "Núcleo de poder de korio",
			["Taiwanese"] = "克銀能量核心",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30309,
		["item_id"] = 23787,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "魔钢稳定器",
			["English"] = "Felsteel Stabilizer",
			["French"] = "Stabilisateur en gangracier",
			["German"] = "Teufelsstahlstabilisator",
			["Korean"] = "지옥강철 안정장치",
			["Mexican"] = "Estabilizador de acero vil",
			["Portuguese"] = "Estabilizador de Açovil",
			["Russian"] = "Стабилизатор из оскверненной стали",
			["Spanish"] = "Estabilizador de acero vil",
			["Taiwanese"] = "魔鋼安置器",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30310,
		["item_id"] = 23736,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔铁炸弹",
			["English"] = "Fel Iron Bomb",
			["French"] = "Bombe en gangrefer",
			["German"] = "Teufelseisenbombe",
			["Korean"] = "지옥무쇠 폭탄",
			["Mexican"] = "Bomba de hierro vil",
			["Portuguese"] = "Bomba de Ferrovil",
			["Russian"] = "Бомба из оскверненного железа",
			["Spanish"] = "Bomba de hierro vil",
			["Taiwanese"] = "魔鐵炸彈",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30311,
		["item_id"] = 23737,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "精金手雷",
			["English"] = "Adamantite Grenade",
			["French"] = "Grenade en adamantite",
			["German"] = "Adamantitgranate",
			["Korean"] = "아다만타이트 수류탄",
			["Mexican"] = "Granada de adamantita",
			["Portuguese"] = "Granada de Adamantita",
			["Russian"] = "Адамантитовая граната",
			["Spanish"] = "Granada de adamantita",
			["Taiwanese"] = "堅鋼手榴彈",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30312,
		["item_id"] = 23742,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "魔铁步枪",
			["English"] = "Fel Iron Musket",
			["French"] = "Mousquet en gangrefer",
			["German"] = "Teufelseisenmuskete",
			["Korean"] = "지옥무쇠 머스킷총",
			["Mexican"] = "Mosquete de hierro vil",
			["Portuguese"] = "Mosquete de Ferrovil",
			["Russian"] = "Мушкет из оскверненного железа",
			["Spanish"] = "Mosquete de hierro vil",
			["Taiwanese"] = "魔鐵槍",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30313,
		["item_id"] = 23746,
		["items"] = {
			23799,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "精金步枪",
			["English"] = "Adamantite Rifle",
			["French"] = "Carabine en adamantite",
			["German"] = "Adamantitgewehr",
			["Korean"] = "아다만타이트 소총",
			["Mexican"] = "Rifle de adamantita",
			["Portuguese"] = "Rifle de Adamantita",
			["Russian"] = "Адамантитовая винтовка",
			["Spanish"] = "Rifle de adamantita",
			["Taiwanese"] = "堅鋼步槍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30314,
		["item_id"] = 23747,
		["items"] = {
			23800,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔钢火枪",
			["English"] = "Felsteel Boomstick",
			["French"] = "Espingole en gangracier",
			["German"] = "Teufelsstahlschießeisen",
			["Korean"] = "지옥강철 붐스틱",
			["Mexican"] = "Bocarda de acero vil",
			["Portuguese"] = "Cano de Atirar de Açovil",
			["Russian"] = "Огнестрел из оскверненной стали",
			["Spanish"] = "Bocarda de acero vil",
			["Taiwanese"] = "魔鋼火槍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30315,
		["item_id"] = 23748,
		["items"] = {
			23802,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "精制氪金步枪",
			["English"] = "Ornate Khorium Rifle",
			["French"] = "Carabine ornée en khorium",
			["German"] = "Verschnörkeltes Khoriumgewehr",
			["Korean"] = "화려한 코륨 소총",
			["Mexican"] = "Rifle de korio ornamentado",
			["Portuguese"] = "Rifle de Kório Ornado",
			["Russian"] = "Узорчатая кориевая винтовка",
			["Spanish"] = "Rifle de korio ornamentado",
			["Taiwanese"] = "華麗克銀步槍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30316,
		["item_id"] = 23758,
		["items"] = {
			23803,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "旋轮护目镜",
			["English"] = "Cogspinner Goggles",
			["French"] = "Lunettes de Tournepignon",
			["German"] = "Zahnradbrille",
			["Korean"] = "톱니바퀴 고글",
			["Mexican"] = "Gafas Volopiñón",
			["Portuguese"] = "Óculos Rodagiros",
			["Russian"] = "Очки прядильщика",
			["Spanish"] = "Gafas Volopiñón",
			["Taiwanese"] = "考格斯賓護目鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30317,
		["item_id"] = 23761,
		["items"] = {
			23804,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "能量放大护目镜",
			["English"] = "Power Amplification Goggles",
			["French"] = "Lunettes d'amplification de puissance",
			["German"] = "Energieverstärkungsbrille",
			["Korean"] = "마력 증폭 고글",
			["Mexican"] = "Gafas de amplificación de poder",
			["Portuguese"] = "Lentes de Amplificação do Poder",
			["Russian"] = "Умножающие силу очки",
			["Spanish"] = "Gafas de amplificación de poder",
			["Taiwanese"] = "能量增強護目鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30318,
		["item_id"] = 23762,
		["items"] = {
			23805,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "超光谱侦测护目镜",
			["English"] = "Ultra-Spectropic Detection Goggles",
			["French"] = "Lunettes de détection ultra-spectroscopique",
			["German"] = "Ultraspektropische Enthüllungsbrille",
			["Korean"] = "초분광 감지 고글",
			["Mexican"] = "Gafas de detección ultraespectrópicas",
			["Portuguese"] = "Óculos de Detecção Ultra-espectrópicos",
			["Russian"] = "Ультраскопические очки обнаружения",
			["Spanish"] = "Gafas de detección ultraespectrópicas",
			["Taiwanese"] = "超光學偵測護目鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30325,
		["item_id"] = 23763,
		["items"] = {
			23806,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "超视距护目镜",
			["English"] = "Hyper-Vision Goggles",
			["French"] = "Lunettes d'hyper-vision",
			["German"] = "Extremsichtbrille",
			["Korean"] = "고감도 고글",
			["Mexican"] = "Gafas de hipervisión",
			["Portuguese"] = "Óculos de Hipervisão",
			["Russian"] = "Очки гиперзрения",
			["Spanish"] = "Gafas de hipervisión",
			["Taiwanese"] = "超視覺護目鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30329,
		["item_id"] = 23764,
		["items"] = {
			23807,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "精金瞄准镜",
			["English"] = "Adamantite Scope",
			["French"] = "Lunette en adamantite",
			["German"] = "Adamantitzielfernrohr",
			["Korean"] = "아다만타이트 조준경",
			["Mexican"] = "Mira de adamantita",
			["Portuguese"] = "Mira de Adamantita",
			["Russian"] = "Адамантитовый прицел",
			["Spanish"] = "Mira de adamantita",
			["Taiwanese"] = "堅鋼瞄準鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30332,
		["item_id"] = 23765,
		["items"] = {
			23808,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "氪金瞄准镜",
			["English"] = "Khorium Scope",
			["French"] = "Lunette en khorium",
			["German"] = "Khoriumzielfernrohr",
			["Korean"] = "코륨 조준경",
			["Mexican"] = "Mira de korio",
			["Portuguese"] = "Mira de Kório",
			["Russian"] = "Кориевый прицел",
			["Spanish"] = "Mira de korio",
			["Taiwanese"] = "克銀瞄準鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30334,
		["item_id"] = 23766,
		["items"] = {
			23809,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "稳定恒金瞄准镜",
			["English"] = "Stabilized Eternium Scope",
			["French"] = "Lunette en éternium stabilisé",
			["German"] = "Geeichtes Eterniumzielfernrohr",
			["Korean"] = "안정된 이터늄 조준경",
			["Mexican"] = "Mira de eternio estabilizada",
			["Portuguese"] = "Mira Estável de Etérnio",
			["Russian"] = "Стабилизированный этерниевый прицел",
			["Spanish"] = "Mira de eternium estabilizada",
			["Taiwanese"] = "穩固恆金瞄準鏡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30337,
		["item_id"] = 23767,
		["items"] = {
			23810,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "打架机器人",
			["English"] = "Crashin' Thrashin' Robot",
			["French"] = "Robot Cogn'Baff",
			["German"] = "Krachbummroboter",
			["Korean"] = "우당탕 쿠당탕 전투로봇",
			["Mexican"] = "Robot triturador",
			["Portuguese"] = "Robô Bate-bate",
			["Russian"] = "Робот \"Бей-Молоти\"",
			["Spanish"] = "Robot triturador",
			["Taiwanese"] = "暴力粉碎機器人",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30341,
		["item_id"] = 23768,
		["items"] = {
			23811,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "白色烟幕弹",
			["English"] = "White Smoke Flare",
			["French"] = "Fumigène blanc",
			["German"] = "Weißes Rauchsignal",
			["Korean"] = "백색 조명탄",
			["Mexican"] = "Bengala de humo blanco",
			["Portuguese"] = "Sinalizador de Fumaça Branca",
			["Russian"] = "Белая дымовая сигнальная ракета",
			["Spanish"] = "Bengala de humo blanco",
			["Taiwanese"] = "白色煙霧照明彈",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30344,
		["item_id"] = 23771,
		["items"] = {
			23814,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "绿色烟幕弹",
			["English"] = "Green Smoke Flare",
			["French"] = "Fumigène vert",
			["German"] = "Grünes Rauchsignal",
			["Korean"] = "녹색 조명탄",
			["Mexican"] = "Bengala de humo verde",
			["Portuguese"] = "Sinalizador de Fumaça Verde",
			["Russian"] = "Зеленая дымовая сигнальная ракета",
			["Spanish"] = "Bengala de humo verde",
			["Taiwanese"] = "綠色煙霧照明彈",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30346,
		["item_id"] = 23772,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "魔铁弹丸",
			["English"] = "Fel Iron Shells",
			["French"] = "Obus en gangrefer",
			["German"] = "Teufelseisenpatronen",
			["Korean"] = "지옥무쇠 탄환",
			["Mexican"] = "Balas de hierro vil",
			["Portuguese"] = "Cartuchos de Ferrovil",
			["Russian"] = "Патроны из оскверненного железа",
			["Spanish"] = "Balas de hierro vil",
			["Taiwanese"] = "魔鐵彈藥",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30347,
		["item_id"] = 34504,
		["items"] = {
			23815,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "精金制弹机",
			["English"] = "Adamantite Shell Machine",
			["French"] = "Presse à obus en adamantite",
			["German"] = "Maschine für Adamantitpatronen",
			["Korean"] = "아다만타이트 탄환 제조기",
			["Mexican"] = "Máquina de balas de adamantita",
			["Portuguese"] = "Máquina de Cartuchos de Adamantita",
			["Russian"] = "Станок для адамантитовых патронов",
			["Spanish"] = "Máquina de balas de adamantita",
			["Taiwanese"] = "堅鋼彈藥製造器",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30348,
		["item_id"] = 23774,
		["items"] = {
			23816,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "魔铁工具箱",
			["English"] = "Fel Iron Toolbox",
			["French"] = "Boîte à outils en gangrefer",
			["German"] = "Werkzeugkasten aus Teufelseisen",
			["Korean"] = "지옥무쇠 연장통",
			["Mexican"] = "Caja de herramientas de hierro vil",
			["Portuguese"] = "Caixa de Ferramentas de Ferrovil",
			["Russian"] = "Ящик для инструментов из оскверненного железа",
			["Spanish"] = "Caja de herramientas de hierro vil",
			["Taiwanese"] = "魔鐵工具箱",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30547,
		["item_id"] = 23819,
		["items"] = {
			23874,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "元素爆盐炸弹",
			["English"] = "Elemental Seaforium Charge",
			["French"] = "Charge d'hydroglycérine élémentaire",
			["German"] = "Elementare Zephyriumladung",
			["Korean"] = "원소 시포리움 폭약",
			["Mexican"] = "Carga de seforio elemental",
			["Portuguese"] = "Carga Elemental de Cequatrum",
			["Russian"] = "Стихийный сефориевый заряд",
			["Spanish"] = "Carga de seforio elemental",
			["Taiwanese"] = "元素爆鹽炸藥",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30548,
		["item_id"] = 23821,
		["items"] = {
			23888,
		},
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "气阀微粒提取器",
			["English"] = "Zapthrottle Mote Extractor",
			["French"] = "Extracteur de granules Zappeur-Gazier",
			["German"] = "Schockdrosselnder Partikelextraktor",
			["Korean"] = "기압조절 가스 추출기",
			["Mexican"] = "Extractor de motas de zapacelerador",
			["Portuguese"] = "Extrator de Partículas Zapeacelera",
			["Russian"] = "Удаленный конденсатор выхлопов",
			["Spanish"] = "Extractor de motas de zapacelerador",
			["Taiwanese"] = "快速節流微粒吸取器",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30551,
		["item_id"] = 33092,
		["items"] = {
			23883,
			35310,
		},
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "治疗药水注射器",
			["English"] = "Healing Potion Injector",
			["French"] = "Injecteur de potion de soins",
			["German"] = "Heiltrankeinspritzung",
			["Korean"] = "치유 물약 주사기",
			["Mexican"] = "Inyector de poción de sanación",
			["Portuguese"] = "Injetor de Poção de Cura",
			["Russian"] = "Набор для лечебных инъекций",
			["Spanish"] = "Inyector de poción de sanación",
			["Taiwanese"] = "治療藥水注射器",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30552,
		["item_id"] = 33093,
		["items"] = {
			23884,
			35311,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "法力药水注射器",
			["English"] = "Mana Potion Injector",
			["French"] = "Injecteur de potion de mana",
			["German"] = "Manatrankeinspritzung",
			["Korean"] = "마나 물약 주사기",
			["Mexican"] = "Inyector de poción de maná",
			["Portuguese"] = "Injetor de Poção de Mana",
			["Russian"] = "Набор для инъекций маны",
			["Spanish"] = "Inyector de poción de maná",
			["Taiwanese"] = "法力藥水注射器",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30556,
		["item_id"] = 23824,
		["items"] = {
			23887,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "超级火箭靴",
			["English"] = "Rocket Boots Xtreme",
			["French"] = "Bottes-fusées extrêmes",
			["German"] = "Raketenstiefel Xtrem",
			["Korean"] = "극한의 로켓 장화",
			["Mexican"] = "Botas cohete Xtremo",
			["Portuguese"] = "Botas-foguete Xtremas",
			["Russian"] = "Экстремальные реактивные сапоги",
			["Spanish"] = "Botas cohete Xtremo",
			["Taiwanese"] = "火箭靴極限版",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 30558,
		["item_id"] = 23826,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "更大的炸弹",
			["English"] = "The Bigger One",
			["French"] = "L'Encore-Plus-Mastoc",
			["German"] = "Der Größere",
			["Korean"] = "대왕폭탄",
			["Mexican"] = "La más grande",
			["Portuguese"] = "O Bombaço",
			["Russian"] = "Величайший",
			["Spanish"] = "La más grande",
			["Taiwanese"] = "特大炸彈",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 23750,
			["sources"] = {
				8126,
				8738,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30560,
		["item_id"] = 23827,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "超级神风炸药",
			["English"] = "Super Sapper Charge",
			["French"] = "Super-charge de sapeur",
			["German"] = "Super Pioniersprengladung",
			["Korean"] = "초강력 공병 폭탄",
			["Mexican"] = "Supercarga de zapador",
			["Portuguese"] = "Supercarga Sapadora",
			["Russian"] = "Превосходная мина",
			["Spanish"] = "Supercarga de zapador",
			["Taiwanese"] = "強力工事炸藥",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 33250,
			["sources"] = {
				8126,
				8738,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30563,
		["item_id"] = 23836,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "地精火箭发射器",
			["English"] = "Goblin Rocket Launcher",
			["French"] = "Lance-roquettes gobelin",
			["German"] = "Goblinraketenwerfer",
			["Korean"] = "고블린 로켓 발사기",
			["Mexican"] = "Lanzacohetes goblin",
			["Portuguese"] = "Lança-foguetes Goblínico",
			["Russian"] = "Гоблинский ракетомет",
			["Spanish"] = "Lanzacohetes goblin",
			["Taiwanese"] = "哥布林火箭發射器",
		},
		["phase"] = 1,
		["specialisation"] = 20222,
		["trainers"] = {
			["price"] = 47500,
			["sources"] = {
				8126,
				8738,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30565,
		["item_id"] = 23838,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "工头的附魔头盔",
			["English"] = "Foreman's Enchanted Helmet",
			["French"] = "Casque de contremaître enchanté",
			["German"] = "Verzauberter Helm des Vorarbeiters",
			["Korean"] = "현장감독의 마법 안전모",
			["Mexican"] = "Casco encantado de supervisor",
			["Portuguese"] = "Capacete Encantado do Encarregado",
			["Russian"] = "Зачарованный шлем штейгера",
			["Spanish"] = "Casco encantado de supervisor",
			["Taiwanese"] = "工頭的附魔盔帽",
		},
		["phase"] = 1,
		["specialisation"] = 20222,
		["trainers"] = {
			["price"] = 95000,
			["sources"] = {
				8126,
				8738,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30566,
		["item_id"] = 23839,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "工头的加固头盔",
			["English"] = "Foreman's Reinforced Helmet",
			["French"] = "Casque de contremaître renforcé",
			["German"] = "Verstärkter Helm des Vorarbeiters",
			["Korean"] = "현장감독의 강화 안전모",
			["Mexican"] = "Casco reforzado de supervisor",
			["Portuguese"] = "Capacete Reforçado do Encarregado",
			["Russian"] = "Укрепленный шлем старшины",
			["Spanish"] = "Casco reforzado de supervisor",
			["Taiwanese"] = "工頭強化盔帽",
		},
		["phase"] = 1,
		["specialisation"] = 20222,
		["trainers"] = {
			["price"] = 95000,
			["sources"] = {
				8126,
				8738,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30568,
		["item_id"] = 23841,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "侏儒喷火炮台",
			["English"] = "Gnomish Flame Turret",
			["French"] = "Tourelle à feu gnome",
			["German"] = "Gnomisches Flammengeschütz",
			["Korean"] = "노움 화염 포탑",
			["Mexican"] = "Torreta de llamas gnoma",
			["Portuguese"] = "Torreta Lança-chamas Gnômica",
			["Russian"] = "Гномская огненная турель",
			["Spanish"] = "Torreta de llamas gnoma",
			["Taiwanese"] = "地精烈焰砲塔",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				7406,
				7944,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30569,
		["item_id"] = 23835,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "侏儒变鸡器",
			["English"] = "Gnomish Poultryizer",
			["French"] = "Pouletisateur gnome",
			["German"] = "Gnomischer Geflügelisierer",
			["Korean"] = "노움 꼬꼬댁 변신장치",
			["Mexican"] = "Pollotizador gnómico",
			["Portuguese"] = "Galinhaitor Gnômico",
			["Russian"] = "Гномский полюсный птицефикатор",
			["Spanish"] = "Pollotizador gnómico",
			["Taiwanese"] = "地精變形器",
		},
		["phase"] = 1,
		["specialisation"] = 20219,
		["trainers"] = {
			["price"] = 35000,
			["sources"] = {
				7406,
				7944,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30570,
		["item_id"] = 23825,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "近似无敌腰带",
			["English"] = "Nigh-Invulnerability Belt",
			["French"] = "Ceinture de quasi-invulnérabilité",
			["German"] = "Gürtel der fast perfekten Unverwundbarkeit",
			["Korean"] = "거의 무적 허리띠",
			["Mexican"] = "Cinturón de cuasi-invulnerabilidad",
			["Portuguese"] = "Cinto da Quase-invulnerabilidade",
			["Russian"] = "Пояс почти полной неуязвимости",
			["Spanish"] = "Cinturón de cuasi-invulnerabilidad",
			["Taiwanese"] = "有限無敵腰帶",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				7406,
				7944,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30574,
		["item_id"] = 23828,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "侏儒能量护目镜",
			["English"] = "Gnomish Power Goggles",
			["French"] = "Lunettes de puissance gnomes",
			["German"] = "Gnomische Machtschutzbrille",
			["Korean"] = "노움 주문증폭 고글",
			["Mexican"] = "Gafas gnómicas de poder",
			["Portuguese"] = "Óculos Gnômicos do Poder",
			["Russian"] = "Гномские силовые очки",
			["Spanish"] = "Gafas gnómicas de poder",
			["Taiwanese"] = "地精能量護目鏡",
		},
		["phase"] = 1,
		["specialisation"] = 20219,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7406,
				7944,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30575,
		["item_id"] = 23829,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "侏儒作战护目镜",
			["English"] = "Gnomish Battle Goggles",
			["French"] = "Lunettes de combat gnomes",
			["German"] = "Gnomische Kampfschutzbrille",
			["Korean"] = "노움 전투 고글",
			["Mexican"] = "Gafas gnomas de batalla",
			["Portuguese"] = "Óculos de Batalha Gnômicos",
			["Russian"] = "Гномские боевые очки",
			["Spanish"] = "Gafas gnomas de batalla",
			["Taiwanese"] = "地精作戰護目鏡",
		},
		["phase"] = 1,
		["specialisation"] = 20219,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				7406,
				7944,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32814,
		["item_id"] = 25886,
		["items"] = {
			25887,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "紫色烟幕弹",
			["English"] = "Purple Smoke Flare",
			["French"] = "Fumigène violet",
			["German"] = "Violettes Rauchsignal",
			["Korean"] = "보라색 조명탄",
			["Mexican"] = "Bengala de humo morado",
			["Portuguese"] = "Sinalizador de Fumaça Roxa",
			["Russian"] = "Лиловая дымовая сигнальная ракета",
			["Spanish"] = "Bengala de humo morado",
			["Taiwanese"] = "紫色煙霧照明彈",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 36954,
		["item_id"] = 30542,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "空间撕裂器 - 52区",
			["English"] = "Dimensional Ripper - Area 52",
			["French"] = "Déchiqueteur dimensionnel - Zone 52",
			["German"] = "Dimensionszerfetzer: Area 52",
			["Korean"] = "차원 분할기: 52번 구역",
			["Mexican"] = "Desgarrador dimensional: Área 52",
			["Portuguese"] = "Estripador Dimensional - Área 52",
			["Russian"] = "Пространственный проходчик - Зона 52",
			["Spanish"] = "Desgarrador dimensional: Área 52",
			["Taiwanese"] = "空間撕裂器 - 52區",
		},
		["phase"] = 1,
		["specialisation"] = 20222,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				21493,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36955,
		["item_id"] = 30544,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "超级安全传送器：托什雷的基地",
			["English"] = "Ultrasafe Transporter - Toshley's Station",
			["French"] = "Transporteur ultra-sécurisé : Poste de Toshley",
			["German"] = "Extrem sicherer Transporter: Toshleys Station",
			["Korean"] = "안전보증 순간이동기: 토쉴리의 연구기지",
			["Mexican"] = "Transportador ultraseguro: Estación de Toshley",
			["Portuguese"] = "Transportador Ultrasseguro: Estação do Tocha",
			["Russian"] = "Сверхбезопасный транспортер на станцию Тошли",
			["Spanish"] = "Transportador ultraseguro: Estación de Toshley",
			["Taiwanese"] = "安全傳送器:托斯利基地",
		},
		["phase"] = 1,
		["specialisation"] = 20219,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				21494,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 39895,
		["item_id"] = 7191,
		["items"] = {
			32381,
		},
		["min_skill"] = 275,
		["name"] = {
			["Chinese"] = "保险丝",
			["English"] = "Fused Wiring",
			["French"] = "Câble avec fusible",
			["German"] = "Verschmorte Verkabelung",
			["Korean"] = "신관 배선",
			["Mexican"] = "Cableado de fusibles",
			["Portuguese"] = "Fiação com Fusível",
			["Russian"] = "Кабельная система с плавкими предохранителями",
			["Spanish"] = "Cableado de fusibles",
			["Taiwanese"] = "保險絲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 39971,
		["item_id"] = 32423,
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "冰霜冲击雷管",
			["English"] = "Icy Blasting Primers",
			["French"] = "Amorces d'explosion glaciale",
			["German"] = "Eisiger Sprengzünder",
			["Korean"] = "얼음 뇌관",
			["Mexican"] = "Cebos explosivos helados",
			["Portuguese"] = "Detonadores Gelados",
			["Russian"] = "Ледяные взрывчатые запалы",
			["Spanish"] = "Cebos explosivos helados",
			["Taiwanese"] = "冰爆雷管",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 39973,
		["item_id"] = 32413,
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "冰霜手雷",
			["English"] = "Frost Grenades",
			["French"] = "Grenades de givre",
			["German"] = "Frostgranaten",
			["Korean"] = "냉기 수류탄",
			["Mexican"] = "Granadas de Escarcha",
			["Portuguese"] = "Granadas de Gelo",
			["Russian"] = "Замораживающие гранаты",
			["Spanish"] = "Granadas de Escarcha",
			["Taiwanese"] = "冰霜手榴彈",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				17634,
				18775,
				17637,
				19576,
				18752,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 40274,
		["item_id"] = 32461,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "狂野机械护目镜",
			["English"] = "Furious Gizmatic Goggles",
			["French"] = "Lunettes bibelomatiques furieuses",
			["German"] = "Gizmatische Wahnsinnsbrille",
			["Korean"] = "맹렬한 기계장치 고글",
			["Mexican"] = "Gafas cacharráticas frenéticas",
			["Portuguese"] = "Óculos Gizmáticos Furiosos",
			["Russian"] = "Яростные механические очки",
			["Spanish"] = "Gafas cacharráticas frenéticas",
			["Taiwanese"] = "狂怒電磁護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41307,
		["item_id"] = 32756,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "陀螺平衡氪金重枪",
			["English"] = "Gyro-balanced Khorium Destroyer",
			["French"] = "Destructeur gyroscopique en khorium",
			["German"] = "Gyrobalancierter Khoriumzerstörer",
			["Korean"] = "균형 잡힌 회전식 코륨 파괴자",
			["Mexican"] = "Destructor de korio giroequilibrado",
			["Portuguese"] = "Destruidor de Kório Giroscópico",
			["Russian"] = "Гиробалансированный кориевый разрушитель",
			["Spanish"] = "Destructor de korio giroequilibrado",
			["Taiwanese"] = "迴轉平衡克銀毀滅火槍",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41311,
		["item_id"] = 32472,
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "审判者护目镜2000型",
			["English"] = "Justicebringer 2000 Specs",
			["French"] = "Bésicles Porte-justice 2000",
			["German"] = "Gerechtomatbrille 2000",
			["Korean"] = "정의의 수호 반사경 2000",
			["Mexican"] = "Gafas de la Justiciera 2000",
			["Portuguese"] = "Lentes Justiceiras 2000",
			["Russian"] = "Очки \"Воздаятель 2000\"",
			["Spanish"] = "Gafas de la Justiciera 2000",
			["Taiwanese"] = "正義化身2000護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41312,
		["item_id"] = 32473,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "坦克眼镜",
			["English"] = "Tankatronic Goggles",
			["French"] = "Lunettes tankatroniques",
			["German"] = "Panzatronikbrille",
			["Korean"] = "전자방어 고글",
			["Mexican"] = "Gafas tanquetrónicas",
			["Portuguese"] = "Óculos de Proteção Tancatrônica",
			["Russian"] = "Танкатронные очки",
			["Spanish"] = "Gafas tanquetrónicas",
			["Taiwanese"] = "坦克電子護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41314,
		["item_id"] = 32474,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "必中护目镜V2.0",
			["English"] = "Surestrike Goggles v2.0",
			["French"] = "Lunettes vise-juste v2.0",
			["German"] = "Volltrefferbrille v2.0",
			["Korean"] = "일격보증 고글 v2.0",
			["Mexican"] = "Gafas de golpe seguro v2.0",
			["Portuguese"] = "Óculos Golpe-certeiro v2.0",
			["Russian"] = "Очки верного удара модель 2.0",
			["Spanish"] = "Gafas de golpe seguro v2,0",
			["Taiwanese"] = "絕對打擊護目鏡v2.0",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41315,
		["item_id"] = 32476,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "齿轮风暴护目镜",
			["English"] = "Gadgetstorm Goggles",
			["French"] = "Lunettes de gadget-orage",
			["German"] = "Gadgetsturmbrille",
			["Korean"] = "폭풍기계장치 고글",
			["Mexican"] = "Gafas trastotormenta",
			["Portuguese"] = "Óculos Tempestatreco",
			["Russian"] = "Очки механического шторма",
			["Spanish"] = "Gafas trastotormenta",
			["Taiwanese"] = "機件護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41316,
		["item_id"] = 32475,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "活力复制器",
			["English"] = "Living Replicator Specs",
			["French"] = "Bésicles vivantes du réplicateur",
			["German"] = "Lebensreplikatorbrille",
			["Korean"] = "생명의 순환 반사경",
			["Mexican"] = "Gafas del Replicador viviente",
			["Portuguese"] = "Óculos do Replicador Vivente",
			["Russian"] = "Живые реплицирующие очки",
			["Spanish"] = "Gafas del Replicador viviente",
			["Taiwanese"] = "生命複製護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41317,
		["item_id"] = 32478,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "死亡一击护目镜X11型",
			["English"] = "Deathblow X11 Goggles",
			["French"] = "Lunettes coup-de-grâce X11",
			["German"] = "Totmacherbrille X11",
			["Korean"] = "죽음의 고글 X11",
			["Mexican"] = "Gafas X11 Arremetida mortal",
			["Portuguese"] = "Óculos Golpe Mortal X11",
			["Russian"] = "Очки смертельного удара X11",
			["Spanish"] = "Gafas X11 Arremetida mortal",
			["Taiwanese"] = "死亡打擊X11護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41318,
		["item_id"] = 32479,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "奇迹治疗罩XT40型",
			["English"] = "Wonderheal XT40 Shades",
			["French"] = "Lunettes de soleil fabulosoin XT40",
			["German"] = "Wunderheilbinokel XT40",
			["Korean"] = "기적의 치유 색안경 XT40",
			["Mexican"] = "Gafas de sol curamaravilla XT40",
			["Portuguese"] = "Óculos da Maravilha Curativa XT40",
			["Russian"] = "Исцеляющий рассеиватель теней XT40",
			["Spanish"] = "Gafas de sol curamaravilla XT40",
			["Taiwanese"] = "驚奇XT40護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41319,
		["item_id"] = 32480,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "月光放大护目镜",
			["English"] = "Magnified Moon Specs",
			["French"] = "Bésicles lunaires amplifiées",
			["German"] = "Mondlupenbrille",
			["Korean"] = "증폭된 달빛 반사경",
			["Mexican"] = "Gafas de la luna de amplificación",
			["Portuguese"] = "Lunóculos de Aumento",
			["Russian"] = "Увеличивающие лунные очки",
			["Spanish"] = "Gafas de la luna de amplificación",
			["Taiwanese"] = "放大月光護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41320,
		["item_id"] = 32494,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "毁灭全视护目镜",
			["English"] = "Destruction Holo-gogs",
			["French"] = "Holo-binocles de destruction",
			["German"] = "Holobrille der Zerstörung",
			["Korean"] = "파괴의 홀로그램 고글",
			["Mexican"] = "Gafas holográficas de destrucción",
			["Portuguese"] = "Holóculos da Destruição",
			["Russian"] = "Голографические очки уничтожения",
			["Spanish"] = "Gafas holográficas de destrucción",
			["Taiwanese"] = "毀滅護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 41321,
		["item_id"] = 32495,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "超级治疗射线4000型",
			["English"] = "Powerheal 4000 Lens",
			["French"] = "Lentille fulgurosoin 4000",
			["German"] = "Superheillinse 4000",
			["Korean"] = "강력한 치유 렌즈 4000",
			["Mexican"] = "Lente de supersanación 4000",
			["Portuguese"] = "Lentes de Supercura 4000",
			["Russian"] = "Линза могущественного целителя-4000",
			["Spanish"] = "Lente de supersanación 4000",
			["Taiwanese"] = "能量4000護目鏡",
		},
		["phase"] = 3,
		["trainers"] = {
			["price"] = 0,
			["sources"] = {
				17634,
				17637,
				18752,
				18775,
				19576,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 44155,
		["item_id"] = 34060,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "飞行器",
			["English"] = "Flying Machine",
			["French"] = "Machine volante",
			["German"] = "Flugmaschine",
			["Korean"] = "비행기",
			["Mexican"] = "Máquina voladora",
			["Portuguese"] = "Máquina Voadora",
			["Russian"] = "Ветролет",
			["Spanish"] = "Máquina voladora",
			["Taiwanese"] = "飛行器",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 120000,
			["sources"] = {
				24868,
				25099,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 44157,
		["item_id"] = 34061,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "涡轮加速飞行器",
			["English"] = "Turbo-Charged Flying Machine",
			["French"] = "Machine volante à turbo-injection",
			["German"] = "Turbogetriebene Flugmaschine",
			["Korean"] = "터보 충전 비행기",
			["Mexican"] = "Máquina voladora turboalimentada",
			["Portuguese"] = "Máquina Voadora Turbocarregada",
			["Russian"] = "Турбоветролет",
			["Spanish"] = "Máquina voladora turboalimentada",
			["Taiwanese"] = "渦輪飛行器",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 180000,
			["sources"] = {
				24868,
				25099,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 44391,
		["item_id"] = 34113,
		["items"] = {
			34114,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "战地修理机器人110G",
			["English"] = "Field Repair Bot 110G",
			["French"] = "Robot réparateur 110G",
			["German"] = "Feldreparaturbot 110G",
			["Korean"] = "야전수리로봇 110G",
			["Mexican"] = "Robot de reparación de campo 110G",
			["Portuguese"] = "Robô de Reparos em Campo 110G",
			["Russian"] = "Полевой ремонтный робот 110G",
			["Spanish"] = "Robot de reparación de campo 110G",
			["Taiwanese"] = "修理機器人110G型",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 46106,
		["item_id"] = 35183,
		["items"] = {
			35191,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "奇迹治疗罩XT68型",
			["English"] = "Wonderheal XT68 Shades",
			["French"] = "Lunettes de soleil fabulosoin XT68",
			["German"] = "Wunderheilbinokel XT68",
			["Korean"] = "기적의 치유 색안경 XT68",
			["Mexican"] = "Gafas de sol curamaravilla XT68",
			["Portuguese"] = "Óculos da Maravilha Curativa XT68",
			["Russian"] = "Исцеляющий рассеиватель теней XT68",
			["Spanish"] = "Gafas de sol curamaravilla XT68",
			["Taiwanese"] = "奇跡治癒XT68遮光鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46107,
		["item_id"] = 35185,
		["items"] = {
			35187,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "审判者护目镜3000型",
			["English"] = "Justicebringer 3000 Specs",
			["French"] = "Bésicles Porte-justice 3000",
			["German"] = "Gerechtomatbrille 3000",
			["Korean"] = "정의의 수호 반사경 3000",
			["Mexican"] = "Gafas de la Justiciera 3000",
			["Portuguese"] = "Lentes Justiceiras 3000",
			["Russian"] = "Очки \"Воздаятель-3000\"",
			["Spanish"] = "Gafas de la Justiciera 3000",
			["Taiwanese"] = "正義使者3000眼鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46108,
		["item_id"] = 35181,
		["items"] = {
			35189,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "超级治疗射线9000型",
			["English"] = "Powerheal 9000 Lens",
			["French"] = "Lentilles fulgurosoin 9000",
			["German"] = "Superheillinse 9000",
			["Korean"] = "강력한 치유 렌즈 9000",
			["Mexican"] = "Lente de supersanación 9000",
			["Portuguese"] = "Lentes de Supercura 9000",
			["Russian"] = "Линза могущественного целителя-9000",
			["Spanish"] = "Lente de supersanación 9000",
			["Taiwanese"] = "能量治癒9000鏡片",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46109,
		["item_id"] = 35182,
		["items"] = {
			35190,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "超级月光放大护目镜",
			["English"] = "Hyper-Magnified Moon Specs",
			["French"] = "Bésicles lunaires hyper-amplifiées",
			["German"] = "Mondmikroskopbrille",
			["Korean"] = "고도로 증폭된 달빛 반사경",
			["Mexican"] = "Gafas de la luna de hiperamplificación",
			["Portuguese"] = "Lunóculos de Hiper-aumento",
			["Russian"] = "Гиперувеличивающие лунные очки",
			["Spanish"] = "Gafas de la luna de hiperamplificación",
			["Taiwanese"] = "超放大月光眼鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46110,
		["item_id"] = 35184,
		["items"] = {
			35192,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "源生同频护目镜",
			["English"] = "Primal-Attuned Goggles",
			["French"] = "Lunettes d'harmonisation primordiale",
			["German"] = "Urgestimmte Brille",
			["Korean"] = "원소 조화의 고글",
			["Mexican"] = "Gafas armonizadas con lo primigenio",
			["Portuguese"] = "Óculos Primajustados",
			["Russian"] = "Очки изначальной гармонии",
			["Spanish"] = "Gafas armonizadas con lo primigenio",
			["Taiwanese"] = "原始調和護目鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46111,
		["item_id"] = 34847,
		["items"] = {
			35186,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "湮灭全视护目镜",
			["English"] = "Annihilator Holo-Gogs",
			["French"] = "Holo-binocles d'annihilateur",
			["German"] = "Holobrille des Vernichters",
			["Korean"] = "파멸의 홀로그램 고글",
			["Mexican"] = "Hologafas de aniquilador",
			["Portuguese"] = "Holóculos do Aniquilador",
			["Russian"] = "Голографические очки аннигиляции",
			["Spanish"] = "Hologafas de aniquilador",
			["Taiwanese"] = "殲滅者環視鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46112,
		["item_id"] = 34355,
		["items"] = {
			35193,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "闪电蚀刻护目镜",
			["English"] = "Lightning Etched Specs",
			["French"] = "Bésicles gravées aux éclairs",
			["German"] = "Blitzgeätzte Brille",
			["Korean"] = "번개 깃든 반사경",
			["Mexican"] = "Gafas con grabados de relámpagos",
			["Portuguese"] = "Óculos Cinzelados com Raios",
			["Russian"] = "Иссеченные молниями очки",
			["Spanish"] = "Gafas de grabados de relámpagos",
			["Taiwanese"] = "閃電蝕刻眼鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46113,
		["item_id"] = 34356,
		["items"] = {
			35194,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "必中护目镜V3.0",
			["English"] = "Surestrike Goggles v3.0",
			["French"] = "Lunettes vise-juste v3.0",
			["German"] = "Volltrefferbrille v3.0",
			["Korean"] = "일격보증 고글 v3.0",
			["Mexican"] = "Gafas de golpe seguro v3.0",
			["Portuguese"] = "Óculos Golpe-certeiro v3.0",
			["Russian"] = "Очки верного удара модель 3.0",
			["Spanish"] = "Gafas de golpe seguro v3.0",
			["Taiwanese"] = "絕對打擊護目鏡v3.0",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46114,
		["item_id"] = 34354,
		["items"] = {
			35195,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "伤害投射护目镜",
			["English"] = "Mayhem Projection Goggles",
			["French"] = "Lunettes de projection de désordre",
			["German"] = "Chaosprognosebrille",
			["Korean"] = "파괴력 투영 고글",
			["Mexican"] = "Gafas de proyección de caos",
			["Portuguese"] = "Lentes de Projeção da Desordem",
			["Russian"] = "Проекционные очки резни",
			["Spanish"] = "Gafas de proyección de caos",
			["Taiwanese"] = "暴行投影護目鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46115,
		["item_id"] = 34357,
		["items"] = {
			35196,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "硬化氪金护目镜",
			["English"] = "Hard Khorium Goggles",
			["French"] = "Lunettes en khorium durci",
			["German"] = "Brille aus Hartkhorium",
			["Korean"] = "단단한 코륨 고글",
			["Mexican"] = "Gafas de korio duro",
			["Portuguese"] = "Óculos de Kório Duro",
			["Russian"] = "Очки из закаленного кория",
			["Spanish"] = "Gafas de korio duro",
			["Taiwanese"] = "特硬克銀護目鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46116,
		["item_id"] = 34353,
		["items"] = {
			35197,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "四核死亡一击护目镜X44型",
			["English"] = "Quad Deathblow X44 Goggles",
			["French"] = "Quadrilunettes coup-de-grâce X44",
			["German"] = "Vieltotmacherbrille X44",
			["Korean"] = "사중 죽음의 고글 X44",
			["Mexican"] = "Gafas de arremetida mortal cuádruple X44",
			["Portuguese"] = "Óculos Quad Golpe Mortal X44",
			["Russian"] = "Очки квадрисмертельного удара X44",
			["Spanish"] = "Gafas de arremetida mortal cuádruple X44",
			["Taiwanese"] = "四倍死亡打擊X44護目鏡",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46697,
		["item_id"] = 35581,
		["items"] = {
			35582,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "轻便型超级火箭靴",
			["English"] = "Rocket Boots Xtreme Lite",
			["French"] = "Bottes-fusées extrêmes légères",
			["German"] = "Raktenstiefel Xtrem-Lite",
			["Korean"] = "가벼운 극한의 로켓 장화",
			["Mexican"] = "Botas cohete Xtremo ligeras",
			["Portuguese"] = "Botas-foguete Xtremas Lite",
			["Russian"] = "Облегченные экстремальные реактивные сапоги",
			["Spanish"] = "Botas cohete Xtremo ligeras",
			["Taiwanese"] = "輕巧型火箭靴極限版",
		},
		["phase"] = 1,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Engineering"], skill)
end
