-------------------------------------------------------
-- All items (Enchanting) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Enchanting"] then RR_DATA["items"]["Enchanting"] = {} end
local tbc_items = 
{
	{
		["drops"] = {
			["sources"] = {
				22822,
			},
		},
		["expansion"] = 2,
		["id"] = 22530,
		["name"] = {
			["Chinese"] = "公式：附魔护腕 - 特效防御",
			["English"] = "Formula: Enchant Bracer - Major Defense",
			["French"] = "Formule : Enchantement de brassard (Défense majeure)",
			["German"] = "Formel: Armschiene - Erhebliche Verteidigung",
			["Korean"] = "주문식: 손목보호구 마법부여 - 상급 방어 숙련",
			["Mexican"] = "Fórmula: encantar brazal: defensa sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Defesa - Braçadeiras",
			["Russian"] = "Формула чар для наручей: защита",
			["Spanish"] = "Fórmula: encantar brazal: defensa sublime",
			["Taiwanese"] = "公式:附魔護腕 - 極效防禦",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22531,
		["name"] = {
			["Chinese"] = "公式：附魔护腕 - 超强治疗",
			["English"] = "Formula: Enchant Bracer - Superior Healing",
			["French"] = "Formule : Enchantement de brassards (Soins excellents)",
			["German"] = "Formel: Armschiene - Überragende Heilung",
			["Korean"] = "주문식: 손목보호구 마법부여 - 상급 치유 마법 강화",
			["Mexican"] = "Fórmula: encantar brazales: sanación excelente",
			["Portuguese"] = "Fórmula: Encantamento Superior de Cura - Braçadeiras",
			["Russian"] = "Формула чар для наручей - лечение II",
			["Spanish"] = "Fórmula: encantar brazal: sanación excelente",
			["Taiwanese"] = "公式:附魔護腕 - 超強治療",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22532,
		["name"] = {
			["Chinese"] = "公式：附魔护腕 - 原始法力回复",
			["English"] = "Formula: Enchant Bracer - Restore Mana Prime",
			["French"] = "Formule : Enchantement de brassards (Restauration du mana premier)",
			["German"] = "Formel: Armschiene - Mana wiederherstellen",
			["Korean"] = "주문식: 손목보호구 마법부여 - 상급 마나 회복",
			["Mexican"] = "Fórmula: encantar brazales: restaurar maná de primera",
			["Portuguese"] = "Fórmula: Encantamento de Restauração Primária de Mana - Braçadeiras",
			["Russian"] = "Формула чар для наручей: восполнение маны",
			["Spanish"] = "Fórmula: encantar brazal: restaurar maná de primera",
			["Taiwanese"] = "公式:附魔護腕 - 基礎法力恢復",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				17803,
			},
		},
		["expansion"] = 2,
		["id"] = 22533,
		["name"] = {
			["Chinese"] = "公式：附魔护腕 - 坚韧",
			["English"] = "Formula: Enchant Bracer - Fortitude",
			["French"] = "Formule : Enchantement de brassard (Robustesse)",
			["German"] = "Formel: Armschiene - Seelenstärke",
			["Korean"] = "주문식: 손목보호구 마법부여 - 인내",
			["Mexican"] = "Fórmula: encantar brazales: entereza",
			["Portuguese"] = "Fórmula: Encantamento de Fortitude - Braçadeira",
			["Russian"] = "Формула чар для наручей - стойкость",
			["Spanish"] = "Fórmula: encantar brazal: entereza",
			["Taiwanese"] = "公式:附魔護腕 - 堅韌",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				19552,
			},
		},
		["expansion"] = 2,
		["id"] = 22534,
		["name"] = {
			["Chinese"] = "公式：附魔护腕 - 法术能量",
			["English"] = "Formula: Enchant Bracer - Spellpower",
			["French"] = "Formule : Enchantement de brassards (Puissance des sorts)",
			["German"] = "Formel: Armschiene - Zaubermacht",
			["Korean"] = "주문식: 손목보호구 마법부여 - 주문 강화",
			["Mexican"] = "Fórmula: encantar brazales: poder con hechizos",
			["Portuguese"] = "Fórmula: Encantamento de Poder Mágico - Braçadeiras",
			["Russian"] = "Формула чар для наручей - сила заклинаний I",
			["Spanish"] = "Fórmula: encantar brazal: poder con hechizos",
			["Taiwanese"] = "公式:附魔護腕 - 法術能量",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22535,
		["name"] = {
			["Chinese"] = "公式：附魔戒指 - 打击",
			["English"] = "Formula: Enchant Ring - Striking",
			["French"] = "Formule : Enchantement d'anneau (Frappe)",
			["German"] = "Formel: Ring - Schlagen",
			["Korean"] = "주문식: 반지 마법부여 - 공격력",
			["Mexican"] = "Fórmula: encantar anillo: golpear",
			["Portuguese"] = "Fórmula: Encantamento de Ataque - Anel",
			["Russian"] = "Формула чар для кольца - удар",
			["Spanish"] = "Fórmula: encantar anillo: golpear",
			["Taiwanese"] = "公式:附魔戒指 - 打擊",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				17518,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22536,
		["name"] = {
			["Chinese"] = "公式：附魔戒指 - 法术能量",
			["English"] = "Formula: Enchant Ring - Spellpower",
			["French"] = "Formule : Enchantement d'anneau (Puissance des sorts)",
			["German"] = "Formel: Ring - Zaubermacht",
			["Korean"] = "주문식: 반지 마법부여 - 주문 강화",
			["Mexican"] = "Fórmula: encantar anillo: poder con hechizos",
			["Portuguese"] = "Fórmula: Encantamento de Poder Mágico - Anel",
			["Russian"] = "Формула чар для кольца: сила заклинаний I",
			["Spanish"] = "Fórmula: encantar anillo: poder con hechizos",
			["Taiwanese"] = "公式:附魔戒指 - 法術能量",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 989,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				21643,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22537,
		["name"] = {
			["Chinese"] = "公式：附魔戒指 - 治疗能量",
			["English"] = "Formula: Enchant Ring - Healing Power",
			["French"] = "Formule : Enchantement d'anneau (Pouvoir de guérison)",
			["German"] = "Formel: Ring - Heilkraft",
			["Korean"] = "주문식: 반지 마법부여 - 치유 마법 강화",
			["Mexican"] = "Fórmula: encantar anillo: poder de sanación",
			["Portuguese"] = "Fórmula: Encantamento de Poder de Cura - Anel",
			["Russian"] = "Формула чар для кольца - целительная сила",
			["Spanish"] = "Fórmula: encantar anillo: poder de sanación",
			["Taiwanese"] = "公式:附魔戒指 - 治療能量",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22538,
		["name"] = {
			["Chinese"] = "公式：附魔戒指 - 属性",
			["English"] = "Formula: Enchant Ring - Stats",
			["French"] = "Formule : Enchantement d'anneau (Caractéristiques)",
			["German"] = "Formel: Ring - Werte",
			["Korean"] = "주문식: 반지 마법부여 - 능력치",
			["Mexican"] = "Fórmula: encantar anillo: estadísticas",
			["Portuguese"] = "Fórmula: Encantamento de Atributos - Anel",
			["Russian"] = "Формула чар для кольца: все характеристики",
			["Spanish"] = "Fórmula: encantar anillo: estadísticas",
			["Taiwanese"] = "公式:附魔戒指 - 屬性",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 1011,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 200000,
			["sources"] = {
				21655,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22539,
		["name"] = {
			["Chinese"] = "公式：附魔盾牌 - 智力",
			["English"] = "Formula: Enchant Shield - Intellect",
			["French"] = "Formule : Enchantement de bouclier (Intelligence)",
			["German"] = "Formel: Schild - Intelligenz",
			["Korean"] = "주문식: 방패 마법부여 - 지능",
			["Mexican"] = "Fórmula: encantar escudo: intelecto",
			["Portuguese"] = "Fórmula: Encantamento de Intelecto - Escudo",
			["Russian"] = "Формула чар для щита - интеллект I",
			["Spanish"] = "Fórmula: encantar escudo: intelecto",
			["Taiwanese"] = "公式:附魔盾牌 - 智力",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				18664,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22540,
		["name"] = {
			["Chinese"] = "公式：附魔盾牌 - 盾牌格档",
			["English"] = "Formula: Enchant Shield - Shield Block",
			["French"] = "Formule : Enchantement de bouclier (Maîtrise du blocage)",
			["German"] = "Formel: Schild - Schildblock",
			["Korean"] = "주문식: 방패 마법부여 - 방패 막기 향상",
			["Mexican"] = "Fórmula: encantar escudo: bloquear con escudo",
			["Portuguese"] = "Fórmula: Encantamento de Bloqueio - Escudo",
			["Russian"] = "Формула чар для щита: блок II",
			["Spanish"] = "Fórmula: encantar escudo: bloquear con escudo",
			["Taiwanese"] = "公式:附魔盾牌 - 盾牌格擋",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22541,
		["name"] = {
			["Chinese"] = "公式：附魔盾牌 - 抗性",
			["English"] = "Formula: Enchant Shield - Resistance",
			["French"] = "Formule : Enchantement de bouclier (Résistance)",
			["German"] = "Formel: Schild - Widerstand",
			["Korean"] = "주문식: 방패 마법부여 - 저항력",
			["Mexican"] = "Fórmula: encantar escudo: resistencia",
			["Portuguese"] = "Fórmula: Encantamento de Resistência - Escudo",
			["Russian"] = "Формула чар для щита: сопротивление",
			["Spanish"] = "Fórmula: encantar escudo: resistencia",
			["Taiwanese"] = "公式:附魔盾牌 - 抗性",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22542,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 活力",
			["English"] = "Formula: Enchant Boots - Vitality",
			["French"] = "Formule : Enchantement de bottes (Vitalité)",
			["German"] = "Formel: Stiefel - Vitalität",
			["Korean"] = "주문식: 장화 마법부여 - 활력",
			["Mexican"] = "Fórmula: encantar botas: vitalidad",
			["Portuguese"] = "Fórmula: Encantamento de Vitalidade - Botas",
			["Russian"] = "Формула чар для обуви - живучесть I",
			["Spanish"] = "Fórmula: encantar botas: vitalidad",
			["Taiwanese"] = "公式:附魔靴子 - 活力",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				18317,
			},
		},
		["expansion"] = 2,
		["id"] = 22543,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 坚韧",
			["English"] = "Formula: Enchant Boots - Fortitude",
			["French"] = "Formule : Enchantement de bottes (Robustesse)",
			["German"] = "Formel: Stiefel - Seelenstärke",
			["Korean"] = "주문식: 장화 마법부여 - 인내",
			["Mexican"] = "Fórmula: encantar botas: entereza",
			["Portuguese"] = "Fórmula: Encantamento de Fortitude - Botas",
			["Russian"] = "Формула чар для обуви - стойкость I",
			["Spanish"] = "Fórmula: encantar botas: entereza",
			["Taiwanese"] = "公式:附魔靴子 - 堅韌",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				18521,
			},
		},
		["expansion"] = 2,
		["id"] = 22544,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 灵敏",
			["English"] = "Formula: Enchant Boots - Dexterity",
			["French"] = "Formule : Enchantement de bottes (Dexterité)",
			["German"] = "Formel: Stiefel - Gewandtheit",
			["Korean"] = "주문식: 장화 마법부여 - 기민함",
			["Mexican"] = "Fórmula: encantar botas: maña",
			["Portuguese"] = "Fórmula: Encantamento de Destreza - Botas",
			["Russian"] = "Формула чар для обуви - стремительность",
			["Spanish"] = "Fórmula: encantar botas: maña",
			["Taiwanese"] = "公式:附魔靴子 - 靈巧",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				16472,
			},
		},
		["expansion"] = 2,
		["id"] = 22545,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 稳固",
			["English"] = "Formula: Enchant Boots - Surefooted",
			["French"] = "Formule : Enchantement de bottes (Pied sûr)",
			["German"] = "Formel: Stiefel - Sicherer Stand",
			["Korean"] = "주문식: 장화 마법부여 - 침착함",
			["Mexican"] = "Fórmula: encantar botas: Pies de plomo",
			["Portuguese"] = "Fórmula: Encantamento de Firmeza - Botas",
			["Russian"] = "Формула чар для обуви - верный шаг",
			["Spanish"] = "Fórmula: encantar botas: Pies de plomo",
			["Taiwanese"] = "公式:附魔靴子 - 穩固",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22547,
		["name"] = {
			["Chinese"] = "公式：附魔胸甲 - 优异属性",
			["English"] = "Formula: Enchant Chest - Exceptional Stats",
			["French"] = "Formule : Enchantement de plastron (Caractéristiques exceptionelles)",
			["German"] = "Formel: Brust - Außergewöhnliche Werte",
			["Korean"] = "주문식: 가슴보호구 마법부여 - 특급 능력치",
			["Mexican"] = "Fórmula: encantar pechera: estadísticas excepcionales",
			["Portuguese"] = "Fórmula: Encantamento Excepcional de Atributos - Torso",
			["Russian"] = "Формула чар для нагрудника - все характеристики V",
			["Spanish"] = "Fórmula: encantar pechera: estadísticas excepcionales",
			["Taiwanese"] = "公式:附魔胸甲 - 特殊屬性",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22548,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 特效抗性",
			["English"] = "Formula: Enchant Cloak - Major Resistance",
			["French"] = "Formule : Enchantement de cape (Résistance majeure)",
			["German"] = "Formel: Umhang - Erheblicher Widerstand",
			["Korean"] = "주문식: 망토 마법부여 - 상급 저항력",
			["Mexican"] = "Fórmula: encantar capa: resistencia sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Resistência - Manto",
			["Russian"] = "Формула чар для плаща: сопротивление IV",
			["Spanish"] = "Fórmula: encantar capa: resistencia sublime",
			["Taiwanese"] = "公式:附魔披風 - 極效抗性",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				20136,
			},
		},
		["expansion"] = 2,
		["id"] = 22551,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 特效智力",
			["English"] = "Formula: Enchant Weapon - Major Intellect",
			["French"] = "Formule : Enchantement d'arme (Intelligence majeure)",
			["German"] = "Formel: Waffe - Erhebliche Intelligenz",
			["Korean"] = "주문식: 무기 마법부여 - 일급 지능",
			["Mexican"] = "Fórmula: encantar arma: intelecto sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Intelecto - Arma",
			["Russian"] = "Формула чар для оружия - интеллект II",
			["Spanish"] = "Fórmula: encantar arma: intelecto sublime",
			["Taiwanese"] = "公式:附魔武器 - 極效智力",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 22552,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 特效打击",
			["English"] = "Formula: Enchant Weapon - Major Striking",
			["French"] = "Formule : Enchantement d'arme (Frappe majeure)",
			["German"] = "Formel: Waffe - Erhebliches Schlagen",
			["Korean"] = "주문식: 무기 마법부여 - 일급 공격력",
			["Mexican"] = "Fórmula: encantar arma: golpear sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Ataque - Arma",
			["Russian"] = "Формула чар для оружия - удар VI",
			["Spanish"] = "Fórmula: encantar arma: golpear sublime",
			["Taiwanese"] = "公式:附魔武器 - 極效打擊",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22553,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 潜能",
			["English"] = "Formula: Enchant Weapon - Potency",
			["French"] = "Formule : Enchantement d'arme (Toute-puissance)",
			["German"] = "Formel: Waffe - Potenz",
			["Korean"] = "주문식: 무기 마법부여 - 근력",
			["Mexican"] = "Fórmula: encantar arma: potencia",
			["Portuguese"] = "Fórmula: Encantamento de Potência - Arma",
			["Russian"] = "Формула чар для оружия - могущество I",
			["Spanish"] = "Fórmula: encantar arma: potencia",
			["Taiwanese"] = "公式:附魔武器 - 潛能",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				17465,
			},
		},
		["expansion"] = 2,
		["id"] = 22554,
		["name"] = {
			["Chinese"] = "公式：附魔双手武器 - 野蛮",
			["English"] = "Formula: Enchant 2H Weapon - Savagery",
			["French"] = "Formule : Enchantement d'arme 2M (Sauvagerie)",
			["German"] = "Formel: Zweihandwaffe - Unbändigkeit",
			["Korean"] = "주문식: 양손 무기 마법부여 - 전투력",
			["Mexican"] = "Fórmula: encantar arma 2M: Salvajismo",
			["Portuguese"] = "Fórmula: Encantamento de Selvageria - Arma de 2M",
			["Russian"] = "Формула чар для двуручного оружия - свирепость",
			["Spanish"] = "Fórmula: encantar arma 2M: Salvajismo",
			["Taiwanese"] = "公式:附魔雙手武器 - 兇蠻",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				22242,
				22243,
			},
		},
		["expansion"] = 2,
		["id"] = 22555,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 特效法术能量",
			["English"] = "Formula: Enchant Weapon - Major Spellpower",
			["French"] = "Formule : Enchantement d'arme (Puissance des sorts majeure)",
			["German"] = "Formel: Waffe - Erhebliche Zaubermacht",
			["Korean"] = "주문식: 무기 마법부여 - 상급 주문 강화",
			["Mexican"] = "Fórmula: encantar arma: poder con hechizos sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Poder Mágico - Arma",
			["Russian"] = "Формула чар для оружия - сила заклинаний II",
			["Spanish"] = "Fórmula: encantar arma: poder con hechizos sublime",
			["Taiwanese"] = "公式:附魔武器 - 極效法術能量",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				20880,
			},
		},
		["expansion"] = 2,
		["id"] = 22556,
		["name"] = {
			["Chinese"] = "公式：附魔双手武器 - 特效敏捷",
			["English"] = "Formula: Enchant 2H Weapon - Major Agility",
			["French"] = "Formule : Enchantement d'arme 2M (Agilité majeure)",
			["German"] = "Formel: Zweihandwaffe - Erhebliche Beweglichkeit",
			["Korean"] = "주문식: 양손 무기 마법부여 - 일급 민첩성",
			["Mexican"] = "Fórmula: encantar arma 2M: agilidad sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Agilidade - Arma de 2M",
			["Russian"] = "Формула чар для двуручного оружия - ловкость II",
			["Spanish"] = "Fórmula: encantar arma 2M: agilidad sublime",
			["Taiwanese"] = "公式:附魔雙手武器 - 極效敏捷",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22557,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 作战专家",
			["English"] = "Formula: Enchant Weapon - Battlemaster",
			["French"] = "Formule : Enchantement d'arme (Maître de guerre)",
			["German"] = "Formel: Waffe - Meister des Kampfes",
			["Korean"] = "주문식: 무기 마법부여 - 전투의 대가",
			["Mexican"] = "Fórmula: encantar arma: maestro de batalla",
			["Portuguese"] = "Fórmula: Encantamento de Mestre de Batalha - Arma",
			["Russian"] = "Формула чар для оружия - военачальник",
			["Spanish"] = "Fórmula: encantar arma: maestro de batalla",
			["Taiwanese"] = "公式:附魔武器 - 戰鬥大師",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 22558,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 魔法激荡",
			["English"] = "Formula: Enchant Weapon - Spellsurge",
			["French"] = "Formule : Enchantement d'arme (Eruption de sort)",
			["German"] = "Formel: Waffe - Zauberflut",
			["Korean"] = "주문식: 무기 마법부여 - 마력의 폭풍",
			["Mexican"] = "Fórmula: encantar arma: oleada de hechizos",
			["Portuguese"] = "Fórmula: Encantamento de Surto de Feitiço - Arma",
			["Russian"] = "Формула чар для оружия - всплеск чар",
			["Spanish"] = "Fórmula: encantar arma: oleada de hechizos",
			["Taiwanese"] = "公式:附魔武器 - 法力回流",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				15687,
			},
		},
		["expansion"] = 2,
		["id"] = 22559,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 猫鼬",
			["English"] = "Formula: Enchant Weapon - Mongoose",
			["French"] = "Formule : Enchantement d'arme (Mangouste)",
			["German"] = "Formel: Waffe - Mungo",
			["Korean"] = "주문식: 무기 마법부여 - 살쾡이",
			["Mexican"] = "Fórmula: encantar arma: mangosta",
			["Portuguese"] = "Fórmula: Encantamento de Mangusto - Arma",
			["Russian"] = "Формула чар для оружия - мангуст",
			["Spanish"] = "Fórmula: encantar arma: mangosta",
			["Taiwanese"] = "公式:附魔武器 - 貓鼬",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				16524,
			},
		},
		["expansion"] = 2,
		["id"] = 22560,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 阳炎",
			["English"] = "Formula: Enchant Weapon - Sunfire",
			["French"] = "Formule : Enchantement d'arme (Feu solaire)",
			["German"] = "Formel: Waffe - Sonnenfeuer",
			["Korean"] = "주문식: 무기 마법부여 - 태양의 불꽃",
			["Mexican"] = "Fórmula: encantar arma: Fuego solar",
			["Portuguese"] = "Fórmula: Encantamento de Fogo Solar - Arma",
			["Russian"] = "Формула чар для оружия - солнечный огонь",
			["Spanish"] = "Fórmula: encantar arma: Fuego Solar",
			["Taiwanese"] = "公式:附魔武器 - 烈日火焰",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				15688,
			},
		},
		["expansion"] = 2,
		["id"] = 22561,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 魂霜",
			["English"] = "Formula: Enchant Weapon - Soulfrost",
			["French"] = "Formule : Enchantement d'arme (Âme de givre)",
			["German"] = "Formel: Waffe - Seelenfrost",
			["Korean"] = "주문식: 무기 마법부여 - 냉기의 영혼",
			["Mexican"] = "Fórmula: encantar arma: escarcha de alma",
			["Portuguese"] = "Fórmula: Encantamento de Congelar Alma - Arma",
			["Russian"] = "Формула чар для оружия - ледяная душа",
			["Spanish"] = "Fórmula: encantar arma: escarcha de alma",
			["Taiwanese"] = "公式:附魔武器 - 靈魂冰霜",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 22562,
		["name"] = {
			["Chinese"] = "公式：超级法力之油",
			["English"] = "Formula: Superior Mana Oil",
			["French"] = "Formule : Huile de mana excellente",
			["German"] = "Formel: Überragendes Manaöl",
			["Korean"] = "주문식: 최고급 마나 오일",
			["Mexican"] = "Fórmula: aceite de maná excelente",
			["Portuguese"] = "Fórmula: Óleo Superior de Mana",
			["Russian"] = "Формула: превосходное масло маны",
			["Spanish"] = "Fórmula: aceite de maná excelente",
			["Taiwanese"] = "公式:超強法力之油",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 50000,
			["sources"] = {
				16635,
				16722,
				19663,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22563,
		["name"] = {
			["Chinese"] = "公式：超级巫师之油",
			["English"] = "Formula: Superior Wizard Oil",
			["French"] = "Formule : Huile de sorcier excellente",
			["German"] = "Formel: Überragendes Zauberöl",
			["Korean"] = "주문식: 최고급 마술사 오일",
			["Mexican"] = "Fórmula: aceite de zahorí excelente",
			["Portuguese"] = "Fórmula: Óleo Superior de Teurgo",
			["Russian"] = "Формула: превосходное волшебное масло",
			["Spanish"] = "Fórmula: aceite de zahorí excelente",
			["Taiwanese"] = "公式:超強巫師之油",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 70000,
			["sources"] = {
				16635,
				16722,
				19663,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 22565,
		["name"] = {
			["Chinese"] = "公式：大块棱光碎片",
			["English"] = "Formula: Large Prismatic Shard",
			["French"] = "Formule : Grand éclat prismatique",
			["German"] = "Formel: Großer Prismasplitter",
			["Korean"] = "주문식: 무지갯빛 큰 결정",
			["Mexican"] = "Fórmula: fragmento centelleante grande",
			["Portuguese"] = "Fórmula: Estilhaço Prismático Grande",
			["Russian"] = "Формула: большой радужный осколок",
			["Spanish"] = "Fórmula: fragmento centelleante grande",
			["Taiwanese"] = "公式:大塊稜石裂片",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				16635,
				16722,
				19663,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24000,
		["name"] = {
			["Chinese"] = "公式：附魔护腕 - 超级治疗",
			["English"] = "Formula: Enchant Bracer - Superior Healing",
			["French"] = "Formule : Enchantement de brassards (Soins excellents)",
			["German"] = "Formel: Armschiene - Überragende Heilung",
			["Korean"] = "주문식: 손목보호구 마법부여 - 상급 치유 마법 강화",
			["Mexican"] = "Fórmula: encantar brazales: sanación excelente",
			["Portuguese"] = "Fórmula: Encantamento Superior de Cura - Braçadeiras",
			["Russian"] = "Формула чар для наручей - лечение II",
			["Spanish"] = "Fórmula: encantar brazal: sanación excelente",
			["Taiwanese"] = "公式:附魔護腕 - 超強治療",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24003,
		["name"] = {
			["Chinese"] = "公式：附魔胸甲 - 优异属性",
			["English"] = "Formula: Enchant Chest - Exceptional Stats",
			["French"] = "Formule : Enchantement de plastron (Caractéristiques exceptionelles)",
			["German"] = "Formel: Brust - Außergewöhnliche Werte",
			["Korean"] = "주문식: 가슴보호구 마법부여 - 특급 능력치",
			["Mexican"] = "Fórmula: encantar pechera: estadísticas excepcionales",
			["Portuguese"] = "Fórmula: Encantamento Excepcional de Atributos - Torso",
			["Russian"] = "Формула чар для нагрудника - все характеристики V",
			["Spanish"] = "Fórmula: encantar pechera: estadísticas excepcionales",
			["Taiwanese"] = "公式:附魔胸甲 - 特殊屬性",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25848,
		["name"] = {
			["Chinese"] = "公式：符文精金棒",
			["English"] = "Formula: Runed Adamantite Rod",
			["French"] = "Formule : Bâtonnet runique en adamantite",
			["German"] = "Formel: Runenverzierte Adamantitrute",
			["Korean"] = "주문식: 룬문자 아다만타이트 마법막대",
			["Mexican"] = "Fórmula: vara rúnica de adamantita",
			["Portuguese"] = "Fórmula: Bastão Rúnico de Adamantita",
			["Russian"] = "Формула: рунический адамантитовый жезл",
			["Spanish"] = "Fórmula: vara rúnica de adamantita",
			["Taiwanese"] = "公式:符文堅鋼魔棒",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				18960,
				19004,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25849,
		["name"] = {
			["Chinese"] = "公式：符文恒金棒",
			["English"] = "Formula: Runed Eternium Rod",
			["French"] = "Formule : Bâtonnet runique en éternium",
			["German"] = "Formel: Runenverzierte Eterniumrute",
			["Korean"] = "주문식: 룬문자 이터늄 마법막대",
			["Mexican"] = "Fórmula: vara rúnica de eternio",
			["Portuguese"] = "Fórmula: Bastão Rúnico de Etérnio",
			["Russian"] = "Формула: рунический этерниевый жезл",
			["Spanish"] = "Fórmula: vara rúnica de eternio",
			["Taiwanese"] = "公式:符文恆金棒",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				19663,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 28270,
		["name"] = {
			["Chinese"] = "公式：附魔胸甲 - 特效韧性",
			["English"] = "Formula: Enchant Chest - Major Resilience",
			["French"] = "Formule : Enchantement de plastron (Résilience majeure)",
			["German"] = "Formel: Brust - Erhebliche Abhärtung",
			["Korean"] = "주문식: 가슴보호구 마법부여 - 일급 탄력성",
			["Mexican"] = "Fórmula: encantar pechera: temple sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Resiliência - Torso",
			["Russian"] = "Формула чар для нагрудника - устойчивость I",
			["Spanish"] = "Fórmula: encantar pechera: temple sublime",
			["Taiwanese"] = "公式:附魔胸甲 - 極效韌性",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 28271,
		["name"] = {
			["Chinese"] = "公式：附魔手套 - 法术打击",
			["English"] = "Formula: Enchant Gloves - Spell Strike",
			["French"] = "Formule : Enchantement de gants (Frappe-sort)",
			["German"] = "Formel: Handschuhe - Zauberschlag",
			["Korean"] = "주문식: 장갑 마법부여 - 주문 적중",
			["Mexican"] = "Fórmula: encantar guantes: golpe con hechizos",
			["Portuguese"] = "Fórmula: Encantamento de Ataque de Feitiço - Luvas",
			["Russian"] = "Формула чар для перчаток: удар заклинаний I",
			["Spanish"] = "Fórmula: encantar guantes: golpe con hechizos",
			["Taiwanese"] = "公式:附魔手套 - 法術打擊",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28272,
		["name"] = {
			["Chinese"] = "公式：附魔手套 - 特效法术能量",
			["English"] = "Formula: Enchant Gloves - Major Spellpower",
			["French"] = "Formule : Enchantement de gants (Puissance des sorts majeure)",
			["German"] = "Formel: Handschuhe - Erhebliche Zaubermacht",
			["Korean"] = "주문식: 장갑 마법부여 - 일급 주문 강화",
			["Mexican"] = "Fórmula: encantar guantes: poder con hechizos sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Poder Mágico - Luvas",
			["Russian"] = "Формула чар для перчаток - сила заклинаний I",
			["Spanish"] = "Fórmula: encantar guantes: poder con hechizos sublime",
			["Taiwanese"] = "公式:附魔手套 - 極效法術能量",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 989,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				21643,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28273,
		["name"] = {
			["Chinese"] = "公式：附魔手套 - 特效治疗",
			["English"] = "Formula: Enchant Gloves - Major Healing",
			["French"] = "Formule : Enchantement de gants (Soins majeurs)",
			["German"] = "Formel: Handschuhe - Erhebliche Heilung",
			["Korean"] = "주문식: 장갑 마법부여 - 일급 치유 마법 강화",
			["Mexican"] = "Fórmula: encantar guantes: sanación sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Cura - Luvas",
			["Russian"] = "Формула чар для перчаток - лечение I",
			["Spanish"] = "Fórmula: encantar guantes: sanación sublime",
			["Taiwanese"] = "公式:附魔手套 - 極效治療",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28274,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 法术穿透",
			["English"] = "Formula: Enchant Cloak - Spell Penetration",
			["French"] = "Formule : Enchantement de cape (Pénétration des sorts)",
			["German"] = "Formel: Umhang - Zauberdurchschlagskraft",
			["Korean"] = "주문식: 망토 마법부여 - 주문 관통력",
			["Mexican"] = "Fórmula: encantar capa: penetración de hechizos",
			["Portuguese"] = "Fórmula: Encantamento de Penetração de Feitiço - Manto",
			["Russian"] = "Формула чар для плаща: проникающая способность заклинаний",
			["Spanish"] = "Fórmula: encantar capa: penetración de hechizos",
			["Taiwanese"] = "公式:附魔披風 - 法術穿透",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				19796,
			},
		},
		["expansion"] = 2,
		["id"] = 28276,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 强效奥术抗性",
			["English"] = "Formula: Enchant Cloak - Greater Arcane Resistance",
			["French"] = "Formule : Enchantement de cape (Résistance aux arcanes supérieure)",
			["German"] = "Formel: Umhang - Großer Arkanwiderstand",
			["Korean"] = "주문식: 망토 마법부여 - 상급 비전 저항력",
			["Mexican"] = "Fórmula: encantar capa: resistencia a lo Arcano superior",
			["Portuguese"] = "Fórmula: Encantamento Maior de Resistência ao Arcano - Manto",
			["Russian"] = "Формула чар для плаща: сопротивление тайной магии I",
			["Spanish"] = "Fórmula: encantar capa: resistencia a lo Arcano superior",
			["Taiwanese"] = "公式:附魔披風 - 強效秘法抗性",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18870,
			},
		},
		["expansion"] = 2,
		["id"] = 28277,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 强效暗影抗性",
			["English"] = "Formula: Enchant Cloak - Greater Shadow Resistance",
			["French"] = "Formule : Enchantement de cape (Résistance à l'Ombre supérieure)",
			["German"] = "Formel: Umhang - Großer Schattenwiderstand",
			["Korean"] = "주문식: 망토 마법부여 - 상급 암흑 저항력",
			["Mexican"] = "Fórmula: encantar capa: resistencia a las Sombras superior",
			["Portuguese"] = "Fórmula: Encantamento Maior de Resistência à Sombra - Manto",
			["Russian"] = "Формула чар для плаща: сопротивление темной магии II",
			["Spanish"] = "Fórmula: encantar capa: resistencia a las Sombras superior",
			["Taiwanese"] = "公式:附魔披風 - 強效暗影抗性",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 28279,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 豹之迅捷",
			["English"] = "Formula: Enchant Boots - Cat's Swiftness",
			["French"] = "Formule : Enchantement de bottes (Rapidité du félin)",
			["German"] = "Formel: Stiefel - Schnelligkeit der Katze",
			["Korean"] = "주문식: 장화 마법부여 - 살쾡이의 날렵함",
			["Mexican"] = "Fórmula: encantar botas: presteza felina",
			["Portuguese"] = "Fórmula: Encantamento de Rapidez do Gato - Botas",
			["Russian"] = "Формула чар для обуви - проворство кошки",
			["Spanish"] = "Fórmula: encantar botas: presteza felina",
			["Taiwanese"] = "公式:附魔靴子 - 貓之迅捷",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 28280,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 野猪之速",
			["English"] = "Formula: Enchant Boots - Boar's Speed",
			["French"] = "Formule : Enchantement de bottes (Vitesse du sanglier)",
			["German"] = "Formel: Stiefel - Flinkheit des Ebers",
			["Korean"] = "주문식: 장화 마법부여 - 멧돼지의 속도",
			["Mexican"] = "Fórmula: encantar botas: velocidad de jabalí",
			["Portuguese"] = "Fórmula: Encantamento de Velocidade do Javali - Botas",
			["Russian"] = "Формула чар для обуви - быстрота вепря",
			["Spanish"] = "Fórmula: encantar botas: velocidad del jabalí",
			["Taiwanese"] = "公式:附魔靴子 - 野豬之速",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 28281,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 特效治疗",
			["English"] = "Formula: Enchant Weapon - Major Healing",
			["French"] = "Formule : Enchantement d'arme (Soins majeurs)",
			["German"] = "Formel: Waffe - Erhebliche Heilung",
			["Korean"] = "주문식: 무기 마법부여 - 일급 치유 마법 강화",
			["Mexican"] = "Fórmula: encantar arma: sanación sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Cura - Arma",
			["Russian"] = "Формула чар для оружия - лечение I",
			["Spanish"] = "Fórmula: encantar arma: sanación sublime",
			["Taiwanese"] = "公式:附魔武器 - 極效治療",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28282,
		["name"] = {
			["Chinese"] = "公式：附魔盾牌 - 特效耐力",
			["English"] = "Formula: Enchant Shield - Major Stamina",
			["French"] = "Formule : Enchantement de bouclier (Endurance majeure)",
			["German"] = "Formel: Schild - Erhebliche Ausdauer",
			["Korean"] = "주문식: 방패 마법부여 - 일급 체력",
			["Mexican"] = "Fórmula: encantar escudo: aguante sublime",
			["Portuguese"] = "Fórmula: Encantamento Elevado de Vigor - Escudo",
			["Russian"] = "Формула чар для щита - выносливость V",
			["Spanish"] = "Fórmula: encantar escudo: aguante sublime",
			["Taiwanese"] = "公式:附魔盾牌 - 極效耐力",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				19663,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33149,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 潜行",
			["English"] = "Formula: Enchant Cloak - Stealth",
			["French"] = "Formule : Enchantement de cape (Camouflage)",
			["German"] = "Formel: Umhang - Verstohlenheit",
			["Korean"] = "주문식: 망토 마법부여 - 은신",
			["Mexican"] = "Fórmula: encantar capa: sigilo",
			["Portuguese"] = "Fórmula: Encantamento de Furtividade - Manto",
			["Russian"] = "Формула чар для плаща: незаметность",
			["Spanish"] = "Fórmula: encantar capa: sigilo",
			["Taiwanese"] = "公式:附魔披風 - 潛行",
		},
		["phase"] = 2,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33150,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 狡诈",
			["English"] = "Formula: Enchant Cloak - Subtlety",
			["French"] = "Formule : Enchantement de cape (Discrétion)",
			["German"] = "Formel: Umhang - Feingefühl",
			["Korean"] = "주문식: 망토 마법부여 - 미묘함",
			["Mexican"] = "Fórmula: encantar capa: sutileza",
			["Portuguese"] = "Fórmula: Encantamento de Sutileza - Manto",
			["Russian"] = "Формула чар для плаща: скрытность",
			["Spanish"] = "Fórmula: encantar capa: sutileza",
			["Taiwanese"] = "公式:附魔披風 - 狡詐",
		},
		["phase"] = 2,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 90000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33151,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 狡诈",
			["English"] = "Formula: Enchant Cloak - Subtlety",
			["French"] = "Formule : Enchantement de cape (Discrétion)",
			["German"] = "Formel: Umhang - Feingefühl",
			["Korean"] = "주문식: 망토 마법부여 - 미묘함",
			["Mexican"] = "Fórmula: encantar capa: sutileza",
			["Portuguese"] = "Fórmula: Encantamento de Sutileza - Manto",
			["Russian"] = "Формула чар для плаща: скрытность",
			["Spanish"] = "Fórmula: encantar capa: sutileza",
			["Taiwanese"] = "公式:附魔披風 - 狡詐",
		},
		["phase"] = 2,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 90000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 1,
		["id"] = 33152,
		["name"] = {
			["Chinese"] = "公式：附魔手套 - 超强敏捷",
			["English"] = "Formula: Enchant Gloves - Superior Agility",
			["French"] = "Formule : Enchantement de gants (Agilité excellente)",
			["German"] = "Formel: Handschuhe - Überragende Beweglichkeit",
			["Korean"] = "주문식: 장갑 마법부여 - 최상급 민첩",
			["Mexican"] = "Fórmula: encantar guantes: agilidad excelente",
			["Portuguese"] = "Fórmula: Encantamento Superior de Agilidade - Luvas",
			["Russian"] = "Формула чар для перчаток: ловкость III",
			["Spanish"] = "Fórmula: encantar guantes: agilidad excelente",
			["Taiwanese"] = "公式:附魔手套 - 超強敏捷",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 989,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				21643,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33153,
		["name"] = {
			["Chinese"] = "公式：附魔手套 - 威胁",
			["English"] = "Formula: Enchant Gloves - Threat",
			["French"] = "Formule : Enchantement de gants (Menace)",
			["German"] = "Formel: Handschuhe - Bedrohung",
			["Korean"] = "주문식: 장갑 마법부여 - 위협",
			["Mexican"] = "Fórmula: encantar guantes: amenaza",
			["Portuguese"] = "Fórmula: Encantamento de Ameaça - Luvas",
			["Russian"] = "Формула чар для перчаток: угроза",
			["Spanish"] = "Fórmula: encantar guantes: amenaza",
			["Taiwanese"] = "公式:附魔手套 - 威脅",
		},
		["phase"] = 2,
		["quality"] = "rare",
		["reputation"] = {
			["faction_id"] = 935,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				21432,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33165,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 强效敏捷",
			["English"] = "Formula: Enchant Weapon - Greater Agility",
			["French"] = "Formule : Enchantement d'arme (Agilité supérieure)",
			["German"] = "Formel: Waffe - Große Beweglichkeit",
			["Korean"] = "주문식: 무기 마법부여 - 상급 민첩",
			["Mexican"] = "Fórmula: encantar arma: agilidad superior",
			["Portuguese"] = "Fórmula: Encantamento Maior de Agilidade - Arma",
			["Russian"] = "Формула чар для оружия - ловкость II",
			["Spanish"] = "Fórmula: encantar arma: agilidad superior",
			["Taiwanese"] = "公式:附魔武器 - 強效敏捷",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 967,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				18255,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				23574,
				23576,
				23577,
				23578,
				23863,
				24239,
			},
		},
		["expansion"] = 2,
		["id"] = 33307,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 斩杀",
			["English"] = "Formula: Enchant Weapon - Executioner",
			["French"] = "Formule : Enchantement d'arme (Exécutrice)",
			["German"] = "Formel: Waffe - Scharfrichter",
			["Korean"] = "주문식: 무기 마법부여 - 집행자",
			["Mexican"] = "Fórmula: encantar arma: verdugo",
			["Portuguese"] = "Fórmula: Encantamento de Carrasco - Arma",
			["Russian"] = "Формула чар для оружия - палач",
			["Spanish"] = "Fórmula: encantar arma: verdugo",
			["Taiwanese"] = "公式:附魔武器 - 處決者",
		},
		["phase"] = 4,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 34872,
		["name"] = {
			["Chinese"] = "公式：虚空碎裂",
			["English"] = "Formula: Void Shatter",
			["French"] = "Formule : Bris de vide",
			["German"] = "Formel: Brechung der Leere",
			["Korean"] = "주문식: 공허의 조각",
			["Mexican"] = "Fórmula: Fragmentar cristal de vacío",
			["Portuguese"] = "Fórmula: Ruptura do Caos",
			["Russian"] = "Формула: дробление кристалла Бездны",
			["Spanish"] = "Fórmula: Fragmentar cristal de vacío",
			["Taiwanese"] = "公式:粉碎虛無",
		},
		["phase"] = 5,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 150000,
			["sources"] = {
				25032,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35297,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 野猪之速",
			["English"] = "Formula: Enchant Boots - Boar's Speed",
			["French"] = "Formule : Enchantement de bottes (Vitesse du sanglier)",
			["German"] = "Formel: Stiefel - Flinkheit des Ebers",
			["Korean"] = "주문식: 장화 마법부여 - 멧돼지의 속도",
			["Mexican"] = "Fórmula: encantar botas: velocidad de jabalí",
			["Portuguese"] = "Fórmula: Encantamento de Velocidade do Javali - Botas",
			["Russian"] = "Формула чар для обуви - быстрота вепря",
			["Spanish"] = "Fórmula: encantar botas: velocidad del jabalí",
			["Taiwanese"] = "公式:附魔靴子 - 野豬之速",
		},
		["phase"] = 5,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35298,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 活力",
			["English"] = "Formula: Enchant Boots - Vitality",
			["French"] = "Formule : Enchantement de bottes (Vitalité)",
			["German"] = "Formel: Stiefel - Vitalität",
			["Korean"] = "주문식: 장화 마법부여 - 활력",
			["Mexican"] = "Fórmula: encantar botas: vitalidad",
			["Portuguese"] = "Fórmula: Encantamento de Vitalidade - Botas",
			["Russian"] = "Формула чар для обуви - живучесть I",
			["Spanish"] = "Fórmula: encantar botas: vitalidad",
			["Taiwanese"] = "公式:附魔靴子 - 活力",
		},
		["phase"] = 5,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35299,
		["name"] = {
			["Chinese"] = "公式：附魔靴子 - 豹之迅捷",
			["English"] = "Formula: Enchant Boots - Cat's Swiftness",
			["French"] = "Formule : Enchantement de bottes (Rapidité du félin)",
			["German"] = "Formel: Stiefel - Schnelligkeit der Katze",
			["Korean"] = "주문식: 장화 마법부여 - 살쾡이의 날렵함",
			["Mexican"] = "Fórmula: encantar botas: presteza felina",
			["Portuguese"] = "Fórmula: Encantamento de Rapidez do Gato - Botas",
			["Russian"] = "Формула чар для обуви - проворство кошки",
			["Spanish"] = "Fórmula: encantar botas: presteza felina",
			["Taiwanese"] = "公式:附魔靴子 - 貓之迅捷",
		},
		["phase"] = 5,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				25740,
			},
		},
		["expansion"] = 2,
		["id"] = 35498,
		["name"] = {
			["Chinese"] = "公式：附魔武器 - 死亡霜冻",
			["English"] = "Formula: Enchant Weapon - Deathfrost",
			["French"] = "Formule : Enchantement d'arme (Givre mortel)",
			["German"] = "Formel: Waffe - Todeskälte",
			["Korean"] = "주문식: 무기 마법부여 - 혹한",
			["Mexican"] = "Fórmula: encantar arma: escarcha letal",
			["Portuguese"] = "Fórmula: Encantamento de Gelo da Morte - Arma",
			["Russian"] = "Формула чар для оружия - смертельный мороз",
			["Spanish"] = "Fórmula: encantar arma: escarcha letal",
			["Taiwanese"] = "公式:附魔武器 - 死亡冰霜",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 35500,
		["name"] = {
			["Chinese"] = "公式：附魔胸甲 - 防御",
			["English"] = "Formula: Enchant Chest - Defense",
			["French"] = "Formule : Enchantement de plastron (Défense)",
			["German"] = "Formel: Brust - Verteidigung",
			["Korean"] = "주문식: 가슴보호구 마법부여 - 방어 숙련",
			["Mexican"] = "Fórmula: encantar pechera: defensa",
			["Portuguese"] = "Fórmula: Encantamento de Defesa - Torso",
			["Russian"] = "Формула чар для нагрудника: защита I",
			["Spanish"] = "Fórmula: encantar pechera: defensa",
			["Taiwanese"] = "公式:附魔胸甲 - 防禦",
		},
		["phase"] = 5,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 150000,
			["sources"] = {
				25032,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				24560,
			},
		},
		["expansion"] = 2,
		["id"] = 35756,
		["name"] = {
			["Chinese"] = "公式：附魔披风 - 钢纹",
			["English"] = "Formula: Enchant Cloak - Steelweave",
			["French"] = "Formule : Enchantement de cape (Tisse-acier)",
			["German"] = "Formel: Umhang - Stahlgewebe",
			["Korean"] = "주문식: 망토 마법부여 - 강철의 매듭",
			["Mexican"] = "Fórmula: encantar capa: tejido de acero",
			["Portuguese"] = "Fórmula: Encantamento de Açotrama - Manto",
			["Russian"] = "Формула чар для плаща: стальная ткань",
			["Spanish"] = "Fórmula: encantar capa: tejido de acero",
			["Taiwanese"] = "公式:附魔披風 - 鋼紋",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Enchanting"], item)
end
