-------------------------------------------------------
-- All skills (Enchanting) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Enchanting"] then RR_DATA["skills"]["Enchanting"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 27899,
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "附魔护腕 - 强壮",
			["English"] = "Enchant Bracer - Brawn",
			["French"] = "Ench. de brassards (Masse musculaire)",
			["German"] = "Armschiene - Muskelkraft",
			["Korean"] = "손목보호구 마법부여 - 완력",
			["Mexican"] = "Encantar brazales: lozanía",
			["Portuguese"] = "Encantamento de Força Muscular - Braçadeiras",
			["Russian"] = "Чары для наручей - грубая сила",
			["Spanish"] = "Encantar brazal: lozanía",
			["Taiwanese"] = "附魔護腕 - 健壯",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 12500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27905,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "附魔护腕 - 属性",
			["English"] = "Enchant Bracer - Stats",
			["French"] = "Ench. de brassards (Caractéristiques)",
			["German"] = "Armschiene - Werte",
			["Korean"] = "손목보호구 마법부여 - 능력치",
			["Mexican"] = "Encantar brazales: estadísticas",
			["Portuguese"] = "Encantamento de Atributos - Braçadeiras",
			["Russian"] = "Чары для наручей - все характеристики I",
			["Spanish"] = "Encantar brazal: estadísticas",
			["Taiwanese"] = "附魔護腕 - 屬性",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 12500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27906,
		["items"] = {
			22530,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "附魔护腕 - 特效防御",
			["English"] = "Enchant Bracer - Major Defense",
			["French"] = "Ench. de brassards (Défense majeure)",
			["German"] = "Armschiene - Erhebliche Verteidigung",
			["Korean"] = "손목보호구 마법부여 - 상급 방어 숙련",
			["Mexican"] = "Encantar brazal: defensa sublime",
			["Portuguese"] = "Encantamento Elevado de Defesa - Braçadeiras",
			["Russian"] = "Чары для наручей: защита",
			["Spanish"] = "Encantar brazal: defensa sublime",
			["Taiwanese"] = "附魔護腕 - 極效防禦",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27911,
		["items"] = {
			22531,
			24000,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "附魔护腕 - 超强治疗",
			["English"] = "Enchant Bracer - Superior Healing",
			["French"] = "Ench. de brassards (Soins excellents)",
			["German"] = "Armschiene - Überragende Heilung",
			["Korean"] = "손목보호구 마법부여 - 상급 치유 마법 강화",
			["Mexican"] = "Encantar brazales: sanación excelente",
			["Portuguese"] = "Encantamento Superior de Cura - Braçadeiras",
			["Russian"] = "Чары для наручей - лечение II",
			["Spanish"] = "Encantar brazal: sanación excelente",
			["Taiwanese"] = "附魔護腕 - 超強治療",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27913,
		["items"] = {
			22532,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "附魔护腕 - 优秀法力回复",
			["English"] = "Enchant Bracer - Restore Mana Prime",
			["French"] = "Ench. de brassards (Rest. du mana premier)",
			["German"] = "Armschiene - Mana wiederherstellen",
			["Korean"] = "손목보호구 마법부여 - 상급 마나 회복",
			["Mexican"] = "Encantar brazales: restaurar maná de primera",
			["Portuguese"] = "Encantamento de Restauração Primária de Mana - Braçadeiras",
			["Russian"] = "Чары для наручей - быстрое восполнение маны",
			["Spanish"] = "Encantar brazal: restaurar maná de primera",
			["Taiwanese"] = "附魔護腕 - 基礎法力恢復",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27914,
		["items"] = {
			22533,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔护腕 - 坚韧",
			["English"] = "Enchant Bracer - Fortitude",
			["French"] = "Ench. de brassards (Robustesse)",
			["German"] = "Armschiene - Seelenstärke",
			["Korean"] = "손목보호구 마법부여 - 인내",
			["Mexican"] = "Encantar brazales: entereza",
			["Portuguese"] = "Encantamento de Fortitude - Braçadeiras",
			["Russian"] = "Чары для наручей - стойкость",
			["Spanish"] = "Encantar brazal: entereza",
			["Taiwanese"] = "附魔護腕 - 堅韌",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27917,
		["items"] = {
			22534,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔护腕 - 法术能量",
			["English"] = "Enchant Bracer - Spellpower",
			["French"] = "Ench. de brassards (Puissance des sorts)",
			["German"] = "Armschiene - Zaubermacht",
			["Korean"] = "손목보호구 마법부여 - 주문 강화",
			["Mexican"] = "Encantar brazales: poder con hechizos",
			["Portuguese"] = "Encantamento de Poder Mágico - Braçadeiras",
			["Russian"] = "Чары для наручей - сила заклинаний I",
			["Spanish"] = "Encantar brazal: poder con hechizos",
			["Taiwanese"] = "附魔護腕 - 法術能量",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27920,
		["items"] = {
			22535,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔戒指 - 打击",
			["English"] = "Enchant Ring - Striking",
			["French"] = "Ench. d'anneau (Frappe)",
			["German"] = "Ring - Schlagen",
			["Korean"] = "반지 마법부여 - 공격력",
			["Mexican"] = "Encantar anillo: golpear",
			["Portuguese"] = "Encantamento de Ataque - Anel",
			["Russian"] = "Чары для кольца - удар",
			["Spanish"] = "Encantar anillo: golpear",
			["Taiwanese"] = "附魔戒指 - 打擊",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27924,
		["items"] = {
			22536,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔戒指 - 法术能量",
			["English"] = "Enchant Ring - Spellpower",
			["French"] = "Ench. d'anneau (Puissance des sorts)",
			["German"] = "Ring - Zaubermacht",
			["Korean"] = "반지 마법부여 - 주문 강화",
			["Mexican"] = "Encantar anillo: poder con hechizos",
			["Portuguese"] = "Encantamento de Poder Mágico - Anel",
			["Russian"] = "Чары для кольца: сила заклинаний I",
			["Spanish"] = "Encantar anillo: poder con hechizos",
			["Taiwanese"] = "附魔戒指 - 法術能量",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27926,
		["items"] = {
			22537,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "附魔戒指 - 治疗能量",
			["English"] = "Enchant Ring - Healing Power",
			["French"] = "Ench. d'anneau (Pouvoir de guérison)",
			["German"] = "Ring - Heilkraft",
			["Korean"] = "반지 마법부여 - 치유 마법 강화",
			["Mexican"] = "Encantar anillo: poder de sanación",
			["Portuguese"] = "Encantamento de Poder de Cura - Anel",
			["Russian"] = "Чары для кольца - целительная сила",
			["Spanish"] = "Encantar anillo: poder de sanación",
			["Taiwanese"] = "附魔戒指 - 治療能量",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27927,
		["items"] = {
			22538,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "附魔戒指 - 属性",
			["English"] = "Enchant Ring - Stats",
			["French"] = "Ench. d'anneau (Caractéristiques)",
			["German"] = "Ring - Werte",
			["Korean"] = "반지 마법부여 - 능력치",
			["Mexican"] = "Encantar anillo: estadísticas",
			["Portuguese"] = "Encantamento de Atributos - Anel",
			["Russian"] = "Чары для кольца - все характеристики",
			["Spanish"] = "Encantar anillo: estadísticas",
			["Taiwanese"] = "附魔戒指 - 屬性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27944,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "附魔盾牌 - 坚韧盾牌",
			["English"] = "Enchant Shield - Tough Shield",
			["French"] = "Ench. de bouclier (Inébranlable)",
			["German"] = "Schild - Harter Schild",
			["Korean"] = "방패 마법부여 - 견고한 방패",
			["Mexican"] = "Encantar escudo: escudo consistente",
			["Portuguese"] = "Encantamento - Escudo Robusto",
			["Russian"] = "Чары для щита: прочный щит",
			["Spanish"] = "Encantar escudo: escudo consistente",
			["Taiwanese"] = "附魔盾牌 - 堅硬盾牌",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27945,
		["items"] = {
			22539,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "附魔盾牌 - 智力",
			["English"] = "Enchant Shield - Intellect",
			["French"] = "Ench. de bouclier (Intelligence)",
			["German"] = "Schild - Intelligenz",
			["Korean"] = "방패 마법부여 - 지능",
			["Mexican"] = "Encantar escudo: intelecto",
			["Portuguese"] = "Encantamento de Intelecto - Escudo",
			["Russian"] = "Чары для щита - интеллект I",
			["Spanish"] = "Encantar escudo: intelecto",
			["Taiwanese"] = "附魔盾牌 - 智力",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27946,
		["items"] = {
			22540,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "附魔盾牌 - 盾牌格挡",
			["English"] = "Enchant Shield - Shield Block",
			["French"] = "Ench. de bouclier (Maîtrise du blocage)",
			["German"] = "Schild - Schildblock",
			["Korean"] = "방패 마법부여 - 방패 막기 향상",
			["Mexican"] = "Encantar escudo: bloquear con escudo",
			["Portuguese"] = "Encantamento de Bloqueio - Escudo",
			["Russian"] = "Чары для щита: блок II",
			["Spanish"] = "Encantar escudo: bloquear con escudo",
			["Taiwanese"] = "附魔盾牌 - 盾牌格擋",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27947,
		["items"] = {
			22541,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔盾牌 - 抗性",
			["English"] = "Enchant Shield - Resistance",
			["French"] = "Ench. de bouclier (Résistance)",
			["German"] = "Schild - Widerstand",
			["Korean"] = "방패 마법부여 - 저항력",
			["Mexican"] = "Encantar escudo: resistencia",
			["Portuguese"] = "Encantamento de Resistência - Escudo",
			["Russian"] = "Чары для щита: сопротивление",
			["Spanish"] = "Encantar escudo: resistencia",
			["Taiwanese"] = "附魔盾牌 - 抗性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27948,
		["items"] = {
			22542,
			35298,
		},
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "附魔长靴 - 活力",
			["English"] = "Enchant Boots - Vitality",
			["French"] = "Ench. de bottes (Vitalité)",
			["German"] = "Stiefel - Vitalität",
			["Korean"] = "장화 마법부여 - 활력",
			["Mexican"] = "Encantar botas: vitalidad",
			["Portuguese"] = "Encantamento de Vitalidade - Botas",
			["Russian"] = "Чары для обуви - живучесть I",
			["Spanish"] = "Encantar botas: vitalidad",
			["Taiwanese"] = "附魔靴子 - 活力",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27950,
		["items"] = {
			22543,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "附魔长靴 - 坚韧",
			["English"] = "Enchant Boots - Fortitude",
			["French"] = "Ench. de bottes (Robustesse)",
			["German"] = "Stiefel - Seelenstärke",
			["Korean"] = "장화 마법부여 - 인내",
			["Mexican"] = "Encantar botas: entereza",
			["Portuguese"] = "Encantamento de Fortitude - Botas",
			["Russian"] = "Чары для обуви - стойкость I",
			["Spanish"] = "Encantar botas: entereza",
			["Taiwanese"] = "附魔靴子 - 堅韌",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27951,
		["items"] = {
			22544,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "附魔长靴 - 灵巧",
			["English"] = "Enchant Boots - Dexterity",
			["French"] = "Ench. de bottes (Dextérité)",
			["German"] = "Stiefel - Gewandtheit",
			["Korean"] = "장화 마법부여 - 기민함",
			["Mexican"] = "Encantar botas: maña",
			["Portuguese"] = "Encantamento de Destreza - Botas",
			["Russian"] = "Чары для обуви - стремительность",
			["Spanish"] = "Encantar botas: maña",
			["Taiwanese"] = "附魔靴子 - 靈巧",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27954,
		["items"] = {
			22545,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "附魔长靴 - 稳固",
			["English"] = "Enchant Boots - Surefooted",
			["French"] = "Ench. de bottes (Pied sûr)",
			["German"] = "Stiefel - Sicherer Stand",
			["Korean"] = "장화 마법부여 - 침착함",
			["Mexican"] = "Encantar botas: Pies de plomo",
			["Portuguese"] = "Encantamento de Firmeza - Botas",
			["Russian"] = "Чары для обуви - верный шаг",
			["Spanish"] = "Encantar botas: pies de plomo",
			["Taiwanese"] = "附魔靴子 - 穩固",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27957,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "附魔胸甲 - 杰出生命",
			["English"] = "Enchant Chest - Exceptional Health",
			["French"] = "Ench. de plastron (Pts vie exceptionnels)",
			["German"] = "Brust - Außergewöhnliche Gesundheit",
			["Korean"] = "가슴보호구 마법부여 - 특급 생명력",
			["Mexican"] = "Encantar pechera: salud excepcional",
			["Portuguese"] = "Encantamento Excepcional de Vida - Torso",
			["Russian"] = "Чары для нагрудника - здоровье VII",
			["Spanish"] = "Encantar pechera: salud excepcional",
			["Taiwanese"] = "附魔胸甲 - 特殊生命",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 17500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27960,
		["items"] = {
			22547,
			24003,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "附魔胸甲 - 杰出属性",
			["English"] = "Enchant Chest - Exceptional Stats",
			["French"] = "Ench. de plastron (Carac. exceptionnelles)",
			["German"] = "Brust - Außergewöhnliche Werte",
			["Korean"] = "가슴보호구 마법부여 - 특급 능력치",
			["Mexican"] = "Encantar pechera: estadísticas excepcionales",
			["Portuguese"] = "Encantamento Excepcional de Atributos - Torso",
			["Russian"] = "Чары для нагрудника - все характеристики V",
			["Spanish"] = "Encantar pechera: estadísticas excepcionales",
			["Taiwanese"] = "附魔胸甲 - 特殊屬性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27961,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "附魔披风 - 特效护甲",
			["English"] = "Enchant Cloak - Major Armor",
			["French"] = "Ench. de cape (Armure majeure)",
			["German"] = "Umhang - Erhebliche Rüstung",
			["Korean"] = "망토 마법부여 - 일급 방어도",
			["Mexican"] = "Encantar capa: armadura sublime",
			["Portuguese"] = "Encantamento Elevado de Armadura - Manto",
			["Russian"] = "Чары для плаща - броня VI",
			["Spanish"] = "Encantar capa: armadura sublime",
			["Taiwanese"] = "附魔披風 - 極效護甲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27962,
		["items"] = {
			22548,
		},
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "附魔披风 - 特效抗性",
			["English"] = "Enchant Cloak - Major Resistance",
			["French"] = "Ench. de cape (Résistance majeure)",
			["German"] = "Umhang - Erheblicher Widerstand",
			["Korean"] = "망토 마법부여 - 상급 저항력",
			["Mexican"] = "Encantar capa: resistencia sublime",
			["Portuguese"] = "Encantamento Elevado de Resistência - Manto",
			["Russian"] = "Чары для плаща: сопротивление IV",
			["Spanish"] = "Encantar capa: resistencia sublime",
			["Taiwanese"] = "附魔披風 - 極效抗性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27967,
		["items"] = {
			22552,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "附魔武器 - 特效打击",
			["English"] = "Enchant Weapon - Major Striking",
			["French"] = "Ench. d'arme (Frappe majeure)",
			["German"] = "Waffe - Erhebliches Schlagen",
			["Korean"] = "무기 마법부여 - 일급 공격력",
			["Mexican"] = "Encantar arma: golpear sublime",
			["Portuguese"] = "Encantamento Elevado de Ataque - Arma",
			["Russian"] = "Чары для оружия - удар VI",
			["Spanish"] = "Encantar arma: golpear sublime",
			["Taiwanese"] = "附魔武器 - 極效打擊",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27968,
		["items"] = {
			22551,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "附魔武器 - 特效智力",
			["English"] = "Enchant Weapon - Major Intellect",
			["French"] = "Ench. d'arme (Intelligence majeure)",
			["German"] = "Waffe - Erhebliche Intelligenz",
			["Korean"] = "무기 마법부여 - 일급 지능",
			["Mexican"] = "Encantar arma: intelecto sublime",
			["Portuguese"] = "Encantamento Elevado de Intelecto - Arma",
			["Russian"] = "Чары для оружия - интеллект II",
			["Spanish"] = "Encantar arma: intelecto sublime",
			["Taiwanese"] = "附魔武器 - 極效智力",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27971,
		["items"] = {
			22554,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔双手武器 - 野蛮",
			["English"] = "Enchant 2H Weapon - Savagery",
			["French"] = "Ench. d'arme 2M (Sauvagerie)",
			["German"] = "Zweihandwaffe - Unbändigkeit",
			["Korean"] = "양손 무기 마법부여 - 전투력",
			["Mexican"] = "Encantar arma 2M: salvajismo",
			["Portuguese"] = "Encantamento de Selvageria - Arma de 2M",
			["Russian"] = "Чары для двуручного оружия - свирепость",
			["Spanish"] = "Encantar arma 2M: salvajismo",
			["Taiwanese"] = "附魔雙手武器 - 兇蠻",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27972,
		["items"] = {
			22553,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔武器 - 力量",
			["English"] = "Enchant Weapon - Potency",
			["French"] = "Ench. d'arme (Toute-puissance)",
			["German"] = "Waffe - Potenz",
			["Korean"] = "무기 마법부여 - 근력",
			["Mexican"] = "Encantar arma: potencia",
			["Portuguese"] = "Encantamento de Potência - Arma",
			["Russian"] = "Чары для оружия - могущество I",
			["Spanish"] = "Encantar arma: potencia",
			["Taiwanese"] = "附魔武器 - 潛能",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27975,
		["items"] = {
			22555,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔武器 - 特效法术能量",
			["English"] = "Enchant Weapon - Major Spellpower",
			["French"] = "Ench. d'arme (Puissance des sorts majeure)",
			["German"] = "Waffe - Erhebliche Zaubermacht",
			["Korean"] = "무기 마법부여 - 상급 주문 강화",
			["Mexican"] = "Encantar arma: poder con hechizos sublime",
			["Portuguese"] = "Encantamento Elevado de Poder Mágico - Arma",
			["Russian"] = "Чары для оружия - сила заклинаний II",
			["Spanish"] = "Encantar arma: poder con hechizos sublime",
			["Taiwanese"] = "附魔武器 - 極效法術能量",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27977,
		["items"] = {
			22556,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔双手武器 - 特效敏捷",
			["English"] = "Enchant 2H Weapon - Major Agility",
			["French"] = "Ench. d'arme 2M (Agilité majeure)",
			["German"] = "Zweihandwaffe - Erhebliche Beweglichkeit",
			["Korean"] = "양손 무기 마법부여 - 일급 민첩성",
			["Mexican"] = "Encantar arma 2M: agilidad sublime",
			["Portuguese"] = "Encantamento Elevado de Agilidade - Arma de 2M",
			["Russian"] = "Чары для двуручного оружия - ловкость II",
			["Spanish"] = "Encantar arma 2M: agilidad sublime",
			["Taiwanese"] = "附魔雙手武器 - 極效敏捷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27981,
		["items"] = {
			22560,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "附魔武器 - 阳炎",
			["English"] = "Enchant Weapon - Sunfire",
			["French"] = "Ench. d'arme (Feu solaire)",
			["German"] = "Waffe - Sonnenfeuer",
			["Korean"] = "무기 마법부여 - 태양의 불꽃",
			["Mexican"] = "Encantar arma: Fuego solar",
			["Portuguese"] = "Encantamento de Fogo Solar - Arma",
			["Russian"] = "Чары для оружия - солнечный огонь",
			["Spanish"] = "Encantar arma: fuego solar",
			["Taiwanese"] = "附魔武器 - 烈日火焰",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27982,
		["items"] = {
			22561,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "附魔武器 - 魂霜",
			["English"] = "Enchant Weapon - Soulfrost",
			["French"] = "Ench. d'arme (Âme de givre)",
			["German"] = "Waffe - Seelenfrost",
			["Korean"] = "무기 마법부여 - 냉기의 영혼",
			["Mexican"] = "Encantar arma: escarcha de alma",
			["Portuguese"] = "Encantamento de Congelar Alma - Arma",
			["Russian"] = "Чары для оружия - ледяная душа",
			["Spanish"] = "Encantar arma: escarcha de alma",
			["Taiwanese"] = "附魔武器 - 靈魂冰霜",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 27984,
		["items"] = {
			22559,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "附魔武器 - 猫鼬",
			["English"] = "Enchant Weapon - Mongoose",
			["French"] = "Ench. d'arme (Mangouste)",
			["German"] = "Waffe - Mungo",
			["Korean"] = "무기 마법부여 - 살쾡이",
			["Mexican"] = "Encantar arma: mangosta",
			["Portuguese"] = "Encantamento de Mangusto - Arma",
			["Russian"] = "Чары для оружия - мангуст",
			["Spanish"] = "Encantar arma: mangosta",
			["Taiwanese"] = "附魔武器 - 貓鼬",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28003,
		["items"] = {
			22558,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔武器 - 魔法激荡",
			["English"] = "Enchant Weapon - Spellsurge",
			["French"] = "Ench. d'arme (Eruption de sort)",
			["German"] = "Waffe - Zauberflut",
			["Korean"] = "무기 마법부여 - 마력의 폭풍",
			["Mexican"] = "Encantar arma: oleada de hechizos",
			["Portuguese"] = "Encantamento de Surto de Feitiço - Arma",
			["Russian"] = "Чары для оружия - всплеск чар",
			["Spanish"] = "Encantar arma: oleada de hechizos",
			["Taiwanese"] = "附魔武器 - 法力回流",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28004,
		["items"] = {
			22557,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔武器 - 作战专家",
			["English"] = "Enchant Weapon - Battlemaster",
			["French"] = "Ench. d'arme (Maître de guerre)",
			["German"] = "Waffe - Meister des Kampfes",
			["Korean"] = "무기 마법부여 - 전투의 대가",
			["Mexican"] = "Encantar arma: maestro de batalla",
			["Portuguese"] = "Encantamento de Mestre de Batalha - Arma",
			["Russian"] = "Чары для оружия - военачальник",
			["Spanish"] = "Encantar arma: maestro de batalla",
			["Taiwanese"] = "附魔武器 - 戰鬥大師",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28016,
		["item_id"] = 22521,
		["items"] = {
			22562,
		},
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "超级法力之油",
			["English"] = "Superior Mana Oil",
			["French"] = "Huile de mana excellente",
			["German"] = "Überragendes Manaöl",
			["Korean"] = "최고급 마나 오일",
			["Mexican"] = "Aceite de maná excelente",
			["Portuguese"] = "Óleo Superior de Mana",
			["Russian"] = "Превосходное масло маны",
			["Spanish"] = "Aceite de maná excelente",
			["Taiwanese"] = "超強法力之油",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28019,
		["item_id"] = 22522,
		["items"] = {
			22563,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "超级巫师之油",
			["English"] = "Superior Wizard Oil",
			["French"] = "Huile de sorcier excellente",
			["German"] = "Überragendes Zauberöl",
			["Korean"] = "최고급 마술사 오일",
			["Mexican"] = "Aceite de zahorí excelente",
			["Portuguese"] = "Óleo Superior de Teurgo",
			["Russian"] = "Превосходное волшебное масло",
			["Spanish"] = "Aceite de zahorí excelente",
			["Taiwanese"] = "超強巫師之油",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28022,
		["item_id"] = 22449,
		["items"] = {
			22565,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "大块棱光碎片",
			["English"] = "Large Prismatic Shard",
			["French"] = "Grand éclat prismatique",
			["German"] = "Großer Prismasplitter",
			["Korean"] = "무지갯빛 큰 결정",
			["Mexican"] = "Fragmento centelleante grande",
			["Portuguese"] = "Estilhaço Prismático Grande",
			["Russian"] = "Большой радужный осколок",
			["Spanish"] = "Fragmento centelleante grande",
			["Taiwanese"] = "大塊稜石裂片",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28027,
		["item_id"] = 22460,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "棱光之球",
			["English"] = "Prismatic Sphere",
			["French"] = "Sphère prismatique",
			["German"] = "Prismasphäre",
			["Korean"] = "무지갯빛 구슬",
			["Mexican"] = "Esfera centelleante",
			["Portuguese"] = "Esfera Prismática",
			["Russian"] = "Радужная сфера",
			["Spanish"] = "Esfera centelleante",
			["Taiwanese"] = "稜石之球",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28028,
		["item_id"] = 22459,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "虚空之球",
			["English"] = "Void Sphere",
			["French"] = "Sphère de Vide",
			["German"] = "Sphäre der Leere",
			["Korean"] = "공허의 구슬",
			["Mexican"] = "Esfera de vacío",
			["Portuguese"] = "Esfera do Caos",
			["Russian"] = "Сфера Бездны",
			["Spanish"] = "Esfera de vacío",
			["Taiwanese"] = "虛無之球",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 80000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32664,
		["item_id"] = 22461,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "符文魔铁棒",
			["English"] = "Runed Fel Iron Rod",
			["French"] = "Bâtonnet runique en gangrefer",
			["German"] = "Runenverzierte Teufelseisenrute",
			["Korean"] = "룬문자 지옥무쇠 마법막대",
			["Mexican"] = "Vara rúnica de hierro vil",
			["Portuguese"] = "Bastão Rúnico de Ferrovil",
			["Russian"] = "Рунический жезл из оскверненного железа",
			["Spanish"] = "Vara rúnica de hierro vil",
			["Taiwanese"] = "符文魔鐵棒",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32665,
		["item_id"] = 22462,
		["items"] = {
			25848,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "符文精金棒",
			["English"] = "Runed Adamantite Rod",
			["French"] = "Bâtonnet runique en adamantite",
			["German"] = "Runenverzierte Adamantitrute",
			["Korean"] = "룬문자 아다만타이트 마법막대",
			["Mexican"] = "Vara rúnica de adamantita",
			["Portuguese"] = "Bastão Rúnico de Adamantita",
			["Russian"] = "Рунический адамантитовый жезл",
			["Spanish"] = "Vara rúnica de adamantita",
			["Taiwanese"] = "符文堅鋼魔棒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32667,
		["item_id"] = 22463,
		["items"] = {
			25849,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "符文恒金棒",
			["English"] = "Runed Eternium Rod",
			["French"] = "Bâtonnet runique en éternium",
			["German"] = "Runenverzierte Eterniumrute",
			["Korean"] = "룬문자 이터늄 마법막대",
			["Mexican"] = "Vara rúnica de eternio",
			["Portuguese"] = "Bastão Rúnico de Etérnio",
			["Russian"] = "Рунический этерниевый жезл",
			["Spanish"] = "Vara rúnica de eternio",
			["Taiwanese"] = "符文恆金棒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33990,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "附魔胸甲 - 特效精神",
			["English"] = "Enchant Chest - Major Spirit",
			["French"] = "Ench. de plastron (Esprit majeur)",
			["German"] = "Brust - Erhebliche Willenskraft",
			["Korean"] = "가슴보호구 마법부여 - 일급 정신력",
			["Mexican"] = "Encantar pechera: espíritu sublime",
			["Portuguese"] = "Encantamento Elevado de Espírito - Torso",
			["Russian"] = "Чары для нагрудника - дух I",
			["Spanish"] = "Encantar pechera: espíritu sublime",
			["Taiwanese"] = "附魔胸甲 - 極效精神",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33991,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "附魔胸甲 - 优秀法力回复",
			["English"] = "Enchant Chest - Restore Mana Prime",
			["French"] = "Ench. de plastron (Rest. du mana premier)",
			["German"] = "Brust - Mana wiederherstellen",
			["Korean"] = "가슴보호구 마법부여 - 상급 마나 회복",
			["Mexican"] = "Encantar pechera: restaurar maná de primera",
			["Portuguese"] = "Encantamento de Restauração Primária de Mana - Torso",
			["Russian"] = "Чары для нагрудника: восполнение маны",
			["Spanish"] = "Encantar pechera: restaurar maná de primera",
			["Taiwanese"] = "附魔胸甲 - 基礎法力恢復",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 12500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33992,
		["items"] = {
			28270,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "附魔胸甲 - 特效韧性",
			["English"] = "Enchant Chest - Major Resilience",
			["French"] = "Ench. de plastron (Résilience majeure)",
			["German"] = "Brust - Erhebliche Abhärtung",
			["Korean"] = "가슴보호구 마법부여 - 일급 탄력성",
			["Mexican"] = "Encantar pechera: temple sublime",
			["Portuguese"] = "Encantamento Elevado de Resiliência - Torso",
			["Russian"] = "Чары для нагрудника - устойчивость I",
			["Spanish"] = "Encantar pechera: temple sublime",
			["Taiwanese"] = "附魔胸甲 - 極效韌性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33993,
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "附魔手套 - 冲击",
			["English"] = "Enchant Gloves - Blasting",
			["French"] = "Ench. de gants (Explosion)",
			["German"] = "Handschuhe - Sprengkraft",
			["Korean"] = "장갑 마법부여 - 폭파",
			["Mexican"] = "Encantar guantes: detonación",
			["Portuguese"] = "Encantamento de Impacto - Luvas",
			["Russian"] = "Чары для перчаток - взрыв I",
			["Spanish"] = "Encantar guantes: detonación",
			["Taiwanese"] = "附魔手套 - 衝擊",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 12500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33994,
		["items"] = {
			28271,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔手套 - 法术打击",
			["English"] = "Enchant Gloves - Spell Strike",
			["French"] = "Ench. de gants (Frappe-sort)",
			["German"] = "Handschuhe - Zauberschlag",
			["Korean"] = "장갑 마법부여 - 주문 적중",
			["Mexican"] = "Encantar guantes: golpe con hechizos",
			["Portuguese"] = "Encantamento de Ataque de Feitiço - Luvas",
			["Russian"] = "Чары для перчаток - удар заклинаний I",
			["Spanish"] = "Encantar guantes: golpe con hechizos",
			["Taiwanese"] = "附魔手套 - 法術打擊",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33995,
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "附魔手套 - 特效力量",
			["English"] = "Enchant Gloves - Major Strength",
			["French"] = "Ench. de gants (Force majeure)",
			["German"] = "Handschuhe - Erhebliche Stärke",
			["Korean"] = "장갑 마법부여 - 일급 힘",
			["Mexican"] = "Encantar guantes: fuerza sublime",
			["Portuguese"] = "Encantamento Elevado de Força - Luvas",
			["Russian"] = "Чары для перчаток - сила III",
			["Spanish"] = "Encantar guantes: fuerza sublime",
			["Taiwanese"] = "附魔手套 - 極效力量",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33996,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "附魔手套 - 突袭",
			["English"] = "Enchant Gloves - Assault",
			["French"] = "Ench. de gants (Assaut)",
			["German"] = "Handschuhe - Sturmangriff",
			["Korean"] = "장갑 마법부여 - 맹공",
			["Mexican"] = "Encantar guantes: asalto",
			["Portuguese"] = "Encantamento de Assalto - Luvas",
			["Russian"] = "Чары для перчаток - штурм I",
			["Spanish"] = "Encantar guantes: asalto",
			["Taiwanese"] = "附魔手套 - 攻擊",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33997,
		["items"] = {
			28272,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔手套 - 特效法术能量",
			["English"] = "Enchant Gloves - Major Spellpower",
			["French"] = "Ench. de gants (Puissance des sorts majeure)",
			["German"] = "Handschuhe - Erhebliche Zaubermacht",
			["Korean"] = "장갑 마법부여 - 일급 주문 강화",
			["Mexican"] = "Encantar guantes: poder con hechizos sublime",
			["Portuguese"] = "Encantamento Elevado de Poder Mágico - Luvas",
			["Russian"] = "Чары для перчаток - сила заклинаний I",
			["Spanish"] = "Encantar guantes: poder con hechizos sublime",
			["Taiwanese"] = "附魔手套 - 極效法術能量",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33999,
		["items"] = {
			28273,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔手套 - 特效治疗",
			["English"] = "Enchant Gloves - Major Healing",
			["French"] = "Ench. de gants (Soins majeurs)",
			["German"] = "Handschuhe - Erhebliche Heilung",
			["Korean"] = "장갑 마법부여 - 일급 치유 마법 강화",
			["Mexican"] = "Encantar guantes: sanación sublime",
			["Portuguese"] = "Encantamento Elevado de Cura - Luvas",
			["Russian"] = "Чары для перчаток - лечение I",
			["Spanish"] = "Encantar guantes: sanación sublime",
			["Taiwanese"] = "附魔手套 - 極效治療",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34001,
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "附魔护腕 - 特效智力",
			["English"] = "Enchant Bracer - Major Intellect",
			["French"] = "Ench. de brassards (Intelligence majeure)",
			["German"] = "Armschiene - Erhebliche Intelligenz",
			["Korean"] = "손목보호구 마법부여 - 일급 지능",
			["Mexican"] = "Encantar brazales: intelecto sublime",
			["Portuguese"] = "Encantamento Elevado de Intelecto - Braçadeiras",
			["Russian"] = "Чары для наручей - интеллект IV",
			["Spanish"] = "Encantar brazal: intelecto sublime",
			["Taiwanese"] = "附魔護腕 - 極效智力",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 12500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34002,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "附魔护腕 - 突袭",
			["English"] = "Enchant Bracer - Assault",
			["French"] = "Ench. de brassards (Assaut)",
			["German"] = "Armschiene - Sturmangriff",
			["Korean"] = "손목보호구 마법부여 - 맹공",
			["Mexican"] = "Encantar brazal: asalto",
			["Portuguese"] = "Encantamento de Assalto - Braçadeiras",
			["Russian"] = "Чары для наручей - штурм II",
			["Spanish"] = "Encantar brazal: asalto",
			["Taiwanese"] = "附魔護腕 - 攻擊",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 12500,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34003,
		["items"] = {
			28274,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "附魔披风 - 法术穿透",
			["English"] = "Enchant Cloak - Spell Penetration",
			["French"] = "Ench. de cape (Pénétration des sorts)",
			["German"] = "Umhang - Zauberdurchschlagskraft",
			["Korean"] = "망토 마법부여 - 주문 관통력",
			["Mexican"] = "Encantar capa: penetración de hechizos",
			["Portuguese"] = "Encantamento de Penetração de Feitiço - Manto",
			["Russian"] = "Чары для плаща: проникающая способность заклинаний",
			["Spanish"] = "Encantar capa: penetración de hechizos",
			["Taiwanese"] = "附魔披風 - 法術穿透",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34004,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "附魔披风 - 强效敏捷",
			["English"] = "Enchant Cloak - Greater Agility",
			["French"] = "Ench. de cape (Agilité supérieure)",
			["German"] = "Umhang - Große Beweglichkeit",
			["Korean"] = "망토 마법부여 - 상급 민첩성",
			["Mexican"] = "Encantar capa: agilidad superior",
			["Portuguese"] = "Encantamento Maior de Agilidade - Manto",
			["Russian"] = "Чары для плаща - ловкость III",
			["Spanish"] = "Encantar capa: agilidad superior",
			["Taiwanese"] = "附魔披風 - 強效敏捷",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34005,
		["items"] = {
			28276,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔披风 - 强效奥术抗性",
			["English"] = "Enchant Cloak - Greater Arcane Resistance",
			["French"] = "Ench. de cape (Résistance aux arcanes supérieure)",
			["German"] = "Umhang - Großer Arkanwiderstand",
			["Korean"] = "망토 마법부여 - 상급 비전 저항력",
			["Mexican"] = "Encantar capa: resistencia a lo Arcano superior",
			["Portuguese"] = "Encantamento Maior de Resistência ao Arcano - Manto",
			["Russian"] = "Чары для плаща: сопротивление тайной магии I",
			["Spanish"] = "Encantar capa: resistencia a lo Arcano superior",
			["Taiwanese"] = "附魔披風 - 強效秘法抗性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34006,
		["items"] = {
			28277,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔披风 - 强效暗影抗性",
			["English"] = "Enchant Cloak - Greater Shadow Resistance",
			["French"] = "Ench. de cape (Résistance à l'Ombre supérieure)",
			["German"] = "Umhang - Großer Schattenwiderstand",
			["Korean"] = "망토 마법부여 - 상급 암흑 저항력",
			["Mexican"] = "Encantar capa: resistencia a las Sombras superior",
			["Portuguese"] = "Encantamento Maior de Resistência à Sombra - Manto",
			["Russian"] = "Чары для плаща: сопротивление темной магии II",
			["Spanish"] = "Encantar capa: resistencia a las Sombras superior",
			["Taiwanese"] = "附魔披風 - 強效暗影抗性",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34007,
		["items"] = {
			28279,
			35299,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔长靴 - 豹之迅捷",
			["English"] = "Enchant Boots - Cat's Swiftness",
			["French"] = "Ench. de bottes (Rapidité du félin)",
			["German"] = "Stiefel - Schnelligkeit der Katze",
			["Korean"] = "장화 마법부여 - 살쾡이의 날렵함",
			["Mexican"] = "Encantar botas: presteza felina",
			["Portuguese"] = "Encantamento de Rapidez do Gato - Botas",
			["Russian"] = "Чары для обуви - проворство кошки",
			["Spanish"] = "Encantar botas: presteza felina",
			["Taiwanese"] = "附魔靴子 - 貓之迅捷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34008,
		["items"] = {
			28280,
			35297,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔长靴 - 野猪之速",
			["English"] = "Enchant Boots - Boar's Speed",
			["French"] = "Ench. de bottes (Vitesse du sanglier)",
			["German"] = "Stiefel - Flinkheit des Ebers",
			["Korean"] = "장화 마법부여 - 멧돼지의 속도",
			["Mexican"] = "Encantar botas: velocidad de jabalí",
			["Portuguese"] = "Encantamento de Velocidade do Javali - Botas",
			["Russian"] = "Чары для обуви - быстрота вепря",
			["Spanish"] = "Encantar botas: velocidad del jabalí",
			["Taiwanese"] = "附魔靴子 - 野豬之速",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34009,
		["items"] = {
			28282,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "附魔盾牌 - 特效耐力",
			["English"] = "Enchant Shield - Major Stamina",
			["French"] = "Ench. de bouclier (Endurance majeure)",
			["German"] = "Schild - Erhebliche Ausdauer",
			["Korean"] = "방패 마법부여 - 일급 체력",
			["Mexican"] = "Encantar escudo: aguante sublime",
			["Portuguese"] = "Encantamento Elevado de Vigor - Escudo",
			["Russian"] = "Чары для щита - выносливость V",
			["Spanish"] = "Encantar escudo: aguante sublime",
			["Taiwanese"] = "附魔盾牌 - 極效耐力",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34010,
		["items"] = {
			28281,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔武器 - 特效治疗",
			["English"] = "Enchant Weapon - Major Healing",
			["French"] = "Ench. d'arme (Soins majeurs)",
			["German"] = "Waffe - Erhebliche Heilung",
			["Korean"] = "무기 마법부여 - 일급 치유 마법 강화",
			["Mexican"] = "Encantar arma: sanación sublime",
			["Portuguese"] = "Encantamento Elevado de Cura - Arma",
			["Russian"] = "Чары для оружия - лечение I",
			["Spanish"] = "Encantar arma: sanación sublime",
			["Taiwanese"] = "附魔武器 - 極效治療",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 42613,
		["item_id"] = 22448,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "转化连结水晶",
			["English"] = "Nexus Transformation",
			["French"] = "Transformation de nexus",
			["German"] = "Nexusverwandlung",
			["Korean"] = "마력 변환",
			["Mexican"] = "Transformación nexa",
			["Portuguese"] = "Transformação de Nexus",
			["Russian"] = "Преображение кристалла-источника",
			["Spanish"] = "Transformación de Nexus",
			["Taiwanese"] = "轉換聯結水晶",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 42615,
		["item_id"] = 22448,
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "小块棱光碎片",
			["English"] = "Small Prismatic Shard",
			["French"] = "Petit éclat prismatique",
			["German"] = "Kleiner Prismasplitter",
			["Korean"] = "무지갯빛 작은 결정",
			["Mexican"] = "Fragmento centelleante pequeño",
			["Portuguese"] = "Estilhaço Prismático Pequeno",
			["Russian"] = "Малый радужный осколок",
			["Spanish"] = "Fragmento centelleante pequeño",
			["Taiwanese"] = "小塊稜石裂片",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 42620,
		["items"] = {
			33165,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔武器 - 强效敏捷",
			["English"] = "Enchant Weapon - Greater Agility",
			["French"] = "Ench. d'arme (Agilité supérieure)",
			["German"] = "Waffe - Große Beweglichkeit",
			["Korean"] = "무기 마법부여 - 상급 민첩",
			["Mexican"] = "Encantar arma: agilidad superior",
			["Portuguese"] = "Encantamento Maior de Agilidade - Arma",
			["Russian"] = "Чары для оружия - ловкость II",
			["Spanish"] = "Encantar arma: agilidad superior",
			["Taiwanese"] = "附魔武器 - 強效敏捷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 42974,
		["items"] = {
			33307,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "附魔武器 - 斩杀",
			["English"] = "Enchant Weapon - Executioner",
			["French"] = "Ench. d'arme (Exécutrice)",
			["German"] = "Waffe - Scharfrichter",
			["Korean"] = "무기 마법부여 - 집행자",
			["Mexican"] = "Encantar arma: verdugo",
			["Portuguese"] = "Encantamento de Carrasco - Arma",
			["Russian"] = "Чары для оружия - палач",
			["Spanish"] = "Encantar arma: verdugo",
			["Taiwanese"] = "附魔武器 - 處決者",
		},
		["phase"] = 4,
	},
	{
		["expansion"] = 2,
		["id"] = 44383,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "附魔盾牌 - 韧性",
			["English"] = "Enchant Shield - Resilience",
			["French"] = "Ench. de bouclier (Résilience)",
			["German"] = "Schild - Abhärtung",
			["Korean"] = "방패 마법부여 - 탄력",
			["Mexican"] = "Encantar escudo: temple",
			["Portuguese"] = "Encantamento de Resiliência - Escudo",
			["Russian"] = "Чары для щита: устойчивость",
			["Spanish"] = "Encantar escudo: temple",
			["Taiwanese"] = "附魔盾牌 - 韌性",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				19540,
				18753,
				19252,
				18773,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 45765,
		["item_id"] = 22449,
		["items"] = {
			34872,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "虚空碎裂",
			["English"] = "Void Shatter",
			["French"] = "Bris de vide",
			["German"] = "Brechung der Leere",
			["Korean"] = "공허의 조각",
			["Mexican"] = "Fragmentar cristal de vacío",
			["Portuguese"] = "Ruptura do Caos",
			["Russian"] = "Дробление кристалла Бездны",
			["Spanish"] = "Fragmentar cristal de vacío",
			["Taiwanese"] = "粉碎虛無",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["holiday"] = 341,
		["id"] = 46578,
		["items"] = {
			35498,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "附魔武器 - 死亡霜冻",
			["English"] = "Enchant Weapon - Deathfrost",
			["French"] = "Ench. d'arme (Givre mortel)",
			["German"] = "Waffe - Todeskälte",
			["Korean"] = "무기 마법부여 - 혹한",
			["Mexican"] = "Encantar arma: escarcha letal",
			["Portuguese"] = "Encantamento de Gelo da Morte - Arma",
			["Russian"] = "Чары для оружия - смертельный мороз",
			["Spanish"] = "Encantar arma: escarcha letal",
			["Taiwanese"] = "附魔武器 - 死亡冰霜",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 46594,
		["items"] = {
			35500,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "附魔胸甲 - 防御",
			["English"] = "Enchant Chest - Defense",
			["French"] = "Ench. de plastron (Défense)",
			["German"] = "Brust - Verteidigung",
			["Korean"] = "가슴보호구 마법부여 - 방어 숙련",
			["Mexican"] = "Encantar pechera: defensa",
			["Portuguese"] = "Encantamento de Defesa - Torso",
			["Russian"] = "Чары для нагрудника: защита I",
			["Spanish"] = "Encantar pechera: defensa",
			["Taiwanese"] = "附魔胸甲 - 防禦",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 47051,
		["items"] = {
			35756,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "附魔披风 - 钢纹",
			["English"] = "Enchant Cloak - Steelweave",
			["French"] = "Ench. de cape (Tisse-acier)",
			["German"] = "Umhang - Stahlgewebe",
			["Korean"] = "망토 마법부여 - 강철의 매듭",
			["Mexican"] = "Encantar capa: tejido de acero",
			["Portuguese"] = "Encantamento de Açotrama - Manto",
			["Russian"] = "Чары для плаща: стальная ткань",
			["Spanish"] = "Encantar capa: tejido de acero",
			["Taiwanese"] = "附魔披風 - 鋼紋",
		},
		["phase"] = 5,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Enchanting"], skill)
end
