-------------------------------------------------------
-- All skills (Mining) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Mining"] then RR_DATA["skills"]["Mining"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 29356,
		["item_id"] = 23445,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "熔炼魔铁",
			["English"] = "Smelt Fel Iron",
			["French"] = "Fonte de gangrefer",
			["German"] = "Teufelseisen verhütten",
			["Korean"] = "지옥무쇠 제련",
			["Mexican"] = "Fundir hierro vil",
			["Portuguese"] = "Fundir Ferrovil",
			["Russian"] = "Выплавка оскверненного железа",
			["Spanish"] = "Fundir hierro vil",
			["Taiwanese"] = "熔煉魔鐵錠",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29358,
		["item_id"] = 23446,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "熔炼精金",
			["English"] = "Smelt Adamantite",
			["French"] = "Fonte de l'adamantite",
			["German"] = "Adamantit verhütten",
			["Korean"] = "아다만타이트 제련",
			["Mexican"] = "Fundir adamantita",
			["Portuguese"] = "Fundir Adamantita",
			["Russian"] = "Выплавка адамантита",
			["Spanish"] = "Fundir adamantita",
			["Taiwanese"] = "熔煉堅鋼錠",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29359,
		["item_id"] = 23447,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "熔炼恒金",
			["English"] = "Smelt Eternium",
			["French"] = "Fonte de l'éternium",
			["German"] = "Eternium verhütten",
			["Korean"] = "이터늄 제련",
			["Mexican"] = "Fundir eternio",
			["Portuguese"] = "Fundir Etérnio",
			["Russian"] = "Выплавка этерния",
			["Spanish"] = "Fundir eternio",
			["Taiwanese"] = "熔煉恆金錠",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29360,
		["item_id"] = 23448,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "熔炼魔钢",
			["English"] = "Smelt Felsteel",
			["French"] = "Fonte de gangracier",
			["German"] = "Teufelsstahl verhütten",
			["Korean"] = "지옥강철 제련",
			["Mexican"] = "Fundir acero vil",
			["Portuguese"] = "Fundir Açovil",
			["Russian"] = "Выплавка оскверненной стали",
			["Spanish"] = "Fundir acero vil",
			["Taiwanese"] = "熔煉魔鋼錠",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29361,
		["item_id"] = 23449,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "熔炼氪金",
			["English"] = "Smelt Khorium",
			["French"] = "Fonte du khorium",
			["German"] = "Khorium verhütten",
			["Korean"] = "코륨 제련",
			["Mexican"] = "Fundir korio",
			["Portuguese"] = "Fundir Kório",
			["Russian"] = "Выплавка кория",
			["Spanish"] = "Fundir korio",
			["Taiwanese"] = "熔煉克銀錠",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29686,
		["item_id"] = 23573,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "熔炼硬化精金",
			["English"] = "Smelt Hardened Adamantite",
			["French"] = "Fonte de l'adamantite trempé",
			["German"] = "Gehärtetes Adamantit verhütten",
			["Korean"] = "강화된 아다만타이트 제련",
			["Mexican"] = "Fundir adamantita endurecida",
			["Portuguese"] = "Fundir Adamantita Temperada",
			["Russian"] = "Выплавка закаленного адамантита",
			["Spanish"] = "Fundir adamantita endurecida",
			["Taiwanese"] = "熔煉特堅鋼錠",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35750,
		["item_id"] = 22573,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "敲碎源生之土",
			["English"] = "Earth Shatter",
			["French"] = "Brise-terre",
			["German"] = "Erdspaltung",
			["Korean"] = "대지의 근원을 티끌로",
			["Mexican"] = "Desmenuzar tierra",
			["Portuguese"] = "Estilhaçar Terra",
			["Russian"] = "Разлом земли",
			["Spanish"] = "Desmenuzar tierra",
			["Taiwanese"] = "大地破碎",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35751,
		["item_id"] = 22574,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "火焰碎裂",
			["English"] = "Fire Sunder",
			["French"] = "Scission du feu",
			["German"] = "Feuerspaltung",
			["Korean"] = "불의 근원을 티끌로",
			["Mexican"] = "Hender Fuego",
			["Portuguese"] = "Partir Fogo",
			["Russian"] = "Разложение огня",
			["Spanish"] = "Hender Fuego",
			["Taiwanese"] = "火焰分離",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				18747,
				18779,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 46353,
		["item_id"] = 35128,
		["items"] = {
			35273,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "熔炼硬化氪金",
			["English"] = "Smelt Hardened Khorium",
			["French"] = "Fonte du khorium trempé",
			["German"] = "Gehärtetes Khorium verhütten",
			["Korean"] = "강화 코륨 제련",
			["Mexican"] = "Fundir korio endurecido",
			["Portuguese"] = "Fundir Kório Temperado",
			["Russian"] = "Выплавка закаленного кория",
			["Spanish"] = "Fundir korio endurecido",
			["Taiwanese"] = "熔煉硬化克銀",
		},
		["phase"] = 5,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Mining"], skill)
end
