-------------------------------------------------------
-- All items (Tailoring) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Tailoring"] then RR_DATA["items"]["Tailoring"] = {} end
local tbc_items = 
{
	{
		["expansion"] = 2,
		["id"] = 21892,
		["name"] = {
			["Chinese"] = "图样：魔化灵纹布卷",
			["English"] = "Pattern: Bolt of Imbued Netherweave",
			["French"] = "Patron : Rouleau de tisse-néant imprégné",
			["German"] = "Muster: Magieerfüllter Netherstoffballen",
			["Korean"] = "도안: 마력 깃든 황천매듭 두루마리",
			["Mexican"] = "Patrón: madeja de tejido abisal imbuido",
			["Portuguese"] = "Molde: Peça de Etertrama Imbuída",
			["Russian"] = "Выкройка: рулон прочной ткани Пустоты",
			["Spanish"] = "Patrón: madeja de tejido abisal imbuido",
			["Taiwanese"] = "圖樣:魔染幽紋布卷",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16638,
				16767,
				19213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21893,
		["name"] = {
			["Chinese"] = "图样：魔化灵纹布包",
			["English"] = "Pattern: Imbued Netherweave Bag",
			["French"] = "Patron : Sac en tisse-néant imprégné",
			["German"] = "Muster: Magieerfüllte Netherstofftasche",
			["Korean"] = "도안: 마력 깃든 황천매듭 가방",
			["Mexican"] = "Patrón: bolsa de tejido abisal imbuido",
			["Portuguese"] = "Molde: Bolsa de Etertrama Imbuída",
			["Russian"] = "Выкройка: сумка из прочной ткани Пустоты",
			["Spanish"] = "Patrón: bolsa de tejido abisal imbuido",
			["Taiwanese"] = "圖樣:魔染幽紋布包",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				19015,
				19213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21894,
		["name"] = {
			["Chinese"] = "图样：灵魂布卷",
			["English"] = "Pattern: Bolt of Soulcloth",
			["French"] = "Patron : Rouleau d'âmétoffe",
			["German"] = "Muster: Seelenstoffballen",
			["Korean"] = "도안: 영혼매듭 두루마리",
			["Mexican"] = "Patrón: madeja de paño de alma",
			["Portuguese"] = "Molde: Peça de Almatrama",
			["Russian"] = "Выкройка: рулон ткани Душ",
			["Spanish"] = "Patrón: madeja de paño de alma",
			["Taiwanese"] = "圖樣:靈魂布卷",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16638,
				16767,
				19015,
				19017,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21895,
		["name"] = {
			["Chinese"] = "图样：原始月布",
			["English"] = "Pattern: Primal Mooncloth",
			["French"] = "Patron : Etoffe lunaire primordiale",
			["German"] = "Muster: Urmondstoff",
			["Korean"] = "도안: 태초의 달빛 옷감",
			["Mexican"] = "Patrón: tela lunar primigenia",
			["Portuguese"] = "Molde: Lunatrama Primeva",
			["Russian"] = "Выкройка: изначальная луноткань",
			["Spanish"] = "Patrón: tela lunar primigenia",
			["Taiwanese"] = "圖樣:原始月布",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				22208,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21896,
		["name"] = {
			["Chinese"] = "图样：灵纹长袍",
			["English"] = "Pattern: Netherweave Robe",
			["French"] = "Patron : Robe en tisse-néant",
			["German"] = "Muster: Netherstoffrobe",
			["Korean"] = "도안: 황천매듭 로브",
			["Mexican"] = "Patrón: toga de tejido abisal",
			["Portuguese"] = "Molde: Veste de Etertrama",
			["Russian"] = "Выкройка: одеяние из ткани Пустоты",
			["Spanish"] = "Patrón: toga de tejido abisal",
			["Taiwanese"] = "圖樣:幽紋長袍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16638,
				16767,
				19213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21897,
		["name"] = {
			["Chinese"] = "图样：灵纹外套",
			["English"] = "Pattern: Netherweave Tunic",
			["French"] = "Patron : Tunique en tisse-néant",
			["German"] = "Muster: Netherstofftunika",
			["Korean"] = "도안: 황천매듭 튜닉",
			["Mexican"] = "Patrón: guerrera de tejido abisal",
			["Portuguese"] = "Molde: Túnica de Etertrama",
			["Russian"] = "Выкройка: мундир из ткани Пустоты",
			["Spanish"] = "Patrón: túnica de tejido abisal",
			["Taiwanese"] = "圖樣:幽紋外套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16638,
				16767,
				19213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21898,
		["name"] = {
			["Chinese"] = "图样：魔化灵纹短裤",
			["English"] = "Pattern: Imbued Netherweave Pants",
			["French"] = "Patron : Pantalon en tisse-néant imprégné",
			["German"] = "Muster: Magieerfüllte Netherstoffhose",
			["Korean"] = "도안: 마력 깃든 황천매듭 바지",
			["Mexican"] = "Patrón: pantalones de tejido abisal imbuido",
			["Portuguese"] = "Molde: Calças de Etertrama Imbuídas",
			["Russian"] = "Выкройка: штаны из прочной ткани Пустоты",
			["Spanish"] = "Patrón: pantalones de tejido abisal imbuido",
			["Taiwanese"] = "圖樣:魔染幽紋便褲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				18011,
				19722,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21899,
		["name"] = {
			["Chinese"] = "图样：魔化灵纹长靴",
			["English"] = "Pattern: Imbued Netherweave Boots",
			["French"] = "Patron : Bottes en tisse-néant imprégné",
			["German"] = "Muster: Magieerfüllte Netherstoffstiefel",
			["Korean"] = "도안: 마력 깃든 황천매듭 장화",
			["Mexican"] = "Patrón: botas de tejido abisal imbuido",
			["Portuguese"] = "Molde: Botas de Etertrama Imbuídas",
			["Russian"] = "Выкройка: сапоги из прочной ткани Пустоты",
			["Spanish"] = "Patrón: botas de tejido abisal imbuido",
			["Taiwanese"] = "圖樣:魔染幽紋長靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				18011,
				19722,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21900,
		["name"] = {
			["Chinese"] = "图样：魔化灵纹长袍",
			["English"] = "Pattern: Imbued Netherweave Robe",
			["French"] = "Patron : Robe en tisse-néant imprégné",
			["German"] = "Muster: Magieerfüllte Netherstoffrobe",
			["Korean"] = "도안: 마력 깃든 황천매듭 로브",
			["Mexican"] = "Patrón: toga de tejido abisal imbuido",
			["Portuguese"] = "Molde: Veste de Etertrama Imbuída",
			["Russian"] = "Выкройка: одеяние из прочной ткани Пустоты",
			["Spanish"] = "Patrón: toga de tejido abisal imbuido",
			["Taiwanese"] = "圖樣:魔染幽紋長袍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19521,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21901,
		["name"] = {
			["Chinese"] = "图样：魔化灵纹外套",
			["English"] = "Pattern: Imbued Netherweave Tunic",
			["French"] = "Patron : Tunique en tisse-néant imprégné",
			["German"] = "Muster: Magieerfüllte Netherstofftunika",
			["Korean"] = "도안: 마력 깃든 황천매듭 튜닉",
			["Mexican"] = "Patrón: guerrera de tejido abisal imbuido",
			["Portuguese"] = "Molde: Túnica de Etertrama Imbuída",
			["Russian"] = "Выкройка: мундир из прочной ткани Пустоты",
			["Spanish"] = "Patrón: túnica de tejido abisal imbuido",
			["Taiwanese"] = "圖樣:魔染幽紋外套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19521,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21902,
		["name"] = {
			["Chinese"] = "图样：灵魂布手套",
			["English"] = "Pattern: Soulcloth Gloves",
			["French"] = "Patron : Gants d'âmétoffe",
			["German"] = "Muster: Seelenstoffhandschuhe",
			["Korean"] = "도안: 영혼매듭 장갑",
			["Mexican"] = "Patrón: guantes de paño de alma",
			["Portuguese"] = "Molde: Luvas de Almatrama",
			["Russian"] = "Выкройка: перчатки из ткани Душ",
			["Spanish"] = "Patrón: guantes de paño de alma",
			["Taiwanese"] = "圖樣:靈魂布手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19015,
				19017,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				16406,
			},
		},
		["expansion"] = 2,
		["id"] = 21903,
		["name"] = {
			["Chinese"] = "图样：灵魂布护肩",
			["English"] = "Pattern: Soulcloth Shoulders",
			["French"] = "Patron : Epaulières d'âmétoffe",
			["German"] = "Muster: Seelenstoffschultern",
			["Korean"] = "도안: 영혼매듭 어깨보호구",
			["Mexican"] = "Patrón: sobrehombros de paño de alma",
			["Portuguese"] = "Molde: Omoplatas de Almatrama",
			["Russian"] = "Выкройка: наплечники из ткани Душ",
			["Spanish"] = "Patrón: sobrehombros de paño de alma",
			["Taiwanese"] = "圖樣:靈魂布護肩",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				16408,
			},
		},
		["expansion"] = 2,
		["id"] = 21904,
		["name"] = {
			["Chinese"] = "图样：灵魂布外衣",
			["English"] = "Pattern: Soulcloth Vest",
			["French"] = "Patron : Gilet d'âmétoffe",
			["German"] = "Muster: Seelenstoffweste",
			["Korean"] = "도안: 영혼매듭 조끼",
			["Mexican"] = "Patrón: jubón de paño de alma",
			["Portuguese"] = "Molde: Colete de Almatrama",
			["Russian"] = "Выкройка: жилет из ткани Душ",
			["Spanish"] = "Patrón: jubón de paño de alma",
			["Taiwanese"] = "圖樣:靈魂布外衣",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				20869,
			},
		},
		["expansion"] = 2,
		["id"] = 21905,
		["name"] = {
			["Chinese"] = "图样：奥法交织护腕",
			["English"] = "Pattern: Arcanoweave Bracers",
			["French"] = "Patron : Brassards en tisse-arcane",
			["German"] = "Muster: Arkanostoffarmschienen",
			["Korean"] = "도안: 비전매듭 팔보호구",
			["Mexican"] = "Patrón: brazales de tejido Arcano",
			["Portuguese"] = "Molde: Braçadeiras de Arcanotrama",
			["Russian"] = "Выкройка: наручи из тайной ткани",
			["Spanish"] = "Patrón: brazales de tejido Arcano",
			["Taiwanese"] = "圖樣:奧紋護腕",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				19168,
			},
		},
		["expansion"] = 2,
		["id"] = 21906,
		["name"] = {
			["Chinese"] = "图样：奥法交织长靴",
			["English"] = "Pattern: Arcanoweave Boots",
			["French"] = "Patron : Bottes en tisse-arcane",
			["German"] = "Muster: Arkanostoffstiefel",
			["Korean"] = "도안: 비전매듭 장화",
			["Mexican"] = "Patrón: botas de tejido Arcano",
			["Portuguese"] = "Molde: Botas de Arcanotrama",
			["Russian"] = "Выкройка: сапоги из тайной ткани",
			["Spanish"] = "Patrón: botas de tejido Arcano",
			["Taiwanese"] = "圖樣:奧紋長靴",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["drops"] = {
			["sources"] = {
				19220,
			},
		},
		["expansion"] = 2,
		["id"] = 21907,
		["name"] = {
			["Chinese"] = "图样：奥法交织长袍",
			["English"] = "Pattern: Arcanoweave Robe",
			["French"] = "Patron : Robe en tisse-arcane",
			["German"] = "Muster: Arkanostoffrobe",
			["Korean"] = "도안: 비전매듭 로브",
			["Mexican"] = "Patrón: toga de tejido Arcano",
			["Portuguese"] = "Molde: Veste de Arcanotrama",
			["Russian"] = "Выкройка: одеяние из тайной ткани",
			["Spanish"] = "Patrón: toga de tejido Arcano",
			["Taiwanese"] = "圖樣:奧紋長袍",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 21908,
		["name"] = {
			["Chinese"] = "图样：魔焰腰带",
			["English"] = "Pattern: Spellfire Belt",
			["French"] = "Patron : Ceinture du feu-sorcier",
			["German"] = "Muster: Zauberfeuergürtel",
			["Korean"] = "도안: 마법불꽃 허리띠",
			["Mexican"] = "Patrón: cinturón de fuego de hechizo",
			["Portuguese"] = "Molde: Cinto de Fogo Místico",
			["Russian"] = "Выкройка: пояс из огненной чароткани",
			["Spanish"] = "Patrón: cinturón fuego de hechizo",
			["Taiwanese"] = "圖樣:魔焰腰帶",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21909,
		["name"] = {
			["Chinese"] = "图样：魔焰手套",
			["English"] = "Pattern: Spellfire Gloves",
			["French"] = "Patron : Gants du feu-sorcier",
			["German"] = "Muster: Zauberfeuerhandschuhe",
			["Korean"] = "도안: 마법불꽃 장갑",
			["Mexican"] = "Patrón: guantes de fuego de hechizo",
			["Portuguese"] = "Molde: Luvas de Fogo Místico",
			["Russian"] = "Выкройка: перчатки из огненной чароткани",
			["Spanish"] = "Patrón: guantes fuego de hechizo",
			["Taiwanese"] = "圖樣:魔焰手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21910,
		["name"] = {
			["Chinese"] = "图样：魔焰长袍",
			["English"] = "Pattern: Spellfire Robe",
			["French"] = "Patron : Robe du feu-sorcier",
			["German"] = "Muster: Zauberfeuerrobe",
			["Korean"] = "도안: 마법불꽃 로브",
			["Mexican"] = "Patrón: toga de fuego de hechizo",
			["Portuguese"] = "Molde: Veste de Fogo Místico",
			["Russian"] = "Выкройка: одеяние из огненной чароткани",
			["Spanish"] = "Patrón: toga fuego de hechizo",
			["Taiwanese"] = "圖樣:魔焰長袍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21911,
		["name"] = {
			["Chinese"] = "图样：魔焰背包",
			["English"] = "Pattern: Spellfire Bag",
			["French"] = "Patron : Sac du feu-sorcier",
			["German"] = "Muster: Zauberfeuertasche",
			["Korean"] = "도안: 마법불꽃 가방",
			["Mexican"] = "Patrón: bolsa de fuego de hechizo",
			["Portuguese"] = "Molde: Bolsa de Fogo Místico",
			["Russian"] = "Выкройка: сумка из огненной чароткани",
			["Spanish"] = "Patrón: bolsa fuego de hechizo",
			["Taiwanese"] = "圖樣:魔焰包",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22213,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21912,
		["name"] = {
			["Chinese"] = "图样：冰霜暗纹护肩",
			["English"] = "Pattern: Frozen Shadoweave Shoulders",
			["French"] = "Patron : Epaulières en tisse-ombre gelé",
			["German"] = "Muster: Eisschattenzwirnschultern",
			["Korean"] = "도안: 얼어붙은 그림자매듭 어깨보호구",
			["Mexican"] = "Patrón: sobrehombros de tejido de sombra congelado",
			["Portuguese"] = "Molde: Omoplatas de Umbratrama Congeladas",
			["Russian"] = "Выкройка: наплечники из застывшей тенеткани",
			["Spanish"] = "Patrón: sobrehombros de tejido de sombra congelado",
			["Taiwanese"] = "圖樣:冰霜影紋護肩",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22212,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21913,
		["name"] = {
			["Chinese"] = "图样：冰霜暗纹长袍",
			["English"] = "Pattern: Frozen Shadoweave Robe",
			["French"] = "Patron : Robe en tisse-ombre gelé",
			["German"] = "Muster: Eisschattenzwirnrobe",
			["Korean"] = "도안: 얼어붙은 그림자매듭 로브",
			["Mexican"] = "Patrón: toga de tejido de sombra congelado",
			["Portuguese"] = "Molde: Veste de Umbratrama Congelada",
			["Russian"] = "Выкройка: одеяние из застывшей тенеткани",
			["Spanish"] = "Patrón: toga de tejido de sombra congelado",
			["Taiwanese"] = "圖樣:冰霜影紋長袍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22212,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21914,
		["name"] = {
			["Chinese"] = "图样：冰霜暗纹长靴",
			["English"] = "Pattern: Frozen Shadoweave Boots",
			["French"] = "Patron : Bottes en tisse-ombre gelé",
			["German"] = "Muster: Eisschattenzwirnstiefel",
			["Korean"] = "도안: 얼어붙은 그림자매듭 장화",
			["Mexican"] = "Patrón: botas de tejido de sombra congelado",
			["Portuguese"] = "Molde: Botas de Umbratrama Congeladas",
			["Russian"] = "Выкройка: сапоги из застывшей тенеткани",
			["Spanish"] = "Patrón: botas de tejido de sombra congelado",
			["Taiwanese"] = "圖樣:冰霜影紋之靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22212,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21915,
		["name"] = {
			["Chinese"] = "图样：黑色暗影背包",
			["English"] = "Pattern: Ebon Shadowbag",
			["French"] = "Patron : Ombresac d'ébène",
			["German"] = "Muster: Schwarzschattentasche",
			["Korean"] = "도안: 칠흑의 암흑 가방",
			["Mexican"] = "Patrón: bolsa de Sombra de ébano",
			["Portuguese"] = "Molde: Bolsombra Ebânea",
			["Russian"] = "Выкройка: черная сумка теней",
			["Spanish"] = "Patrón: bolsa de Sombra de ébano",
			["Taiwanese"] = "圖樣:黑檀暗影包",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22212,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21916,
		["name"] = {
			["Chinese"] = "图样：原始月布腰带",
			["English"] = "Pattern: Primal Mooncloth Belt",
			["French"] = "Patron : Ceinture d'étoffe lunaire primordiale",
			["German"] = "Muster: Urmondstoffgürtel",
			["Korean"] = "도안: 태초의 달빛매듭 허리띠",
			["Mexican"] = "Patrón: cinturón de tela lunar primigenia",
			["Portuguese"] = "Molde: Cinto de Lunatrama Primeva",
			["Russian"] = "Выкройка: пояс из изначальной луноткани",
			["Spanish"] = "Patrón: cinturón de tela lunar primigenia",
			["Taiwanese"] = "圖樣:原始月布腰帶",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22208,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21917,
		["name"] = {
			["Chinese"] = "图样：原始月布长袍",
			["English"] = "Pattern: Primal Mooncloth Robe",
			["French"] = "Patron : Robe d'étoffe lunaire primordiale",
			["German"] = "Muster: Urmondstoffrobe",
			["Korean"] = "도안: 태초의 달빛매듭 로브",
			["Mexican"] = "Patrón: toga de tela lunar primigenia",
			["Portuguese"] = "Molde: Veste de Lunatrama Primeva",
			["Russian"] = "Выкройка: одеяние из изначальной луноткани",
			["Spanish"] = "Patrón: toga de tela lunar primigenia",
			["Taiwanese"] = "圖樣:原始月布長袍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22208,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21918,
		["name"] = {
			["Chinese"] = "图样：原始月布护肩",
			["English"] = "Pattern: Primal Mooncloth Shoulders",
			["French"] = "Patron : Epaulières d'étoffe lunaire primordiale",
			["German"] = "Muster: Urmondstoffschultern",
			["Korean"] = "도안: 태초의 달빛매듭 어깨보호대",
			["Mexican"] = "Patrón: sobrehombros de tela lunar primigenia",
			["Portuguese"] = "Molde: Omoplatas de Lunatrama Primeva",
			["Russian"] = "Выкройка: наплечники из изначальной луноткани",
			["Spanish"] = "Patrón: sobrehombros de tela lunar primigenia",
			["Taiwanese"] = "圖樣:原始月布護肩",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22208,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 21919,
		["name"] = {
			["Chinese"] = "图样：原始月布包",
			["English"] = "Pattern: Primal Mooncloth Bag",
			["French"] = "Patron : Sac d'étoffe lunaire primordiale",
			["German"] = "Muster: Urmondstofftasche",
			["Korean"] = "도안: 태초의 달빛매듭 가방",
			["Mexican"] = "Patrón: bolsa de tela lunar primigenia",
			["Portuguese"] = "Molde: Bolsa de Lunatrama Primeva",
			["Russian"] = "Выкройка: сумка из изначальной луноткани",
			["Spanish"] = "Patrón: bolsa de tela lunar primigenia",
			["Taiwanese"] = "圖樣:原始月布包",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				22208,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24292,
		["name"] = {
			["Chinese"] = "图样：秘法魔线",
			["English"] = "Pattern: Mystic Spellthread",
			["French"] = "Patron : Fil ensorcelé mystique",
			["German"] = "Muster: Mystischer Zauberfaden",
			["Korean"] = "도안: 신비한 마력의 실타래",
			["Mexican"] = "Patrón: hilo de hechizo místico",
			["Portuguese"] = "Molde: Magilinha Mística",
			["Russian"] = "Выкройка: таинственная чародейская нить",
			["Spanish"] = "Patrón: hilo de hechizo místico",
			["Taiwanese"] = "圖樣:神秘法術絲線",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24293,
		["name"] = {
			["Chinese"] = "图样：银色魔线",
			["English"] = "Pattern: Silver Spellthread",
			["French"] = "Patron : Fil ensorcelé argenté",
			["German"] = "Muster: Silberner Zauberfaden",
			["Korean"] = "도안: 마력의 은 실타래",
			["Mexican"] = "Patrón: hilo de hechizo de plata",
			["Portuguese"] = "Molde: Magilinha Prateada",
			["Russian"] = "Выкройка: серебряная чародейская нить",
			["Spanish"] = "Patrón: hilo de hechizo de plata",
			["Taiwanese"] = "圖樣:銀色法術絲線",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24294,
		["name"] = {
			["Chinese"] = "图样：符文魔线",
			["English"] = "Pattern: Runic Spellthread",
			["French"] = "Patron : Fil ensorcelé runique",
			["German"] = "Muster: Runenverzierter Zauberfaden",
			["Korean"] = "도안: 마력의 룬문자 실타래",
			["Mexican"] = "Patrón: hilo de hechizo rúnico",
			["Portuguese"] = "Molde: Magilinha Rúnica",
			["Russian"] = "Выкройка: руническая чародейская нить",
			["Spanish"] = "Patrón: hilo de hechizo rúnico",
			["Taiwanese"] = "圖樣:符文法術絲線",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 360000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24295,
		["name"] = {
			["Chinese"] = "图样：金色魔线",
			["English"] = "Pattern: Golden Spellthread",
			["French"] = "Patron : Fil ensorcelé doré",
			["German"] = "Muster: Goldener Zauberfaden",
			["Korean"] = "도안: 마력의 황금 실타래",
			["Mexican"] = "Patrón: hilo de hechizo dorado",
			["Portuguese"] = "Molde: Magilinha Dourada",
			["Russian"] = "Выкройка: золотая чародейская нить",
			["Spanish"] = "Patrón: hilo de hechizo dorado",
			["Taiwanese"] = "圖樣:金色法術絲線",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 360000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 24296,
		["name"] = {
			["Chinese"] = "图样：不屈护腕",
			["English"] = "Pattern: Unyielding Bracers",
			["French"] = "Patron : Brassards inflexibles",
			["German"] = "Muster: Armschienen des Unerschütterlichen",
			["Korean"] = "도안: 불굴의 팔보호구",
			["Mexican"] = "Patrón: brazales implacables",
			["Portuguese"] = "Molde: Braçadeiras Obstinadas",
			["Russian"] = "Выкройка: наручи непреклонности",
			["Spanish"] = "Patrón: brazales implacables",
			["Taiwanese"] = "圖樣:不屈護腕",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				19428,
				21904,
				18317,
			},
		},
		["expansion"] = 2,
		["id"] = 24297,
		["name"] = {
			["Chinese"] = "图样：浩劫护腕",
			["English"] = "Pattern: Bracers of Havok",
			["French"] = "Patron : Brassards de Sans-quartier",
			["German"] = "Muster: Armschienen der Verwüstung",
			["Korean"] = "도안: 대혼란의 팔보호구",
			["Mexican"] = "Patrón: brazales del caos",
			["Portuguese"] = "Molde: Braçadeiras da Tormenta",
			["Russian"] = "Выкройка: наручи Разора",
			["Spanish"] = "Patrón: Brazales del caos",
			["Taiwanese"] = "圖樣:哈伏克護腕",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18323,
			},
		},
		["expansion"] = 2,
		["id"] = 24298,
		["name"] = {
			["Chinese"] = "图样：黑色侵袭护腕",
			["English"] = "Pattern: Blackstrike Bracers",
			["French"] = "Patron : Brassards de noire frappe",
			["German"] = "Muster: Schwarzgestreifte Armschienen",
			["Korean"] = "도안: 검은 강타의 팔보호구",
			["Mexican"] = "Patrón: brazales golpenegro",
			["Portuguese"] = "Molde: Braçadeiras Golpenegro",
			["Russian"] = "Выкройка: наручи Черного удара",
			["Spanish"] = "Patrón: brazales golpenegro",
			["Taiwanese"] = "圖樣:黑擊護腕",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18848,
			},
		},
		["expansion"] = 2,
		["id"] = 24299,
		["name"] = {
			["Chinese"] = "图样：黑色虚空披风",
			["English"] = "Pattern: Cloak of the Black Void",
			["French"] = "Patron : Cape du vide noir",
			["German"] = "Muster: Umhang der schwarzen Leere",
			["Korean"] = "도안: 검은 공허의 망토",
			["Mexican"] = "Patrón: capa del Vacío Negro",
			["Portuguese"] = "Molde: Manto do Caos Negro",
			["Russian"] = "Выкройка: плащ черной бездны",
			["Spanish"] = "Patrón: capa del Vacío Negro",
			["Taiwanese"] = "圖樣:黑色虛無披風",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				16949,
				18171,
				18328,
				18314,
			},
		},
		["expansion"] = 2,
		["id"] = 24300,
		["name"] = {
			["Chinese"] = "图样：永恒披风",
			["English"] = "Pattern: Cloak of Eternity",
			["French"] = "Patron : Cape d'éternité",
			["German"] = "Muster: Umhang der Ewigkeit",
			["Korean"] = "도안: 영원의 망토",
			["Mexican"] = "Patrón: capa de eternidad",
			["Portuguese"] = "Molde: Manto da Eternidade",
			["Russian"] = "Выкройка: плащ вечности",
			["Spanish"] = "Patrón: capa de eternidad",
			["Taiwanese"] = "圖樣:永恆披風",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				19428,
			},
		},
		["expansion"] = 2,
		["id"] = 24301,
		["name"] = {
			["Chinese"] = "图样：白色治愈斗篷",
			["English"] = "Pattern: White Remedy Cape",
			["French"] = "Patron : Cape du remède blanc",
			["German"] = "Muster: Weißer Arzneikittel",
			["Korean"] = "도안: 백색 치유의 외투",
			["Mexican"] = "Patrón: manteo blanco de enmienda",
			["Portuguese"] = "Molde: Capa Curativa Branca",
			["Russian"] = "Выкройка: белая лечебная накидка",
			["Spanish"] = "Patrón: manteo blanco de enmienda",
			["Taiwanese"] = "圖樣:白色治療斗篷",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 24302,
		["name"] = {
			["Chinese"] = "图样：不屈束带",
			["English"] = "Pattern: Unyielding Girdle",
			["French"] = "Patron : Ceinturon inflexible",
			["German"] = "Muster: Gurt des Unerschütterlichen",
			["Korean"] = "도안: 불굴의 벨트",
			["Mexican"] = "Patrón: faja implacable",
			["Portuguese"] = "Molde: Cinturão Obstinado",
			["Russian"] = "Выкройка: ремень непреклонности",
			["Spanish"] = "Patrón: faja implacable",
			["Taiwanese"] = "圖樣:不屈束腰",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				17860,
				17882,
			},
		},
		["expansion"] = 2,
		["id"] = 24303,
		["name"] = {
			["Chinese"] = "图样：毁灭束带",
			["English"] = "Pattern: Girdle of Ruination",
			["French"] = "Patron : Ceinturon de saccage",
			["German"] = "Muster: Gurt der Zerstörung",
			["Korean"] = "도안: 몰락의 벨트",
			["Mexican"] = "Patrón: faja de ruina",
			["Portuguese"] = "Molde: Cinturão da Ruína",
			["Russian"] = "Выкройка: ремень опустошения",
			["Spanish"] = "Patrón: faja de ruina",
			["Taiwanese"] = "圖樣:禍根束腰",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				17802,
			},
		},
		["expansion"] = 2,
		["id"] = 24304,
		["name"] = {
			["Chinese"] = "图样：黑色知识腰带",
			["English"] = "Pattern: Black Belt of Knowledge",
			["French"] = "Patron : Ceinture noire de connaissance",
			["German"] = "Muster: Schwarzer Gürtel des Wissens",
			["Korean"] = "도안: 지식의 검은 허리띠",
			["Mexican"] = "Patrón: cinturón negro de sabiduría",
			["Portuguese"] = "Molde: Cinto Preto do Conhecimento",
			["Russian"] = "Выкройка: черный пояс знания",
			["Spanish"] = "Patrón: cinturón negro de sabiduría",
			["Taiwanese"] = "圖樣:黑色學識腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				18323,
			},
		},
		["expansion"] = 2,
		["id"] = 24305,
		["name"] = {
			["Chinese"] = "图样：坚毅披风",
			["English"] = "Pattern: Resolute Cape",
			["French"] = "Patron : Cape résolue",
			["German"] = "Muster: Cape der Entschlossenheit",
			["Korean"] = "도안: 결의의 외투",
			["Mexican"] = "Patrón: manteo de resolución",
			["Portuguese"] = "Molde: Capa Resoluta",
			["Russian"] = "Выкройка: накидка твердости",
			["Spanish"] = "Patrón: manteo de resolución",
			["Taiwanese"] = "圖樣:堅決斗篷",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 24306,
		["name"] = {
			["Chinese"] = "图样：复仇披风",
			["English"] = "Pattern: Vengeance Wrap",
			["French"] = "Patron : Houppelande vengeresse",
			["German"] = "Muster: Wickeltuch der Vergeltung",
			["Korean"] = "도안: 복수의 외투",
			["Mexican"] = "Patrón: sobrevesta de venganza",
			["Portuguese"] = "Molde: Mantelete da Vingança",
			["Russian"] = "Выкройка: плащ отмщения",
			["Spanish"] = "Patrón: brazalete de venganza",
			["Taiwanese"] = "圖樣:復仇裹布",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				18497,
				18524,
			},
		},
		["expansion"] = 2,
		["id"] = 24307,
		["name"] = {
			["Chinese"] = "图样：法力编织披风",
			["English"] = "Pattern: Manaweave Cloak",
			["French"] = "Patron : Cape en tisse-mana",
			["German"] = "Muster: Managewirkter Umhang",
			["Korean"] = "도안: 마나매듭 망토",
			["Mexican"] = "Patrón: capa de tejido de maná",
			["Portuguese"] = "Molde: Manto de Manatrama",
			["Russian"] = "Выкройка: плащ из ткани маны",
			["Spanish"] = "Patrón: capa de tejido de maná",
			["Taiwanese"] = "圖樣:法力之紋披風",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				20885,
			},
		},
		["expansion"] = 2,
		["id"] = 24308,
		["name"] = {
			["Chinese"] = "图样：白色治愈短裤",
			["English"] = "Pattern: Whitemend Pants",
			["French"] = "Patron : Pantalon de la blanche guérison",
			["German"] = "Muster: Hose des weißen Heilers",
			["Korean"] = "도안: 백마법 바지",
			["Mexican"] = "Patrón: pantalones con remiendos blancos",
			["Portuguese"] = "Molde: Calças Remendalvas",
			["Russian"] = "Выкройка: штаны Белого целителя",
			["Spanish"] = "Patrón: pantalones con remiendos blancos",
			["Taiwanese"] = "圖樣:白癒便褲",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				18708,
			},
		},
		["expansion"] = 2,
		["id"] = 24309,
		["name"] = {
			["Chinese"] = "图样：法术打击短裤",
			["English"] = "Pattern: Spellstrike Pants",
			["French"] = "Patron : Pantalon frappe-sort",
			["German"] = "Muster: Hose des Zauberschlags",
			["Korean"] = "도안: 마법 강타의 바지",
			["Mexican"] = "Patrón: pantalones de golpe de hechizo",
			["Portuguese"] = "Molde: Calças do Golpe Mágico",
			["Russian"] = "Выкройка: штаны сокрушительной магии",
			["Spanish"] = "Patrón: pantalones de golpe de hechizo",
			["Taiwanese"] = "圖樣:法擊便褲",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				17978,
			},
		},
		["expansion"] = 2,
		["id"] = 24310,
		["name"] = {
			["Chinese"] = "图样：战斗施法短裤",
			["English"] = "Pattern: Battlecast Pants",
			["French"] = "Patron : Pantalon d'escarmouche",
			["German"] = "Muster: Hose des Schlachtenzaubers",
			["Korean"] = "도안: 전투시전술 바지",
			["Mexican"] = "Patrón: pantalones de conjuro de batalla",
			["Portuguese"] = "Molde: Calças de Feitiço Bélico",
			["Russian"] = "Выкройка: штаны боевого заклятья",
			["Spanish"] = "Patrón: pantalones de conjuro de batalla",
			["Taiwanese"] = "圖樣:戰放便褲",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				17977,
			},
		},
		["expansion"] = 2,
		["id"] = 24311,
		["name"] = {
			["Chinese"] = "图样：白色治愈兜帽",
			["English"] = "Pattern: Whitemend Hood",
			["French"] = "Patron : Chaperon de la blanche guérison",
			["German"] = "Muster: Kapuze des weißen Heilers",
			["Korean"] = "도안: 백마법 두건",
			["Mexican"] = "Patrón: caperuza con remiendos blancos",
			["Portuguese"] = "Molde: Capuz Remendalvo",
			["Russian"] = "Выкройка: капюшон Белого целителя",
			["Spanish"] = "Patrón: caperuza con remiendos blancos",
			["Taiwanese"] = "圖樣:白癒兜帽",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				16807,
			},
		},
		["expansion"] = 2,
		["id"] = 24312,
		["name"] = {
			["Chinese"] = "图样：法术打击兜帽",
			["English"] = "Pattern: Spellstrike Hood",
			["French"] = "Patron : Chaperon frappe-sort",
			["German"] = "Muster: Kapuze des Zauberschlags",
			["Korean"] = "도안: 마법 강타의 두건",
			["Mexican"] = "Patrón: caperuza de golpe de hechizo",
			["Portuguese"] = "Molde: Capuz do Golpe Mágico",
			["Russian"] = "Выкройка: капюшон сокрушительной магии",
			["Spanish"] = "Patrón: caperuza de golpe de hechizo",
			["Taiwanese"] = "圖樣:法擊兜帽",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				17798,
			},
		},
		["expansion"] = 2,
		["id"] = 24313,
		["name"] = {
			["Chinese"] = "图样：战斗施法罩帽",
			["English"] = "Pattern: Battlecast Hood",
			["French"] = "Patron : Chaperon d'escarmouche",
			["German"] = "Muster: Kapuze des Schlachtenzaubers",
			["Korean"] = "도안: 전투시전술 두건",
			["Mexican"] = "Patrón: caperuza de conjuro de batalla",
			["Portuguese"] = "Molde: Capuz de Feitiço Bélico",
			["Russian"] = "Выкройка: капюшон боевого заклятья",
			["Spanish"] = "Patrón: caperuza de conjuro de batalla",
			["Taiwanese"] = "圖樣:戰放兜帽",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 24314,
		["name"] = {
			["Chinese"] = "图样：珠宝袋",
			["English"] = "Pattern: Bag of Jewels",
			["French"] = "Patron : Sac de joyaux",
			["German"] = "Muster: Juwelenbeutel",
			["Korean"] = "도안: 보석 자루",
			["Mexican"] = "Patrón: bolsa de joyas",
			["Portuguese"] = "Molde: Saco de Joias",
			["Russian"] = "Выкройка: мешочек для драгоценностей",
			["Spanish"] = "Patrón: bolsa de joyas",
			["Taiwanese"] = "圖樣:寶石包",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 933,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				20242,
				23007,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 24316,
		["name"] = {
			["Chinese"] = "图样：魔法布",
			["English"] = "Pattern: Spellcloth",
			["French"] = "Patron : Etoffe ensorcelée",
			["German"] = "Muster: Zauberstoff",
			["Korean"] = "도안: 마력 깃든 옷감",
			["Mexican"] = "Patrón: paño de hechizos",
			["Portuguese"] = "Molde: Encantrama",
			["Russian"] = "Выкройка: чароткань",
			["Spanish"] = "Patrón: paño de hechizos",
			["Taiwanese"] = "圖樣:魔法布",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				22213,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				20046,
				21212,
				21214,
				21217,
			},
		},
		["expansion"] = 2,
		["id"] = 30280,
		["name"] = {
			["Chinese"] = "图样：冲击腰带",
			["English"] = "Pattern: Belt of Blasting",
			["French"] = "Patron : Ceinture d'explosion",
			["German"] = "Muster: Gürtel der Zauberwucht",
			["Korean"] = "도안: 발파의 허리띠",
			["Mexican"] = "Patrón: cinturón de detonación",
			["Portuguese"] = "Molde: Cinto do Impacto",
			["Russian"] = "Выкройка: пояс взрыва",
			["Spanish"] = "Patrón: cinturón de detonación",
			["Taiwanese"] = "圖樣:衝擊腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				20046,
				21212,
				21213,
				21214,
				21216,
			},
		},
		["expansion"] = 2,
		["id"] = 30281,
		["name"] = {
			["Chinese"] = "图样：长路腰带",
			["English"] = "Pattern: Belt of the Long Road",
			["French"] = "Patron : Ceinture du long chemin",
			["German"] = "Muster: Gürtel des langen Weges",
			["Korean"] = "도안: 긴 여정의 허리띠",
			["Mexican"] = "Patrón: cinturón del largo camino",
			["Portuguese"] = "Molde: Cinto da Longa Estrada",
			["Russian"] = "Выкройка: пояс дальней дороги",
			["Spanish"] = "Patrón: cinturón del largo camino",
			["Taiwanese"] = "圖樣:長路腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30282,
		["name"] = {
			["Chinese"] = "图样：冲击长靴",
			["English"] = "Pattern: Boots of Blasting",
			["French"] = "Patron : Bottes d'explosion",
			["German"] = "Muster: Stiefel der Zauberwucht",
			["Korean"] = "도안: 발파의 장화",
			["Mexican"] = "Patrón: botas de detonación",
			["Portuguese"] = "Molde: Botas do Impacto",
			["Russian"] = "Выкройка: сапоги взрыва",
			["Spanish"] = "Patrón: botas de detonación",
			["Taiwanese"] = "圖樣:衝擊之靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30283,
		["name"] = {
			["Chinese"] = "图样：长路之靴",
			["English"] = "Pattern: Boots of the Long Road",
			["French"] = "Patron : Bottes du long chemin",
			["German"] = "Muster: Stiefel des langen Weges",
			["Korean"] = "도안: 긴 여정의 장화",
			["Mexican"] = "Patrón: botas del largo camino",
			["Portuguese"] = "Molde: Botas da Longa Estrada",
			["Russian"] = "Выкройка: сапоги дальней дороги",
			["Spanish"] = "Patrón: botas del largo camino",
			["Taiwanese"] = "圖樣:長路之靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 30483,
		["name"] = {
			["Chinese"] = "图样：暗影布",
			["English"] = "Pattern: Shadowcloth",
			["French"] = "Patron : Etoffe d'ombre",
			["German"] = "Muster: Schattenstoff",
			["Korean"] = "도안: 어둠 깃든 옷감",
			["Mexican"] = "Patrón: paño de las Sombras",
			["Portuguese"] = "Molde: Umbratrama",
			["Russian"] = "Выкройка: тенеткань",
			["Spanish"] = "Patrón: paño de las Sombras",
			["Taiwanese"] = "圖樣:暗影布",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				22212,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30833,
		["name"] = {
			["Chinese"] = "图样：奥术闪避披风",
			["English"] = "Pattern: Cloak of Arcane Evasion",
			["French"] = "Patron : Cape d'évasion arcanique",
			["German"] = "Muster: Umhang der Arkanflucht",
			["Korean"] = "도안: 비전 회피의 망토",
			["Mexican"] = "Patrón: capa de evasión Arcana",
			["Portuguese"] = "Molde: Manto de Evasão Arcana",
			["Russian"] = "Выкройка: плащ защиты от чар",
			["Spanish"] = "Patrón: capa de evasión Arcana",
			["Taiwanese"] = "圖樣:秘法迴避披風",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1011,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				21655,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30842,
		["name"] = {
			["Chinese"] = "图样：烈焰之心护腕",
			["English"] = "Pattern: Flameheart Bracers",
			["French"] = "Patron : Brassards coeur-de-flammes",
			["German"] = "Muster: Flammenherzarmschienen",
			["Korean"] = "도안: 화염심장 팔보호구",
			["Mexican"] = "Patrón: brazales de corazón de llamas",
			["Portuguese"] = "Molde: Braçadeiras Cordiflama",
			["Russian"] = "Выкройка: наручи пламенного сердца",
			["Spanish"] = "Patrón: brazales de corazón de llamas",
			["Taiwanese"] = "圖樣:烈焰之心護腕",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30843,
		["name"] = {
			["Chinese"] = "图样：烈焰之心手套",
			["English"] = "Pattern: Flameheart Gloves",
			["French"] = "Patron : Gants coeur-de-flammes",
			["German"] = "Muster: Flammenherzhandschuhe",
			["Korean"] = "도안: 화염심장 장갑",
			["Mexican"] = "Patrón: guantes de corazón de llamas",
			["Portuguese"] = "Molde: Luvas Cordiflama",
			["Russian"] = "Выкройка: перчатки пламенного сердца",
			["Spanish"] = "Patrón: guantes de corazón de llamas",
			["Taiwanese"] = "圖樣:烈焰之心手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30844,
		["name"] = {
			["Chinese"] = "图样：烈焰之心外衣",
			["English"] = "Pattern: Flameheart Vest",
			["French"] = "Patron : Gilet coeur-de-flammes",
			["German"] = "Muster: Flammenherzweste",
			["Korean"] = "도안: 화염심장 조끼",
			["Mexican"] = "Patrón: jubón de corazón de llamas",
			["Portuguese"] = "Molde: Colete Cordiflama",
			["Russian"] = "Выкройка: жилет пламенного сердца",
			["Spanish"] = "Patrón: jubón de corazón de llamas",
			["Taiwanese"] = "圖樣:烈焰之心外衣",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 100000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32437,
		["name"] = {
			["Chinese"] = "图样：灵魂卫士便鞋",
			["English"] = "Pattern: Soulguard Slippers",
			["French"] = "Dessin : Mules garde-âme",
			["German"] = "Muster: Schuhe der Seelenwache",
			["Korean"] = "도안: 영혼의 수호자 덧신",
			["Mexican"] = "Patrón: zapatillas de guarda de almas",
			["Portuguese"] = "Molde: Sapatilhas Guard'almas",
			["Russian"] = "Выкройка: туфли стража духа",
			["Spanish"] = "Patrón: zapatillas de guarda de almas",
			["Taiwanese"] = "圖樣:靈魂守護軟靴",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32438,
		["name"] = {
			["Chinese"] = "图样：灵魂卫士护腕",
			["English"] = "Pattern: Soulguard Bracers",
			["French"] = "Dessin : Poignets garde-âme",
			["German"] = "Muster: Armschienen der Seelenwache",
			["Korean"] = "도안: 영혼의 수호자 팔보호구",
			["Mexican"] = "Patrón: brazales de guarda de almas",
			["Portuguese"] = "Molde: Braçadeiras Guard'almas",
			["Russian"] = "Выкройка: наручи стража духа",
			["Spanish"] = "Patrón: brazales de guarda de almas",
			["Taiwanese"] = "圖樣:靈魂守護護腕",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32439,
		["name"] = {
			["Chinese"] = "图样：灵魂卫士护腿",
			["English"] = "Pattern: Soulguard Leggings",
			["French"] = "Dessin : Jambières garde-âme",
			["German"] = "Muster: Gamaschen der Seelenwache",
			["Korean"] = "도안: 영혼의 수호자 다리보호구",
			["Mexican"] = "Patrón: leotardos de guarda de almas",
			["Portuguese"] = "Molde: Perneiras Guard'almas",
			["Russian"] = "Выкройка: поножи стража духа",
			["Spanish"] = "Patrón: leotardos de guarda de almas",
			["Taiwanese"] = "圖樣:靈魂守護護腿",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32440,
		["name"] = {
			["Chinese"] = "图样：灵魂卫士束带",
			["English"] = "Pattern: Soulguard Girdle",
			["French"] = "Dessin : Cilice garde-âme",
			["German"] = "Muster: Gurt der Seelenwache",
			["Korean"] = "도안: 영혼의 수호자 벨트",
			["Mexican"] = "Patrón: faja de guarda de almas",
			["Portuguese"] = "Molde: Cinturão Guard'almas",
			["Russian"] = "Выкройка: ремень стража духа",
			["Spanish"] = "Patrón: faja de guarda de almas",
			["Taiwanese"] = "圖樣:靈魂守護束腰",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32447,
		["name"] = {
			["Chinese"] = "图样：夜色之末",
			["English"] = "Pattern: Night's End",
			["French"] = "Dessin : Au bout de la nuit",
			["German"] = "Muster: Nachtend",
			["Korean"] = "도안: 밤의 끝자락",
			["Mexican"] = "Patrón: Fin de la noche",
			["Portuguese"] = "Molde: Fim da Noite",
			["Russian"] = "Выкройка: Предел ночи",
			["Spanish"] = "Patrón: Fin de la noche",
			["Taiwanese"] = "圖樣:夜幕之終",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32752,
		["name"] = {
			["Chinese"] = "图样：迅捷治疗护腕",
			["English"] = "Pattern: Swiftheal Wraps",
			["French"] = "Patron : Couvre-bras des soins vifs",
			["German"] = "Muster: Flinkheiltücher",
			["Korean"] = "도안: 신속한 치유의 손목끈",
			["Mexican"] = "Patrón: brazaletes Sanapresto",
			["Portuguese"] = "Molde: Braceletes da Cura Célere",
			["Russian"] = "Выкройка: повязки быстрого исцеления",
			["Spanish"] = "Patrón: brazaletes Sanaveloz",
			["Taiwanese"] = "圖樣:速癒裹帶",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32753,
		["name"] = {
			["Chinese"] = "图样：迅捷治疗衬肩",
			["English"] = "Pattern: Swiftheal Mantle",
			["French"] = "Patron : Mantelet des soins vifs",
			["German"] = "Muster: Flinkheilmantelung",
			["Korean"] = "도안: 신속한 치유의 어깨보호대",
			["Mexican"] = "Patrón: manto Sanapresto",
			["Portuguese"] = "Molde: Dragonas da Cura Célere",
			["Russian"] = "Выкройка: мантия быстрого исцеления",
			["Spanish"] = "Patrón: manto Sanaveloz",
			["Taiwanese"] = "圖樣:速癒披肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32754,
		["name"] = {
			["Chinese"] = "图样：敏锐思维护腕",
			["English"] = "Pattern: Bracers of Nimble Thought",
			["French"] = "Patron : Brassards de la pensée agile",
			["German"] = "Muster: Armschienen des flinken Gedankens",
			["Korean"] = "도안: 기민한 사고의 팔보호구",
			["Mexican"] = "Patrón: brazales de pensamiento ágil",
			["Portuguese"] = "Molde: Braçadeiras do Pensamento Ligeiro",
			["Russian"] = "Выкройка: наручи сообразительности",
			["Spanish"] = "Patrón: brazales de pensamiento ágil",
			["Taiwanese"] = "圖樣:靈機護腕",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32755,
		["name"] = {
			["Chinese"] = "图样：敏锐思维衬肩",
			["English"] = "Pattern: Mantle of Nimble Thought",
			["French"] = "Patron : Mantelet de la pensée agile",
			["German"] = "Muster: Mantelung des flinken Gedankens",
			["Korean"] = "도안: 기민한 사고의 어깨보호대",
			["Mexican"] = "Patrón: manto de pensamiento ágil",
			["Portuguese"] = "Molde: Dragonas do Pensamento Ligeiro",
			["Russian"] = "Выкройка: мантия сообразительности",
			["Spanish"] = "Patrón: manto de pensamiento ágil",
			["Taiwanese"] = "圖樣:靈機披肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["holiday"] = 141,
		["id"] = 34261,
		["name"] = {
			["Chinese"] = "图样：绿色冬衣",
			["English"] = "Pattern: Green Winter Clothes",
			["French"] = "Patron : Vêtements d'hiver verts",
			["German"] = "Muster: Grüne Winterkleidung",
			["Korean"] = "도안: 초록색 겨울 의복",
			["Mexican"] = "Patrón: ropa de invierno verde",
			["Portuguese"] = "Molde: Roupas Verdes de Inverno",
			["Russian"] = "Выкройка: зеленые зимние одежды",
			["Spanish"] = "Patrón: ropa de invierno verde",
			["Taiwanese"] = "圖樣:綠色冬裝",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["price"] = 5000,
			["sources"] = {
				13420,
			},
		},
	},
	{
		["expansion"] = 2,
		["holiday"] = 141,
		["id"] = 34319,
		["name"] = {
			["Chinese"] = "图样：红色冬衣",
			["English"] = "Pattern: Red Winter Clothes",
			["French"] = "Patron : Vêtements d'hiver rouges",
			["German"] = "Muster: Rote Winterkleidung",
			["Korean"] = "도안: 붉은색 겨울 의복",
			["Mexican"] = "Patrón: ropa de invierno roja",
			["Portuguese"] = "Molde: Roupas Vermelhas de Inverno",
			["Russian"] = "Выкройка: красные зимние одежды",
			["Spanish"] = "Patrón: ropa de invierno roja",
			["Taiwanese"] = "圖樣:紅色冬裝",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["price"] = 5000,
			["sources"] = {
				13433,
			},
		},
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35204,
		["name"] = {
			["Chinese"] = "图样：阳炎护手",
			["English"] = "Pattern: Sunfire Handwraps",
			["French"] = "Patron : Protège-mains du feu solaire",
			["German"] = "Muster: Sonnenfeuerhandlappen",
			["Korean"] = "도안: 태양불꽃 장갑",
			["Mexican"] = "Patrón: manijas de fuego solar",
			["Portuguese"] = "Molde: Mitenes do Fogo Solar",
			["Russian"] = "Выкройка: повязки солнечного огня",
			["Spanish"] = "Patrón: manijas de Fuego Solar",
			["Taiwanese"] = "圖樣:日炎裹手",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35205,
		["name"] = {
			["Chinese"] = "图样：永恒光芒之手",
			["English"] = "Pattern: Hands of Eternal Light",
			["French"] = "Patron : Mains de la lumière éternelle",
			["German"] = "Muster: Hände des ewigen Lichtes",
			["Korean"] = "도안: 영원한 빛의 장갑",
			["Mexican"] = "Patrón: manos de Luz eterna",
			["Portuguese"] = "Molde: Luvas da Luz Eterna",
			["Russian"] = "Выкройка: перчатки вечного света",
			["Spanish"] = "Patrón: manos de Luz eterna",
			["Taiwanese"] = "圖樣:永恆之光手套",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35206,
		["name"] = {
			["Chinese"] = "图样：阳炎之袍",
			["English"] = "Pattern: Sunfire Robe",
			["French"] = "Patron : Robe du feu solaire",
			["German"] = "Muster: Sonnenfeuerrobe",
			["Korean"] = "도안: 태양불꽃 로브",
			["Mexican"] = "Patrón: toga de fuego solar",
			["Portuguese"] = "Molde: Veste do Fogo Solar",
			["Russian"] = "Выкройка: одеяние солнечного огня",
			["Spanish"] = "Patrón: toga de Fuego Solar",
			["Taiwanese"] = "圖樣:日炎長袍",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35207,
		["name"] = {
			["Chinese"] = "图样：永恒光芒长袍",
			["English"] = "Pattern: Robe of Eternal Light",
			["French"] = "Patron : Robe de la lumière éternelle",
			["German"] = "Muster: Robe des ewigen Lichtes",
			["Korean"] = "도안: 영원한 빛의 로브",
			["Mexican"] = "Patrón: toga de Luz eterna",
			["Portuguese"] = "Molde: Veste da Luz Eterna",
			["Russian"] = "Выкройка: одеяние вечного света",
			["Spanish"] = "Patrón: toga de Luz eterna",
			["Taiwanese"] = "圖樣:永恆之光長袍",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35308,
		["name"] = {
			["Chinese"] = "图样：不屈护腕",
			["English"] = "Pattern: Unyielding Bracers",
			["French"] = "Patron : Brassards inflexibles",
			["German"] = "Muster: Armschienen des Unerschütterlichen",
			["Korean"] = "도안: 불굴의 팔보호구",
			["Mexican"] = "Patrón: brazales implacables",
			["Portuguese"] = "Molde: Braçadeiras Obstinadas",
			["Russian"] = "Выкройка: наручи непреклонности",
			["Spanish"] = "Patrón: brazales implacables",
			["Taiwanese"] = "圖樣:不屈護腕",
		},
		["phase"] = 5,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35309,
		["name"] = {
			["Chinese"] = "图样：不屈束带",
			["English"] = "Pattern: Unyielding Girdle",
			["French"] = "Patron : Ceinturon inflexible",
			["German"] = "Muster: Gurt des Unerschütterlichen",
			["Korean"] = "도안: 불굴의 벨트",
			["Mexican"] = "Patrón: faja implacable",
			["Portuguese"] = "Molde: Cinturão Obstinado",
			["Russian"] = "Выкройка: ремень непреклонности",
			["Spanish"] = "Patrón: faja implacable",
			["Taiwanese"] = "圖樣:不屈束腰",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 37915,
		["name"] = {
			["Chinese"] = "图样：女鞋",
			["English"] = "Pattern: Dress Shoes",
			["French"] = "Patron : Chaussures habillées",
			["German"] = "Muster: Edle Schuhe",
			["Korean"] = "도안: 드레스 신발",
			["Mexican"] = "Patrón: zapatos para vestido",
			["Portuguese"] = "Molde: Sapatos Sociais",
			["Russian"] = "Выкройка: парадные ботинки",
			["Spanish"] = "Patrón: zapatos para vestido",
			["Taiwanese"] = "圖樣:禮服輕鞋",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 5000,
			["sources"] = {
				15165,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 38229,
		["name"] = {
			["Chinese"] = "图样：麦卡的草药包",
			["English"] = "Pattern: Mycah's Botanical Bag",
			["French"] = "Patron : Sac de botanique de Mycah",
			["German"] = "Muster: Mycahs Botanikerbeutel",
			["Korean"] = "도안: 미카의 채집용 주머니",
			["Mexican"] = "Patrón: bolsa de botánica de Mycah",
			["Portuguese"] = "Molde: Sacola Botânica de Mika",
			["Russian"] = "Выкройка: ботаническая сумка Микаа",
			["Spanish"] = "Patrón: bolsa de botánica de Mycah",
			["Taiwanese"] = "圖樣:麥卡的植物袋",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["currency"] = 24245,
			["price"] = 25,
			["sources"] = {
				18382,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 38327,
		["name"] = {
			["Chinese"] = "图样：流浪乐队外套",
			["English"] = "Pattern: Haliscan Jacket",
			["French"] = "Patron : Veste d'Haliscan",
			["German"] = "Muster: Haliskanjackett",
			["Korean"] = "도안: 악사의 재킷",
			["Mexican"] = "Patrón: chaqueta de haliscan",
			["Portuguese"] = "Molde: Jaqueta de Aykaramba",
			["Russian"] = "Выкройка: куртка Халискана",
			["Spanish"] = "Patrón: chaqueta de haliscan",
			["Taiwanese"] = "圖樣:哈里斯康夾克",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 5000,
			["sources"] = {
				15165,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 38328,
		["name"] = {
			["Chinese"] = "图样：流浪乐队长裤",
			["English"] = "Pattern: Haliscan Pantaloons",
			["French"] = "Patron : Culotte d'Haliscan",
			["German"] = "Muster: Haliskanpantalons",
			["Korean"] = "도안: 악사의 바지",
			["Mexican"] = "Patrón: pantalones de jaliscan",
			["Portuguese"] = "Molde: Pantalonas de Aykaramba",
			["Russian"] = "Выкройка: кюлоты Халискана",
			["Spanish"] = "Patrón: bombachos de haliscan",
			["Taiwanese"] = "圖樣:哈里斯康窄褲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 4500,
			["sources"] = {
				15165,
			},
		},
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Tailoring"], item)
end
