-------------------------------------------------------
-- All skills (Tailoring) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Tailoring"] then RR_DATA["skills"]["Tailoring"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 26745,
		["item_id"] = 21840,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "灵纹布卷",
			["English"] = "Bolt of Netherweave",
			["French"] = "Rouleau de tisse-néant",
			["German"] = "Netherstoffballen",
			["Korean"] = "황천매듭 두루마리",
			["Mexican"] = "Madeja de tejido abisal",
			["Portuguese"] = "Peça de Etertrama",
			["Russian"] = "Рулон ткани Пустоты",
			["Spanish"] = "Madeja de tejido abisal",
			["Taiwanese"] = "幽紋布卷",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26746,
		["item_id"] = 21841,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "灵纹布包",
			["English"] = "Netherweave Bag",
			["French"] = "Sac en tisse-néant",
			["German"] = "Netherstofftasche",
			["Korean"] = "황천매듭 가방",
			["Mexican"] = "Bolsa de tejido abisal",
			["Portuguese"] = "Bolsa de Etertrama",
			["Russian"] = "Сумка из ткани Пустоты",
			["Spanish"] = "Bolsa de tejido abisal",
			["Taiwanese"] = "幽紋布包",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26747,
		["item_id"] = 21842,
		["items"] = {
			21892,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "魔化灵纹布卷",
			["English"] = "Bolt of Imbued Netherweave",
			["French"] = "Rouleau de tisse-néant imprégné",
			["German"] = "Magieerfüllter Netherstoffballen",
			["Korean"] = "마력 깃든 황천매듭 두루마리",
			["Mexican"] = "Madeja de tejido abisal imbuido",
			["Portuguese"] = "Peça de Etertrama Imbuída",
			["Russian"] = "Рулон прочной ткани Пустоты",
			["Spanish"] = "Madeja de tejido abisal imbuido",
			["Taiwanese"] = "魔染幽紋布卷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26749,
		["item_id"] = 21843,
		["items"] = {
			21893,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "魔化灵纹布包",
			["English"] = "Imbued Netherweave Bag",
			["French"] = "Sac en tisse-néant imprégné",
			["German"] = "Magieerfüllte Netherstofftasche",
			["Korean"] = "마력 깃든 황천매듭 가방",
			["Mexican"] = "Bolsa de tejido abisal imbuido",
			["Portuguese"] = "Bolsa de Etertrama Imbuída",
			["Russian"] = "Сумка из прочной ткани Пустоты",
			["Spanish"] = "Bolsa de tejido abisal imbuido",
			["Taiwanese"] = "魔染幽紋布包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26750,
		["item_id"] = 21844,
		["items"] = {
			21894,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "灵魂布卷",
			["English"] = "Bolt of Soulcloth",
			["French"] = "Rouleau d'âmétoffe",
			["German"] = "Seelenstoffballen",
			["Korean"] = "영혼매듭 두루마리",
			["Mexican"] = "Madeja de paño de alma",
			["Portuguese"] = "Peça de Almatrama",
			["Russian"] = "Рулон ткани Душ",
			["Spanish"] = "Madeja de paño de alma",
			["Taiwanese"] = "靈魂布卷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26751,
		["item_id"] = 21845,
		["items"] = {
			21895,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "原始月布",
			["English"] = "Primal Mooncloth",
			["French"] = "Etoffe lunaire primordiale",
			["German"] = "Urmondstoff",
			["Korean"] = "태초의 달빛 옷감",
			["Mexican"] = "Tela lunar primigenia",
			["Portuguese"] = "Lunatrama Primeva",
			["Russian"] = "Изначальная луноткань",
			["Spanish"] = "Tela lunar primigenia",
			["Taiwanese"] = "原始月布",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26752,
		["item_id"] = 21846,
		["items"] = {
			21908,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "魔焰腰带",
			["English"] = "Spellfire Belt",
			["French"] = "Ceinture du feu-sorcier",
			["German"] = "Zauberfeuergürtel",
			["Korean"] = "마법불꽃 허리띠",
			["Mexican"] = "Cinturón de fuego de hechizo",
			["Portuguese"] = "Cinto de Fogo Místico",
			["Russian"] = "Пояс из огненной чароткани",
			["Spanish"] = "Cinturón fuego de hechizo",
			["Taiwanese"] = "魔焰腰帶",
		},
		["phase"] = 1,
		["specialisation"] = 26797,
	},
	{
		["expansion"] = 2,
		["id"] = 26753,
		["item_id"] = 21847,
		["items"] = {
			21909,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔焰手套",
			["English"] = "Spellfire Gloves",
			["French"] = "Gants du feu-sorcier",
			["German"] = "Zauberfeuerhandschuhe",
			["Korean"] = "마법불꽃 장갑",
			["Mexican"] = "Guantes de fuego de hechizo",
			["Portuguese"] = "Luvas de Fogo Místico",
			["Russian"] = "Перчатки из огненной чароткани",
			["Spanish"] = "Guantes fuego de hechizo",
			["Taiwanese"] = "魔焰手套",
		},
		["phase"] = 1,
		["specialisation"] = 26797,
	},
	{
		["expansion"] = 2,
		["id"] = 26754,
		["item_id"] = 21848,
		["items"] = {
			21910,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "魔焰长袍",
			["English"] = "Spellfire Robe",
			["French"] = "Robe du feu-sorcier",
			["German"] = "Zauberfeuerrobe",
			["Korean"] = "마법불꽃 로브",
			["Mexican"] = "Toga de fuego de hechizo",
			["Portuguese"] = "Veste de Fogo Místico",
			["Russian"] = "Одеяние из огненной чароткани",
			["Spanish"] = "Toga fuego de hechizo",
			["Taiwanese"] = "魔焰長袍",
		},
		["phase"] = 1,
		["specialisation"] = 26797,
	},
	{
		["expansion"] = 2,
		["id"] = 26755,
		["item_id"] = 21858,
		["items"] = {
			21911,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "魔焰背包",
			["English"] = "Spellfire Bag",
			["French"] = "Sac du feu-sorcier",
			["German"] = "Zauberfeuertasche",
			["Korean"] = "마법불꽃 가방",
			["Mexican"] = "Bolsa de fuego de hechizo",
			["Portuguese"] = "Bolsa de Fogo Místico",
			["Russian"] = "Сумка из огненной чароткани",
			["Spanish"] = "Bolsa fuego de hechizo",
			["Taiwanese"] = "魔焰包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26756,
		["item_id"] = 21869,
		["items"] = {
			21912,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "冰霜暗纹护肩",
			["English"] = "Frozen Shadoweave Shoulders",
			["French"] = "Epaulières en tisse-ombre gelé",
			["German"] = "Eisschattenzwirnschultern",
			["Korean"] = "얼어붙은 그림자매듭 어깨보호구",
			["Mexican"] = "Sobrehombros de tejido de sombra congelado",
			["Portuguese"] = "Omoplatas de Umbratrama Congeladas",
			["Russian"] = "Наплечники из застывшей тенеткани",
			["Spanish"] = "Sobrehombros de tejido de sombra congelado",
			["Taiwanese"] = "冰霜影紋護肩",
		},
		["phase"] = 1,
		["specialisation"] = 26801,
	},
	{
		["expansion"] = 2,
		["id"] = 26757,
		["item_id"] = 21870,
		["items"] = {
			21914,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "冰霜暗纹长靴",
			["English"] = "Frozen Shadoweave Boots",
			["French"] = "Bottes en tisse-ombre gelé",
			["German"] = "Eisschattenzwirnstiefel",
			["Korean"] = "얼어붙은 그림자매듭 장화",
			["Mexican"] = "Botas de tejido de sombra congelado",
			["Portuguese"] = "Botas de Umbratrama Congeladas",
			["Russian"] = "Сапоги из застывшей тенеткани",
			["Spanish"] = "Botas de tejido de sombra congelado",
			["Taiwanese"] = "冰霜影紋之靴",
		},
		["phase"] = 1,
		["specialisation"] = 26801,
	},
	{
		["expansion"] = 2,
		["id"] = 26758,
		["item_id"] = 21871,
		["items"] = {
			21913,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "冰霜暗纹外衣",
			["English"] = "Frozen Shadoweave Robe",
			["French"] = "Robe en tisse-ombre gelé",
			["German"] = "Eisschattenzwirnrobe",
			["Korean"] = "얼어붙은 그림자매듭 로브",
			["Mexican"] = "Toga de tejido de sombra congelado",
			["Portuguese"] = "Veste de Umbratrama Congelada",
			["Russian"] = "Одеяние из застывшей тенеткани",
			["Spanish"] = "Túnica de tejido de sombra congelado",
			["Taiwanese"] = "冰霜影紋長袍",
		},
		["phase"] = 1,
		["specialisation"] = 26801,
	},
	{
		["expansion"] = 2,
		["id"] = 26759,
		["item_id"] = 21872,
		["items"] = {
			21915,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "黑色暗影背包",
			["English"] = "Ebon Shadowbag",
			["French"] = "Ombresac d'ébène",
			["German"] = "Schwarzschattentasche",
			["Korean"] = "칠흑의 암흑 가방",
			["Mexican"] = "Bolsa de las Sombras de ébano",
			["Portuguese"] = "Bolsombra Ebânea",
			["Russian"] = "Черная сумка теней",
			["Spanish"] = "Bolsa de las Sombras de ébano",
			["Taiwanese"] = "黑檀暗影包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26760,
		["item_id"] = 21873,
		["items"] = {
			21916,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "原始月布腰带",
			["English"] = "Primal Mooncloth Belt",
			["French"] = "Ceinture d'étoffe lunaire primordiale",
			["German"] = "Urmondstoffgürtel",
			["Korean"] = "태초의 달빛매듭 허리띠",
			["Mexican"] = "Cinturón de tela lunar primigenia",
			["Portuguese"] = "Cinto de Lunatrama Primeva",
			["Russian"] = "Пояс из изначальной луноткани",
			["Spanish"] = "Cinturón de tela lunar primigenia",
			["Taiwanese"] = "原始月布腰帶",
		},
		["phase"] = 1,
		["specialisation"] = 26798,
	},
	{
		["expansion"] = 2,
		["id"] = 26761,
		["item_id"] = 21874,
		["items"] = {
			21918,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "原始月布护肩",
			["English"] = "Primal Mooncloth Shoulders",
			["French"] = "Epaulières d'étoffe lunaire primordiale",
			["German"] = "Urmondstoffschultern",
			["Korean"] = "태초의 달빛매듭 어깨보호대",
			["Mexican"] = "Sobrehombros de tela lunar primigenia",
			["Portuguese"] = "Omoplatas de Lunatrama Primeva",
			["Russian"] = "Наплечники из изначальной луноткани",
			["Spanish"] = "Sobrehombros de tela lunar primigenia",
			["Taiwanese"] = "原始月布護肩",
		},
		["phase"] = 1,
		["specialisation"] = 26798,
	},
	{
		["expansion"] = 2,
		["id"] = 26762,
		["item_id"] = 21875,
		["items"] = {
			21917,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "原始月布长袍",
			["English"] = "Primal Mooncloth Robe",
			["French"] = "Robe d'étoffe lunaire primordiale",
			["German"] = "Urmondstoffrobe",
			["Korean"] = "태초의 달빛매듭 로브",
			["Mexican"] = "Toga de tela lunar primigenia",
			["Portuguese"] = "Veste de Lunatrama Primeva",
			["Russian"] = "Одеяние из изначальной луноткани",
			["Spanish"] = "Toga de tela lunar primigenia",
			["Taiwanese"] = "原始月布長袍",
		},
		["phase"] = 1,
		["specialisation"] = 26798,
	},
	{
		["expansion"] = 2,
		["id"] = 26763,
		["item_id"] = 21876,
		["items"] = {
			21919,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "原始月布包",
			["English"] = "Primal Mooncloth Bag",
			["French"] = "Sac d'étoffe lunaire primordiale",
			["German"] = "Urmondstofftasche",
			["Korean"] = "태초의 달빛매듭 가방",
			["Mexican"] = "Bolsa de tela lunar primigenia",
			["Portuguese"] = "Bolsa de Lunatrama Primeva",
			["Russian"] = "Сумка из изначальной луноткани",
			["Spanish"] = "Bolsa de tela lunar primigenia",
			["Taiwanese"] = "原始月布包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26764,
		["item_id"] = 21849,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "灵纹护腕",
			["English"] = "Netherweave Bracers",
			["French"] = "Brassards en tisse-néant",
			["German"] = "Netherstoffarmschienen",
			["Korean"] = "황천매듭 팔보호구",
			["Mexican"] = "Brazales de tejido abisal",
			["Portuguese"] = "Braçadeiras de Etertrama",
			["Russian"] = "Наручи из ткани Пустоты",
			["Spanish"] = "Brazales de tejido abisal",
			["Taiwanese"] = "幽紋護腕",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26765,
		["item_id"] = 21850,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "灵纹腰带",
			["English"] = "Netherweave Belt",
			["French"] = "Ceinture en tisse-néant",
			["German"] = "Netherstoffgürtel",
			["Korean"] = "황천매듭 허리띠",
			["Mexican"] = "Cinturón de tejido abisal",
			["Portuguese"] = "Cinto de Etertrama",
			["Russian"] = "Пояс из ткани Пустоты",
			["Spanish"] = "Cinturón de tejido abisal",
			["Taiwanese"] = "幽紋腰帶",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26770,
		["item_id"] = 21851,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "灵纹手套",
			["English"] = "Netherweave Gloves",
			["French"] = "Gants en tisse-néant",
			["German"] = "Netherstoffhandschuhe",
			["Korean"] = "황천매듭 장갑",
			["Mexican"] = "Guantes de tejido abisal",
			["Portuguese"] = "Luvas de Etertrama",
			["Russian"] = "Перчатки из ткани Пустоты",
			["Spanish"] = "Guantes de tejido abisal",
			["Taiwanese"] = "幽紋手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26771,
		["item_id"] = 21852,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "灵纹短裤",
			["English"] = "Netherweave Pants",
			["French"] = "Pantalon en tisse-néant",
			["German"] = "Netherstoffhose",
			["Korean"] = "황천매듭 바지",
			["Mexican"] = "Pantalones de tejido abisal",
			["Portuguese"] = "Calças de Etertrama",
			["Russian"] = "Штаны из ткани Пустоты",
			["Spanish"] = "Pantalones de tejido abisal",
			["Taiwanese"] = "幽紋便褲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26772,
		["item_id"] = 21853,
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "灵纹长靴",
			["English"] = "Netherweave Boots",
			["French"] = "Bottes en tisse-néant",
			["German"] = "Netherstoffstiefel",
			["Korean"] = "황천매듭 장화",
			["Mexican"] = "Botas de tejido abisal",
			["Portuguese"] = "Botas de Etertrama",
			["Russian"] = "Сапоги из ткани Пустоты",
			["Spanish"] = "Botas de tejido abisal",
			["Taiwanese"] = "幽紋長靴",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18749,
				18772,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 26773,
		["item_id"] = 21854,
		["items"] = {
			21896,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "灵纹长袍",
			["English"] = "Netherweave Robe",
			["French"] = "Robe en tisse-néant",
			["German"] = "Netherstoffrobe",
			["Korean"] = "황천매듭 로브",
			["Mexican"] = "Toga de tejido abisal",
			["Portuguese"] = "Veste de Etertrama",
			["Russian"] = "Одеяние из ткани Пустоты",
			["Spanish"] = "Toga de tejido abisal",
			["Taiwanese"] = "幽紋長袍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26774,
		["item_id"] = 21855,
		["items"] = {
			21897,
		},
		["min_skill"] = 345,
		["name"] = {
			["Chinese"] = "灵纹外套",
			["English"] = "Netherweave Tunic",
			["French"] = "Tunique en tisse-néant",
			["German"] = "Netherstofftunika",
			["Korean"] = "황천매듭 튜닉",
			["Mexican"] = "Guerrera de tejido abisal",
			["Portuguese"] = "Túnica de Etertrama",
			["Russian"] = "Мундир из ткани Пустоты",
			["Spanish"] = "Túnica de tejido abisal",
			["Taiwanese"] = "幽紋外套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26775,
		["item_id"] = 21859,
		["items"] = {
			21898,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "魔化灵纹短裤",
			["English"] = "Imbued Netherweave Pants",
			["French"] = "Pantalon en tisse-néant imprégné",
			["German"] = "Magieerfüllte Netherstoffhose",
			["Korean"] = "마력 깃든 황천매듭 바지",
			["Mexican"] = "Pantalones de tejido abisal imbuido",
			["Portuguese"] = "Calças de Etertrama Imbuída",
			["Russian"] = "Штаны из прочной ткани Пустоты",
			["Spanish"] = "Pantalones de tejido abisal imbuido",
			["Taiwanese"] = "魔染幽紋便褲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26776,
		["item_id"] = 21860,
		["items"] = {
			21899,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔化灵纹长靴",
			["English"] = "Imbued Netherweave Boots",
			["French"] = "Bottes en tisse-néant imprégné",
			["German"] = "Magieerfüllte Netherstoffstiefel",
			["Korean"] = "마력 깃든 황천매듭 장화",
			["Mexican"] = "Botas de tejido abisal imbuido",
			["Portuguese"] = "Botas de Etertrama Imbuída",
			["Russian"] = "Сапоги из прочной ткани Пустоты",
			["Spanish"] = "Botas de tejido abisal imbuido",
			["Taiwanese"] = "魔染幽紋長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26777,
		["item_id"] = 21861,
		["items"] = {
			21900,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔化灵纹长袍",
			["English"] = "Imbued Netherweave Robe",
			["French"] = "Robe en tisse-néant imprégné",
			["German"] = "Magieerfüllte Netherstoffrobe",
			["Korean"] = "마력 깃든 황천매듭 로브",
			["Mexican"] = "Toga de tejido abisal imbuido",
			["Portuguese"] = "Veste de Etertrama Imbuída",
			["Russian"] = "Одеяние из прочной ткани Пустоты",
			["Spanish"] = "Toga de tejido abisal imbuido",
			["Taiwanese"] = "魔染幽紋長袍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26778,
		["item_id"] = 21862,
		["items"] = {
			21901,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔化灵纹外套",
			["English"] = "Imbued Netherweave Tunic",
			["French"] = "Tunique en tisse-néant imprégné",
			["German"] = "Magieerfüllte Netherstofftunika",
			["Korean"] = "마력 깃든 황천매듭 튜닉",
			["Mexican"] = "Guerrera de tejido abisal imbuido",
			["Portuguese"] = "Túnica de Etertrama Imbuída",
			["Russian"] = "Мундир из прочной ткани Пустоты",
			["Spanish"] = "Túnica de tejido abisal imbuido",
			["Taiwanese"] = "魔染幽紋外套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26779,
		["item_id"] = 21863,
		["items"] = {
			21902,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "灵魂布手套",
			["English"] = "Soulcloth Gloves",
			["French"] = "Gants d'âmétoffe",
			["German"] = "Seelenstoffhandschuhe",
			["Korean"] = "영혼매듭 장갑",
			["Mexican"] = "Guantes de paño de alma",
			["Portuguese"] = "Luvas de Almatrama",
			["Russian"] = "Перчатки из ткани Душ",
			["Spanish"] = "Guantes de paño de alma",
			["Taiwanese"] = "靈魂布手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26780,
		["item_id"] = 21864,
		["items"] = {
			21903,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "灵魂布护肩",
			["English"] = "Soulcloth Shoulders",
			["French"] = "Epaulières d'âmétoffe",
			["German"] = "Seelenstoffschultern",
			["Korean"] = "영혼매듭 어깨보호구",
			["Mexican"] = "Sobrehombros de paño de alma",
			["Portuguese"] = "Omoplatas de Almatrama",
			["Russian"] = "Наплечники из ткани Душ",
			["Spanish"] = "Sobrehombros de paño de alma",
			["Taiwanese"] = "靈魂布護肩",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26781,
		["item_id"] = 21865,
		["items"] = {
			21904,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "灵魂布外衣",
			["English"] = "Soulcloth Vest",
			["French"] = "Gilet d'âmétoffe",
			["German"] = "Seelenstoffweste",
			["Korean"] = "영혼매듭 조끼",
			["Mexican"] = "Jubón de paño de alma",
			["Portuguese"] = "Colete de Almatrama",
			["Russian"] = "Жилет из ткани Душ",
			["Spanish"] = "Jubón de paño de alma",
			["Taiwanese"] = "靈魂布外衣",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26782,
		["item_id"] = 21866,
		["items"] = {
			21905,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "奥法交织护腕",
			["English"] = "Arcanoweave Bracers",
			["French"] = "Brassards en tisse-arcane",
			["German"] = "Arkanostoffarmschienen",
			["Korean"] = "비전매듭 팔보호구",
			["Mexican"] = "Brazales de tejido Arcano",
			["Portuguese"] = "Braçadeiras de Arcanotrama",
			["Russian"] = "Наручи из тайной ткани",
			["Spanish"] = "Brazales de tejido Arcano",
			["Taiwanese"] = "奧紋護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26783,
		["item_id"] = 21867,
		["items"] = {
			21906,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "奥法交织长靴",
			["English"] = "Arcanoweave Boots",
			["French"] = "Bottes en tisse-arcane",
			["German"] = "Arkanostoffstiefel",
			["Korean"] = "비전매듭 장화",
			["Mexican"] = "Botas de tejido Arcano",
			["Portuguese"] = "Botas de Arcanotrama",
			["Russian"] = "Сапоги из тайной ткани",
			["Spanish"] = "Botas de tejido Arcano",
			["Taiwanese"] = "奧紋長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 26784,
		["item_id"] = 21868,
		["items"] = {
			21907,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "奥法交织长袍",
			["English"] = "Arcanoweave Robe",
			["French"] = "Robe en tisse-arcane",
			["German"] = "Arkanostoffrobe",
			["Korean"] = "비전매듭 로브",
			["Mexican"] = "Toga de tejido Arcano",
			["Portuguese"] = "Veste de Arcanotrama",
			["Russian"] = "Одеяние из тайной ткани",
			["Spanish"] = "Toga de tejido Arcano",
			["Taiwanese"] = "奧紋長袍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31373,
		["item_id"] = 24271,
		["items"] = {
			24316,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔法布",
			["English"] = "Spellcloth",
			["French"] = "Etoffe ensorcelée",
			["German"] = "Zauberstoff",
			["Korean"] = "마력 깃든 옷감",
			["Mexican"] = "Paño de hechizos",
			["Portuguese"] = "Encantrama",
			["Russian"] = "Чароткань",
			["Spanish"] = "Paño de hechizos",
			["Taiwanese"] = "魔法布",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31430,
		["item_id"] = 24273,
		["items"] = {
			24292,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "秘法魔线",
			["English"] = "Mystic Spellthread",
			["French"] = "Fil ensorcelé mystique",
			["German"] = "Mystischer Zauberfaden",
			["Korean"] = "신비한 마력의 실타래",
			["Mexican"] = "Hilo de hechizo místico",
			["Portuguese"] = "Magilinha Mística",
			["Russian"] = "Таинственная чародейская нить",
			["Spanish"] = "Hilo de hechizo místico",
			["Taiwanese"] = "神秘法術絲線",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31431,
		["item_id"] = 24275,
		["items"] = {
			24293,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "银色魔线",
			["English"] = "Silver Spellthread",
			["French"] = "Fil ensorcelé argenté",
			["German"] = "Silberner Zauberfaden",
			["Korean"] = "마력의 은 실타래",
			["Mexican"] = "Hilo de hechizo de plata",
			["Portuguese"] = "Magilinha Prateada",
			["Russian"] = "Серебряная чародейская нить",
			["Spanish"] = "Hilo de hechizo de plata",
			["Taiwanese"] = "銀色法術絲線",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31432,
		["item_id"] = 24274,
		["items"] = {
			24294,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "符文魔线",
			["English"] = "Runic Spellthread",
			["French"] = "Fil ensorcelé runique",
			["German"] = "Runenverzierter Zauberfaden",
			["Korean"] = "마력의 룬문자 실타래",
			["Mexican"] = "Hilo de hechizo rúnico",
			["Portuguese"] = "Magilinha Rúnica",
			["Russian"] = "Руническая чародейская нить",
			["Spanish"] = "Hilo de hechizo rúnico",
			["Taiwanese"] = "符文法術絲線",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31433,
		["item_id"] = 24276,
		["items"] = {
			24295,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "金色魔线",
			["English"] = "Golden Spellthread",
			["French"] = "Fil ensorcelé doré",
			["German"] = "Goldener Zauberfaden",
			["Korean"] = "마력의 황금 실타래",
			["Mexican"] = "Hilo de hechizo de oro",
			["Portuguese"] = "Magilinha Dourada",
			["Russian"] = "Золотая чародейская нить",
			["Spanish"] = "Hilo de hechizo de oro",
			["Taiwanese"] = "金色法術絲線",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31434,
		["item_id"] = 24249,
		["items"] = {
			24296,
			35308,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "不屈护腕",
			["English"] = "Unyielding Bracers",
			["French"] = "Brassards inflexibles",
			["German"] = "Armschienen des Unerschütterlichen",
			["Korean"] = "불굴의 팔보호구",
			["Mexican"] = "Brazales implacables",
			["Portuguese"] = "Braçadeiras Obstinadas",
			["Russian"] = "Наручи непреклонности",
			["Spanish"] = "Brazales implacables",
			["Taiwanese"] = "不屈護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31435,
		["item_id"] = 24250,
		["items"] = {
			24297,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "浩劫护腕",
			["English"] = "Bracers of Havok",
			["French"] = "Brassards de Sans-quartier",
			["German"] = "Armschienen der Verwüstung",
			["Korean"] = "대혼란의 팔보호구",
			["Mexican"] = "Brazales del caos",
			["Portuguese"] = "Braçadeiras da Tormenta",
			["Russian"] = "Наручи Разора",
			["Spanish"] = "Brazales del caos",
			["Taiwanese"] = "哈伏克護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31437,
		["item_id"] = 24251,
		["items"] = {
			24298,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "黑色侵袭护腕",
			["English"] = "Blackstrike Bracers",
			["French"] = "Brassards de noire frappe",
			["German"] = "Schwarzgestreifte Armschienen",
			["Korean"] = "검은 강타의 팔보호구",
			["Mexican"] = "Brazales golpenegro",
			["Portuguese"] = "Braçadeiras Golpenegro",
			["Russian"] = "Наручи Черного удара",
			["Spanish"] = "Brazales golpenegro",
			["Taiwanese"] = "黑擊護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31438,
		["item_id"] = 24252,
		["items"] = {
			24299,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "黑色虚空披风",
			["English"] = "Cloak of the Black Void",
			["French"] = "Cape du vide noir",
			["German"] = "Umhang der schwarzen Leere",
			["Korean"] = "검은 공허의 망토",
			["Mexican"] = "Capa del vacío negro",
			["Portuguese"] = "Manto do Caos Negro",
			["Russian"] = "Плащ черной бездны",
			["Spanish"] = "Capa del vacío negro",
			["Taiwanese"] = "黑色虛無披風",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31440,
		["item_id"] = 24253,
		["items"] = {
			24300,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "永恒披风",
			["English"] = "Cloak of Eternity",
			["French"] = "Cape d'éternité",
			["German"] = "Umhang der Ewigkeit",
			["Korean"] = "영원의 망토",
			["Mexican"] = "Capa de eternidad",
			["Portuguese"] = "Manto da Eternidade",
			["Russian"] = "Плащ вечности",
			["Spanish"] = "Capa de eternidad",
			["Taiwanese"] = "永恆披風",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31441,
		["item_id"] = 24254,
		["items"] = {
			24301,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "白色治愈斗篷",
			["English"] = "White Remedy Cape",
			["French"] = "Cape du remède blanc",
			["German"] = "Weißer Arzneikittel",
			["Korean"] = "백색 치유의 외투",
			["Mexican"] = "Manteo blanco de enmienda",
			["Portuguese"] = "Capa Curativa Branca",
			["Russian"] = "Белая лечебная накидка",
			["Spanish"] = "Manteo blanco de enmienda",
			["Taiwanese"] = "白色治療斗篷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31442,
		["item_id"] = 24255,
		["items"] = {
			24302,
			35309,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "不屈束带",
			["English"] = "Unyielding Girdle",
			["French"] = "Ceinturon inflexible",
			["German"] = "Gurt des Unerschütterlichen",
			["Korean"] = "불굴의 벨트",
			["Mexican"] = "Faja implacable",
			["Portuguese"] = "Cinturão Obstinado",
			["Russian"] = "Ремень непреклонности",
			["Spanish"] = "Faja implacable",
			["Taiwanese"] = "不屈束腰",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31443,
		["item_id"] = 24256,
		["items"] = {
			24303,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "毁灭束带",
			["English"] = "Girdle of Ruination",
			["French"] = "Ceinturon de saccage",
			["German"] = "Gurt der Zerstörung",
			["Korean"] = "몰락의 벨트",
			["Mexican"] = "Faja de ruina",
			["Portuguese"] = "Cinturão da Ruína",
			["Russian"] = "Ремень опустошения",
			["Spanish"] = "Faja de ruina",
			["Taiwanese"] = "禍根束腰",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31444,
		["item_id"] = 24257,
		["items"] = {
			24304,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "黑色知识腰带",
			["English"] = "Black Belt of Knowledge",
			["French"] = "Ceinture noire de connaissance",
			["German"] = "Schwarzer Gürtel des Wissens",
			["Korean"] = "지식의 검은 허리띠",
			["Mexican"] = "Cinturón negro de sabiduría",
			["Portuguese"] = "Cinto Preto do Conhecimento",
			["Russian"] = "Черный пояс знания",
			["Spanish"] = "Cinturón negro de sabiduría",
			["Taiwanese"] = "黑色學識腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31448,
		["item_id"] = 24258,
		["items"] = {
			24305,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "坚毅披风",
			["English"] = "Resolute Cape",
			["French"] = "Cape résolue",
			["German"] = "Cape der Entschlossenheit",
			["Korean"] = "결의의 외투",
			["Mexican"] = "Manteo de resolución",
			["Portuguese"] = "Capa Resoluta",
			["Russian"] = "Накидка твердости",
			["Spanish"] = "Manteo resuelto",
			["Taiwanese"] = "堅決斗篷",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31449,
		["item_id"] = 24259,
		["items"] = {
			24306,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "复仇披风",
			["English"] = "Vengeance Wrap",
			["French"] = "Houppelande vengeresse",
			["German"] = "Wickeltuch der Vergeltung",
			["Korean"] = "복수의 외투",
			["Mexican"] = "Sobrevesta de venganza",
			["Portuguese"] = "Mantelete da Vingança",
			["Russian"] = "Плащ отмщения",
			["Spanish"] = "Brazalete de venganza",
			["Taiwanese"] = "復仇披風",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31450,
		["item_id"] = 24260,
		["items"] = {
			24307,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "法力编织披风",
			["English"] = "Manaweave Cloak",
			["French"] = "Cape en tisse-mana",
			["German"] = "Managewirkter Umhang",
			["Korean"] = "마나매듭 망토",
			["Mexican"] = "Capa de tejido de maná",
			["Portuguese"] = "Manto de Manatrama",
			["Russian"] = "Плащ из ткани маны",
			["Spanish"] = "Capa de tejido de maná",
			["Taiwanese"] = "法力之紋披風",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31451,
		["item_id"] = 24261,
		["items"] = {
			24308,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "白色治愈短裤",
			["English"] = "Whitemend Pants",
			["French"] = "Pantalon de la blanche guérison",
			["German"] = "Hose des weißen Heilers",
			["Korean"] = "백마법 바지",
			["Mexican"] = "Pantalones con remiendos blancos",
			["Portuguese"] = "Calças Remendalvas",
			["Russian"] = "Штаны Белого целителя",
			["Spanish"] = "Pantalones con remiendos blancos",
			["Taiwanese"] = "白癒便褲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31452,
		["item_id"] = 24262,
		["items"] = {
			24309,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "法术打击短裤",
			["English"] = "Spellstrike Pants",
			["French"] = "Pantalon frappe-sort",
			["German"] = "Hose des Zauberschlags",
			["Korean"] = "마법 강타의 바지",
			["Mexican"] = "Pantalones de golpe de hechizo",
			["Portuguese"] = "Calças do Golpe Mágico",
			["Russian"] = "Штаны сокрушительной магии",
			["Spanish"] = "Pantalones de golpe de hechizo",
			["Taiwanese"] = "法擊便褲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31453,
		["item_id"] = 24263,
		["items"] = {
			24310,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "战斗施法短裤",
			["English"] = "Battlecast Pants",
			["French"] = "Pantalon d'escarmouche",
			["German"] = "Hose des Schlachtenzaubers",
			["Korean"] = "전투시전술 바지",
			["Mexican"] = "Pantalones de conjuro de batalla",
			["Portuguese"] = "Calças de Feitiço Bélico",
			["Russian"] = "Штаны боевого заклятья",
			["Spanish"] = "Pantalones de conjuro de batalla",
			["Taiwanese"] = "戰放便褲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31454,
		["item_id"] = 24264,
		["items"] = {
			24311,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "白色治愈兜帽",
			["English"] = "Whitemend Hood",
			["French"] = "Chaperon de la blanche guérison",
			["German"] = "Kapuze des weißen Heilers",
			["Korean"] = "백마법 두건",
			["Mexican"] = "Caperuza con remiendos blancos",
			["Portuguese"] = "Capuz Remendalvo",
			["Russian"] = "Капюшон белого целителя",
			["Spanish"] = "Caperuza con remiendos blancos",
			["Taiwanese"] = "白癒兜帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31455,
		["item_id"] = 24266,
		["items"] = {
			24312,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "法术打击兜帽",
			["English"] = "Spellstrike Hood",
			["French"] = "Chaperon frappe-sort",
			["German"] = "Kapuze des Zauberschlags",
			["Korean"] = "마법 강타의 두건",
			["Mexican"] = "Caperuza de golpe de hechizo",
			["Portuguese"] = "Capuz do Golpe Mágico",
			["Russian"] = "Капюшон сокрушительной магии",
			["Spanish"] = "Caperuza de golpe de hechizo",
			["Taiwanese"] = "法擊兜帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31456,
		["item_id"] = 24267,
		["items"] = {
			24313,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "战斗施法罩帽",
			["English"] = "Battlecast Hood",
			["French"] = "Chaperon d'escarmouche",
			["German"] = "Kapuze des Schlachtenzaubers",
			["Korean"] = "전투시전술 두건",
			["Mexican"] = "Caperuza de conjuro de batalla",
			["Portuguese"] = "Capuz de Feitiço Bélico",
			["Russian"] = "Капюшон боевого заклятья",
			["Spanish"] = "Caperuza de conjuro de batalla",
			["Taiwanese"] = "戰放兜帽",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31459,
		["item_id"] = 24270,
		["items"] = {
			24314,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "珠宝袋",
			["English"] = "Bag of Jewels",
			["French"] = "Sac de joyaux",
			["German"] = "Juwelenbeutel",
			["Korean"] = "보석 자루",
			["Mexican"] = "Bolsa de joyas",
			["Portuguese"] = "Saco de Joias",
			["Russian"] = "Мешочек для драгоценностей",
			["Spanish"] = "Bolsa de joyas",
			["Taiwanese"] = "寶石包",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 31460,
		["item_id"] = 24268,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "灵纹投网",
			["English"] = "Netherweave Net",
			["French"] = "Filet en tisse-néant",
			["German"] = "Netherstoffnetz",
			["Korean"] = "황천매듭 그물",
			["Mexican"] = "Red de tejido abisal",
			["Portuguese"] = "Rede de Etertrama",
			["Russian"] = "Сеть из ткани Пустоты",
			["Spanish"] = "Red de tejido abisal",
			["Taiwanese"] = "幽紋之網",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				18749,
				18772,
				11557,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36315,
		["item_id"] = 30038,
		["items"] = {
			30280,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "冲击腰带",
			["English"] = "Belt of Blasting",
			["French"] = "Ceinture d'explosion",
			["German"] = "Gürtel der Zauberwucht",
			["Korean"] = "발파의 허리띠",
			["Mexican"] = "Cinturón de detonación",
			["Portuguese"] = "Cinto do Impacto",
			["Russian"] = "Пояс взрыва",
			["Spanish"] = "Cinturón de detonación",
			["Taiwanese"] = "衝擊腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36316,
		["item_id"] = 30036,
		["items"] = {
			30281,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "长路腰带",
			["English"] = "Belt of the Long Road",
			["French"] = "Ceinture du long chemin",
			["German"] = "Gürtel des langen Weges",
			["Korean"] = "긴 여정의 허리띠",
			["Mexican"] = "Cinturón del largo camino",
			["Portuguese"] = "Cinto da Longa Estrada",
			["Russian"] = "Пояс дальней дороги",
			["Spanish"] = "Cinturón del largo camino",
			["Taiwanese"] = "長路腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36317,
		["item_id"] = 30037,
		["items"] = {
			30282,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "冲击长靴",
			["English"] = "Boots of Blasting",
			["French"] = "Bottes d'explosion",
			["German"] = "Stiefel der Zauberwucht",
			["Korean"] = "발파의 장화",
			["Mexican"] = "Botas de detonación",
			["Portuguese"] = "Botas do Impacto",
			["Russian"] = "Сапоги взрыва",
			["Spanish"] = "Botas de detonación",
			["Taiwanese"] = "衝擊之靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36318,
		["item_id"] = 30035,
		["items"] = {
			30283,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "长路之靴",
			["English"] = "Boots of the Long Road",
			["French"] = "Bottes du long chemin",
			["German"] = "Stiefel des langen Weges",
			["Korean"] = "긴 여정의 장화",
			["Mexican"] = "Botas del largo camino",
			["Portuguese"] = "Botas da Longa Estrada",
			["Russian"] = "Сапоги дальней дороги",
			["Spanish"] = "Botas del largo camino",
			["Taiwanese"] = "長路之靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36686,
		["item_id"] = 24272,
		["items"] = {
			30483,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "暗影布",
			["English"] = "Shadowcloth",
			["French"] = "Etoffe d'ombre",
			["German"] = "Schattenstoff",
			["Korean"] = "어둠 깃든 옷감",
			["Mexican"] = "Paño de las Sombras",
			["Portuguese"] = "Umbratrama",
			["Russian"] = "Тенеткань",
			["Spanish"] = "Paño de las Sombras",
			["Taiwanese"] = "暗影布",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 37873,
		["item_id"] = 30831,
		["items"] = {
			30833,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "奥术闪避披风",
			["English"] = "Cloak of Arcane Evasion",
			["French"] = "Cape d'évasion arcanique",
			["German"] = "Umhang der Arkanflucht",
			["Korean"] = "비전 회피의 망토",
			["Mexican"] = "Capa de evasión Arcana",
			["Portuguese"] = "Manto de Evasão Arcana",
			["Russian"] = "Плащ защиты от чар",
			["Spanish"] = "Capa de evasión Arcana",
			["Taiwanese"] = "秘法迴避披風",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 37882,
		["item_id"] = 30837,
		["items"] = {
			30842,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "烈焰之心护腕",
			["English"] = "Flameheart Bracers",
			["French"] = "Brassards coeur-de-flammes",
			["German"] = "Flammenherzarmschienen",
			["Korean"] = "화염심장 팔보호구",
			["Mexican"] = "Brazales de corazón de llamas",
			["Portuguese"] = "Braçadeiras Cordiflama",
			["Russian"] = "Наручи пламенного сердца",
			["Spanish"] = "Brazales de corazón de llamas",
			["Taiwanese"] = "烈焰之心護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 37883,
		["item_id"] = 30838,
		["items"] = {
			30843,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "烈焰之心手套",
			["English"] = "Flameheart Gloves",
			["French"] = "Gants coeur-de-flammes",
			["German"] = "Flammenherzhandschuhe",
			["Korean"] = "화염심장 장갑",
			["Mexican"] = "Guantes de corazón de llamas",
			["Portuguese"] = "Luvas Cordiflama",
			["Russian"] = "Перчатки пламенного сердца",
			["Spanish"] = "Guantes de corazón de llamas",
			["Taiwanese"] = "烈焰之心手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 37884,
		["item_id"] = 30839,
		["items"] = {
			30844,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "烈焰之心外衣",
			["English"] = "Flameheart Vest",
			["French"] = "Gilet coeur-de-flammes",
			["German"] = "Flammenherzweste",
			["Korean"] = "화염심장 조끼",
			["Mexican"] = "Jubón de corazón de llamas",
			["Portuguese"] = "Colete Cordiflama",
			["Russian"] = "Жилет пламенного сердца",
			["Spanish"] = "Jubón de corazón de llamas",
			["Taiwanese"] = "烈焰之心外衣",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 40020,
		["item_id"] = 32391,
		["items"] = {
			32437,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "灵魂卫士便鞋",
			["English"] = "Soulguard Slippers",
			["French"] = "Mules garde-âme",
			["German"] = "Schuhe der Seelenwache",
			["Korean"] = "영혼의 수호자 덧신",
			["Mexican"] = "Zapatillas de guarda de almas",
			["Portuguese"] = "Sapatilhas Guard'almas",
			["Russian"] = "Туфли стража духа",
			["Spanish"] = "Zapatillas de guarda de almas",
			["Taiwanese"] = "靈魂守護軟靴",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40021,
		["item_id"] = 32392,
		["items"] = {
			32438,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "灵魂卫士护腕",
			["English"] = "Soulguard Bracers",
			["French"] = "Poignets garde-âme",
			["German"] = "Armschienen der Seelenwache",
			["Korean"] = "영혼의 수호자 팔보호구",
			["Mexican"] = "Brazales de guarda de almas",
			["Portuguese"] = "Braçadeiras Guard'almas",
			["Russian"] = "Наручи стража духа",
			["Spanish"] = "Brazales de guarda de almas",
			["Taiwanese"] = "靈魂守護護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40023,
		["item_id"] = 32389,
		["items"] = {
			32439,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "灵魂卫士护腿",
			["English"] = "Soulguard Leggings",
			["French"] = "Jambières garde-âme",
			["German"] = "Gamaschen der Seelenwache",
			["Korean"] = "영혼의 수호자 다리보호구",
			["Mexican"] = "Leotardos de guarda de almas",
			["Portuguese"] = "Perneiras Guard'almas",
			["Russian"] = "Поножи стража духа",
			["Spanish"] = "Leotardos de guarda de almas",
			["Taiwanese"] = "靈魂守護護腿",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40024,
		["item_id"] = 32390,
		["items"] = {
			32440,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "灵魂卫士束带",
			["English"] = "Soulguard Girdle",
			["French"] = "Cilice garde-âme",
			["German"] = "Gurt der Seelenwache",
			["Korean"] = "영혼의 수호자 벨트",
			["Mexican"] = "Faja de guarda de almas",
			["Portuguese"] = "Cinturão Guard'almas",
			["Russian"] = "Ремень стража духа",
			["Spanish"] = "Faja de guarda de almas",
			["Taiwanese"] = "靈魂守護束腰",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40060,
		["item_id"] = 32420,
		["items"] = {
			32447,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "夜色之末",
			["English"] = "Night's End",
			["French"] = "Au bout de la nuit",
			["German"] = "Nachtend",
			["Korean"] = "밤의 끝자락",
			["Mexican"] = "Fin de la Noche",
			["Portuguese"] = "Fim da Noite",
			["Russian"] = "Предел ночи",
			["Spanish"] = "Fin de la Noche",
			["Taiwanese"] = "夜幕之終",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41205,
		["item_id"] = 32586,
		["items"] = {
			32754,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "敏锐思维护腕",
			["English"] = "Bracers of Nimble Thought",
			["French"] = "Brassards de la pensée agile",
			["German"] = "Armschienen des flinken Gedankens",
			["Korean"] = "기민한 사고의 팔보호구",
			["Mexican"] = "Brazales de pensamiento ágil",
			["Portuguese"] = "Braçadeiras do Pensamento Ligeiro",
			["Russian"] = "Наручи сообразительности",
			["Spanish"] = "Brazales de pensamiento ágil",
			["Taiwanese"] = "靈機護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41206,
		["item_id"] = 32587,
		["items"] = {
			32755,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "敏锐思维衬肩",
			["English"] = "Mantle of Nimble Thought",
			["French"] = "Mantelet de la pensée agile",
			["German"] = "Mantelung des flinken Gedankens",
			["Korean"] = "기민한 사고의 어깨보호대",
			["Mexican"] = "Manto de pensamiento ágil",
			["Portuguese"] = "Dragonas do Pensamento Ligeiro",
			["Russian"] = "Мантия сообразительности",
			["Spanish"] = "Manto de pensamiento ágil",
			["Taiwanese"] = "靈機披肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41207,
		["item_id"] = 32584,
		["items"] = {
			32752,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "迅捷治疗护腕",
			["English"] = "Swiftheal Wraps",
			["French"] = "Couvre-bras des soins vifs",
			["German"] = "Flinkheiltücher",
			["Korean"] = "신속한 치유의 손목끈",
			["Mexican"] = "Brazaletes Sanapresto",
			["Portuguese"] = "Braceletes da Cura Célere",
			["Russian"] = "Повязки быстрого исцеления",
			["Spanish"] = "Brazaletes Sanaveloz",
			["Taiwanese"] = "速癒裹帶",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41208,
		["item_id"] = 32585,
		["items"] = {
			32753,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "迅捷治疗衬肩",
			["English"] = "Swiftheal Mantle",
			["French"] = "Mantelet des soins vifs",
			["German"] = "Flinkheilmantelung",
			["Korean"] = "신속한 치유의 어깨보호대",
			["Mexican"] = "Manto Sanapresto",
			["Portuguese"] = "Dragonas da Cura Célere",
			["Russian"] = "Мантия быстрого исцеления",
			["Spanish"] = "Manto Sanaveloz",
			["Taiwanese"] = "速癒披肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 44950,
		["item_id"] = 34087,
		["items"] = {
			34261,
		},
		["min_skill"] = 250,
		["name"] = {
			["Chinese"] = "绿色冬衣",
			["English"] = "Green Winter Clothes",
			["French"] = "Vêtements d'hiver verts",
			["German"] = "Grüne Winterkleidung",
			["Korean"] = "초록색 겨울 의복",
			["Mexican"] = "Ropa de invierno verde",
			["Portuguese"] = "Roupas Verdes de Inverno",
			["Russian"] = "Зеленые зимние одежды",
			["Spanish"] = "Ropa de invierno verde",
			["Taiwanese"] = "綠色冬裝",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 44958,
		["item_id"] = 34085,
		["items"] = {
			34319,
		},
		["min_skill"] = 250,
		["name"] = {
			["Chinese"] = "红色冬衣",
			["English"] = "Red Winter Clothes",
			["French"] = "Vêtements d'hiver rouges",
			["German"] = "Rote Winterkleidung",
			["Korean"] = "붉은색 겨울 의복",
			["Mexican"] = "Ropa de invierno roja",
			["Portuguese"] = "Roupas Vermelhas de Inverno",
			["Russian"] = "Красные зимние одежды",
			["Spanish"] = "Ropa de invierno roja",
			["Taiwanese"] = "紅色冬裝",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 46128,
		["item_id"] = 34366,
		["items"] = {
			35204,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "阳炎护手",
			["English"] = "Sunfire Handwraps",
			["French"] = "Protège-mains du feu solaire",
			["German"] = "Sonnenfeuerhandlappen",
			["Korean"] = "태양불꽃 장갑",
			["Mexican"] = "Manijas de fuego solar",
			["Portuguese"] = "Mitenes do Fogo Solar",
			["Russian"] = "Повязки солнечного огня",
			["Spanish"] = "Manijas de Fuego Solar",
			["Taiwanese"] = "日炎裹手",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46129,
		["item_id"] = 34367,
		["items"] = {
			35205,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "永恒光芒之手",
			["English"] = "Hands of Eternal Light",
			["French"] = "Mains de la lumière éternelle",
			["German"] = "Hände des ewigen Lichtes",
			["Korean"] = "영원한 빛의 장갑",
			["Mexican"] = "Manos de Luz eterna",
			["Portuguese"] = "Luvas da Luz Eterna",
			["Russian"] = "Перчатки вечного света",
			["Spanish"] = "Manos de Luz eterna",
			["Taiwanese"] = "永恆之光手套",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46130,
		["item_id"] = 34364,
		["items"] = {
			35206,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "阳炎之袍",
			["English"] = "Sunfire Robe",
			["French"] = "Robe du feu solaire",
			["German"] = "Sonnenfeuerrobe",
			["Korean"] = "태양불꽃 로브",
			["Mexican"] = "Toga de fuego solar",
			["Portuguese"] = "Veste do Fogo Solar",
			["Russian"] = "Одеяние солнечного огня",
			["Spanish"] = "Túnica de Fuego Solar",
			["Taiwanese"] = "日炎長袍",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46131,
		["item_id"] = 34365,
		["items"] = {
			35207,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "永恒光芒长袍",
			["English"] = "Robe of Eternal Light",
			["French"] = "Robe de la lumière éternelle",
			["German"] = "Robe des ewigen Lichtes",
			["Korean"] = "영원한 빛의 로브",
			["Mexican"] = "Toga de Luz eterna",
			["Portuguese"] = "Veste da Luz Eterna",
			["Russian"] = "Одеяние вечного света",
			["Spanish"] = "Toga de Luz eterna",
			["Taiwanese"] = "永恆之光長袍",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 49677,
		["item_id"] = 6836,
		["items"] = {
			37915,
		},
		["min_skill"] = 250,
		["name"] = {
			["Chinese"] = "女鞋",
			["English"] = "Dress Shoes",
			["French"] = "Chaussures habillées",
			["German"] = "Edle Schuhe",
			["Korean"] = "드레스 신발",
			["Mexican"] = "Zapatos para vestido",
			["Portuguese"] = "Sapatos Sociais",
			["Russian"] = "Парадные ботинки",
			["Spanish"] = "Zapatos para vestido",
			["Taiwanese"] = "禮服輕鞋",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 50194,
		["item_id"] = 38225,
		["items"] = {
			38229,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "麦卡的草药包",
			["English"] = "Mycah's Botanical Bag",
			["French"] = "Sac de botanique de Mycah",
			["German"] = "Mycahs Botanikerbeutel",
			["Korean"] = "미카의 채집 주머니",
			["Mexican"] = "Bolsa de botánica de Mycah",
			["Portuguese"] = "Sacola Botânica de Mika",
			["Russian"] = "Ботаническая сумка Микаа",
			["Spanish"] = "Bolsa de botánica de Mycah",
			["Taiwanese"] = "麥卡的植物袋",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 50644,
		["item_id"] = 38277,
		["items"] = {
			38327,
		},
		["min_skill"] = 250,
		["name"] = {
			["Chinese"] = "流浪乐队外套",
			["English"] = "Haliscan Jacket",
			["French"] = "Veste d'Haliscan",
			["German"] = "Haliskanjackett",
			["Korean"] = "악사의 재킷",
			["Mexican"] = "Chaqueta de haliscan",
			["Portuguese"] = "Jaqueta de Aykaramba",
			["Russian"] = "Куртка Халискана",
			["Spanish"] = "Chaqueta de haliscan",
			["Taiwanese"] = "哈里斯康夾克",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 50647,
		["item_id"] = 38278,
		["items"] = {
			38328,
		},
		["min_skill"] = 245,
		["name"] = {
			["Chinese"] = "流浪乐队长裤",
			["English"] = "Haliscan Pantaloons",
			["French"] = "Culotte d'Haliscan",
			["German"] = "Haliskanpantalons",
			["Korean"] = "악사의 바지",
			["Mexican"] = "Pantalones de jaliscan",
			["Portuguese"] = "Pantalonas de Aykaramba",
			["Russian"] = "Кюлоты Халискана",
			["Spanish"] = "Bombachos de haliscan",
			["Taiwanese"] = "哈里斯康窄褲",
		},
		["phase"] = 1,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Tailoring"], skill)
end
