-------------------------------------------------------
-- All items (Blacksmithing) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Blacksmithing"] then RR_DATA["items"]["Blacksmithing"] = {} end
local tbc_items = 
{
	{
		["expansion"] = 2,
		["id"] = 23590,
		["name"] = {
			["Chinese"] = "设计图：精金重槌",
			["English"] = "Plans: Adamantite Maul",
			["French"] = "Plans : Maillet en adamantite",
			["German"] = "Pläne: Adamantitschlägel",
			["Korean"] = "도면: 아다만타이트 마울",
			["Mexican"] = "Diseño: gran maza de adamantita",
			["Portuguese"] = "Instruções: Malho de Adamantita",
			["Russian"] = "Чертеж: адамантитовая кувалда",
			["Spanish"] = "Diseño: gran maza de adamantita",
			["Taiwanese"] = "設計圖:堅鋼大槌",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16670,
				16713,
				19662,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23591,
		["name"] = {
			["Chinese"] = "设计图：精金利斧",
			["English"] = "Plans: Adamantite Cleaver",
			["French"] = "Plans : Fendoir en adamantite",
			["German"] = "Pläne: Adamantitbeil",
			["Korean"] = "도면: 아다만타이트 클레버",
			["Mexican"] = "Diseño: cuchilla de adamantita",
			["Portuguese"] = "Instruções: Cutelo de Adamantita",
			["Russian"] = "Чертеж: адамантитовый колун",
			["Spanish"] = "Diseño: cuchilla de adamantita",
			["Taiwanese"] = "設計圖:堅鋼斬斧",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16670,
				16713,
				19662,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23592,
		["name"] = {
			["Chinese"] = "设计图：精金匕首",
			["English"] = "Plans: Adamantite Dagger",
			["French"] = "Plans : Dague en adamantite",
			["German"] = "Pläne: Adamantitdolch",
			["Korean"] = "도면: 아다만타이트 단검",
			["Mexican"] = "Diseño: daga de adamantita",
			["Portuguese"] = "Instruções: Adaga de Adamantita",
			["Russian"] = "Чертеж: адамантитовый кинжал",
			["Spanish"] = "Diseño: daga de adamantita",
			["Taiwanese"] = "設計圖:堅鋼匕首",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16670,
				16713,
				19662,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23593,
		["name"] = {
			["Chinese"] = "设计图：精金轻剑",
			["English"] = "Plans: Adamantite Rapier",
			["French"] = "Plans : Rapière en adamantite",
			["German"] = "Pläne: Adamantitrapier",
			["Korean"] = "도면: 아다만타이트 레이피어",
			["Mexican"] = "Diseño: estoque de adamantita",
			["Portuguese"] = "Instruções: Florete de Adamantita",
			["Russian"] = "Чертеж: адамантитовая шпага",
			["Spanish"] = "Diseño: estoque de adamantita",
			["Taiwanese"] = "設計圖:堅鋼細劍",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				16670,
				16713,
				19662,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23594,
		["name"] = {
			["Chinese"] = "设计图：精金板甲护腕",
			["English"] = "Plans: Adamantite Plate Bracers",
			["French"] = "Plans : Brassards en plaques d'adamantite",
			["German"] = "Pläne: Adamantitarmschienen",
			["Korean"] = "도면: 아다만타이트 판금 팔보호구",
			["Mexican"] = "Diseño: brazales de placas de adamantita",
			["Portuguese"] = "Instruções: Braçadeiras de Placa de Adamantita",
			["Russian"] = "Чертеж: адамантитовые латные наручи",
			["Spanish"] = "Diseño: brazales de placas de adamantita",
			["Taiwanese"] = "設計圖:堅鋼鎧甲護腕",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19694,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23595,
		["name"] = {
			["Chinese"] = "设计图：精金板甲手套",
			["English"] = "Plans: Adamantite Plate Gloves",
			["French"] = "Plans : Gants en plaques d'adamantite",
			["German"] = "Pläne: Adamantithandschuhe",
			["Korean"] = "도면: 아다만타이트 판금 장갑",
			["Mexican"] = "Diseño: guantes de placas de adamantita",
			["Portuguese"] = "Instruções: Luvas de Placa de Adamantita",
			["Russian"] = "Чертеж: адамантитовые латные перчатки",
			["Spanish"] = "Diseño: guantes de placas de adamantita",
			["Taiwanese"] = "設計圖:堅鋼鎧甲手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19694,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23596,
		["name"] = {
			["Chinese"] = "设计图：精金胸甲",
			["English"] = "Plans: Adamantite Breastplate",
			["French"] = "Plans : Cuirasse en adamantite",
			["German"] = "Pläne: Adamantitbrustplatte",
			["Korean"] = "도면: 아다만타이트 흉갑",
			["Mexican"] = "Diseño: coraza de adamantita",
			["Portuguese"] = "Instruções: Peitoral de Adamantita",
			["Russian"] = "Чертеж: адамантитовая кираса",
			["Spanish"] = "Diseño: coraza de adamantita",
			["Taiwanese"] = "設計圖:堅鋼胸甲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19694,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23597,
		["name"] = {
			["Chinese"] = "设计图：魔化精金腰带",
			["English"] = "Plans: Enchanted Adamantite Belt",
			["French"] = "Plans : Ceinture enchantée en adamantite",
			["German"] = "Pläne: Verzauberter Adamantitgürtel",
			["Korean"] = "도면: 마력 깃든 아다만타이트 허리띠",
			["Mexican"] = "Diseño: cinturón de adamantita encantada",
			["Portuguese"] = "Instruções: Cinto de Adamantita Encantada",
			["Russian"] = "Чертеж: зачарованный адамантитовый пояс",
			["Spanish"] = "Diseño: cinturón de adamantita encantado",
			["Taiwanese"] = "設計圖:附魔堅鋼腰帶",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23598,
		["name"] = {
			["Chinese"] = "设计图：魔化精金长靴",
			["English"] = "Plans: Enchanted Adamantite Boots",
			["French"] = "Plans : Bottes enchantées en adamantite",
			["German"] = "Pläne: Verzauberte Adamantitstiefel",
			["Korean"] = "도면: 마력 깃든 아다만타이트 장화",
			["Mexican"] = "Diseño: botas de adamantita encantada",
			["Portuguese"] = "Instruções: Botas de Adamantita Encantada",
			["Russian"] = "Чертеж: зачарованные адамантитовые сапоги",
			["Spanish"] = "Diseño: botas de adamantita encantada",
			["Taiwanese"] = "設計圖:附魔堅鋼長靴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23599,
		["name"] = {
			["Chinese"] = "设计图：魔化精金胸甲",
			["English"] = "Plans: Enchanted Adamantite Breastplate",
			["French"] = "Plans : Cuirasse enchantée en adamantite",
			["German"] = "Pläne: Verzauberte Adamantitbrustplatte",
			["Korean"] = "도면: 마력 깃든 아다만타이트 흉갑",
			["Mexican"] = "Diseño: coraza de adamantita encantada",
			["Portuguese"] = "Instruções: Peitoral de Adamantita Encantada",
			["Russian"] = "Чертеж: зачарованная адамантитовая кираса",
			["Spanish"] = "Diseño: coraza de adamantita encantada",
			["Taiwanese"] = "設計圖:附魔堅鋼胸甲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23600,
		["name"] = {
			["Chinese"] = "设计图：魔化精金护腿",
			["English"] = "Plans: Enchanted Adamantite Leggings",
			["French"] = "Plans : Jambières enchantées en adamantite",
			["German"] = "Pläne: Verzauberte Adamantitgamaschen",
			["Korean"] = "도면: 마력 깃든 아다만타이트 다리보호구",
			["Mexican"] = "Diseño: Leotardos de adamantita encantada",
			["Portuguese"] = "Instruções: Perneiras de Adamantita Encantada",
			["Russian"] = "Чертеж: зачарованные адамантитовые поножи",
			["Spanish"] = "Diseño: Leotardos de adamantita encantados",
			["Taiwanese"] = "設計圖:附魔堅鋼護腿",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 934,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19331,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23601,
		["name"] = {
			["Chinese"] = "设计图：灭焰护腕",
			["English"] = "Plans: Flamebane Bracers",
			["French"] = "Plans : Brassards plaie-des-flammes",
			["German"] = "Pläne: Flammenbannarmschienen",
			["Korean"] = "도면: 화염파멸 팔보호구",
			["Mexican"] = "Diseño: brazales Aterrallamas",
			["Portuguese"] = "Instruções: Braçadeiras Cortachama",
			["Russian"] = "Чертеж: наручи огненной гибели",
			["Spanish"] = "Diseño: brazales aterrallamas",
			["Taiwanese"] = "設計圖:烈焰毀滅護腕",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23602,
		["name"] = {
			["Chinese"] = "设计图：灭焰头盔",
			["English"] = "Plans: Flamebane Helm",
			["French"] = "Plans : Casque plaie-des-flammes",
			["German"] = "Pläne: Flammenbannhelm",
			["Korean"] = "도면: 화염파멸 투구",
			["Mexican"] = "Diseño: yelmo Aterrallamas",
			["Portuguese"] = "Instruções: Elmo Cortachama",
			["Russian"] = "Чертеж: шлем огненной гибели",
			["Spanish"] = "Diseño: yelmo aterrallamas",
			["Taiwanese"] = "設計圖:烈焰毀滅頭盔",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23603,
		["name"] = {
			["Chinese"] = "设计图：灭焰手套",
			["English"] = "Plans: Flamebane Gloves",
			["French"] = "Plans : Gants plaie-des-flammes",
			["German"] = "Pläne: Flammenbannhandschuhe",
			["Korean"] = "도면: 화염파멸 장갑",
			["Mexican"] = "Diseño: guantes Aterrallamas",
			["Portuguese"] = "Instruções: Luvas Cortachama",
			["Russian"] = "Чертеж: перчатки огненной гибели",
			["Spanish"] = "Diseño: guantes aterrallamas",
			["Taiwanese"] = "設計圖:烈焰毀滅手套",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23604,
		["name"] = {
			["Chinese"] = "设计图：灭焰胸甲",
			["English"] = "Plans: Flamebane Breastplate",
			["French"] = "Plans : Cuirasse plaie-des-flammes",
			["German"] = "Pläne: Flammenbannbrustplatte",
			["Korean"] = "도면: 화염파멸 흉갑",
			["Mexican"] = "Diseño: coraza Aterrallamas",
			["Portuguese"] = "Instruções: Peitoral Cortachama",
			["Russian"] = "Чертеж: кираса огненной гибели",
			["Spanish"] = "Diseño: coraza aterrallamas",
			["Taiwanese"] = "設計圖:烈焰毀滅胸甲",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 932,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				19321,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				18497,
			},
		},
		["expansion"] = 2,
		["id"] = 23605,
		["name"] = {
			["Chinese"] = "设计图：魔钢手套",
			["English"] = "Plans: Felsteel Gloves",
			["French"] = "Plans : Gants en gangracier",
			["German"] = "Pläne: Teufelsstahlhandschuhe",
			["Korean"] = "도면: 지옥강철 장갑",
			["Mexican"] = "Diseño: guantes de acero vil",
			["Portuguese"] = "Instruções: Luvas de Açovil",
			["Russian"] = "Чертеж: перчатки из оскверненной стали",
			["Spanish"] = "Diseño: guantes de acero vil",
			["Taiwanese"] = "設計圖:魔鋼手套",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				20900,
			},
		},
		["expansion"] = 2,
		["id"] = 23606,
		["name"] = {
			["Chinese"] = "设计图：魔钢护腿",
			["English"] = "Plans: Felsteel Leggings",
			["French"] = "Plans : Jambières en gangracier",
			["German"] = "Pläne: Teufelsstahlgamaschen",
			["Korean"] = "도면: 지옥강철 다리보호구",
			["Mexican"] = "Diseño: leotardos de acero vil",
			["Portuguese"] = "Instruções: Perneiras de Açovil",
			["Russian"] = "Чертеж: поножи из оскверненной стали",
			["Spanish"] = "Diseño: leotardos de acero vil",
			["Taiwanese"] = "設計圖:魔鋼護腿",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18830,
			},
		},
		["expansion"] = 2,
		["id"] = 23607,
		["name"] = {
			["Chinese"] = "设计图：魔钢头盔",
			["English"] = "Plans: Felsteel Helm",
			["French"] = "Plans : Casque en gangracier",
			["German"] = "Pläne: Teufelsstahlhelm",
			["Korean"] = "도면: 지옥강철 투구",
			["Mexican"] = "Diseño: yelmo de acero vil",
			["Portuguese"] = "Instruções: Elmo de Açovil",
			["Russian"] = "Чертеж: шлем из оскверненной стали",
			["Spanish"] = "Diseño: yelmo de acero vil",
			["Taiwanese"] = "設計圖:魔鋼頭盔",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18203,
			},
		},
		["expansion"] = 2,
		["id"] = 23608,
		["name"] = {
			["Chinese"] = "设计图：氪金腰带",
			["English"] = "Plans: Khorium Belt",
			["French"] = "Plans : Ceinture en khorium",
			["German"] = "Pläne: Khoriumgürtel",
			["Korean"] = "도면: 코륨 허리띠",
			["Mexican"] = "Diseño: cinturón de korio",
			["Portuguese"] = "Instruções: Cinto de Kório",
			["Russian"] = "Чертеж: кориевый пояс",
			["Spanish"] = "Diseño: cinturón de korio",
			["Taiwanese"] = "設計圖:克銀腰帶",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				20878,
			},
		},
		["expansion"] = 2,
		["id"] = 23609,
		["name"] = {
			["Chinese"] = "设计图：氪金短裤",
			["English"] = "Plans: Khorium Pants",
			["French"] = "Plans : Pantalon en khorium",
			["German"] = "Pläne: Khoriumhose",
			["Korean"] = "도면: 코륨 바지",
			["Mexican"] = "Diseño: pantalones de korio",
			["Portuguese"] = "Instruções: Calças de Kório",
			["Russian"] = "Чертеж: кориевые штаны",
			["Spanish"] = "Diseño: pantalones de korio",
			["Taiwanese"] = "設計圖:克銀便褲",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18873,
			},
		},
		["expansion"] = 2,
		["id"] = 23610,
		["name"] = {
			["Chinese"] = "设计图：氪金战靴",
			["English"] = "Plans: Khorium Boots",
			["French"] = "Plans : Bottes en khorium",
			["German"] = "Pläne: Khoriumstiefel",
			["Korean"] = "도면: 코륨 장화",
			["Mexican"] = "Diseño: botas de korio",
			["Portuguese"] = "Instruções: Botas de Kório",
			["Russian"] = "Чертеж: кориевые сапоги",
			["Spanish"] = "Diseño: botas de korio",
			["Taiwanese"] = "設計圖:克銀長靴",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				17136,
			},
		},
		["expansion"] = 2,
		["id"] = 23611,
		["name"] = {
			["Chinese"] = "设计图：怒钢手套",
			["English"] = "Plans: Ragesteel Gloves",
			["French"] = "Plans : Gants Rage-acier",
			["German"] = "Pläne: Zornstahlhandschuhe",
			["Korean"] = "도면: 분노의 강철 장갑",
			["Mexican"] = "Diseño: guantes de acerira",
			["Portuguese"] = "Instruções: Luvas de Furiaço",
			["Russian"] = "Чертеж: перчатки из яростной стали",
			["Spanish"] = "Diseño: guantes de acerira",
			["Taiwanese"] = "設計圖:怒鋼手套",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				16952,
			},
		},
		["expansion"] = 2,
		["id"] = 23612,
		["name"] = {
			["Chinese"] = "设计图：怒钢头盔",
			["English"] = "Plans: Ragesteel Helm",
			["French"] = "Plans : Casque Rage-acier",
			["German"] = "Pläne: Zornstahlhelm",
			["Korean"] = "도면: 분노의 강철 투구",
			["Mexican"] = "Diseño: yelmo de acerira",
			["Portuguese"] = "Instruções: Elmo de Furiaço",
			["Russian"] = "Чертеж: шлем из яростной стали",
			["Spanish"] = "Diseño: yelmo de acerira",
			["Taiwanese"] = "設計圖:怒鋼頭盔",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				21454,
			},
		},
		["expansion"] = 2,
		["id"] = 23613,
		["name"] = {
			["Chinese"] = "设计图：怒钢胸甲",
			["English"] = "Plans: Ragesteel Breastplate",
			["French"] = "Plans : Cuirasse Rage-acier",
			["German"] = "Pläne: Zornstahlbrustplatte",
			["Korean"] = "도면: 분노의 강철 흉갑",
			["Mexican"] = "Diseño: coraza de acerira",
			["Portuguese"] = "Instruções: Peitoral de Furiaço",
			["Russian"] = "Чертеж: кираса из яростной стали",
			["Spanish"] = "Diseño: coraza de acerira",
			["Taiwanese"] = "設計圖:怒鋼胸甲",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				18314,
			},
		},
		["expansion"] = 2,
		["id"] = 23615,
		["name"] = {
			["Chinese"] = "设计图：迅钢手套",
			["English"] = "Plans: Swiftsteel Gloves",
			["French"] = "Plans : Gants en vif-acier",
			["German"] = "Pläne: Flinkstahlhandschuhe",
			["Korean"] = "도면: 신속의 강철 장갑",
			["Mexican"] = "Diseño: guantes de acero presto",
			["Portuguese"] = "Instruções: Luvas de Celeraço",
			["Russian"] = "Чертеж: перчатки из быстростали",
			["Spanish"] = "Diseño: guantes de acero presto",
			["Taiwanese"] = "設計圖:迅鋼手套",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["sources"] = {
				17975,
			},
		},
		["expansion"] = 2,
		["id"] = 23617,
		["name"] = {
			["Chinese"] = "设计图：和谐胸甲",
			["English"] = "Plans: Earthpeace Breastplate",
			["French"] = "Plans : Cuirasse Paix-de-la-terre",
			["German"] = "Pläne: Brustplatte des Erdfriedens",
			["Korean"] = "도면: 평온한 대지의 흉갑",
			["Mexican"] = "Diseño: coraza de paz terrenal",
			["Portuguese"] = "Instruções: Peitoral da Paz Terrena",
			["Russian"] = "Чертеж: кираса Мира",
			["Spanish"] = "Diseño: coraza de paz terrenal",
			["Taiwanese"] = "設計圖:大地和平胸甲",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 23618,
		["name"] = {
			["Chinese"] = "设计图：精金磨刀石",
			["English"] = "Plans: Adamantite Sharpening Stone",
			["French"] = "Plans : Pierre à aiguiser adamantine",
			["German"] = "Pläne: Adamantitwetzstein",
			["Korean"] = "도면: 아다만타이트 숫돌",
			["Mexican"] = "Diseño: piedra de afilar de adamantita",
			["Portuguese"] = "Instruções: Pedra de Afiar de Adamantita",
			["Russian"] = "Чертеж: адамантитовое точило",
			["Spanish"] = "Diseño: piedra de afilar de adamantita",
			["Taiwanese"] = "設計圖:堅鋼磨刀石",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 23619,
		["name"] = {
			["Chinese"] = "设计图：魔钢盾刺",
			["English"] = "Plans: Felsteel Shield Spike",
			["French"] = "Plans : Pointe de bouclier en gangracier",
			["German"] = "Pläne: Teufelsstahlschildstachel",
			["Korean"] = "도면: 지옥강철 방패 스파이크",
			["Mexican"] = "Diseño: punta de escudo de acero vil",
			["Portuguese"] = "Instruções: Espigão de Escudo de Açovil",
			["Russian"] = "Чертеж: шип для щита из оскверненной стали",
			["Spanish"] = "Diseño: punta de escudo de acero vil",
			["Taiwanese"] = "設計圖:魔鋼盾刺",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 946,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17657,
			},
		},
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23620,
		["name"] = {
			["Chinese"] = "设计图：魔怒护手",
			["English"] = "Plans: Felfury Gauntlets",
			["French"] = "Plans : Gantelets gangrefurie",
			["German"] = "Pläne: Teufelszornstulpen",
			["Korean"] = "도면: 격노의 지옥 건틀릿",
			["Mexican"] = "Diseño: guanteletes de furia vil",
			["Portuguese"] = "Instruções: Manoplas Furiavil",
			["Russian"] = "Чертеж: рукавицы ярости Скверны",
			["Spanish"] = "Diseño: guanteletes de furia vil",
			["Taiwanese"] = "設計圖:魔怒護手",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23621,
		["name"] = {
			["Chinese"] = "设计图：铁塔护手",
			["English"] = "Plans: Gauntlets of the Iron Tower",
			["French"] = "Plans : Gantelets de la tour de fer",
			["German"] = "Pläne: Stulpen des eisernen Turms",
			["Korean"] = "도면: 철탑의 건틀릿",
			["Mexican"] = "Diseño: guanteletes de la Torre de Hierro",
			["Portuguese"] = "Instruções: Manoplas da Torre de Ferro",
			["Russian"] = "Чертеж: рукавицы Железной крепости",
			["Spanish"] = "Diseño: guanteletes de la Torre de Hierro",
			["Taiwanese"] = "設計圖:鐵塔護手",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				22016,
			},
		},
		["expansion"] = 2,
		["id"] = 23622,
		["name"] = {
			["Chinese"] = "设计图：钢钳护手",
			["English"] = "Plans: Steelgrip Gauntlets",
			["French"] = "Plans : Gantelets Poigne-d'acier",
			["German"] = "Pläne: Stahlgriffstulpen",
			["Korean"] = "도면: 강철죔쇠 건틀릿",
			["Mexican"] = "Diseño: guanteletes de presacero",
			["Portuguese"] = "Instruções: Manoplas Punho-de-aço",
			["Russian"] = "Чертеж: рукавицы стальной хватки",
			["Spanish"] = "Diseño: guanteletes de presacero",
			["Taiwanese"] = "設計圖:鋼握護手",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				18312,
			},
		},
		["expansion"] = 2,
		["id"] = 23623,
		["name"] = {
			["Chinese"] = "设计图：风暴头盔",
			["English"] = "Plans: Storm Helm",
			["French"] = "Plans : Casque tempête",
			["German"] = "Pläne: Helm des Sturms",
			["Korean"] = "도면: 폭풍 투구",
			["Mexican"] = "Diseño: yelmo de tormenta",
			["Portuguese"] = "Instruções: Elmo da Tempestade",
			["Russian"] = "Чертеж: шлем бури",
			["Spanish"] = "Diseño: yelmo de tormenta",
			["Taiwanese"] = "設計圖:風暴頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23624,
		["name"] = {
			["Chinese"] = "设计图：坚定防御者头盔",
			["English"] = "Plans: Helm of the Stalwart Defender",
			["French"] = "Plans : Heaume du fidèle défenseur",
			["German"] = "Pläne: Helm des tapferen Verteidigers",
			["Korean"] = "도면: 강인한 수호자의 투구",
			["Mexican"] = "Diseño: yelmo de adepto defensor",
			["Portuguese"] = "Instruções: Elmo do Defensor Impávido",
			["Russian"] = "Чертеж: шлем стойкого защитника",
			["Spanish"] = "Diseño: yelmo de adepto defensor",
			["Taiwanese"] = "設計圖:堅實防衛者頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23625,
		["name"] = {
			["Chinese"] = "设计图：誓言守护者头盔",
			["English"] = "Plans: Oathkeeper's Helm",
			["French"] = "Plans : Casque de la parole donnée",
			["German"] = "Pläne: Helm der Eidestreue",
			["Korean"] = "도면: 굳은 신념의 투구",
			["Mexican"] = "Diseño: yelmo de El Guardián del Juramento",
			["Portuguese"] = "Instruções: Elmo do Guardião do Juramento",
			["Russian"] = "Чертеж: шлем хранителя клятвы",
			["Spanish"] = "Diseño: yelmo de El Guardián del Juramento",
			["Taiwanese"] = "設計圖:誓言守護者頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23626,
		["name"] = {
			["Chinese"] = "设计图：黑色魔钢护腕",
			["English"] = "Plans: Black Felsteel Bracers",
			["French"] = "Plans : Brassards noirs en gangracier",
			["German"] = "Pläne: Schwarze Teufelsstahlarmschienen",
			["Korean"] = "도면: 검은 지옥강철 팔보호구",
			["Mexican"] = "Diseño: brazales de acero vil negros",
			["Portuguese"] = "Instruções: Braçadeiras de Açovil Pretas",
			["Russian"] = "Чертеж: черные наручи из оскверненной стали",
			["Spanish"] = "Diseño: brazales de acero vil negros",
			["Taiwanese"] = "設計圖:黑魔鋼護腕",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23627,
		["name"] = {
			["Chinese"] = "设计图：绿色要塞护腕",
			["English"] = "Plans: Bracers of the Green Fortress",
			["French"] = "Plans : Brassards de la forteresse verte",
			["German"] = "Pläne: Armschienen der grünen Festung",
			["Korean"] = "도면: 푸른 요새의 팔보호구",
			["Mexican"] = "Diseño: brazales de la Fortaleza Verde",
			["Portuguese"] = "Instruções: Braçadeiras da Fortaleza Verde",
			["Russian"] = "Чертеж: наручи зеленой крепости",
			["Spanish"] = "Diseño: brazales de la Fortaleza Verde",
			["Taiwanese"] = "設計圖:綠色堡壘護腕",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23628,
		["name"] = {
			["Chinese"] = "设计图：神宠护腕",
			["English"] = "Plans: Blessed Bracers",
			["French"] = "Plans : Brassards bénis",
			["German"] = "Pläne: Gesegnete Armschienen",
			["Korean"] = "도면: 축복받은 팔보호구",
			["Mexican"] = "Diseño: brazales benditos",
			["Portuguese"] = "Instruções: Braçadeiras Abençoadas",
			["Russian"] = "Чертеж: благословенные наручи",
			["Spanish"] = "Diseño: brazales benditos",
			["Taiwanese"] = "設計圖:受祝福的護腕",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23629,
		["name"] = {
			["Chinese"] = "设计图：魔钢长剑",
			["English"] = "Plans: Felsteel Longblade",
			["French"] = "Plans : Lame longue en gangracier",
			["German"] = "Pläne: Teufelsstahllangschwert",
			["Korean"] = "도면: 지옥강철 장검",
			["Mexican"] = "Diseño: hoja larga de acero vil",
			["Portuguese"] = "Instruções: Lâmina Longa de Açovil",
			["Russian"] = "Чертеж: длинный меч из оскверненной стали",
			["Spanish"] = "Diseño: hoja larga de acero vil",
			["Taiwanese"] = "設計圖:魔鋼長刃",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23630,
		["name"] = {
			["Chinese"] = "设计图：氪金圣剑",
			["English"] = "Plans: Khorium Champion",
			["French"] = "Plans : Champion en khorium",
			["German"] = "Pläne: Khoriumchampion",
			["Korean"] = "도면: 용사의 코륨검",
			["Mexican"] = "Diseño: campeón de korio",
			["Portuguese"] = "Instruções: Campeão de Kório",
			["Russian"] = "Чертеж: кориевый защитник",
			["Spanish"] = "Diseño: campeón de korio",
			["Taiwanese"] = "設計圖:克銀勇士",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23631,
		["name"] = {
			["Chinese"] = "设计图：魔能利斧",
			["English"] = "Plans: Fel Edged Battleaxe",
			["French"] = "Plans : Hache de bataille à tranchant gangrené",
			["German"] = "Pläne: Teuflisch scharfe Kampfaxt",
			["Korean"] = "도면: 지옥날 전투도끼",
			["Mexican"] = "Diseño: hacha de batalla vil afilada",
			["Portuguese"] = "Instruções: Machado de Batalha Cortevil",
			["Russian"] = "Чертеж: боевой топор с кромкой Скверны",
			["Spanish"] = "Diseño: hacha de batalla vil afilada",
			["Taiwanese"] = "設計圖:魔鋒戰斧",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23632,
		["name"] = {
			["Chinese"] = "设计图：魔钢收割者",
			["English"] = "Plans: Felsteel Reaper",
			["French"] = "Plans : Faucheuse en gangracier",
			["German"] = "Pläne: Teufelsstahlschneide",
			["Korean"] = "도면: 지옥강철 도끼",
			["Mexican"] = "Diseño: segadora de acero vil",
			["Portuguese"] = "Instruções: Foice de Açovil",
			["Russian"] = "Чертеж: жнец из оскверненной стали",
			["Spanish"] = "Diseño: segadora de acero vil",
			["Taiwanese"] = "設計圖:魔鋼斧",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23633,
		["name"] = {
			["Chinese"] = "设计图：符印战锤",
			["English"] = "Plans: Runic Hammer",
			["French"] = "Plans : Marteau runique",
			["German"] = "Pläne: Runenverzierter Hammer",
			["Korean"] = "도면: 룬문자 망치",
			["Mexican"] = "Diseño: martillo rúnico",
			["Portuguese"] = "Instruções: Martelo Rúnico",
			["Russian"] = "Чертеж: рунический молот",
			["Spanish"] = "Diseño: martillo rúnico",
			["Taiwanese"] = "設計圖:符文錘",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23634,
		["name"] = {
			["Chinese"] = "设计图：魔能强化战槌",
			["English"] = "Plans: Fel Hardened Maul",
			["French"] = "Plans : Maillet corrompu durci",
			["German"] = "Pläne: Teufelsgehärteter Schlägel",
			["Korean"] = "도면: 지옥 경화 마울",
			["Mexican"] = "Diseño: gran maza endurecida vil",
			["Portuguese"] = "Instruções: Malho Petrevil",
			["Russian"] = "Чертеж: закаленная Скверной кувалда",
			["Spanish"] = "Diseño: gran maza endurecida vil",
			["Taiwanese"] = "設計圖:魔鐵強化槌",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23635,
		["name"] = {
			["Chinese"] = "设计图：恒金符文之刃",
			["English"] = "Plans: Eternium Runed Blade",
			["French"] = "Plans : Lame runique en éternium",
			["German"] = "Pläne: Runenverzierte Eterniumklinge",
			["Korean"] = "도면: 이터늄 룬검",
			["Mexican"] = "Diseño: hoja rúnica de eternio",
			["Portuguese"] = "Instruções: Lâmina Rúnica de Etérnio",
			["Russian"] = "Чертеж: этерниевый рунический клинок",
			["Spanish"] = "Diseño: hoja rúnica de eternio",
			["Taiwanese"] = "設計圖:恆金符文刃",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23636,
		["name"] = {
			["Chinese"] = "设计图：挽歌",
			["English"] = "Plans: Dirge",
			["French"] = "Plans : Complainte",
			["German"] = "Pläne: Todeslied",
			["Korean"] = "도면: 진혼곡",
			["Mexican"] = "Diseño: Réquiem",
			["Portuguese"] = "Instruções: Réquiem",
			["Russian"] = "Чертеж: Погребальный Плач",
			["Spanish"] = "Diseño: Réquiem",
			["Taiwanese"] = "設計圖:輓歌之刃",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 23637,
		["name"] = {
			["Chinese"] = "设计图：永恒之手",
			["English"] = "Plans: Hand of Eternity",
			["French"] = "Plans : Main de l'éternité",
			["German"] = "Pläne: Hand der Ewigkeit",
			["Korean"] = "도면: 영원의 손길",
			["Mexican"] = "Diseño: mano de la eternidad",
			["Portuguese"] = "Instruções: Mão da Eternidade",
			["Russian"] = "Чертеж: Рука Вечности",
			["Spanish"] = "Diseño: mano de la eternidad",
			["Taiwanese"] = "設計圖:永恆之手",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 23638,
		["name"] = {
			["Chinese"] = "设计图：次级护盾结界",
			["English"] = "Plans: Lesser Ward of Shielding",
			["French"] = "Plans : Gardien de sauvegarde inférieur",
			["German"] = "Pläne: Geringer Zauberschutz der Abschirmung",
			["Korean"] = "도면: 하급 수호의 보호막",
			["Mexican"] = "Diseño: resguardo de escudo inferior",
			["Portuguese"] = "Instruções: Proteção Inferior de Anteparo",
			["Russian"] = "Чертеж: простой оберег",
			["Spanish"] = "Diseño: resguardo de escudo inferior",
			["Taiwanese"] = "設計圖:次級護盾禦符",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				16583,
				19373,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				18853,
			},
		},
		["expansion"] = 2,
		["id"] = 23639,
		["name"] = {
			["Chinese"] = "设计图：强效护盾结界",
			["English"] = "Plans: Greater Ward of Shielding",
			["French"] = "Plans : Gardien de sauvegarde supérieur",
			["German"] = "Pläne: Großer Zauberschutz der Abschirmung",
			["Korean"] = "도면: 상급 수호의 보호막",
			["Mexican"] = "Diseño: resguardo de escudo superior",
			["Portuguese"] = "Instruções: Proteção Maior de Anteparo",
			["Russian"] = "Чертеж: сильный оберег",
			["Spanish"] = "Diseño: resguardo de escudo superior",
			["Taiwanese"] = "設計圖:強效護盾禦符",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["expansion"] = 2,
		["id"] = 24002,
		["name"] = {
			["Chinese"] = "设计图：魔钢盾刺",
			["English"] = "Plans: Felsteel Shield Spike",
			["French"] = "Plans : Pointe de bouclier en gangracier",
			["German"] = "Pläne: Teufelsstahlschildstachel",
			["Korean"] = "도면: 지옥강철 방패 스파이크",
			["Mexican"] = "Diseño: punta de escudo de acero vil",
			["Portuguese"] = "Instruções: Espigão de Escudo de Açovil",
			["Russian"] = "Чертеж: шип для щита из оскверненной стали",
			["Spanish"] = "Diseño: punta de escudo de acero vil",
			["Taiwanese"] = "設計圖:魔鋼盾刺",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 947,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17585,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25526,
		["name"] = {
			["Chinese"] = "设计图：强效结界符文",
			["English"] = "Plans: Greater Rune of Warding",
			["French"] = "Plans : Rune de garde supérieure",
			["German"] = "Pläne: Große Rune des Schutzes",
			["Korean"] = "도면: 상급 수호의 룬",
			["Mexican"] = "Diseño: runa de amparo superior",
			["Portuguese"] = "Instruções: Runa Maior de Proteção",
			["Russian"] = "Чертеж: сильная охранная руна",
			["Spanish"] = "Diseño: runa de amparo superior",
			["Taiwanese"] = "設計圖:強效結界符文",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25846,
		["name"] = {
			["Chinese"] = "设计图：精金棒",
			["English"] = "Plans: Adamantite Rod",
			["French"] = "Plans : Bâtonnet en adamantite",
			["German"] = "Pläne: Adamantitrute",
			["Korean"] = "도면: 아다만타이트 마법막대",
			["Mexican"] = "Diseño: vara de adamantita",
			["Portuguese"] = "Instruções: Bastão de Adamantita",
			["Russian"] = "Чертеж: адамантитовый жезл",
			["Spanish"] = "Diseño: vara de adamantita",
			["Taiwanese"] = "設計圖:堅鋼魔棒",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40000,
			["sources"] = {
				19662,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 25847,
		["name"] = {
			["Chinese"] = "设计图：恒金棒",
			["English"] = "Plans: Eternium Rod",
			["French"] = "Plans : Bâtonnet en éternium",
			["German"] = "Pläne: Eterniumrute",
			["Korean"] = "도면: 이터늄 마법막대",
			["Mexican"] = "Diseño: vara de eternio",
			["Portuguese"] = "Instruções: Bastão de Etérnio",
			["Russian"] = "Чертеж: этерниевый жезл",
			["Spanish"] = "Diseño: vara de eternio",
			["Taiwanese"] = "設計圖:恆金棒",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 120000,
			["sources"] = {
				16583,
				19373,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 28632,
		["name"] = {
			["Chinese"] = "设计图：精金平衡石",
			["English"] = "Plans: Adamantite Weightstone",
			["French"] = "Plans : Pierre de lest d'adamantite",
			["German"] = "Pläne: Adamantitgewichtsstein",
			["Korean"] = "도면: 아다만타이트 무게추",
			["Mexican"] = "Diseño: contrapeso de adamantita",
			["Portuguese"] = "Instruções: Contrapeso de Adamantita",
			["Russian"] = "Чертеж: адамантитовое грузило",
			["Spanish"] = "Diseño: contrapeso de adamantita",
			["Taiwanese"] = "設計圖:堅鋼平衡石",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 60000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["drops"] = {
			["sources"] = {
				18805,
				20046,
				21212,
				21214,
				21216,
			},
		},
		["expansion"] = 2,
		["id"] = 30321,
		["name"] = {
			["Chinese"] = "设计图：守护者腰带",
			["English"] = "Plans: Belt of the Guardian",
			["French"] = "Plans : Ceinture du gardien",
			["German"] = "Pläne: Gürtel des Wächters",
			["Korean"] = "도면: 수호병의 허리띠",
			["Mexican"] = "Diseño: cinturón del guardián",
			["Portuguese"] = "Instruções: Cinto do Guardião",
			["Russian"] = "Чертеж: пояс хранителя",
			["Spanish"] = "Diseño: cinturón del guardián",
			["Taiwanese"] = "設計圖:守衛者腰帶",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30322,
		["name"] = {
			["Chinese"] = "设计图：红色战斗腰带",
			["English"] = "Plans: Red Belt of Battle",
			["French"] = "Plans : Ceinture de bataille rouge",
			["German"] = "Pläne: Roter Gürtel der Schlacht",
			["Korean"] = "도면: 전투의 붉은 허리띠",
			["Mexican"] = "Diseño: cinturón de batalla rojo",
			["Portuguese"] = "Instruções: Cinto Vermelho de Batalha",
			["Russian"] = "Чертеж: красный пояс битвы",
			["Spanish"] = "Diseño: cinturón rojo de batalla",
			["Taiwanese"] = "設計圖:紅色戰鬥腰帶",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30323,
		["name"] = {
			["Chinese"] = "设计图：保卫者战靴",
			["English"] = "Plans: Boots of the Protector",
			["French"] = "Plans : Bottes du protecteur",
			["German"] = "Pläne: Stiefel des Beschützers",
			["Korean"] = "도면: 파수병의 장화",
			["Mexican"] = "Diseño: botas del protector",
			["Portuguese"] = "Instruções: Botas do Protetor",
			["Russian"] = "Чертеж: сапоги защитника",
			["Spanish"] = "Diseño: botas del protector",
			["Taiwanese"] = "設計圖:保衛者之靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3607,
				3845,
			},
		},
		["expansion"] = 2,
		["id"] = 30324,
		["name"] = {
			["Chinese"] = "设计图：红色浩劫长靴",
			["English"] = "Plans: Red Havoc Boots",
			["French"] = "Plans : Bottes du tumulte rouges",
			["German"] = "Pläne: Rote Stiefel der Verwüstung",
			["Korean"] = "도면: 붉은 파괴의 장화",
			["Mexican"] = "Diseño: botas de caos rojas",
			["Portuguese"] = "Instruções: Botas Vermelhas da Destruição",
			["Russian"] = "Чертеж: сапоги красного хаоса",
			["Spanish"] = "Diseño: botas de caos rojas",
			["Taiwanese"] = "設計圖:紅色浩劫長靴",
		},
		["phase"] = 2,
		["quality"] = "epic",
	},
	{
		["expansion"] = 2,
		["id"] = 31390,
		["name"] = {
			["Chinese"] = "设计图：野性卫士胸甲",
			["English"] = "Plans: Wildguard Breastplate",
			["French"] = "Plans : Cuirasse de la garde fauve",
			["German"] = "Pläne: Brustplatte der Wildwacht",
			["Korean"] = "도면: 야생수호 흉갑",
			["Mexican"] = "Diseño: coraza de guardia salvaje",
			["Portuguese"] = "Instruções: Peitoral Selvaguarda",
			["Russian"] = "Чертеж: кираса стража леса",
			["Spanish"] = "Diseño: coraza de guardia salvaje",
			["Taiwanese"] = "設計圖:野性看守者胸甲",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 8,
		},
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31391,
		["name"] = {
			["Chinese"] = "设计图：野性卫士护腿",
			["English"] = "Plans: Wildguard Leggings",
			["French"] = "Plans : Jambières de la garde fauve",
			["German"] = "Pläne: Gamaschen der Wildwacht",
			["Korean"] = "도면: 야생수호 다리보호구",
			["Mexican"] = "Diseño: leotardos de guardia salvaje",
			["Portuguese"] = "Instruções: Perneiras Selvaguarda",
			["Russian"] = "Чертеж: поножи стража леса",
			["Spanish"] = "Diseño: leotardos de guardia salvaje",
			["Taiwanese"] = "設計圖:野性看守者護腿",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31392,
		["name"] = {
			["Chinese"] = "设计图：野性卫士头盔",
			["English"] = "Plans: Wildguard Helm",
			["French"] = "Plans : Heaume de la garde fauve",
			["German"] = "Pläne: Helm der Wildwacht",
			["Korean"] = "도면: 야생수호 투구",
			["Mexican"] = "Diseño: yelmo de guardia salvaje",
			["Portuguese"] = "Instruções: Elmo Selvaguarda",
			["Russian"] = "Чертеж: шлем стража леса",
			["Spanish"] = "Diseño: yelmo de guardia salvaje",
			["Taiwanese"] = "設計圖:野性看守者頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["reputation"] = {
			["faction_id"] = 942,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				17904,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31393,
		["name"] = {
			["Chinese"] = "设计图：寒冰卫士胸甲",
			["English"] = "Plans: Iceguard Breastplate",
			["French"] = "Plans : Cuirasse de gardeglace",
			["German"] = "Pläne: Brustplatte der Eiswache",
			["Korean"] = "도면: 얼음수호 흉갑",
			["Mexican"] = "Diseño: coraza de guardia de hielo",
			["Portuguese"] = "Instruções: Peitoral Barragelo",
			["Russian"] = "Чертеж: кираса ледяного стража",
			["Spanish"] = "Diseño: coraza de guardia de hielo",
			["Taiwanese"] = "設計圖:冰霜守衛胸甲",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["reputation"] = {
			["faction_id"] = 967,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				16388,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31394,
		["name"] = {
			["Chinese"] = "设计图：寒冰卫士护腿",
			["English"] = "Plans: Iceguard Leggings",
			["French"] = "Plans : Jambières de gardeglace",
			["German"] = "Pläne: Gamaschen der Eiswache",
			["Korean"] = "도면: 얼음수호 다리보호구",
			["Mexican"] = "Diseño: leotardos de guardia de hielo",
			["Portuguese"] = "Instruções: Perneiras Barragelo",
			["Russian"] = "Чертеж: поножи ледяного стража",
			["Spanish"] = "Diseño: leotardos de guardia de hielo",
			["Taiwanese"] = "設計圖:冰霜守衛護腿",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["reputation"] = {
			["faction_id"] = 967,
			["level_id"] = 7,
		},
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				16388,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31395,
		["name"] = {
			["Chinese"] = "设计图：寒冰卫士头盔",
			["English"] = "Plans: Iceguard Helm",
			["French"] = "Plans : Heaume de gardeglace",
			["German"] = "Pläne: Helm der Eiswache",
			["Korean"] = "도면: 얼음수호 투구",
			["Mexican"] = "Diseño: yelmo de guardia de hielo",
			["Portuguese"] = "Instruções: Elmo Barragelo",
			["Russian"] = "Чертеж: шлем ледяного стража",
			["Spanish"] = "Diseño: yelmo de guardia de hielo",
			["Taiwanese"] = "設計圖:冰霜守衛頭盔",
		},
		["phase"] = 1,
		["quality"] = "epic",
		["reputation"] = {
			["faction_id"] = 967,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 240000,
			["sources"] = {
				16388,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32441,
		["name"] = {
			["Chinese"] = "设计图：影钢战靴",
			["English"] = "Plans: Shadesteel Sabots",
			["French"] = "Dessin : Sabots en ombracier",
			["German"] = "Pläne: Dämmerstahlschuhe",
			["Korean"] = "도면: 어둠강철 장화",
			["Mexican"] = "Diseño: zuecos de acero de sombras",
			["Portuguese"] = "Instruções: Botas Sombradaço",
			["Russian"] = "Чертеж: тенестальные сабо",
			["Spanish"] = "Diseño: zuecos de acero de Sombras",
			["Taiwanese"] = "設計圖:影堅戰靴",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32442,
		["name"] = {
			["Chinese"] = "设计图：影钢护腕",
			["English"] = "Plans: Shadesteel Bracers",
			["French"] = "Dessin : Brassards en ombracier",
			["German"] = "Pläne: Dämmerstahlarmschienen",
			["Korean"] = "도면: 어둠강철 팔보호구",
			["Mexican"] = "Diseño: brazales de acero de sombras",
			["Portuguese"] = "Instruções: Braçadeiras Sombradaço",
			["Russian"] = "Чертеж: тенестальные наручи",
			["Spanish"] = "Diseño: brazales de acero de Sombras",
			["Taiwanese"] = "設計圖:影堅護腕",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32443,
		["name"] = {
			["Chinese"] = "设计图：影钢腿甲",
			["English"] = "Plans: Shadesteel Greaves",
			["French"] = "Dessin : Grèves en ombracier",
			["German"] = "Pläne: Dämmerstahlbeinschützer",
			["Korean"] = "도면: 어둠강철 경갑",
			["Mexican"] = "Diseño: grebas de acero de sombras",
			["Portuguese"] = "Instruções: Grevas Sombradaço",
			["Russian"] = "Чертеж: тенестальные наголенники",
			["Spanish"] = "Diseño: grebas de acero de Sombras",
			["Taiwanese"] = "設計圖:影堅護脛",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 6,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32444,
		["name"] = {
			["Chinese"] = "设计图：影钢束带",
			["English"] = "Plans: Shadesteel Girdle",
			["French"] = "Dessin : Ceinturon en ombracier",
			["German"] = "Pläne: Dämmerstahlgurt",
			["Korean"] = "도면: 어둠강철 벨트",
			["Mexican"] = "Diseño: faja de acero de sombras",
			["Portuguese"] = "Instruções: Cinturão Sombradaço",
			["Russian"] = "Чертеж: тенестальной ремень",
			["Spanish"] = "Diseño: faja de acero de Sombras",
			["Taiwanese"] = "設計圖:影堅束腰",
		},
		["phase"] = 3,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 1077,
			["level_id"] = 5,
		},
		["vendors"] = {
			["price"] = 80000,
			["sources"] = {
				23159,
			},
		},
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32736,
		["name"] = {
			["Chinese"] = "设计图：迅钢护腕",
			["English"] = "Plans: Swiftsteel Bracers",
			["French"] = "Plans : Brassards en vif-acier",
			["German"] = "Pläne: Flinkstahlarmschienen",
			["Korean"] = "도면: 신속의 강철 팔보호구",
			["Mexican"] = "Diseño: brazales de acero presto",
			["Portuguese"] = "Instruções: Braçadeiras de Celeraço",
			["Russian"] = "Чертеж: наручи из быстростали",
			["Spanish"] = "Diseño: brazales de acero presto",
			["Taiwanese"] = "設計圖:迅鋼護腕",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32737,
		["name"] = {
			["Chinese"] = "设计图：迅钢护肩",
			["English"] = "Plans: Swiftsteel Shoulders",
			["French"] = "Plans : Epaulières en vif-acier",
			["German"] = "Pläne: Flinkstahlschultern",
			["Korean"] = "도면: 신속의 강철 어깨보호구",
			["Mexican"] = "Diseño: sobrehombros de acero presto",
			["Portuguese"] = "Instruções: Omoplatas de Celeraço",
			["Russian"] = "Чертеж: наплечники из быстростали",
			["Spanish"] = "Diseño: sobrehombros de acero presto",
			["Taiwanese"] = "設計圖:迅鋼護肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32738,
		["name"] = {
			["Chinese"] = "设计图：晨钢护腕",
			["English"] = "Plans: Dawnsteel Bracers",
			["French"] = "Plans : Brassards en acier de l'aube",
			["German"] = "Pläne: Morgenstahlarmschienen",
			["Korean"] = "도면: 여명의 강철 팔보호구",
			["Mexican"] = "Diseño: brazales albacero",
			["Portuguese"] = "Instruções: Braçadeiras de Alvoraço",
			["Russian"] = "Чертеж: наручи рассветной стали",
			["Spanish"] = "Diseño: brazales albacero",
			["Taiwanese"] = "設計圖:黎明鋼鐵護腕",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				3606,
				3959,
			},
		},
		["expansion"] = 2,
		["id"] = 32739,
		["name"] = {
			["Chinese"] = "设计图：晨钢护肩",
			["English"] = "Plans: Dawnsteel Shoulders",
			["French"] = "Plans : Epaulières en acier de l'aube",
			["German"] = "Pläne: Morgenstahlschultern",
			["Korean"] = "도면: 여명의 강철 어깨보호구",
			["Mexican"] = "Diseño: sobrehombros albacero",
			["Portuguese"] = "Instruções: Omoplatas de Alvoraço",
			["Russian"] = "Чертеж: наплечники рассветной стали",
			["Spanish"] = "Diseño: sobrehombros albacero",
			["Taiwanese"] = "設計圖:黎明鋼鐵護肩",
		},
		["phase"] = 3,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				21050,
				21059,
				21060,
				21061,
			},
		},
		["expansion"] = 2,
		["id"] = 33174,
		["name"] = {
			["Chinese"] = "设计图：怒钢护肩",
			["English"] = "Plans: Ragesteel Shoulders",
			["French"] = "Plans : Epaulières Rage-acier",
			["German"] = "Pläne: Zornstahlschultern",
			["Korean"] = "도면: 분노의 강철 어깨보호구",
			["Mexican"] = "Diseño: sobrehombros de acerira",
			["Portuguese"] = "Instruções: Omoplatas de Furiaço",
			["Russian"] = "Чертеж: наплечники из яростной стали",
			["Spanish"] = "Diseño: sobrehombros de acerira",
			["Taiwanese"] = "設計圖:怒鋼護肩",
		},
		["phase"] = 1,
		["quality"] = "rare",
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 33186,
		["name"] = {
			["Chinese"] = "设计图：精金武器链",
			["English"] = "Plans: Adamantite Weapon Chain",
			["French"] = "Plans : Dragonne en adamantite",
			["German"] = "Pläne: Adamantitwaffenkette",
			["Korean"] = "도면: 아다만타이트 무기 사슬",
			["Mexican"] = "Diseño: cadena de adamantita",
			["Portuguese"] = "Instruções: Corrente de Arma de Adamantita",
			["Russian"] = "Чертеж: адамантитовая оружейная цепь",
			["Spanish"] = "Diseño: cadena de adamantita",
			["Taiwanese"] = "設計圖:堅鋼武器鍊",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
	},
	{
		["expansion"] = 2,
		["id"] = 33792,
		["name"] = {
			["Chinese"] = "设计图：铜质重剑",
			["English"] = "Plans: Heavy Copper Longsword",
			["French"] = "Plans : Lourde épée longue en cuivre",
			["German"] = "Pläne: Schweres Kupferlangschwert",
			["Korean"] = "도면: 단단한 구리 장검",
			["Mexican"] = "Diseño: tizona de cobre pesada",
			["Portuguese"] = "Instruções: Espada Longa Pesada de Cobre",
			["Russian"] = "Чертеж: тяжелый медный длинный меч",
			["Spanish"] = "Diseño: tizona de cobre pesada",
			["Taiwanese"] = "設計圖:重銅長劍",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["quests"] = {
			1578,
		}
	},
	{
		["drops"] = {
			["range"] = {
				["max_xp_level"] = 73,
				["min_xp_level"] = 65,
			},
		},
		["expansion"] = 2,
		["id"] = 33954,
		["name"] = {
			["Chinese"] = "设计图：正义力量之锤",
			["English"] = "Plans: Hammer of Righteous Might",
			["French"] = "Plans : Marteau de la puissance pieuse",
			["German"] = "Pläne: Hammer der rechtschaffenen Macht",
			["Korean"] = "도면: 정의로운 힘의 망치",
			["Mexican"] = "Diseño: martillo de poderío recto",
			["Portuguese"] = "Instruções: Martelo do Poder Íntegro",
			["Russian"] = "Чертеж: молот праведной мощи",
			["Spanish"] = "Diseño: martillo de poderío recto",
			["Taiwanese"] = "設計圖:公正力量之錘",
		},
		["phase"] = 1,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35208,
		["name"] = {
			["Chinese"] = "设计图：圣日护手",
			["English"] = "Plans: Sunblessed Gauntlets",
			["French"] = "Plans : Gantelets bénis par le soleil",
			["German"] = "Pläne: Sonnengesegnete Stulpen",
			["Korean"] = "도면: 태양의 축복 건틀릿",
			["Mexican"] = "Diseño: guanteletes bendecidos por el sol",
			["Portuguese"] = "Instruções: Manoplas Abençoadas pelo Sol",
			["Russian"] = "Чертеж: рукавицы солнечного благословения",
			["Spanish"] = "Diseño: guanteletes bendecidos por el sol",
			["Taiwanese"] = "設計圖:太陽祝福護手",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35209,
		["name"] = {
			["Chinese"] = "设计图：硬化氪金拳甲",
			["English"] = "Plans: Hard Khorium Battlefists",
			["French"] = "Plans : Poings armés en khorium durci",
			["German"] = "Pläne: Kampffäuste aus Hartkhorium",
			["Korean"] = "도면: 단단한 코륨 전투판금 건틀릿",
			["Mexican"] = "Diseño: puños de batalla de korio duro",
			["Portuguese"] = "Instruções: Manápulas de Kório Duro",
			["Russian"] = "Чертеж: кулачные перчатки из закаленного кория",
			["Spanish"] = "Diseño: puños de batalla de korio duro",
			["Taiwanese"] = "設計圖:特硬克銀戰拳",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35210,
		["name"] = {
			["Chinese"] = "设计图：圣日胸甲",
			["English"] = "Plans: Sunblessed Breastplate",
			["French"] = "Plans : Cuirasse bénie par le soleil",
			["German"] = "Pläne: Sonnengesegnete Brustplatte",
			["Korean"] = "도면: 태양의 축복 흉갑",
			["Mexican"] = "Diseño: coraza bendecida por el sol",
			["Portuguese"] = "Instruções: Peitoral Abençoado pelo Sol",
			["Russian"] = "Чертеж: кираса солнечного благословения",
			["Spanish"] = "Diseño: coraza bendecida por el sol",
			["Taiwanese"] = "設計圖:太陽祝福胸甲",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["zone_ids"] = {
				4075,
			},
		},
		["expansion"] = 2,
		["id"] = 35211,
		["name"] = {
			["Chinese"] = "设计图：硬化氪金战甲",
			["English"] = "Plans: Hard Khorium Battleplate",
			["French"] = "Plans : Armure de bataille en khorium durci",
			["German"] = "Pläne: Kampfplatte aus Hartkhorium",
			["Korean"] = "도면: 단단한 코륨 전투판금 흉갑",
			["Mexican"] = "Diseño: placa de batalla de korio duro",
			["Portuguese"] = "Instruções: Loriga de Kório Duro",
			["Russian"] = "Чертеж: боевой доспех из закаленного кория",
			["Spanish"] = "Diseño: placa de batalla de korio duro",
			["Taiwanese"] = "設計圖:特硬克銀戰甲",
		},
		["phase"] = 5,
		["quality"] = "epic",
	},
	{
		["drops"] = {
			["sources"] = {
				24664,
			},
		},
		["expansion"] = 2,
		["id"] = 35296,
		["name"] = {
			["Chinese"] = "设计图：精金武器链",
			["English"] = "Plans: Adamantite Weapon Chain",
			["French"] = "Plans : Dragonne en adamantite",
			["German"] = "Pläne: Adamantitwaffenkette",
			["Korean"] = "도면: 아다만타이트 무기 사슬",
			["Mexican"] = "Diseño: cadena de adamantita",
			["Portuguese"] = "Instruções: Corrente de Arma de Adamantita",
			["Russian"] = "Чертеж: адамантитовая оружейная цепь",
			["Spanish"] = "Diseño: cadena de adamantita",
			["Taiwanese"] = "設計圖:堅鋼武器鍊",
		},
		["phase"] = 5,
		["quality"] = "uncommon",
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Blacksmithing"], item)
end
