-------------------------------------------------------
-- All skills (Blacksmithing) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Blacksmithing"] then RR_DATA["skills"]["Blacksmithing"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 29545,
		["item_id"] = 23482,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔铁板甲手套",
			["English"] = "Fel Iron Plate Gloves",
			["French"] = "Gants en plaques de gangrefer",
			["German"] = "Teufelseisenplattenhandschuhe",
			["Korean"] = "지옥무쇠 장갑",
			["Mexican"] = "Guantes de placas de hierro vil",
			["Portuguese"] = "Luvas de Placa de Ferrovil",
			["Russian"] = "Латные перчатки из оскверненного железа",
			["Spanish"] = "Guantes de placas de hierro vil",
			["Taiwanese"] = "魔鐵鎧甲手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29547,
		["item_id"] = 23484,
		["min_skill"] = 305,
		["name"] = {
			["Chinese"] = "魔铁板甲腰带",
			["English"] = "Fel Iron Plate Belt",
			["French"] = "Ceinture en plaques de gangrefer",
			["German"] = "Teufelseisenplattengürtel",
			["Korean"] = "지옥무쇠 허리띠",
			["Mexican"] = "Cinturón de placas de hierro vil",
			["Portuguese"] = "Cinturão de Placa de Ferrovil",
			["Russian"] = "Латный пояс из оскверненного железа",
			["Spanish"] = "Cinturón de placas de hierro vil",
			["Taiwanese"] = "魔鐵鎧甲腰帶",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29548,
		["item_id"] = 23487,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "魔铁板甲战靴",
			["English"] = "Fel Iron Plate Boots",
			["French"] = "Bottes en plaques de gangrefer",
			["German"] = "Teufelseisenplattenstiefel",
			["Korean"] = "지옥무쇠 장화",
			["Mexican"] = "Botas de placas de hierro vil",
			["Portuguese"] = "Botas de Placa de Ferrovil",
			["Russian"] = "Латные сапоги из оскверненного железа",
			["Spanish"] = "Botas de placas de hierro vil",
			["Taiwanese"] = "魔鐵鎧甲長靴",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29549,
		["item_id"] = 23488,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "魔铁板甲短裤",
			["English"] = "Fel Iron Plate Pants",
			["French"] = "Pantalon en plaques de gangrefer",
			["German"] = "Teufelseisenplattenhose",
			["Korean"] = "지옥무쇠 바지",
			["Mexican"] = "Pantalones de placas de hierro vil",
			["Portuguese"] = "Calças de Placa de Ferrovil",
			["Russian"] = "Латные набедренники из оскверненного железа",
			["Spanish"] = "Pantalones de placas de hierro vil",
			["Taiwanese"] = "魔鐵鎧甲便褲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29550,
		["item_id"] = 23489,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "魔铁胸甲",
			["English"] = "Fel Iron Breastplate",
			["French"] = "Cuirasse en gangrefer",
			["German"] = "Teufelseisenbrustplatte",
			["Korean"] = "지옥무쇠 흉갑",
			["Mexican"] = "Coraza de hierro vil",
			["Portuguese"] = "Peitoral de Ferrovil",
			["Russian"] = "Кираса из оскверненного железа",
			["Spanish"] = "Coraza de hierro vil",
			["Taiwanese"] = "魔鐵胸甲",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29551,
		["item_id"] = 23493,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔铁链甲罩帽",
			["English"] = "Fel Iron Chain Coif",
			["French"] = "Camail en anneaux de gangrefer",
			["German"] = "Teufelseisenkettenhelmkappe",
			["Korean"] = "지옥무쇠 사슬 코이프",
			["Mexican"] = "Almófar de anillas de hierro vil",
			["Portuguese"] = "Coifa Encadeada de Ferrovil",
			["Russian"] = "Плетеный капюшон из оскверненного железа",
			["Spanish"] = "Almófar de anillas de hierro vil",
			["Taiwanese"] = "魔鐵鍊甲頭盔",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29552,
		["item_id"] = 23491,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "魔铁链甲手套",
			["English"] = "Fel Iron Chain Gloves",
			["French"] = "Gants en anneaux de gangrefer",
			["German"] = "Teufelseisenkettenhandschuhe",
			["Korean"] = "지옥무쇠 사슬 장갑",
			["Mexican"] = "Guantes de anillas de hierro vil",
			["Portuguese"] = "Luvas Encadeadas de Ferrovil",
			["Russian"] = "Плетеные перчатки из оскверненного железа",
			["Spanish"] = "Guantes de anillas de hierro vil",
			["Taiwanese"] = "魔鐵鍊甲手套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 18000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29553,
		["item_id"] = 23494,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "魔铁链甲护腕",
			["English"] = "Fel Iron Chain Bracers",
			["French"] = "Brassards en anneaux de gangrefer",
			["German"] = "Teufelseisenkettenarmschienen",
			["Korean"] = "지옥무쇠 사슬 팔보호구",
			["Mexican"] = "Brazales de anillas de hierro vil",
			["Portuguese"] = "Braçadeiras Encadeadas de Ferrovil",
			["Russian"] = "Плетеные наручи из оскверненного железа",
			["Spanish"] = "Brazales de anillas de hierro vil",
			["Taiwanese"] = "魔鐵鍊甲護腕",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29556,
		["item_id"] = 23490,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "魔铁链甲外套",
			["English"] = "Fel Iron Chain Tunic",
			["French"] = "Tunique en anneaux de gangrefer",
			["German"] = "Teufelseisenkettentunika",
			["Korean"] = "지옥무쇠 사슬 조끼",
			["Mexican"] = "Guerrera de anillas de hierro vil",
			["Portuguese"] = "Túnica Encadeada de Ferrovil",
			["Russian"] = "Плетеный мундир из оскверненного железа",
			["Spanish"] = "Túnica de anillas de hierro vil",
			["Taiwanese"] = "魔鐵鍊甲外套",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 22000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29557,
		["item_id"] = 23497,
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "魔铁短斧",
			["English"] = "Fel Iron Hatchet",
			["French"] = "Hachette en gangrefer",
			["German"] = "Teufelseisenkriegsbeil",
			["Korean"] = "지옥무쇠 도끼",
			["Mexican"] = "Hachuela de hierro vil",
			["Portuguese"] = "Machadinha de Ferrovil",
			["Russian"] = "Секира из оскверненного железа",
			["Spanish"] = "Hachuela de hierro vil",
			["Taiwanese"] = "魔鐵短斧",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 18000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29558,
		["item_id"] = 23498,
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "魔铁战锤",
			["English"] = "Fel Iron Hammer",
			["French"] = "Marteau en gangrefer",
			["German"] = "Teufelseisenhammer",
			["Korean"] = "지옥무쇠 망치",
			["Mexican"] = "Martillo de hierro vil",
			["Portuguese"] = "Martelo de Ferrovil",
			["Russian"] = "Молот из оскверненного железа",
			["Spanish"] = "Martillo de hierro vil",
			["Taiwanese"] = "魔鐵錘",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 20000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29565,
		["item_id"] = 23499,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "魔铁巨剑",
			["English"] = "Fel Iron Greatsword",
			["French"] = "Estramaçon en gangrefer",
			["German"] = "Teufelseisengroßschwert",
			["Korean"] = "지옥무쇠 대검",
			["Mexican"] = "Espada magna de hierro vil",
			["Portuguese"] = "Montante de Ferrovil",
			["Russian"] = "Большой меч из оскверненного железа",
			["Spanish"] = "Espada magna de hierro vil",
			["Taiwanese"] = "魔鐵巨劍",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 22000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29566,
		["item_id"] = 23502,
		["items"] = {
			23590,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "精金重槌",
			["English"] = "Adamantite Maul",
			["French"] = "Maillet en adamantite",
			["German"] = "Adamantitschlägel",
			["Korean"] = "아다만타이트 마울",
			["Mexican"] = "Gran maza de adamantita",
			["Portuguese"] = "Malho de Adamantita",
			["Russian"] = "Адамантитовая кувалда",
			["Spanish"] = "Gran maza de adamantita",
			["Taiwanese"] = "堅鋼大槌",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29568,
		["item_id"] = 23503,
		["items"] = {
			23591,
		},
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "精金利斧",
			["English"] = "Adamantite Cleaver",
			["French"] = "Fendoir en adamantite",
			["German"] = "Adamantitbeil",
			["Korean"] = "아다만타이트 클레버",
			["Mexican"] = "Cuchilla de adamantita",
			["Portuguese"] = "Cutelo de Adamantita",
			["Russian"] = "Адамантитовый колун",
			["Spanish"] = "Cuchilla de adamantita",
			["Taiwanese"] = "堅鋼斬斧",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29569,
		["item_id"] = 23504,
		["items"] = {
			23592,
		},
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "精金匕首",
			["English"] = "Adamantite Dagger",
			["French"] = "Dague en adamantite",
			["German"] = "Adamantitdolch",
			["Korean"] = "아다만타이트 단검",
			["Mexican"] = "Daga de adamantita",
			["Portuguese"] = "Adaga de Adamantita",
			["Russian"] = "Адамантитовый кинжал",
			["Spanish"] = "Daga de adamantita",
			["Taiwanese"] = "堅鋼匕首",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29571,
		["item_id"] = 23505,
		["items"] = {
			23593,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "精金轻剑",
			["English"] = "Adamantite Rapier",
			["French"] = "Rapière en adamantite",
			["German"] = "Adamantitrapier",
			["Korean"] = "아다만타이트 레이피어",
			["Mexican"] = "Estoque de adamantita",
			["Portuguese"] = "Florete de Adamantita",
			["Russian"] = "Адамантитовая шпага",
			["Spanish"] = "Estoque de adamantita",
			["Taiwanese"] = "堅鋼細劍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29603,
		["item_id"] = 23506,
		["items"] = {
			23594,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "精金板甲护腕",
			["English"] = "Adamantite Plate Bracers",
			["French"] = "Brassards en plaques d'adamantite",
			["German"] = "Adamantitarmschienen",
			["Korean"] = "아다만타이트 판금 팔보호구",
			["Mexican"] = "Brazales de placas de adamantita",
			["Portuguese"] = "Braçadeiras de Placa de Adamantita",
			["Russian"] = "Адамантитовые латные наручи",
			["Spanish"] = "Brazales de placas de adamantita",
			["Taiwanese"] = "堅鋼鎧甲護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29605,
		["item_id"] = 23508,
		["items"] = {
			23595,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "精金板甲手套",
			["English"] = "Adamantite Plate Gloves",
			["French"] = "Gants en plaques d'adamantite",
			["German"] = "Adamantithandschuhe",
			["Korean"] = "아다만타이트 판금 장갑",
			["Mexican"] = "Guantes de placas de adamantita",
			["Portuguese"] = "Luvas de Placa de Adamantita",
			["Russian"] = "Адамантитовые латные перчатки",
			["Spanish"] = "Guantes de placas de adamantita",
			["Taiwanese"] = "堅鋼鎧甲手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29606,
		["item_id"] = 23507,
		["items"] = {
			23596,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "精金胸甲",
			["English"] = "Adamantite Breastplate",
			["French"] = "Cuirasse en adamantite",
			["German"] = "Adamantitbrustplatte",
			["Korean"] = "아다만타이트 흉갑",
			["Mexican"] = "Coraza de adamantita",
			["Portuguese"] = "Peitoral de Adamantita",
			["Russian"] = "Адамантитовая кираса",
			["Spanish"] = "Coraza de adamantita",
			["Taiwanese"] = "堅鋼胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29608,
		["item_id"] = 23510,
		["items"] = {
			23597,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "魔化精金腰带",
			["English"] = "Enchanted Adamantite Belt",
			["French"] = "Ceinture enchantée en adamantite",
			["German"] = "Verzauberter Adamantitgürtel",
			["Korean"] = "마력 깃든 아다만타이트 허리띠",
			["Mexican"] = "Cinturón de adamantita encantada",
			["Portuguese"] = "Cinto de Adamantita Encantada",
			["Russian"] = "Зачарованный адамантитовый пояс",
			["Spanish"] = "Cinturón de adamantita encantado",
			["Taiwanese"] = "附魔堅鋼腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29610,
		["item_id"] = 23509,
		["items"] = {
			23599,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔化精金胸甲",
			["English"] = "Enchanted Adamantite Breastplate",
			["French"] = "Cuirasse enchantée en adamantite",
			["German"] = "Verzauberte Adamantitbrustplatte",
			["Korean"] = "마력 깃든 아다만타이트 흉갑",
			["Mexican"] = "Coraza de adamantita encantada",
			["Portuguese"] = "Peitoral de Adamantita Encantada",
			["Russian"] = "Зачарованная адамантитовая кираса",
			["Spanish"] = "Coraza de adamantita encantada",
			["Taiwanese"] = "附魔堅鋼胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29611,
		["item_id"] = 23511,
		["items"] = {
			23598,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "魔化精金长靴",
			["English"] = "Enchanted Adamantite Boots",
			["French"] = "Bottes enchantées en adamantite",
			["German"] = "Verzauberte Adamantitstiefel",
			["Korean"] = "마력 깃든 아다만타이트 장화",
			["Mexican"] = "Botas de adamantita encantada",
			["Portuguese"] = "Botas de Adamantita Encantada",
			["Russian"] = "Зачарованные адамантитовые сапоги",
			["Spanish"] = "Botas de adamantita encantada",
			["Taiwanese"] = "附魔堅鋼長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29613,
		["item_id"] = 23512,
		["items"] = {
			23600,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔化精金护腿",
			["English"] = "Enchanted Adamantite Leggings",
			["French"] = "Jambières enchantées en adamantite",
			["German"] = "Verzauberte Adamantitgamaschen",
			["Korean"] = "마력 깃든 아다만타이트 다리보호구",
			["Mexican"] = "Leotardos de adamantita encantada",
			["Portuguese"] = "Perneiras de Adamantita Encantada",
			["Russian"] = "Зачарованные адамантитовые поножи",
			["Spanish"] = "Leotardos de adamantita encantados",
			["Taiwanese"] = "附魔堅鋼護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29614,
		["item_id"] = 23515,
		["items"] = {
			23601,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "灭焰护腕",
			["English"] = "Flamebane Bracers",
			["French"] = "Brassards plaie-des-flammes",
			["German"] = "Flammenbannarmschienen",
			["Korean"] = "화염파멸 팔보호구",
			["Mexican"] = "Brazales Aterrallamas",
			["Portuguese"] = "Braçadeiras Cortachama",
			["Russian"] = "Наручи огненной гибели",
			["Spanish"] = "Brazales aterrallamas",
			["Taiwanese"] = "烈焰毀滅護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29615,
		["item_id"] = 23516,
		["items"] = {
			23602,
		},
		["min_skill"] = 355,
		["name"] = {
			["Chinese"] = "灭焰头盔",
			["English"] = "Flamebane Helm",
			["French"] = "Casque plaie-des-flammes",
			["German"] = "Flammenbannhelm",
			["Korean"] = "화염파멸 투구",
			["Mexican"] = "Yelmo Aterrallamas",
			["Portuguese"] = "Elmo Cortachama",
			["Russian"] = "Шлем огненной гибели",
			["Spanish"] = "Yelmo aterrallamas",
			["Taiwanese"] = "烈焰毀滅頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29616,
		["item_id"] = 23514,
		["items"] = {
			23603,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "灭焰手套",
			["English"] = "Flamebane Gloves",
			["French"] = "Gants plaie-des-flammes",
			["German"] = "Flammenbannhandschuhe",
			["Korean"] = "화염파멸 장갑",
			["Mexican"] = "Guantes Aterrallamas",
			["Portuguese"] = "Luvas Cortachama",
			["Russian"] = "Перчатки огненной гибели",
			["Spanish"] = "Guantes aterrallamas",
			["Taiwanese"] = "烈焰毀滅手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29617,
		["item_id"] = 23513,
		["items"] = {
			23604,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "灭焰胸甲",
			["English"] = "Flamebane Breastplate",
			["French"] = "Cuirasse plaie-des-flammes",
			["German"] = "Flammenbannbrustplatte",
			["Korean"] = "화염파멸 흉갑",
			["Mexican"] = "Coraza Aterrallamas",
			["Portuguese"] = "Peitoral Cortachama",
			["Russian"] = "Кираса огненной гибели",
			["Spanish"] = "Coraza aterrallamas",
			["Taiwanese"] = "烈焰毀滅胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29619,
		["item_id"] = 23517,
		["items"] = {
			23605,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔钢手套",
			["English"] = "Felsteel Gloves",
			["French"] = "Gants en gangracier",
			["German"] = "Teufelsstahlhandschuhe",
			["Korean"] = "지옥강철 장갑",
			["Mexican"] = "Guantes de acero vil",
			["Portuguese"] = "Luvas de Açovil",
			["Russian"] = "Перчатки из оскверненной стали",
			["Spanish"] = "Guantes de acero vil",
			["Taiwanese"] = "魔鋼手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29620,
		["item_id"] = 23518,
		["items"] = {
			23606,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔钢护腿",
			["English"] = "Felsteel Leggings",
			["French"] = "Jambières en gangracier",
			["German"] = "Teufelsstahlgamaschen",
			["Korean"] = "지옥강철 다리보호구",
			["Mexican"] = "Leotardos de acero vil",
			["Portuguese"] = "Perneiras de Açovil",
			["Russian"] = "Поножи из оскверненной стали",
			["Spanish"] = "Leotardos de acero vil",
			["Taiwanese"] = "魔鋼護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29621,
		["item_id"] = 23519,
		["items"] = {
			23607,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔钢头盔",
			["English"] = "Felsteel Helm",
			["French"] = "Casque en gangracier",
			["German"] = "Teufelsstahlhelm",
			["Korean"] = "지옥강철 투구",
			["Mexican"] = "Yelmo de acero vil",
			["Portuguese"] = "Elmo de Açovil",
			["Russian"] = "Шлем из оскверненной стали",
			["Spanish"] = "Yelmo de acero vil",
			["Taiwanese"] = "魔鋼頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29622,
		["item_id"] = 23532,
		["items"] = {
			23621,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "铁塔护手",
			["English"] = "Gauntlets of the Iron Tower",
			["French"] = "Gantelets de la Tour de fer",
			["German"] = "Stulpen des eisernen Turms",
			["Korean"] = "철탑의 건틀릿",
			["Mexican"] = "Guanteletes de la Torre de Hierro",
			["Portuguese"] = "Manoplas da Torre de Ferro",
			["Russian"] = "Рукавицы Железной крепости",
			["Spanish"] = "Guanteletes de la Torre de Hierro",
			["Taiwanese"] = "鐵塔護手",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29628,
		["item_id"] = 23524,
		["items"] = {
			23608,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "氪金腰带",
			["English"] = "Khorium Belt",
			["French"] = "Ceinture en khorium",
			["German"] = "Khoriumgürtel",
			["Korean"] = "코륨 허리띠",
			["Mexican"] = "Cinturón de korio",
			["Portuguese"] = "Cinto de Kório",
			["Russian"] = "Кориевый пояс",
			["Spanish"] = "Cinturón de korio",
			["Taiwanese"] = "克銀腰帶",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29629,
		["item_id"] = 23523,
		["items"] = {
			23609,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "氪金短裤",
			["English"] = "Khorium Pants",
			["French"] = "Pantalon en khorium",
			["German"] = "Khoriumhose",
			["Korean"] = "코륨 바지",
			["Mexican"] = "Pantalones de korio",
			["Portuguese"] = "Calças de Kório",
			["Russian"] = "Кориевые штаны",
			["Spanish"] = "Pantalones de korio",
			["Taiwanese"] = "克銀便褲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29630,
		["item_id"] = 23525,
		["items"] = {
			23610,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "氪金战靴",
			["English"] = "Khorium Boots",
			["French"] = "Bottes en khorium",
			["German"] = "Khoriumstiefel",
			["Korean"] = "코륨 장화",
			["Mexican"] = "Botas de korio",
			["Portuguese"] = "Botas de Kório",
			["Russian"] = "Кориевые сапоги",
			["Spanish"] = "Botas de korio",
			["Taiwanese"] = "克銀長靴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29642,
		["item_id"] = 23520,
		["items"] = {
			23611,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "怒钢手套",
			["English"] = "Ragesteel Gloves",
			["French"] = "Gants Rage-acier",
			["German"] = "Zornstahlhandschuhe",
			["Korean"] = "분노의 강철 장갑",
			["Mexican"] = "Guantes de acerira",
			["Portuguese"] = "Luvas de Furiaço",
			["Russian"] = "Перчатки из яростной стали",
			["Spanish"] = "Guantes de acerira",
			["Taiwanese"] = "怒鋼手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29643,
		["item_id"] = 23521,
		["items"] = {
			23612,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "怒钢头盔",
			["English"] = "Ragesteel Helm",
			["French"] = "Casque Rage-acier",
			["German"] = "Zornstahlhelm",
			["Korean"] = "분노의 강철 투구",
			["Mexican"] = "Yelmo de acerira",
			["Portuguese"] = "Elmo de Furiaço",
			["Russian"] = "Шлем из яростной стали",
			["Spanish"] = "Yelmo de acerira",
			["Taiwanese"] = "怒鋼頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29645,
		["item_id"] = 23522,
		["items"] = {
			23613,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "怒钢胸甲",
			["English"] = "Ragesteel Breastplate",
			["French"] = "Cuirasse Rage-acier",
			["German"] = "Zornstahlbrustplatte",
			["Korean"] = "분노의 강철 흉갑",
			["Mexican"] = "Coraza de acerira",
			["Portuguese"] = "Peitoral de Furiaço",
			["Russian"] = "Кираса из яростной стали",
			["Spanish"] = "Coraza de acerira",
			["Taiwanese"] = "怒鋼胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29648,
		["item_id"] = 23526,
		["items"] = {
			23615,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "迅钢手套",
			["English"] = "Swiftsteel Gloves",
			["French"] = "Gants en vif-acier",
			["German"] = "Flinkstahlhandschuhe",
			["Korean"] = "신속의 강철 장갑",
			["Mexican"] = "Guantes de acero presto",
			["Portuguese"] = "Luvas de Celeraço",
			["Russian"] = "Перчатки из быстростали",
			["Spanish"] = "Guantes de acero presto",
			["Taiwanese"] = "迅鋼手套",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29649,
		["item_id"] = 23527,
		["items"] = {
			23617,
		},
		["min_skill"] = 370,
		["name"] = {
			["Chinese"] = "和谐胸甲",
			["English"] = "Earthpeace Breastplate",
			["French"] = "Cuirasse Paix-de-la-terre",
			["German"] = "Brustplatte des Erdfriedens",
			["Korean"] = "평온한 대지의 흉갑",
			["Mexican"] = "Coraza de paz terrenal",
			["Portuguese"] = "Peitoral da Paz Terrena",
			["Russian"] = "Кираса Мира",
			["Spanish"] = "Coraza de paz terrenal",
			["Taiwanese"] = "大地和平胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29654,
		["item_id"] = 23528,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔能磨刀石",
			["English"] = "Fel Sharpening Stone",
			["French"] = "Pierre à aiguiser gangrée",
			["German"] = "Teuflischer Wetzstein",
			["Korean"] = "지옥의 숫돌",
			["Mexican"] = "Piedra de afilar vil",
			["Portuguese"] = "Pedra de Afiar Vil",
			["Russian"] = "Точило Скверны",
			["Spanish"] = "Piedra de afilar vil",
			["Taiwanese"] = "惡魔磨刀石",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 29656,
		["item_id"] = 23529,
		["items"] = {
			23618,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "精金磨刀石",
			["English"] = "Adamantite Sharpening Stone",
			["French"] = "Pierre à aiguiser adamantine",
			["German"] = "Adamantitwetzstein",
			["Korean"] = "아다만타이트 숫돌",
			["Mexican"] = "Piedra de afilar de adamantita",
			["Portuguese"] = "Pedra de Afiar de Adamantita",
			["Russian"] = "Адамантитовое точило",
			["Spanish"] = "Piedra de afilar de adamantita",
			["Taiwanese"] = "堅鋼磨刀石",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29657,
		["item_id"] = 23530,
		["items"] = {
			23619,
			24002,
		},
		["min_skill"] = 360,
		["name"] = {
			["Chinese"] = "魔钢盾刺",
			["English"] = "Felsteel Shield Spike",
			["French"] = "Pointe de bouclier en gangracier",
			["German"] = "Teufelsstahlschildstachel",
			["Korean"] = "지옥강철 방패 스파이크",
			["Mexican"] = "Punta de escudo de acero vil",
			["Portuguese"] = "Espigão de Escudo de Açovil",
			["Russian"] = "Шип для щита из оскверненной стали",
			["Spanish"] = "Punta de escudo de acero vil",
			["Taiwanese"] = "魔鋼盾刺",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29658,
		["item_id"] = 23531,
		["items"] = {
			23620,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔怒护手",
			["English"] = "Felfury Gauntlets",
			["French"] = "Gantelets gangrefurie",
			["German"] = "Teufelszornstulpen",
			["Korean"] = "격노의 지옥 건틀릿",
			["Mexican"] = "Guanteletes de furia vil",
			["Portuguese"] = "Manoplas Furiavil",
			["Russian"] = "Рукавицы ярости Скверны",
			["Spanish"] = "Guanteletes de furia vil",
			["Taiwanese"] = "魔怒護手",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29662,
		["item_id"] = 23533,
		["items"] = {
			23622,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "钢钳护手",
			["English"] = "Steelgrip Gauntlets",
			["French"] = "Gantelets Poigne-d'acier",
			["German"] = "Stahlgriffstulpen",
			["Korean"] = "강철죔쇠 건틀릿",
			["Mexican"] = "Guanteletes de presacero",
			["Portuguese"] = "Manoplas Punho-de-aço",
			["Russian"] = "Рукавицы стальной хватки",
			["Spanish"] = "Guanteletes de presacero",
			["Taiwanese"] = "鋼握護手",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29663,
		["item_id"] = 23534,
		["items"] = {
			23623,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "风暴头盔",
			["English"] = "Storm Helm",
			["French"] = "Casque tempête",
			["German"] = "Helm des Sturms",
			["Korean"] = "폭풍 투구",
			["Mexican"] = "Yelmo de tormenta",
			["Portuguese"] = "Elmo da Tempestade",
			["Russian"] = "Шлем бури",
			["Spanish"] = "Yelmo de tormenta",
			["Taiwanese"] = "風暴頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29664,
		["item_id"] = 23535,
		["items"] = {
			23624,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "坚定防御者头盔",
			["English"] = "Helm of the Stalwart Defender",
			["French"] = "Heaume du fidèle défenseur",
			["German"] = "Helm des tapferen Verteidigers",
			["Korean"] = "강인한 수호자의 투구",
			["Mexican"] = "Yelmo de adepto defensor",
			["Portuguese"] = "Elmo do Defensor Impávido",
			["Russian"] = "Шлем стойкого защитника",
			["Spanish"] = "Yelmo de adepto defensor",
			["Taiwanese"] = "堅實防衛者頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29668,
		["item_id"] = 23536,
		["items"] = {
			23625,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "誓言守护者头盔",
			["English"] = "Oathkeeper's Helm",
			["French"] = "Casque de la parole donnée",
			["German"] = "Helm der Eidestreue",
			["Korean"] = "굳은 신념의 투구",
			["Mexican"] = "Yelmo de El Guardián del Juramento",
			["Portuguese"] = "Elmo do Guardião do Juramento",
			["Russian"] = "Шлем хранителя клятвы",
			["Spanish"] = "Yelmo de El Guardián del Juramento",
			["Taiwanese"] = "誓言守護者頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29669,
		["item_id"] = 23537,
		["items"] = {
			23626,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "黑色魔钢护腕",
			["English"] = "Black Felsteel Bracers",
			["French"] = "Brassards noirs en gangracier",
			["German"] = "Schwarze Teufelsstahlarmschienen",
			["Korean"] = "검은 지옥강철 팔보호구",
			["Mexican"] = "Brazales de acero vil negros",
			["Portuguese"] = "Braçadeiras de Açovil Pretas",
			["Russian"] = "Черные наручи из оскверненной стали",
			["Spanish"] = "Brazales de acero vil negros",
			["Taiwanese"] = "黑魔鋼護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29671,
		["item_id"] = 23538,
		["items"] = {
			23627,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "绿色要塞护腕",
			["English"] = "Bracers of the Green Fortress",
			["French"] = "Brassards de la forteresse verte",
			["German"] = "Armschienen der grünen Festung",
			["Korean"] = "푸른 요새의 팔보호구",
			["Mexican"] = "Brazales de la Fortaleza Verde",
			["Portuguese"] = "Braçadeiras da Fortaleza Verde",
			["Russian"] = "Наручи зеленой крепости",
			["Spanish"] = "Brazales de la Fortaleza Verde",
			["Taiwanese"] = "綠色堡壘護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29672,
		["item_id"] = 23539,
		["items"] = {
			23628,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "神宠护腕",
			["English"] = "Blessed Bracers",
			["French"] = "Brassards bénis",
			["German"] = "Gesegnete Armschienen",
			["Korean"] = "축복받은 팔보호구",
			["Mexican"] = "Brazales benditos",
			["Portuguese"] = "Braçadeiras Abençoadas",
			["Russian"] = "Благословенные наручи",
			["Spanish"] = "Brazales benditos",
			["Taiwanese"] = "受祝福的護腕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29692,
		["item_id"] = 23540,
		["items"] = {
			23629,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔钢长剑",
			["English"] = "Felsteel Longblade",
			["French"] = "Lame longue en gangracier",
			["German"] = "Teufelsstahllangschwert",
			["Korean"] = "지옥강철 장검",
			["Mexican"] = "Hoja larga de acero vil",
			["Portuguese"] = "Lâmina Longa de Açovil",
			["Russian"] = "Длинный меч из оскверненной стали",
			["Spanish"] = "Hoja larga de acero vil",
			["Taiwanese"] = "魔鋼長刃",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29693,
		["item_id"] = 23541,
		["items"] = {
			23630,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "氪金圣剑",
			["English"] = "Khorium Champion",
			["French"] = "Champion en khorium",
			["German"] = "Khoriumchampion",
			["Korean"] = "용사의 코륨검",
			["Mexican"] = "Campeón de korio",
			["Portuguese"] = "Campeão de Kório",
			["Russian"] = "Кориевый защитник",
			["Spanish"] = "Campeón de korio",
			["Taiwanese"] = "克銀勇士",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29694,
		["item_id"] = 23542,
		["items"] = {
			23631,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔能利斧",
			["English"] = "Fel Edged Battleaxe",
			["French"] = "Hache de bataille à tranchant gangrené",
			["German"] = "Teuflisch scharfe Kampfaxt",
			["Korean"] = "지옥날 전투도끼",
			["Mexican"] = "Hacha de batalla vil afilada",
			["Portuguese"] = "Machado de Batalha Cortevil",
			["Russian"] = "Боевой топор с кромкой Скверны",
			["Spanish"] = "Hacha de batalla vil afilada",
			["Taiwanese"] = "魔鋒戰斧",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29695,
		["item_id"] = 23543,
		["items"] = {
			23632,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔钢斧",
			["English"] = "Felsteel Reaper",
			["French"] = "Faucheuse en gangracier",
			["German"] = "Teufelsstahlschneide",
			["Korean"] = "지옥강철 도끼",
			["Mexican"] = "Segadora de acero vil",
			["Portuguese"] = "Foice de Açovil",
			["Russian"] = "Жнец из оскверненной стали",
			["Spanish"] = "Segadora de acero vil",
			["Taiwanese"] = "魔鋼斧",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29696,
		["item_id"] = 23544,
		["items"] = {
			23633,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "符印战锤",
			["English"] = "Runic Hammer",
			["French"] = "Marteau runique",
			["German"] = "Runenverzierter Hammer",
			["Korean"] = "룬문자 망치",
			["Mexican"] = "Martillo rúnico",
			["Portuguese"] = "Martelo Rúnico",
			["Russian"] = "Рунический молот",
			["Spanish"] = "Martillo rúnico",
			["Taiwanese"] = "符文錘",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29697,
		["item_id"] = 23546,
		["items"] = {
			23634,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "魔能强化战槌",
			["English"] = "Fel Hardened Maul",
			["French"] = "Maillet corrompu durci",
			["German"] = "Teufelsgehärteter Schlägel",
			["Korean"] = "지옥 경화 마울",
			["Mexican"] = "Gran maza vil endurecida",
			["Portuguese"] = "Malho Petrevil",
			["Russian"] = "Закаленная Скверной кувалда",
			["Spanish"] = "Gran maza vil endurecida",
			["Taiwanese"] = "魔鐵強化槌",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29698,
		["item_id"] = 23554,
		["items"] = {
			23635,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "恒金符文之刃",
			["English"] = "Eternium Runed Blade",
			["French"] = "Lame runique en éternium",
			["German"] = "Runenverzierte Eterniumklinge",
			["Korean"] = "이터늄 룬검",
			["Mexican"] = "Hoja rúnica de eternio",
			["Portuguese"] = "Lâmina Rúnica de Etérnio",
			["Russian"] = "Этерниевый рунический клинок",
			["Spanish"] = "Hoja rúnica de eternio",
			["Taiwanese"] = "恆金符文刃",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29699,
		["item_id"] = 23555,
		["items"] = {
			23636,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "挽歌",
			["English"] = "Dirge",
			["French"] = "Complainte",
			["German"] = "Todeslied",
			["Korean"] = "진혼곡",
			["Mexican"] = "Réquiem",
			["Portuguese"] = "Réquiem",
			["Russian"] = "Погребальный Плач",
			["Spanish"] = "Réquiem",
			["Taiwanese"] = "輓歌之刃",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29700,
		["item_id"] = 23556,
		["items"] = {
			23637,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "永恒之手",
			["English"] = "Hand of Eternity",
			["French"] = "Main de l'éternité",
			["German"] = "Hand der Ewigkeit",
			["Korean"] = "영원의 손길",
			["Mexican"] = "Mano de la eternidad",
			["Portuguese"] = "Mão da Eternidade",
			["Russian"] = "Рука Вечности",
			["Spanish"] = "Mano de la eternidad",
			["Taiwanese"] = "永恆之手",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29728,
		["item_id"] = 23575,
		["items"] = {
			23638,
		},
		["min_skill"] = 340,
		["name"] = {
			["Chinese"] = "次级护盾结界",
			["English"] = "Lesser Ward of Shielding",
			["French"] = "Gardien de sauvegarde inférieur",
			["German"] = "Geringer Zauberschutz der Abschirmung",
			["Korean"] = "하급 수호의 보호막",
			["Mexican"] = "Resguardo de escudo inferior",
			["Portuguese"] = "Proteção Inferior de Anteparo",
			["Russian"] = "Простой оберег",
			["Spanish"] = "Resguardo de escudo inferior",
			["Taiwanese"] = "次級護盾護咒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 29729,
		["item_id"] = 23576,
		["items"] = {
			23639,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "强效护盾结界",
			["English"] = "Greater Ward of Shielding",
			["French"] = "Gardien de sauvegade supérieur",
			["German"] = "Großer Zauberschutz der Abschirmung",
			["Korean"] = "상급 수호의 보호막",
			["Mexican"] = "Resguardo de escudo superior",
			["Portuguese"] = "Proteção Maior de Anteparo",
			["Russian"] = "Сильный оберег",
			["Spanish"] = "Resguardo de escudo superior",
			["Taiwanese"] = "強效護盾護咒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32284,
		["item_id"] = 23559,
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "次级结界符文",
			["English"] = "Lesser Rune of Warding",
			["French"] = "Rune de garde inférieure",
			["German"] = "Geringe Rune des Schutzes",
			["Korean"] = "하급 수호의 룬",
			["Mexican"] = "Runa de amparo inferior",
			["Portuguese"] = "Runa Inferior de Proteção",
			["Russian"] = "Простая охранная руна",
			["Spanish"] = "Runa de amparo inferior",
			["Taiwanese"] = "次級結界符文",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 25000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32285,
		["item_id"] = 25521,
		["items"] = {
			25526,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "强效结界符文",
			["English"] = "Greater Rune of Warding",
			["French"] = "Rune de garde supérieure",
			["German"] = "Große Rune des Schutzes",
			["Korean"] = "상급 수호의 룬",
			["Mexican"] = "Runa de amparo superior",
			["Portuguese"] = "Runa Maior de Proteção",
			["Russian"] = "Сильная охранная руна",
			["Spanish"] = "Runa de amparo superior",
			["Taiwanese"] = "強效結界符文",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32655,
		["item_id"] = 25843,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔铁棒",
			["English"] = "Fel Iron Rod",
			["French"] = "Bâtonnet en gangrefer",
			["German"] = "Teufelseisenrute",
			["Korean"] = "지옥무쇠 마법막대",
			["Mexican"] = "Vara de hierro vil",
			["Portuguese"] = "Bastão de Ferrovil",
			["Russian"] = "Жезл из оскверненного железа",
			["Spanish"] = "Vara de hierro vil",
			["Taiwanese"] = "魔鐵棒",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 32656,
		["item_id"] = 25844,
		["items"] = {
			25846,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "精金棒",
			["English"] = "Adamantite Rod",
			["French"] = "Bâtonnet en adamantite",
			["German"] = "Adamantitrute",
			["Korean"] = "아다만타이트 마법막대",
			["Mexican"] = "Vara de adamantita",
			["Portuguese"] = "Bastão de Adamantita",
			["Russian"] = "Адамантитовый жезл",
			["Spanish"] = "Vara de adamantita",
			["Taiwanese"] = "堅鋼魔棒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 32657,
		["item_id"] = 25845,
		["items"] = {
			25847,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "恒金棒",
			["English"] = "Eternium Rod",
			["French"] = "Bâtonnet en éternium",
			["German"] = "Eterniumrute",
			["Korean"] = "이터늄 마법막대",
			["Mexican"] = "Vara de eternio",
			["Portuguese"] = "Bastão de Etérnio",
			["Russian"] = "Этерниевый жезл",
			["Spanish"] = "Vara de eternio",
			["Taiwanese"] = "恆金棒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34529,
		["item_id"] = 23563,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "虚空链衫",
			["English"] = "Nether Chain Shirt",
			["French"] = "Cotte d'anneaux du Néant",
			["German"] = "Netherkettenhemd",
			["Korean"] = "황천의 사슬 조끼",
			["Mexican"] = "Camisa de anillas abisales",
			["Portuguese"] = "Camiseta Encadeada do Éter",
			["Russian"] = "Плетеная рубашка Пустоты",
			["Spanish"] = "Camisa de anillas abisales",
			["Taiwanese"] = "虛空鍊衫",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34530,
		["item_id"] = 23564,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "扭曲虚空链衫",
			["English"] = "Twisting Nether Chain Shirt",
			["French"] = "Cotte d'anneaux du Néant distordu",
			["German"] = "Kettenhemd des wirbelnden Nethers",
			["Korean"] = "뒤틀린 황천의 사슬 조끼",
			["Mexican"] = "Camisa de anillas de El Vacío Abisal",
			["Portuguese"] = "Cota Encadeada da Espiral Etérea",
			["Russian"] = "Плетеная рубашка Круговерти Пустоты",
			["Spanish"] = "Camisa de anillas de El Vacío Abisal",
			["Taiwanese"] = "扭曲虛空鍊衫",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34533,
		["item_id"] = 28483,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "王者胸甲",
			["English"] = "Breastplate of Kings",
			["French"] = "Cuirasse des rois",
			["German"] = "Brustplatte der Könige",
			["Korean"] = "왕의 흉갑",
			["Mexican"] = "Coraza de reyes",
			["Portuguese"] = "Peitoral dos Reis",
			["Russian"] = "Кираса Королей",
			["Spanish"] = "Coraza de reyes",
			["Taiwanese"] = "王者胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34534,
		["item_id"] = 28484,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "王者壁垒",
			["English"] = "Bulwark of Kings",
			["French"] = "Rempart des rois",
			["German"] = "Bollwerk der Könige",
			["Korean"] = "왕의 보루흉갑",
			["Mexican"] = "Baluarte de reyes",
			["Portuguese"] = "Baluarte dos Reis",
			["Russian"] = "Оплот королей",
			["Spanish"] = "Baluarte de reyes",
			["Taiwanese"] = "諸王壁壘",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34535,
		["item_id"] = 28425,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "火焰卫士",
			["English"] = "Fireguard",
			["French"] = "Garde du feu",
			["German"] = "Brandwache",
			["Korean"] = "불꽃의 수호검",
			["Mexican"] = "Guardia de fuego",
			["Portuguese"] = "Flamiguarda",
			["Russian"] = "Огненный страж",
			["Spanish"] = "Guardia de fuego",
			["Taiwanese"] = "火焰衛士",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34537,
		["item_id"] = 28426,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "光芒卫士",
			["English"] = "Blazeguard",
			["French"] = "Brasegarde",
			["German"] = "Lodernder Wächter",
			["Korean"] = "타오르는 수호검",
			["Mexican"] = "Guardia abrasadora",
			["Portuguese"] = "Guarda Infernal",
			["Russian"] = "Пылкий страж",
			["Spanish"] = "Guardia abrasadora",
			["Taiwanese"] = "燃燒守護者",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34538,
		["item_id"] = 28428,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "狮心之刃",
			["English"] = "Lionheart Blade",
			["French"] = "Lame Coeur-de-lion",
			["German"] = "Löwenherzklinge",
			["Korean"] = "사자심장 검",
			["Mexican"] = "Hoja de corazón de león",
			["Portuguese"] = "Lâmina do Coração de Leão",
			["Russian"] = "Клинок львиного сердца",
			["Spanish"] = "Hoja de corazón de león",
			["Taiwanese"] = "獅心之刃",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34540,
		["item_id"] = 28429,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "狮心圣剑",
			["English"] = "Lionheart Champion",
			["French"] = "Championne Coeur-de-lion",
			["German"] = "Löwenherzchampion",
			["Korean"] = "용사의 사자심장 검",
			["Mexican"] = "Campeón corazón de león",
			["Portuguese"] = "Campeão Coração de Leão",
			["Russian"] = "Защитник львиного сердца",
			["Spanish"] = "Campeón corazón de león",
			["Taiwanese"] = "獅心勇士劍",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34541,
		["item_id"] = 28431,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "位面战斧",
			["English"] = "The Planar Edge",
			["French"] = "Tranchant planaire",
			["German"] = "Die Planaraxt",
			["Korean"] = "차원의 도끼",
			["Mexican"] = "El filo bidimensional",
			["Portuguese"] = "O Gume Planar",
			["Russian"] = "Грань Миров",
			["Spanish"] = "El filo bidimensional",
			["Taiwanese"] = "異界之鋒",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34542,
		["item_id"] = 28432,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "黑色位面战斧",
			["English"] = "Black Planar Edge",
			["French"] = "Tranchant planaire noir",
			["German"] = "Schwarze Planaraxt",
			["Korean"] = "검은 차원의 도끼",
			["Mexican"] = "Filo bidimensional negro",
			["Portuguese"] = "Gume Negro Planar",
			["Russian"] = "Черная Грань Миров",
			["Spanish"] = "Filo bidimensional negro",
			["Taiwanese"] = "黑色異界之鋒",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34543,
		["item_id"] = 28434,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "新月",
			["English"] = "Lunar Crescent",
			["French"] = "Croissant lunaire",
			["German"] = "Mondsichel",
			["Korean"] = "초승달 도끼",
			["Mexican"] = "Hacha curva lunar",
			["Portuguese"] = "Lua Crescente",
			["Russian"] = "Лунный Серп",
			["Spanish"] = "Luna creciente",
			["Taiwanese"] = "新月斧",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34544,
		["item_id"] = 28435,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "月牙屠斧",
			["English"] = "Mooncleaver",
			["French"] = "Tranchelune",
			["German"] = "Mondspaltbeil",
			["Korean"] = "달빛 클레버",
			["Mexican"] = "Cortaluna",
			["Portuguese"] = "Fendelua",
			["Russian"] = "Лунный колун",
			["Spanish"] = "Cortaluna",
			["Taiwanese"] = "月光斬斧",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34545,
		["item_id"] = 28437,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "龙拳之锤",
			["English"] = "Drakefist Hammer",
			["French"] = "Marteau poing-de-drake",
			["German"] = "Drachenfaust",
			["Korean"] = "비룡갈퀴 망치",
			["Mexican"] = "Martillo de puñodraco",
			["Portuguese"] = "Martelo de Punhodraco",
			["Russian"] = "Молот Драконьей длани",
			["Spanish"] = "Martillo de puñodraco",
			["Taiwanese"] = "龍拳之錘",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 100000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34546,
		["item_id"] = 28438,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "巨龙之喉",
			["English"] = "Dragonmaw",
			["French"] = "Gueule-de-dragon",
			["German"] = "Drachenmal",
			["Korean"] = "용아귀",
			["Mexican"] = "Faucedraco",
			["Portuguese"] = "Presa do Dragão",
			["Russian"] = "Dragonmaw",
			["Spanish"] = "Faucedraco",
			["Taiwanese"] = "龍喉",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34548,
		["item_id"] = 28441,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "惊雷",
			["English"] = "Deep Thunder",
			["French"] = "Tonnerre-profond",
			["German"] = "Donnergroll",
			["Korean"] = "천둥번개 망치",
			["Mexican"] = "Trueno profundo",
			["Portuguese"] = "Trovão Profundo",
			["Russian"] = "Глубокий Гром",
			["Spanish"] = "Trueno profundo",
			["Taiwanese"] = "深雷",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 250000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34607,
		["item_id"] = 28420,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔能平衡石",
			["English"] = "Fel Weightstone",
			["French"] = "Pierre de lest gangrenée",
			["German"] = "Teufelsgewichtsstein",
			["Korean"] = "지옥 무게추",
			["Mexican"] = "Contrapeso vil",
			["Portuguese"] = "Contrapeso Vil",
			["Russian"] = "Грузило Скверны",
			["Spanish"] = "Contrapeso vil",
			["Taiwanese"] = "惡魔平衡石",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 15000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34608,
		["item_id"] = 28421,
		["items"] = {
			28632,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "精金平衡石",
			["English"] = "Adamantite Weightstone",
			["French"] = "Pierre de lest d'adamantite",
			["German"] = "Adamantitgewichtsstein",
			["Korean"] = "아다만타이트 무게추",
			["Mexican"] = "Contrapeso de adamantita",
			["Portuguese"] = "Contrapeso de Adamantita",
			["Russian"] = "Адамантитовое грузило",
			["Spanish"] = "Contrapeso de adamantita",
			["Taiwanese"] = "堅鋼平衡石",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 34979,
		["item_id"] = 29201,
		["min_skill"] = 100,
		["name"] = {
			["Chinese"] = "厚重青铜飞镖",
			["English"] = "Thick Bronze Darts",
			["French"] = "Fléchettes lourdes en bronze",
			["German"] = "Schwere bronzene Wurfspeere",
			["Korean"] = "두꺼운 청동 창",
			["Mexican"] = "Dardos de bronce gruesos",
			["Portuguese"] = "Dardos de Bronze Grossos",
			["Russian"] = "Утолщенные бронзовые дротики",
			["Spanish"] = "Dardos de bronce gruesos",
			["Taiwanese"] = "厚青銅飛鏢",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 600,
			["sources"] = {
				15400,
				16669,
				4258,
				17245,
				2836,
				3136,
				6299,
				3174,
				3557,
				16823,
				4596,
				2998,
				16724,
				16583,
				3355,
				514,
				5511,
				1241,
				3478,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34981,
		["item_id"] = 29202,
		["min_skill"] = 200,
		["name"] = {
			["Chinese"] = "旋风钢斧",
			["English"] = "Whirling Steel Axes",
			["French"] = "Haches tourbillonnantes en acier",
			["German"] = "Wirbelnde Stahläxte",
			["Korean"] = "소용돌이치는 강철 도끼",
			["Mexican"] = "Hachas giratorias de acero",
			["Portuguese"] = "Machados Giratórios de Aço",
			["Russian"] = "Крутящиеся стальные топоры",
			["Spanish"] = "Hachas giratorias de acero",
			["Taiwanese"] = "旋風鐵斧",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 7500,
			["sources"] = {
				15400,
				16669,
				4258,
				17245,
				2836,
				3136,
				6299,
				3174,
				3557,
				16823,
				4596,
				2998,
				16724,
				16583,
				3355,
				514,
				5511,
				1241,
				3478,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34982,
		["item_id"] = 29203,
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "魔化瑟银飞刀",
			["English"] = "Enchanted Thorium Blades",
			["French"] = "Lames en thorium enchanté",
			["German"] = "Verzauberte Thoriumklingen",
			["Korean"] = "마력 깃든 토륨 나이프",
			["Mexican"] = "Hojas de torio encantado",
			["Portuguese"] = "Lâminas de Tório Encantado",
			["Russian"] = "Зачарованные ториевые клинки",
			["Spanish"] = "Hojas de torio encantado",
			["Taiwanese"] = "附魔瑟銀刃",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				15400,
				16669,
				4258,
				17245,
				2836,
				3136,
				6299,
				3174,
				3557,
				16823,
				4596,
				2998,
				16724,
				16583,
				3355,
				514,
				5511,
				1241,
				3478,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34983,
		["item_id"] = 29204,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "魔钢密语匕首",
			["English"] = "Felsteel Whisper Knives",
			["French"] = "Couteaux de murmure en gangracier",
			["German"] = "Flüsternde Teufelsstahlklingen",
			["Korean"] = "속삭이는 지옥강철 나이프",
			["Mexican"] = "Cuchillos susurrantes de acero vil",
			["Portuguese"] = "Facas Sussurrantes de Açovil",
			["Russian"] = "Шепчущие ножи из оскверненной стали",
			["Spanish"] = "Cuchillos susurrantes de acero vil",
			["Taiwanese"] = "魔鋼耳語小刀",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 50000,
			["sources"] = {
				16823,
				16583,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36122,
		["item_id"] = 30069,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "地铸护腿",
			["English"] = "Earthforged Leggings",
			["French"] = "Jambières de forge-terre",
			["German"] = "Erdgeschmiedete Gamaschen",
			["Korean"] = "대지로 벼려낸 다리보호구",
			["Mexican"] = "Leotardos terraforjados",
			["Portuguese"] = "Perneiras Forjadas em Terra",
			["Russian"] = "Поножи земной кузни",
			["Spanish"] = "Leotardos terraforjados",
			["Taiwanese"] = "地鑄護腿",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36124,
		["item_id"] = 30070,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "风铸护腿",
			["English"] = "Windforged Leggings",
			["French"] = "Jambières de forge-vent",
			["German"] = "Windgeschmiedete Gamaschen",
			["Korean"] = "바람으로 벼려낸 다리보호구",
			["Mexican"] = "Leotardos ventoforjados",
			["Portuguese"] = "Perneiras Forjadas em Vento",
			["Russian"] = "Закаленные ветрами поножи",
			["Spanish"] = "Leotardos ventoforjado",
			["Taiwanese"] = "風冶護腿",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36125,
		["item_id"] = 30071,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "轻型地铸利刃",
			["English"] = "Light Earthforged Blade",
			["French"] = "Lame légère de forge-terre",
			["German"] = "Leichte erdgeschmiedete Klinge",
			["Korean"] = "대지로 벼려낸 검",
			["Mexican"] = "Hoja terraforjada ligera",
			["Portuguese"] = "Lâmina Leve Forjada em Terra",
			["Russian"] = "Легкий клинок земной кузни",
			["Spanish"] = "Hoja terraforjada ligera",
			["Taiwanese"] = "輕地鑄之刃",
		},
		["phase"] = 1,
		["specialisation"] = 9787,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36126,
		["item_id"] = 30072,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "轻型天铸战斧",
			["English"] = "Light Skyforged Axe",
			["French"] = "Hache légère de forge-ciel",
			["German"] = "Leichte himmelsgeschmiedete Axt",
			["Korean"] = "하늘로 벼려낸 도끼",
			["Mexican"] = "Hacha cieloforjada ligera",
			["Portuguese"] = "Machado Leve Forjado em Céu",
			["Russian"] = "Легкий топор небесной кузни",
			["Spanish"] = "Hacha cieloforjada ligera",
			["Taiwanese"] = "空鑄輕斧",
		},
		["phase"] = 1,
		["specialisation"] = 9787,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36128,
		["item_id"] = 30073,
		["min_skill"] = 260,
		["name"] = {
			["Chinese"] = "轻型灰烬铸锤",
			["English"] = "Light Emberforged Hammer",
			["French"] = "Marteau léger de forge-braise",
			["German"] = "Leichter glutgeschmiedeter Hammer",
			["Korean"] = "불꽃으로 벼려낸 망치",
			["Mexican"] = "Martillo ascuaforjado ligero",
			["Portuguese"] = "Martelo Leve Forjado em Brasa",
			["Russian"] = "Легкий углекованный молот",
			["Spanish"] = "Martillo ascuaforjado ligero",
			["Taiwanese"] = "輕煤鑄之錘",
		},
		["phase"] = 1,
		["specialisation"] = 9787,
		["trainers"] = {
			["price"] = 10000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36129,
		["item_id"] = 30074,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "重型地铸胸甲",
			["English"] = "Heavy Earthforged Breastplate",
			["French"] = "Cuirasse lourde de forge-terre",
			["German"] = "Schwere erdgeschmiedete Brustplatte",
			["Korean"] = "대지로 벼려낸 강화 흉갑",
			["Mexican"] = "Coraza terraforjada pesada",
			["Portuguese"] = "Peitoral Forjado em Terra Pesado",
			["Russian"] = "Тяжелая броня земной кузни",
			["Spanish"] = "Coraza terraforjada pesada",
			["Taiwanese"] = "重型地鑄胸甲",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36130,
		["item_id"] = 30076,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "雷铸战甲",
			["English"] = "Stormforged Hauberk",
			["French"] = "Haubert de forge-foudre",
			["German"] = "Sturmgeschmiedete Halsberge",
			["Korean"] = "폭풍으로 벼려낸 흉갑",
			["Mexican"] = "Camisote Tronaforjado",
			["Portuguese"] = "Cota Forjada em Tempestade",
			["Russian"] = "Закаленный бурей хауберк",
			["Spanish"] = "Camisote tronaforjado",
			["Taiwanese"] = "暴風冶煉鍊衫",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36131,
		["item_id"] = 30077,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "风铸轻剑",
			["English"] = "Windforged Rapier",
			["French"] = "Rapière de forge-vent",
			["German"] = "Windgeschmiedetes Rapier",
			["Korean"] = "바람으로 벼려낸 레이피어",
			["Mexican"] = "Estoque ventoforjado",
			["Portuguese"] = "Florete Forjado em Vento",
			["Russian"] = "Закаленная ветрами рапира",
			["Spanish"] = "Estoque ventoforjado",
			["Taiwanese"] = "風冶細劍",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36133,
		["item_id"] = 30086,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "石铸巨剑",
			["English"] = "Stoneforged Claymore",
			["French"] = "Claymore de forge-pierre",
			["German"] = "Steingeschmiedetes Claymore",
			["Korean"] = "돌로 벼려낸 클레이모어",
			["Mexican"] = "Mandoble de forja de piedra",
			["Portuguese"] = "Espadão Forjado em Pedra",
			["Russian"] = "Окованный камнем клеймор",
			["Spanish"] = "Espada claymore de forja de piedra",
			["Taiwanese"] = "石鑄巨刃劍",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36134,
		["item_id"] = 30087,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "雷铸战斧",
			["English"] = "Stormforged Axe",
			["French"] = "Hache de forge-foudre",
			["German"] = "Sturmgeschmiedete Axt",
			["Korean"] = "폭풍으로 벼려낸 도끼",
			["Mexican"] = "Hacha Tronaforjado",
			["Portuguese"] = "Machado Forjado em Tempestade",
			["Russian"] = "Закаленный бурей топор",
			["Spanish"] = "Hacha tronaforjada",
			["Taiwanese"] = "暴風冶煉之斧",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36135,
		["item_id"] = 30088,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "天铸巨斧",
			["English"] = "Skyforged Great Axe",
			["French"] = "Bardiche forge-ciel",
			["German"] = "Himmelsgeschmiedete Großaxt",
			["Korean"] = "하늘로 벼려낸 거대한 도끼",
			["Mexican"] = "Gran hacha cieloforjada",
			["Portuguese"] = "Grande Machado Forjado em Céu",
			["Russian"] = "Большой топор небесной кузни",
			["Spanish"] = "Gran hacha cieloforjada",
			["Taiwanese"] = "空鑄巨斧",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36136,
		["item_id"] = 30089,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "熔铸战锤",
			["English"] = "Lavaforged Warhammer",
			["French"] = "Marteau de guerre de forge-lave",
			["German"] = "Lavageschmiedeter Kriegshammer",
			["Korean"] = "용암으로 벼려낸 전투망치",
			["Mexican"] = "Martillo de guerra lavaforjado",
			["Portuguese"] = "Martelo de Guerra Forjado em Lava",
			["Russian"] = "Закаленный в лаве боевой молот",
			["Spanish"] = "Martillo de guerra lavaforjado",
			["Taiwanese"] = "熔鑄戰錘",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36137,
		["item_id"] = 30093,
		["min_skill"] = 330,
		["name"] = {
			["Chinese"] = "巨型地铸战锤",
			["English"] = "Great Earthforged Hammer",
			["French"] = "Grand marteau de forge-terre",
			["German"] = "Großer erdgeschmiedeter Hammer",
			["Korean"] = "대지로 벼려낸 거대한 망치",
			["Mexican"] = "Gran martillo terraforjado",
			["Portuguese"] = "Grande Martelo Forjado em Terra",
			["Russian"] = "Большой молот земной кузни",
			["Spanish"] = "Gran martillo terraforjado",
			["Taiwanese"] = "大型地鑄戰錘",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 40000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36256,
		["item_id"] = 23565,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "扭曲虚空的拥抱",
			["English"] = "Embrace of the Twisting Nether",
			["French"] = "Etreinte du Néant distordu",
			["German"] = "Umarmung des wirbelnden Nethers",
			["Korean"] = "뒤틀린 황천의 선물",
			["Mexican"] = "Abrazo de El Vacío Abisal",
			["Portuguese"] = "Abraço da Espiral Etérea",
			["Russian"] = "Облачение Круговерти Пустоты",
			["Spanish"] = "Abrazo de El Vacío Abisal",
			["Taiwanese"] = "扭曲虛空之擁",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36257,
		["item_id"] = 28485,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "列王壁垒",
			["English"] = "Bulwark of the Ancient Kings",
			["French"] = "Rempart des anciens rois",
			["German"] = "Bollwerk der uralten Könige",
			["Korean"] = "고대 왕의 보루흉갑",
			["Mexican"] = "Baluarte de los antiguos reyes",
			["Portuguese"] = "Baluarte dos Reis Ancestrais",
			["Russian"] = "Оплот древних королей",
			["Spanish"] = "Baluarte de los antiguos reyes",
			["Taiwanese"] = "遠古諸王壁壘",
		},
		["phase"] = 1,
		["specialisation"] = 9788,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				5164,
				11177,
				7230,
				20125,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36258,
		["item_id"] = 28427,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "光芒之怒",
			["English"] = "Blazefury",
			["French"] = "Brasefurie",
			["German"] = "Lodernder Zorn",
			["Korean"] = "타오르는 격노",
			["Mexican"] = "Furia abrasadora",
			["Portuguese"] = "Ardenfúria",
			["Russian"] = "Пламенное неистовство",
			["Spanish"] = "Furia abrasadora",
			["Taiwanese"] = "燃燒之怒",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36259,
		["item_id"] = 28430,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "狮心斩杀者",
			["English"] = "Lionheart Executioner",
			["French"] = "Exécutrice Coeur-de-lion",
			["German"] = "Löwenherzrichtklinge",
			["Korean"] = "집행의 사자심장 검",
			["Mexican"] = "Verdugo corazón de león",
			["Portuguese"] = "Carrasco Coração de Leão",
			["Russian"] = "Палач львиного сердца",
			["Spanish"] = "Verdugo corazón de león",
			["Taiwanese"] = "獅心斬首者",
		},
		["phase"] = 1,
		["specialisation"] = 17039,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36260,
		["item_id"] = 28433,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "邪恶位面战斧",
			["English"] = "Wicked Edge of the Planes",
			["French"] = "Tranchant cruel des plans",
			["German"] = "Tückische Schneide der Ebenen",
			["Korean"] = "사악한 차원의 도끼",
			["Mexican"] = "Filo despiadado de los planos",
			["Portuguese"] = "Gume Perverso das Planícies",
			["Russian"] = "Гибельный край миров",
			["Spanish"] = "Filo despiadado de los planos",
			["Taiwanese"] = "諸界邪鋒",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36261,
		["item_id"] = 28436,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "血月",
			["English"] = "Bloodmoon",
			["French"] = "Lune sanguine",
			["German"] = "Blutmond",
			["Korean"] = "피의 달",
			["Mexican"] = "Luna de sangre",
			["Portuguese"] = "Sangreluna",
			["Russian"] = "Кровавая луна",
			["Spanish"] = "Luna de sangre",
			["Taiwanese"] = "血月",
		},
		["phase"] = 1,
		["specialisation"] = 17041,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36262,
		["item_id"] = 28439,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "巨龙之击",
			["English"] = "Dragonstrike",
			["French"] = "Frappe de dragon",
			["German"] = "Drachenschlag",
			["Korean"] = "용의 일격",
			["Mexican"] = "Golpe de dragón",
			["Portuguese"] = "Golpe de Dragão",
			["Russian"] = "Удар дракона",
			["Spanish"] = "Golpe de dragón",
			["Taiwanese"] = "龍擊",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36263,
		["item_id"] = 28442,
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "风暴使者",
			["English"] = "Stormherald",
			["French"] = "Héraut de la tempête",
			["German"] = "Bote des Sturms",
			["Korean"] = "폭풍의 전령",
			["Mexican"] = "Heraldo de la tormenta",
			["Portuguese"] = "Arauto da Tormenta",
			["Russian"] = "Штормовестник",
			["Spanish"] = "Heraldo de la tormenta",
			["Taiwanese"] = "風暴信使",
		},
		["phase"] = 1,
		["specialisation"] = 17040,
		["trainers"] = {
			["price"] = 500000,
			["sources"] = {
				11178,
				7232,
				11146,
				7231,
				20124,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 36389,
		["item_id"] = 30034,
		["items"] = {
			30321,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "守护者腰带",
			["English"] = "Belt of the Guardian",
			["French"] = "Ceinture du gardien",
			["German"] = "Gürtel des Wächters",
			["Korean"] = "수호병의 허리띠",
			["Mexican"] = "Cinturón del guardián",
			["Portuguese"] = "Cinto do Guardião",
			["Russian"] = "Пояс хранителя",
			["Spanish"] = "Cinturón del guardián",
			["Taiwanese"] = "守衛者腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36390,
		["item_id"] = 30032,
		["items"] = {
			30322,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "红色战斗腰带",
			["English"] = "Red Belt of Battle",
			["French"] = "Ceinture de bataille rouge",
			["German"] = "Roter Gürtel der Schlacht",
			["Korean"] = "전투의 붉은 허리띠",
			["Mexican"] = "Cinturón de batalla rojo",
			["Portuguese"] = "Cinto Vermelho de Batalha",
			["Russian"] = "Красный пояс битвы",
			["Spanish"] = "Cinturón rojo de batalla",
			["Taiwanese"] = "紅色戰鬥腰帶",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36391,
		["item_id"] = 30033,
		["items"] = {
			30323,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "保卫者战靴",
			["English"] = "Boots of the Protector",
			["French"] = "Bottes du protecteur",
			["German"] = "Stiefel des Beschützers",
			["Korean"] = "파수병의 장화",
			["Mexican"] = "Botas del protector",
			["Portuguese"] = "Botas do Protetor",
			["Russian"] = "Сапоги защитника",
			["Spanish"] = "Botas del protector",
			["Taiwanese"] = "保衛者之靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 36392,
		["item_id"] = 30031,
		["items"] = {
			30324,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "红色浩劫长靴",
			["English"] = "Red Havoc Boots",
			["French"] = "Bottes du tumulte rouges",
			["German"] = "Rote Stiefel der Verwüstung",
			["Korean"] = "붉은 파괴의 장화",
			["Mexican"] = "Botas de caos rojas",
			["Portuguese"] = "Botas Vermelhas da Destruição",
			["Russian"] = "Сапоги красного хаоса",
			["Spanish"] = "Botas de caos rojas",
			["Taiwanese"] = "紅色浩劫戰靴",
		},
		["phase"] = 2,
	},
	{
		["expansion"] = 2,
		["id"] = 38473,
		["item_id"] = 31364,
		["items"] = {
			31390,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "野性卫士胸甲",
			["English"] = "Wildguard Breastplate",
			["French"] = "Cuirasse de la garde fauve",
			["German"] = "Brustplatte der Wildwacht",
			["Korean"] = "야생수호 흉갑",
			["Mexican"] = "Coraza de guardia salvaje",
			["Portuguese"] = "Peitoral Selvaguarda",
			["Russian"] = "Кираса стража леса",
			["Spanish"] = "Coraza de guardia salvaje",
			["Taiwanese"] = "野性看守者胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38475,
		["item_id"] = 31367,
		["items"] = {
			31391,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "野性卫士护腿",
			["English"] = "Wildguard Leggings",
			["French"] = "Jambières de la garde fauve",
			["German"] = "Gamaschen der Wildwacht",
			["Korean"] = "야생수호 다리보호구",
			["Mexican"] = "Leotardos de guardia salvaje",
			["Portuguese"] = "Perneiras Selvaguarda",
			["Russian"] = "Поножи стража леса",
			["Spanish"] = "Leotardos de guardia salvaje",
			["Taiwanese"] = "野性看守者護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38476,
		["item_id"] = 31368,
		["items"] = {
			31392,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "野性卫士头盔",
			["English"] = "Wildguard Helm",
			["French"] = "Heaume de la garde fauve",
			["German"] = "Helm der Wildwacht",
			["Korean"] = "야생수호 투구",
			["Mexican"] = "Yelmo de guardia salvaje",
			["Portuguese"] = "Elmo Selvaguarda",
			["Russian"] = "Шлем стража леса",
			["Spanish"] = "Yelmo de guardia salvaje",
			["Taiwanese"] = "野性看守者頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38477,
		["item_id"] = 31369,
		["items"] = {
			31393,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "寒冰卫士胸甲",
			["English"] = "Iceguard Breastplate",
			["French"] = "Cuirasse de gardeglace",
			["German"] = "Brustplatte der Eiswache",
			["Korean"] = "얼음수호 흉갑",
			["Mexican"] = "Coraza de guardia de hielo",
			["Portuguese"] = "Peitoral Barragelo",
			["Russian"] = "Кираса ледяного стража",
			["Spanish"] = "Coraza de guardia de hielo",
			["Taiwanese"] = "冰霜守衛胸甲",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38478,
		["item_id"] = 31370,
		["items"] = {
			31394,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "寒冰卫士护腿",
			["English"] = "Iceguard Leggings",
			["French"] = "Jambières de gardeglace",
			["German"] = "Gamaschen der Eiswache",
			["Korean"] = "얼음수호 다리보호구",
			["Mexican"] = "Leotardos de guardia de hielo",
			["Portuguese"] = "Perneiras Barragelo",
			["Russian"] = "Поножи ледяного стража",
			["Spanish"] = "Leotardos de guardia de hielo",
			["Taiwanese"] = "冰霜守衛護腿",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38479,
		["item_id"] = 31371,
		["items"] = {
			31395,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "寒冰卫士头盔",
			["English"] = "Iceguard Helm",
			["French"] = "Heaume de gardeglace",
			["German"] = "Helm der Eiswache",
			["Korean"] = "얼음수호 투구",
			["Mexican"] = "Yelmo de guardia de hielo",
			["Portuguese"] = "Elmo Barragelo",
			["Russian"] = "Шлем ледяного стража",
			["Spanish"] = "Yelmo de guardia de hielo",
			["Taiwanese"] = "冰霜守衛頭盔",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 40033,
		["item_id"] = 32402,
		["items"] = {
			32441,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "影钢战靴",
			["English"] = "Shadesteel Sabots",
			["French"] = "Sabots en ombracier",
			["German"] = "Dämmerstahlschuhe",
			["Korean"] = "어둠강철 장화",
			["Mexican"] = "Zuecos de acero de Sombras",
			["Portuguese"] = "Botas Sombradaço",
			["Russian"] = "Тенестальные сабо",
			["Spanish"] = "Zuecos de acero de Sombras",
			["Taiwanese"] = "影堅戰靴",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40034,
		["item_id"] = 32403,
		["items"] = {
			32442,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "影钢护腕",
			["English"] = "Shadesteel Bracers",
			["French"] = "Brassards en ombracier",
			["German"] = "Dämmerstahlarmschienen",
			["Korean"] = "어둠강철 팔보호구",
			["Mexican"] = "Brazales de acero de Sombras",
			["Portuguese"] = "Braçadeiras Sombradaço",
			["Russian"] = "Тенестальные наручи",
			["Spanish"] = "Brazales de acero de Sombras",
			["Taiwanese"] = "影堅護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40035,
		["item_id"] = 32404,
		["items"] = {
			32443,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "影钢腿甲",
			["English"] = "Shadesteel Greaves",
			["French"] = "Grèves en ombracier",
			["German"] = "Dämmerstahlbeinschützer",
			["Korean"] = "어둠강철 경갑",
			["Mexican"] = "Grebas de acero de Sombras",
			["Portuguese"] = "Grevas Sombradaço",
			["Russian"] = "Тенестальные наголенники",
			["Spanish"] = "Grebas de acero de Sombras",
			["Taiwanese"] = "影堅護脛",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 40036,
		["item_id"] = 32401,
		["items"] = {
			32444,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "影钢束带",
			["English"] = "Shadesteel Girdle",
			["French"] = "Ceinturon en ombracier",
			["German"] = "Dämmerstahlgurt",
			["Korean"] = "어둠강철 벨트",
			["Mexican"] = "Faja de acero de Sombras",
			["Portuguese"] = "Cinturão Sombradaço",
			["Russian"] = "Тенестальной ремень",
			["Spanish"] = "Faja de acero de Sombras",
			["Taiwanese"] = "影堅束腰",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41132,
		["item_id"] = 32568,
		["items"] = {
			32736,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "迅钢护腕",
			["English"] = "Swiftsteel Bracers",
			["French"] = "Brassards en vif-acier",
			["German"] = "Flinkstahlarmschienen",
			["Korean"] = "신속의 강철 팔보호구",
			["Mexican"] = "Brazales de acero presto",
			["Portuguese"] = "Braçadeiras de Celeraço",
			["Russian"] = "Наручи из быстростали",
			["Spanish"] = "Brazales de acero presto",
			["Taiwanese"] = "迅鋼護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41133,
		["item_id"] = 32570,
		["items"] = {
			32737,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "迅钢护肩",
			["English"] = "Swiftsteel Shoulders",
			["French"] = "Epaulières en vif-acier",
			["German"] = "Flinkstahlschultern",
			["Korean"] = "신속의 강철 어깨보호구",
			["Mexican"] = "Sobrehombros de acero presto",
			["Portuguese"] = "Omoplatas de Celeraço",
			["Russian"] = "Наплечники из быстростали",
			["Spanish"] = "Sobrehombros de acero presto",
			["Taiwanese"] = "迅鋼護肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41134,
		["item_id"] = 32571,
		["items"] = {
			32738,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "晨光护腕",
			["English"] = "Dawnsteel Bracers",
			["French"] = "Brassards en acier de l'aube",
			["German"] = "Morgenstahlarmschienen",
			["Korean"] = "여명의 강철 팔보호구",
			["Mexican"] = "Brazales albacero",
			["Portuguese"] = "Braçadeiras de Alvoraço",
			["Russian"] = "Наручи рассветной стали",
			["Spanish"] = "Brazales albacero",
			["Taiwanese"] = "黎明鋼鐵護腕",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 41135,
		["item_id"] = 32573,
		["items"] = {
			32739,
		},
		["min_skill"] = 375,
		["name"] = {
			["Chinese"] = "晨钢护肩",
			["English"] = "Dawnsteel Shoulders",
			["French"] = "Epaulières en acier de l'aube",
			["German"] = "Morgenstahlschultern",
			["Korean"] = "여명의 강철 어깨보호구",
			["Mexican"] = "Sobrehombros albacero",
			["Portuguese"] = "Omoplatas de Alvoraço",
			["Russian"] = "Наплечники рассветной стали",
			["Spanish"] = "Sobrehombros albacero",
			["Taiwanese"] = "黎明鋼鐵護肩",
		},
		["phase"] = 3,
	},
	{
		["expansion"] = 2,
		["id"] = 42662,
		["item_id"] = 33173,
		["items"] = {
			33174,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "怒钢护肩",
			["English"] = "Ragesteel Shoulders",
			["French"] = "Epaulières Rage-acier",
			["German"] = "Zornstahlschultern",
			["Korean"] = "분노의 강철 어깨보호구",
			["Mexican"] = "Sobrehombros de acerira",
			["Portuguese"] = "Omoplatas de Furiaço",
			["Russian"] = "Наплечники из яростной стали",
			["Spanish"] = "Sobrehombros de acerira",
			["Taiwanese"] = "怒鋼護肩",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 42688,
		["item_id"] = 33185,
		["items"] = {
			33186,
			35296,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "精金武器链",
			["English"] = "Adamantite Weapon Chain",
			["French"] = "Dragonne en adamantite",
			["German"] = "Adamantitwaffenkette",
			["Korean"] = "아다만타이트 무기 사슬",
			["Mexican"] = "Cadena de adamantita",
			["Portuguese"] = "Corrente de Arma de Adamantita",
			["Russian"] = "Адамантитовая оружейная цепь",
			["Spanish"] = "Cadena de adamantita",
			["Taiwanese"] = "堅鋼武器鍊",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43549,
		["item_id"] = 33791,
		["items"] = {
			33792,
		},
		["min_skill"] = 35,
		["name"] = {
			["Chinese"] = "铜质重剑",
			["English"] = "Heavy Copper Longsword",
			["French"] = "Lourde épée longue en cuivre",
			["German"] = "Schweres Kupferlangschwert",
			["Korean"] = "단단한 구리 장검",
			["Mexican"] = "Tizona de cobre pesada",
			["Portuguese"] = "Espada Longa Pesada de Cobre",
			["Russian"] = "Тяжелый медный длинный меч",
			["Spanish"] = "Tizona de cobre pesada",
			["Taiwanese"] = "重銅長劍",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43846,
		["item_id"] = 32854,
		["items"] = {
			33954,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "正义力量之锤",
			["English"] = "Hammer of Righteous Might",
			["French"] = "Marteau de la puissance pieuse",
			["German"] = "Hammer der rechtschaffenen Macht",
			["Korean"] = "정의로운 힘의 망치",
			["Mexican"] = "Martillo de poderío recto",
			["Portuguese"] = "Martelo do Poder Íntegro",
			["Russian"] = "Молот праведной мощи",
			["Spanish"] = "Martillo de poderío recto",
			["Taiwanese"] = "公正力量之錘",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 46140,
		["item_id"] = 34380,
		["items"] = {
			35208,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "圣日护手",
			["English"] = "Sunblessed Gauntlets",
			["French"] = "Gantelets bénis par le soleil",
			["German"] = "Sonnengesegnete Stulpen",
			["Korean"] = "태양의 축복 건틀릿",
			["Mexican"] = "Guanteletes bendecidos por el sol",
			["Portuguese"] = "Manoplas Abençoadas pelo Sol",
			["Russian"] = "Рукавицы солнечного благословения",
			["Spanish"] = "Guanteletes bendecidos por el sol",
			["Taiwanese"] = "太陽祝福護手",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46141,
		["item_id"] = 34378,
		["items"] = {
			35209,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "硬化氪金拳甲",
			["English"] = "Hard Khorium Battlefists",
			["French"] = "Poings armés en khorium durci",
			["German"] = "Kampffäuste aus Hartkhorium",
			["Korean"] = "단단한 코륨 전투판금 건틀릿",
			["Mexican"] = "Puños de batalla de korio duro",
			["Portuguese"] = "Manápulas de Kório Duro",
			["Russian"] = "Кулачные перчатки из закаленного кория",
			["Spanish"] = "Puños de batalla de korio duro",
			["Taiwanese"] = "特硬克銀戰拳",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46142,
		["item_id"] = 34379,
		["items"] = {
			35210,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "圣日胸甲",
			["English"] = "Sunblessed Breastplate",
			["French"] = "Cuirasse bénie par le soleil",
			["German"] = "Sonnengesegnete Brustplatte",
			["Korean"] = "태양의 축복 흉갑",
			["Mexican"] = "Coraza bendecida por el sol",
			["Portuguese"] = "Peitoral Abençoado pelo Sol",
			["Russian"] = "Кираса солнечного благословения",
			["Spanish"] = "Coraza bendecida por el sol",
			["Taiwanese"] = "太陽祝福胸甲",
		},
		["phase"] = 5,
	},
	{
		["expansion"] = 2,
		["id"] = 46144,
		["item_id"] = 34377,
		["items"] = {
			35211,
		},
		["min_skill"] = 365,
		["name"] = {
			["Chinese"] = "硬化氪金战甲",
			["English"] = "Hard Khorium Battleplate",
			["French"] = "Armure de bataille en khorium durci",
			["German"] = "Kampfplatte aus Hartkhorium",
			["Korean"] = "단단한 코륨 전투판금 흉갑",
			["Mexican"] = "Placa de batalla de korio duro",
			["Portuguese"] = "Loriga de Kório Duro",
			["Russian"] = "Боевой доспех из закаленного кория",
			["Spanish"] = "Placa de batalla de korio duro",
			["Taiwanese"] = "特硬克銀戰甲",
		},
		["phase"] = 5,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Blacksmithing"], skill)
end
