-- ============================================================================
-- RecipeRadar: Core/Localization.lua
-- Multi-language dictionary (10 languages)
-- ============================================================================

local RR = RecipeRadar
RR.L = {}

local locale = GetLocale()

local defaultStrings = {
    ["ADDON_NAME"] = "RecipeRadar",
    ["RECIPES"] = "Recipes",
    ["ALTS"] = "Alts / Twinks",
    ["NPCS"] = "World & NPCs",
    ["OPTIONS"] = "Options",
    ["SEARCH_PLACEHOLDER"] = "Search recipes, items, NPCs...",
    ["MODE_MISSING"] = "Missing",
    ["MODE_KNOWN"] = "Known",
    ["MODE_ALL"] = "All",
    ["ZONE_ANY"] = "Any Zone",
    ["ZONE_CURRENT"] = "Current Zone",
    ["ZONE_LAST"] = "Last Zone",
    ["SOURCE_ALL"] = "All Sources",
    ["SOURCE_TRAINER"] = "Trainer",
    ["SOURCE_VENDOR"] = "Vendor",
    ["SOURCE_QUEST"] = "Quest",
    ["SOURCE_DROP"] = "Mob Drop",
    ["SOURCE_OBJECT"] = "Object / World",
    ["SOURCE_HOLIDAY"] = "Holiday / Seasonal",
    ["TOMTOM_WAYPOINT"] = "TomTom Waypoint",
    ["TOMTOM_ADDED"] = "Added waypoint to %s in %s (%s, %s)",
    ["PROGRESS"] = "Progress",
    ["REAGENTS"] = "Required Materials",
    ["ACQUISITION"] = "Acquisition Source",
    ["ALTS_STATUS"] = "Realm Character Status",
    ["LEARNED"] = "Learned",
    ["REQUIRES_SKILL"] = "Requires %s (%d)",
    ["NO_RECIPES_FOUND"] = "No recipes found matching current filters.",
    ["TOOLTIP_TOGGLE"] = "Left Click: Toggle RecipeRadar tracker",
    ["TOOLTIP_DRAG"] = "Right Drag: Move button position",
    ["TOOLTIP_MINIMAP_DRAG"] = "Left Drag: Move around minimap",
    ["SELECT_A_RECIPE"] = "Select a Recipe",
    ["REQUIRES_PROFESSION"] = "Requires Profession",
    ["NO_MATERIALS"] = "No materials data available.",
    ["SOURCE_DETAILS"] = "Source details",
    ["NO_REAGENTS"] = "No reagents required.",
    ["UNKNOWN_SOURCE"] = "Unknown Source",
    ["TRAINER_LOCATION"] = "Trainer: %s\nLocation: %s (%s, %s)",
    ["VENDOR_LOCATION"] = "Vendor: %s\nLocation: %s (%s, %s)",
    ["DROP_LOCATION"] = "Drop: %s\nLocation: %s (%s, %s)",
    ["QUEST_LOCATION"] = "Quest: %s\nLocation: %s",
    ["NO_ALTS_REALM"] = "No alts on this realm.",
    ["TOMTOM_NOT_INSTALLED"] = "TomTom is not installed! Location: ",
    ["FREE"] = "Free",
    ["LOADED_WELCOME"] = "loaded! Type /rr to open.",
    ["CMD_HELP_HEADER"] = "RecipeRadar Commands:",
    ["CMD_HELP_TOGGLE"] = " - Toggle RecipeRadar window",
    ["CMD_HELP_OPT"] = " - Open options",
    ["CMD_HELP_ALTS"] = " - Open alt character tracker",
    ["CMD_HELP_NPC"] = " - Open NPC / World explorer",
}

local translations = {
    deDE = {
        ["RECIPES"] = "Rezepte",
        ["ALTS"] = "Twinks / Alts",
        ["NPCS"] = "Welt & NPCs",
        ["OPTIONS"] = "Optionen",
        ["SEARCH_PLACEHOLDER"] = "Rezept, Item oder NPC suchen...",
        ["MODE_MISSING"] = "Fehlend",
        ["MODE_KNOWN"] = "Gelernt",
        ["MODE_ALL"] = "Alle",
        ["ZONE_ANY"] = "Alle Zonen",
        ["ZONE_CURRENT"] = "Aktuelle Zone",
        ["ZONE_LAST"] = "Letzte Zone",
        ["SOURCE_ALL"] = "Alle Quellen",
        ["SOURCE_TRAINER"] = "Lehrer",
        ["SOURCE_VENDOR"] = "Händler",
        ["SOURCE_QUEST"] = "Quest",
        ["SOURCE_DROP"] = "Gegner-Beute",
        ["SOURCE_OBJECT"] = "Objekt / Welt",
        ["SOURCE_HOLIDAY"] = "Weltereignis",
        ["TOMTOM_WAYPOINT"] = "TomTom Wegpunkt",
        ["PROGRESS"] = "Fortschritt",
        ["REAGENTS"] = "Benötigte Materialien",
        ["ACQUISITION"] = "Bezugsquelle",
        ["ALTS_STATUS"] = "Twink Status (Dieser Realm)",
        ["LEARNED"] = "Gelernt",
        ["REQUIRES_SKILL"] = "Benötigt %s (%d)",
        ["NO_RECIPES_FOUND"] = "Keine Rezepte für die aktuellen Filter gefunden.",
        ["TOOLTIP_TOGGLE"] = "Linksklick: RecipeRadar öffnen / schließen",
        ["TOOLTIP_DRAG"] = "Rechtsklick + Ziehen: Position verschieben",
        ["TOOLTIP_MINIMAP_DRAG"] = "Linksklick + Ziehen: Um Minimap bewegen",
        ["SELECT_A_RECIPE"] = "Wähle ein Rezept aus",
        ["REQUIRES_PROFESSION"] = "Benötigt Beruf",
        ["NO_MATERIALS"] = "Keine Materialdaten verfügbar.",
        ["SOURCE_DETAILS"] = "Fundort-Details",
        ["NO_REAGENTS"] = "Keine Reagenzien erforderlich.",
        ["UNKNOWN_SOURCE"] = "Unbekannte Quelle",
        ["TRAINER_LOCATION"] = "Lehrer: %s\nStandort: %s (%s, %s)",
        ["VENDOR_LOCATION"] = "Händler: %s\nStandort: %s (%s, %s)",
        ["DROP_LOCATION"] = "Beute von: %s\nStandort: %s (%s, %s)",
        ["QUEST_LOCATION"] = "Quest: %s\nStandort: %s",
        ["NO_ALTS_REALM"] = "Keine Twinks auf diesem Realm.",
        ["TOMTOM_NOT_INSTALLED"] = "TomTom ist nicht installiert! Standort: ",
        ["FREE"] = "Kostenlos",
        ["LOADED_WELCOME"] = "geladen! Gib /rr ein zum Öffnen.",
        ["CMD_HELP_HEADER"] = "RecipeRadar Befehle:",
        ["CMD_HELP_TOGGLE"] = " - RecipeRadar Fenster öffnen/schließen",
        ["CMD_HELP_OPT"] = " - Optionen öffnen",
        ["CMD_HELP_ALTS"] = " - Twink-Übersicht öffnen",
        ["CMD_HELP_NPC"] = " - NPC / Welt-Explorer öffnen",
    },
    frFR = {
        ["RECIPES"] = "Recettes",
        ["ALTS"] = "Personnages",
        ["OPTIONS"] = "Options",
        ["MODE_MISSING"] = "Manquant",
        ["MODE_KNOWN"] = "Connu",
        ["MODE_ALL"] = "Tout",
        ["ZONE_ANY"] = "Toutes les zones",
        ["PROGRESS"] = "Progression",
        ["REAGENTS"] = "Composants requis",
        ["LEARNED"] = "Appris",
    },
    ruRU = {
        ["RECIPES"] = "Рецепты",
        ["ALTS"] = "Твинки",
        ["OPTIONS"] = "Настройки",
        ["MODE_MISSING"] = "Не изучено",
        ["MODE_KNOWN"] = "Изучено",
        ["MODE_ALL"] = "Все",
        ["ZONE_ANY"] = "Любая зона",
        ["PROGRESS"] = "Прогресс",
        ["REAGENTS"] = "Реагенты",
        ["LEARNED"] = "Изучено",
    },
    zhCN = {
        ["RECIPES"] = "配方",
        ["ALTS"] = "小号",
        ["OPTIONS"] = "选项",
        ["MODE_MISSING"] = "未学习",
        ["MODE_KNOWN"] = "已学习",
        ["MODE_ALL"] = "全部",
        ["ZONE_ANY"] = "任意区域",
        ["PROGRESS"] = "进度",
        ["REAGENTS"] = "所需材料",
        ["LEARNED"] = "已学习",
    },
    zhTW = {
        ["RECIPES"] = "配方",
        ["ALTS"] = "分身",
        ["OPTIONS"] = "選項",
        ["MODE_MISSING"] = "未學習",
        ["MODE_KNOWN"] = "已學習",
        ["MODE_ALL"] = "全部",
        ["ZONE_ANY"] = "所有區域",
        ["PROGRESS"] = "進度",
        ["REAGENTS"] = "所需材料",
        ["LEARNED"] = "已學習",
    },
}

-- Metatable fallback to default English strings
local currentLocaleStrings = translations[locale] or {}
setmetatable(RR.L, {
    __index = function(_, key)
        return currentLocaleStrings[key] or defaultStrings[key] or key
    end
})
