-------------------------------------------------------
-- All items (Cooking) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["items"]["Cooking"] then RR_DATA["items"]["Cooking"] = {} end
local tbc_items = 
{
	{
		["expansion"] = 2,
		["id"] = 22647,
		["name"] = {
			["Chinese"] = "食谱：松脆蜘蛛",
			["English"] = "Recipe: Crunchy Spider Surprise",
			["French"] = "Recette : Surprise d'araignée croustillante",
			["German"] = "Rezept: Knusperspinne Surprise",
			["Korean"] = "조리법: 바삭바삭한 거미 튀김",
			["Mexican"] = "Receta: sorpresa de araña crujiente",
			["Portuguese"] = "Receita: Escondidinho Crocante de Aranha",
			["Russian"] = "Рецепт: хрустящий паучий десерт",
			["Spanish"] = "Receta: sorpresa de araña crujiente",
			["Taiwanese"] = "食譜:香脆蜘蛛大餐",
		},
		["phase"] = 1,
		["quality"] = "common",
		["quests"] = {
			9171,
		},
		["vendors"] = {
			["price"] = 400,
			["sources"] = {
				16253,
				18427,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27684,
		["name"] = {
			["Chinese"] = "食谱：美味秃鹫",
			["English"] = "Recipe: Buzzard Bites",
			["French"] = "Recette : Bouchées de busard",
			["German"] = "Rezept: Bussardbissen",
			["Korean"] = "조리법: 독수리 꼬치",
			["Mexican"] = "Receta: pinchito de águila ratonera",
			["Portuguese"] = "Receita: Iscas de Urubu",
			["Russian"] = "Рецепт: закуска из канюка",
			["Spanish"] = "Receta: pinchito de águila ratonera",
			["Taiwanese"] = "食譜:禿鷲便餐",
		},
		["phase"] = 1,
		["quality"] = "common",
		["quests"] = {
			9356,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27685,
		["name"] = {
			["Chinese"] = "食谱：山猫肉排",
			["English"] = "Recipe: Lynx Steak",
			["French"] = "Recette : Steak de lynx",
			["German"] = "Rezept: Luchssteak",
			["Korean"] = "조리법: 스라소니 스테이크",
			["Mexican"] = "Receta: chuleta de lince",
			["Portuguese"] = "Receita: Filé de Lince",
			["Russian"] = "Рецепт: стейк из рысятины",
			["Spanish"] = "Receta: chuleta de lince",
			["Taiwanese"] = "食譜:山貓肉排",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 40,
			["sources"] = {
				16262,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27686,
		["name"] = {
			["Chinese"] = "食谱：月痕鹿腰肉",
			["English"] = "Recipe: Roasted Moongraze Tenderloin",
			["French"] = "Recette : Filet de frôle-lune rôti",
			["German"] = "Rezept: Geröstete Mondweidenlenden",
			["Korean"] = "조리법: 달새김 안심 스테이크",
			["Mexican"] = "Receta: solomillo de venado lunar asado",
			["Portuguese"] = "Receita: Lombo Assado de Pastoluna",
			["Russian"] = "Рецепт: жареная вырезка лунного оленя",
			["Spanish"] = "Receta: solomillo de venado lunar asado",
			["Taiwanese"] = "食譜:燒烤牧月鹿腰肉",
		},
		["phase"] = 1,
		["quality"] = "common",
		["quests"] = {
			9454,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27687,
		["name"] = {
			["Chinese"] = "食谱：美味翅根",
			["English"] = "Recipe: Bat Bites",
			["French"] = "Recette : Bouchées à la chauve-souris",
			["German"] = "Rezept: Fledermausbissen",
			["Korean"] = "조리법: 박쥐 꼬치",
			["Mexican"] = "Receta: pinchitos de murciélago",
			["Portuguese"] = "Receita: Iscas de Morcego",
			["Russian"] = "Рецепт: закуска из летучей мыши",
			["Spanish"] = "Receta: pinchitos de murciélago",
			["Taiwanese"] = "食譜:蝙蝠餐點",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 400,
			["sources"] = {
				16253,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27688,
		["name"] = {
			["Chinese"] = "食谱：掠食者热狗",
			["English"] = "Recipe: Ravager Dog",
			["French"] = "Recette : Croque-ravageur",
			["German"] = "Rezept: Heißer Hetzer",
			["Korean"] = "조리법: 칼날발톱 핫도그",
			["Mexican"] = "Receta: perrito de devastador",
			["Portuguese"] = "Receita: Cachorro-quente de Assolador",
			["Russian"] = "Рецепт: сосиска из мяса опустошителя",
			["Spanish"] = "Receta: perro devastador",
			["Taiwanese"] = "食譜:劫毀熱狗",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 20000,
			["sources"] = {
				16585,
				16826,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27689,
		["name"] = {
			["Chinese"] = "食谱：孢子小吃",
			["English"] = "Recipe: Sporeling Snack",
			["French"] = "Recette : En-cas sporelin",
			["German"] = "Rezept: Sporlingschmaus",
			["Korean"] = "조리법: 스포어링 과자",
			["Mexican"] = "Receta: tentempié de esporino",
			["Portuguese"] = "Receita: Biscoito de Sporeggar",
			["Russian"] = "Рецепт: закуска спорлингов",
			["Spanish"] = "Receta: tentempié de esporino",
			["Taiwanese"] = "食譜:小孢子點心",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 970,
			["level_id"] = 4,
		},
		["vendors"] = {
			["currency"] = 24245,
			["price"] = 25,
			["sources"] = {
				18382,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27690,
		["name"] = {
			["Chinese"] = "食谱：烟熏蜥蜴",
			["English"] = "Recipe: Blackened Basilisk",
			["French"] = "Recette : Basilic noirci",
			["German"] = "Rezept: Schwarzgebratener Basilisk",
			["Korean"] = "조리법: 바실리스크 장작구이",
			["Mexican"] = "Receta: basilisco ennegrecido",
			["Portuguese"] = "Receita: Basilisco Esturricado",
			["Russian"] = "Рецепт: копченый василиск",
			["Spanish"] = "Receta: basilisco ennegrecido",
			["Taiwanese"] = "食譜：煙熏蜥蜴",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				18957,
				19038,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27691,
		["name"] = {
			["Chinese"] = "食谱：烧烤裂蹄牛",
			["English"] = "Recipe: Roasted Clefthoof",
			["French"] = "Recette : Sabot-fourchu rôti",
			["German"] = "Rezept: Gerösteter Grollhuf",
			["Korean"] = "조리법: 갈래발굽 숯불구이",
			["Mexican"] = "Receta: uñagrieta asado",
			["Portuguese"] = "Receita: Fenoceronte Assado",
			["Russian"] = "Рецепт: жареное мясо копытня",
			["Spanish"] = "Receta: uñagrieta asado",
			["Taiwanese"] = "食譜：燒烤裂蹄牛",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				20096,
				20097,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27692,
		["name"] = {
			["Chinese"] = "食谱：迁跃兽汉堡",
			["English"] = "Recipe: Warp Burger",
			["French"] = "Recette : Steak dimensionnel",
			["German"] = "Rezept: Doppelwarper",
			["Korean"] = "조리법: 차원의 버거",
			["Mexican"] = "Receta: hamburguesa de distorsión",
			["Portuguese"] = "Receita: Hambúrguer Estranho",
			["Russian"] = "Рецепт: котлета из прыгуаны",
			["Spanish"] = "Receta: hamburguesa de distorsión",
			["Taiwanese"] = "食譜：遷躍獸漢堡",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				18957,
				19038,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27693,
		["name"] = {
			["Chinese"] = "食谱：塔布肉排",
			["English"] = "Recipe: Talbuk Steak",
			["French"] = "Recette : Steak de talbuk",
			["German"] = "Rezept: Talbuksteak",
			["Korean"] = "조리법: 탈부크 스테이크",
			["Mexican"] = "Receta: chuleta de talbuk",
			["Portuguese"] = "Receita: Bife de Talbuque",
			["Russian"] = "Рецепт: стейк из талбука",
			["Spanish"] = "Receta: chuleta de talbuk",
			["Taiwanese"] = "食譜：塔布肉排",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				20096,
				20097,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27694,
		["name"] = {
			["Chinese"] = "食谱：烟熏鲑鱼",
			["English"] = "Recipe: Blackened Trout",
			["French"] = "Recette : Truite noircie",
			["German"] = "Rezept: Schwarzgebratene Forelle",
			["Korean"] = "조리법: 송어 장작구이",
			["Mexican"] = "Receta: trucha ennegrecida",
			["Portuguese"] = "Receita: Truta Esturricada",
			["Russian"] = "Рецепт: копченая форель",
			["Spanish"] = "Receta: trucha ennegrecida",
			["Taiwanese"] = "食譜：煙熏鲑魚",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 18000,
			["sources"] = {
				18015,
				20028,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27695,
		["name"] = {
			["Chinese"] = "食谱：美味魔尾鱼",
			["English"] = "Recipe: Feltail Delight",
			["French"] = "Recette : Délice de gangre-queue",
			["German"] = "Rezept: Teufelsfinne Supreme",
			["Korean"] = "조리법: 지옥꼬리퉁돔 별미",
			["Mexican"] = "Receta: delicias de colavil",
			["Portuguese"] = "Receita: Delícia de Caudavil",
			["Russian"] = "Рецепт: лакомство из сквернохвоста",
			["Spanish"] = "Receta: delicias de colavil",
			["Taiwanese"] = "食譜：美味魔尾魚",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 20000,
			["sources"] = {
				18011,
				20028,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27696,
		["name"] = {
			["Chinese"] = "食谱：烟熏孢子鱼",
			["English"] = "Recipe: Blackened Sporefish",
			["French"] = "Recette : Poisson-spore noirci",
			["German"] = "Rezept: Schwarzgebratener Sporenfisch",
			["Korean"] = "조리법: 포자물고기 장작구이",
			["Mexican"] = "Receta: pescado con esporas ennegrecido",
			["Portuguese"] = "Receita: Esporoso Esturricado",
			["Russian"] = "Рецепт: копченый спороус",
			["Spanish"] = "Receta: pescado con esporas ennegrecido",
			["Taiwanese"] = "食譜：煙熏孢子魚",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 20000,
			["sources"] = {
				18911,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27697,
		["name"] = {
			["Chinese"] = "食谱：烤泥鱼",
			["English"] = "Recipe: Grilled Mudfish",
			["French"] = "Recette : Eperlan grillé",
			["German"] = "Rezept: Gegrillter Matschflosser",
			["Korean"] = "조리법: 미꾸라지 구이",
			["Mexican"] = "Receta: pezfango a la parrilla",
			["Portuguese"] = "Receita: Muçum Grelhado",
			["Russian"] = "Рецепт: жареная ильница",
			["Spanish"] = "Receta: pezfango a la parrilla",
			["Taiwanese"] = "食譜：烤泥魚",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				20096,
				20097,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27698,
		["name"] = {
			["Chinese"] = "食谱：水煮蓝鱼",
			["English"] = "Recipe: Poached Bluefish",
			["French"] = "Recette : Tassergal poché",
			["German"] = "Rezept: Gedünstete Blauflosse",
			["Korean"] = "조리법: 삶은 게르치",
			["Mexican"] = "Receta: pezazul pochado",
			["Portuguese"] = "Receita: Azulinho Poché",
			["Russian"] = "Рецепт: вареный луфарь",
			["Spanish"] = "Receta: pezazul pochado",
			["Taiwanese"] = "食譜：水煮藍魚",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				20096,
				20097,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27699,
		["name"] = {
			["Chinese"] = "食谱：金色鱼柳",
			["English"] = "Recipe: Golden Fish Sticks",
			["French"] = "Recette : Bâtonnets de poisson doré",
			["German"] = "Rezept: Goldfischstäbchen",
			["Korean"] = "조리법: 황금 어묵",
			["Mexican"] = "Receta: palitos de pez dorado",
			["Portuguese"] = "Receita: Palitinhos de Peixe Dourado",
			["Russian"] = "Рецепт: палочки из золотой рыбки",
			["Spanish"] = "Receta: palitos de pez dorado",
			["Taiwanese"] = "食譜：金色魚柳",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				18960,
				19296,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27700,
		["name"] = {
			["Chinese"] = "食谱：香辣小龙虾",
			["English"] = "Recipe: Spicy Crawdad",
			["French"] = "Recette : Ecrevisse épicée",
			["German"] = "Rezept: Würziger Flusskrebs",
			["Korean"] = "조리법: 매운 가재",
			["Mexican"] = "Receta: cigala picante",
			["Portuguese"] = "Receita: Lagostim Picante",
			["Russian"] = "Рецепт: рак с пряностями",
			["Spanish"] = "Receta: cigala picante",
			["Taiwanese"] = "食譜：香辣小龍蝦",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				18960,
				19296,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 27736,
		["name"] = {
			["Chinese"] = "大师级烹饪教材",
			["English"] = "Master Cookbook",
			["French"] = "Recettes du Maître-queux",
			["German"] = "Meisterkochbuch",
			["Korean"] = "대가의 요리책",
			["Mexican"] = "Libro de cocina de chef",
			["Portuguese"] = "Livro de Receitas do Mestre",
			["Russian"] = "Поварская книга",
			["Spanish"] = "Libro de cocina de chef",
			["Taiwanese"] = "大師級烹饪教材",
		},
		["phase"] = 1,
		["vendors"] = {
			["price"] = 20000,
			["sources"] = {
				18987,
				18988,
				18993,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 30156,
		["name"] = {
			["Chinese"] = "食谱：蚌柳",
			["English"] = "Recipe: Clam Bar",
			["French"] = "Recette : Bâtonnet de palourdes",
			["German"] = "Rezept: Muschelriegel",
			["Korean"] = "조리법: 조개맛살",
			["Mexican"] = "Receta: barrita de almeja",
			["Portuguese"] = "Receita: Barrinha de Marisco",
			["Russian"] = "Рецепт: батончик из мяса моллюска",
			["Spanish"] = "Receta: barrita de almeja",
			["Taiwanese"] = "食譜：蚌柳",
		},
		["phase"] = 1,
		["quality"] = "common",
		["reputation"] = {
			["faction_id"] = 970,
			["level_id"] = 4,
		},
		["vendors"] = {
			["currency"] = 24245,
			["price"] = 1,
			["sources"] = {
				18382,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31674,
		["name"] = {
			["Chinese"] = "食谱：香脆蛇",
			["English"] = "Recipe: Crunchy Serpent",
			["French"] = "Recette : Serpent croustillant",
			["German"] = "Rezept: Knusperschlange",
			["Korean"] = "조리법: 바삭바삭 천둥매 튀김",
			["Mexican"] = "Receta: serpiente crujiente",
			["Portuguese"] = "Receita: Serpente Crocante",
			["Russian"] = "Рецепт: поджаристый змей",
			["Spanish"] = "Receta: serpiente crujiente",
			["Taiwanese"] = "食譜：香脆蛇",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				20916,
				21113,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 31675,
		["name"] = {
			["Chinese"] = "食谱：莫克纳萨肋排",
			["English"] = "Recipe: Mok'Nathal Shortribs",
			["French"] = "Recette : Côtelettes mok'nathal",
			["German"] = "Rezept: Rippchen der Mok'Nathal",
			["Korean"] = "조리법: 모크나탈 갈비",
			["Mexican"] = "Receta: costillitas de Mok'Nathal",
			["Portuguese"] = "Receita: Costelinhas de Mok'Nathal",
			["Russian"] = "Рецепт: ребрышки из Мок'Натала",
			["Spanish"] = "Receta: costillitas de Mok'Nathal",
			["Taiwanese"] = "食譜：莫克納薩肋排",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 30000,
			["sources"] = {
				20916,
				21113,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33869,
		["name"] = {
			["Chinese"] = "食谱：烤血鳞鱼",
			["English"] = "Recipe: Broiled Bloodfin",
			["French"] = "Recette : Aileron-de-sang grillé",
			["German"] = "Rezept: Gebratene Blutflosse",
			["Korean"] = "조리법: 피지느러미 구이",
			["Mexican"] = "Receta: sangraleta a la parrilla",
			["Portuguese"] = "Receita: Pinassangre Grelhado",
			["Russian"] = "Рецепт: зажаренный на открытом огне афиохаракс",
			["Spanish"] = "Receta: sangraleta a la parrilla",
			["Taiwanese"] = "食譜：烤血鱗魚",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["quests"] = {
			11379,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33870,
		["name"] = {
			["Chinese"] = "食谱：骨鱼汤",
			["English"] = "Recipe: Skullfish Soup",
			["French"] = "Recette : Soupe de poisson-crâne",
			["German"] = "Rezept: Schädelfischsuppe",
			["Korean"] = "조리법: 해골물고기 수프",
			["Mexican"] = "Receta: sopa de pez calavera",
			["Portuguese"] = "Receita: Sopa de Kranikola",
			["Russian"] = "Рецепт: суп из рыбы-черепа",
			["Spanish"] = "Receta: sopa de pez calavera",
			["Taiwanese"] = "食譜：骨魚湯",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["quests"] = {
			11379,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33871,
		["name"] = {
			["Chinese"] = "食谱：风暴牛排",
			["English"] = "Recipe: Stormchops",
			["French"] = "Recette : Côtelettes foudroyantes",
			["German"] = "Rezept: Sturmkoteletts",
			["Korean"] = "조리법: 번개구이",
			["Mexican"] = "Receta: costillas de truenos",
			["Portuguese"] = "Receita: Costeletas Tempestuosas",
			["Russian"] = "Рецепт: буреветчина",
			["Spanish"] = "Receta: costillas de truenos",
			["Taiwanese"] = "食譜：風暴牛排",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["quests"] = {
			11379,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33873,
		["name"] = {
			["Chinese"] = "食谱：热辣塔布羊排",
			["English"] = "Recipe: Spicy Hot Talbuk",
			["French"] = "Recette : Talbuk extra piquant",
			["German"] = "Rezept: Feuriger Würztalbuk",
			["Korean"] = "조리법: 매콤한 양념 탈부크 구이",
			["Mexican"] = "Receta: talbuk con guindillas",
			["Portuguese"] = "Receita: Talbuque Apimentado",
			["Russian"] = "Рецепт: острый стейк из талбука",
			["Spanish"] = "Receta: talbuk con guindillas",
			["Taiwanese"] = "食譜：熱辣塔布羊排",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["quests"] = {
			11379,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33875,
		["name"] = {
			["Chinese"] = "食谱：金布勒宠物食品",
			["English"] = "Recipe: Kibler's Bits",
			["French"] = "Recette : Croquettes de Kibler",
			["German"] = "Rezept: Kiblers Häppchen",
			["Korean"] = "조리법: 키블러의 간식",
			["Mexican"] = "Receta: tapitas de Kibler",
			["Portuguese"] = "Receita: Iscas de Kibler",
			["Russian"] = "Рецепт: \"Кит и кот\"",
			["Spanish"] = "Receta: tapitas de Kibler",
			["Taiwanese"] = "食譜：金布勒寵物食品",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["quests"] = {
			11379,
		},
	},
	{
		["expansion"] = 2,
		["id"] = 33925,
		["name"] = {
			["Chinese"] = "食谱：美味巧克力蛋糕",
			["English"] = "Recipe: Delicious Chocolate Cake",
			["French"] = "Recette : Gâteau au chocolat délicieux",
			["German"] = "Rezept: Köstlicher Schokoladenkuchen",
			["Korean"] = "조리법: 맛좋은 초콜릿 케이크",
			["Mexican"] = "Receta: pastel de chocolate delicioso",
			["Portuguese"] = "Receita: Bolo de Chocolate Delicioso",
			["Russian"] = "Рецепт: вкусный шоколадный торт",
			["Spanish"] = "Receta: pastel de chocolate delicioso",
			["Taiwanese"] = "食譜：美味巧克力蛋糕",
		},
		["phase"] = 1,
		["quality"] = "rare",
		["quests"] = {
			11379,
		},
	},
	{
		["expansion"] = 2,
		["holiday"] = 141,
		["id"] = 34413,
		["name"] = {
			["Chinese"] = "食谱：热苹果酒",
			["English"] = "Recipe: Hot Apple Cider",
			["French"] = "Recette : Cidre chaud",
			["German"] = "Rezept: Heißer Apfelwein",
			["Korean"] = "조리법: 따뜻한 사과맛 탄산수",
			["Mexican"] = "Receta: sidra de manzana caliente",
			["Portuguese"] = "Receita: Cidra de Maçã Quente",
			["Russian"] = "Рецепт: горячий яблочный сидр",
			["Spanish"] = "Receta: sidra de manzana caliente",
			["Taiwanese"] = "食譜:熱蘋果酒",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["vendors"] = {
			["price"] = 10000,
			["sources"] = {
				13420,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 34834,
		["name"] = {
			["Chinese"] = "食谱：拉姆瑟船长的特酿啤酒",
			["English"] = "Recipe: Captain Rumsey's Lager",
			["French"] = "Recette : Brune du capitaine Rumsey",
			["German"] = "Rezept: Kapitän Rumseys Lagerbier",
			["Korean"] = "조리법: 럼지 선장의 맥주",
			["Mexican"] = "Receta: cerveza del capitán Rumsey",
			["Portuguese"] = "Receita: Lager do Capitão Rumsey",
			["Russian"] = "Рецепт: светлое пиво капитана Ромси",
			["Spanish"] = "Receta: cerveza del capitán Rumsey",
			["Taiwanese"] = "食譜:蘭姆西船長的淡啤酒",
		},
		["phase"] = 1,
		["quality"] = "uncommon",
		["quests"] = {
			11665,
		},
		["special_action"] = "random reward",
	},
	{
		["expansion"] = 2,
		["id"] = 35564,
		["name"] = {
			["Chinese"] = "食谱：熊肉串烧",
			["English"] = "Recipe: Charred Bear Kabobs",
			["French"] = "Recette : Kébab d'ours grillé",
			["German"] = "Rezept: Verkohlter Bärenkebap",
			["Korean"] = "조리법: 곰 갈빗살 꼬치구이",
			["Mexican"] = "Receta: kebab de oso carbonizado",
			["Portuguese"] = "Receita: Kebab Torrado de Urso",
			["Russian"] = "Рецепт: кебаб из медвежатины на углях",
			["Spanish"] = "Receta: kebab de oso carbonizado",
			["Taiwanese"] = "食譜:燒烤熊肉串",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 18000,
			["sources"] = {
				2803,
				2806,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 35566,
		["name"] = {
			["Chinese"] = "食谱：多汁熊肉汉堡",
			["English"] = "Recipe: Juicy Bear Burger",
			["French"] = "Recette : Steak d'ours juteux",
			["German"] = "Rezept: Saftiger Bärenburger",
			["Korean"] = "조리법: 맛있는 곰 갈빗살 버거",
			["Mexican"] = "Receta: hamburguesa de oso jugosa",
			["Portuguese"] = "Receita: Hamburgurso Suculento",
			["Russian"] = "Рецепт: сочная котлета из медвежатины",
			["Spanish"] = "Receta: hamburguesa de oso jugosa",
			["Taiwanese"] = "食譜:多汁熊排堡",
		},
		["phase"] = 1,
		["quality"] = "common",
		["vendors"] = {
			["price"] = 18000,
			["sources"] = {
				2803,
				2806,
			},
		},
	},
}

for _, item in ipairs(tbc_items) do
	table.insert(RR_DATA["items"]["Cooking"], item)
end
