-------------------------------------------------------
-- All skills (Cooking) - The Burning Crusade Delta
-------------------------------------------------------
if not RR_DATA["skills"]["Cooking"] then RR_DATA["skills"]["Cooking"] = {} end
local tbc_skills = 
{
	{
		["expansion"] = 2,
		["id"] = 25704,
		["item_id"] = 21072,
		["items"] = {
			21099,
		},
		["min_skill"] = 80,
		["name"] = {
			["Chinese"] = "烤鼠尾鱼",
			["English"] = "Smoked Sagefish",
			["French"] = "Sagerelle fumée",
			["German"] = "Geräucherter Weisenfisch",
			["Korean"] = "훈제 총명어",
			["Mexican"] = "Sabiola ahumada",
			["Portuguese"] = "Sabichão Defumado",
			["Russian"] = "Копченый шалфокунь",
			["Spanish"] = "Sabiola ahumada",
			["Taiwanese"] = "烤鼠尾魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 25954,
		["item_id"] = 21217,
		["items"] = {
			21219,
		},
		["min_skill"] = 175,
		["name"] = {
			["Chinese"] = "美味鼠尾鱼",
			["English"] = "Sagefish Delight",
			["French"] = "Délice de sagerelle",
			["German"] = "Weisenfisch Supreme",
			["Korean"] = "총명어 별미",
			["Mexican"] = "Delicia de sabiola",
			["Portuguese"] = "Delícia de Sabichão",
			["Russian"] = "Деликатес из шалфокуня",
			["Spanish"] = "Delicia de sabiola",
			["Taiwanese"] = "美味鼠尾魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 28267,
		["item_id"] = 22645,
		["items"] = {
			22647,
		},
		["min_skill"] = 60,
		["name"] = {
			["Chinese"] = "松脆蜘蛛",
			["English"] = "Crunchy Spider Surprise",
			["French"] = "Surprise d'araignée croustillante",
			["German"] = "Knusperspinne Surprise",
			["Korean"] = "바삭바삭한 거미 튀김",
			["Mexican"] = "Sorpresa de araña crujiente",
			["Portuguese"] = "Escondidinho Crocante de Aranha",
			["Russian"] = "Хрустящий паучий десерт",
			["Spanish"] = "Sorpresa de araña crujiente",
			["Taiwanese"] = "香脆蜘蛛大餐",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33276,
		["item_id"] = 27635,
		["items"] = {
			27685,
		},
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "山猫肉排",
			["English"] = "Lynx Steak",
			["French"] = "Steak de lynx",
			["German"] = "Luchssteak",
			["Korean"] = "스라소니 스테이크",
			["Mexican"] = "Chuleta de lince",
			["Portuguese"] = "Filé de Lince",
			["Russian"] = "Стейк из рысятины",
			["Spanish"] = "Chuleta de lince",
			["Taiwanese"] = "山貓肉排",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33277,
		["item_id"] = 24105,
		["items"] = {
			27686,
		},
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "月痕鹿腰肉",
			["English"] = "Roasted Moongraze Tenderloin",
			["French"] = "Filet de frôle-lune rôti",
			["German"] = "Geröstete Mondweidenlenden",
			["Korean"] = "달새김 안심 스테이크",
			["Mexican"] = "Solomillo de venado lunar asado",
			["Portuguese"] = "Lombo Assado de Pastoluna",
			["Russian"] = "Жареная вырезка лунного оленя",
			["Spanish"] = "Solomillo de venado lunar asado",
			["Taiwanese"] = "燒烤牧月鹿腰肉",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33278,
		["item_id"] = 27636,
		["items"] = {
			27687,
		},
		["min_skill"] = 50,
		["name"] = {
			["Chinese"] = "美味翅根",
			["English"] = "Bat Bites",
			["French"] = "Bouchées à la chauve-souris",
			["German"] = "Fledermausbissen",
			["Korean"] = "박쥐 꼬치",
			["Mexican"] = "Pinchitos de murciélago",
			["Portuguese"] = "Iscas de Morcego",
			["Russian"] = "Закуска из летучей мыши",
			["Spanish"] = "Pinchitos de murciélago",
			["Taiwanese"] = "蝙蝠餐點",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33279,
		["item_id"] = 27651,
		["items"] = {
			27684,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "美味秃鹫",
			["English"] = "Buzzard Bites",
			["French"] = "Bouchées de busard",
			["German"] = "Bussardbissen",
			["Korean"] = "독수리 꼬치",
			["Mexican"] = "Pinchito de águila ratonera",
			["Portuguese"] = "Iscas de Urubu",
			["Russian"] = "Закуска из канюка",
			["Spanish"] = "Pinchito de águila ratonera",
			["Taiwanese"] = "禿鷲便餐",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33284,
		["item_id"] = 27655,
		["items"] = {
			27688,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "掠食者热狗",
			["English"] = "Ravager Dog",
			["French"] = "Croque-ravageur",
			["German"] = "Heißer Hetzer",
			["Korean"] = "칼날발톱 핫도그",
			["Mexican"] = "Perrito de devastador",
			["Portuguese"] = "Cachorro-quente de Assolador",
			["Russian"] = "Сосиска из мяса опустошителя",
			["Spanish"] = "Perro devastador",
			["Taiwanese"] = "劫毀熱狗",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33285,
		["item_id"] = 27656,
		["items"] = {
			27689,
		},
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "孢子小吃",
			["English"] = "Sporeling Snack",
			["French"] = "En-cas sporelin",
			["German"] = "Sporlingschmaus",
			["Korean"] = "스포어링 과자",
			["Mexican"] = "Tentempié de esporino",
			["Portuguese"] = "Biscoito de Sporeggar",
			["Russian"] = "Закуска спорлингов",
			["Spanish"] = "Tentempié de esporino",
			["Taiwanese"] = "小孢子點心",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33286,
		["item_id"] = 27657,
		["items"] = {
			27690,
		},
		["min_skill"] = 315,
		["name"] = {
			["Chinese"] = "烟熏蜥蜴",
			["English"] = "Blackened Basilisk",
			["French"] = "Basilic noirci",
			["German"] = "Schwarzgebratener Basilisk",
			["Korean"] = "바실리스크 장작구이",
			["Mexican"] = "Basilisco ennegrecido",
			["Portuguese"] = "Basilisco Esturricado",
			["Russian"] = "Почерневший василиск",
			["Spanish"] = "Basilisco ennegrecido",
			["Taiwanese"] = "煙熏蜥蜴",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33287,
		["item_id"] = 27658,
		["items"] = {
			27691,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "烧烤裂蹄牛",
			["English"] = "Roasted Clefthoof",
			["French"] = "Sabot-fourchu rôti",
			["German"] = "Gerösteter Grollhuf",
			["Korean"] = "갈래발굽 숯불구이",
			["Mexican"] = "Uñagrieta asado",
			["Portuguese"] = "Fenoceronte Assado",
			["Russian"] = "Жареное мясо копытня",
			["Spanish"] = "Uñagrieta asado",
			["Taiwanese"] = "燒烤裂蹄牛",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33288,
		["item_id"] = 27659,
		["items"] = {
			27692,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "迁跃兽汉堡",
			["English"] = "Warp Burger",
			["French"] = "Steak dimensionnel",
			["German"] = "Doppelwarper",
			["Korean"] = "차원의 버거",
			["Mexican"] = "Hamburguesa de distorsión",
			["Portuguese"] = "Hambúrguer Estranho",
			["Russian"] = "Котлета из прыгуаны",
			["Spanish"] = "Hamburguesa de distorsión",
			["Taiwanese"] = "遷躍獸漢堡",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33289,
		["item_id"] = 27660,
		["items"] = {
			27693,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "塔布肉排",
			["English"] = "Talbuk Steak",
			["French"] = "Steak de talbuk",
			["German"] = "Talbuksteak",
			["Korean"] = "탈부크 스테이크",
			["Mexican"] = "Chuleta de talbuk",
			["Portuguese"] = "Bife de Talbuque",
			["Russian"] = "Стейк из талбука",
			["Spanish"] = "Chuleta de talbuk",
			["Taiwanese"] = "塔布肉排",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33290,
		["item_id"] = 27661,
		["items"] = {
			27694,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "烟熏鲑鱼",
			["English"] = "Blackened Trout",
			["French"] = "Truite noircie",
			["German"] = "Schwarzgebratene Forelle",
			["Korean"] = "송어 장작구이",
			["Mexican"] = "Trucha ennegrecida",
			["Portuguese"] = "Truta Esturricada",
			["Russian"] = "Копченая форель",
			["Spanish"] = "Trucha ennegrecida",
			["Taiwanese"] = "煙熏鲑魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33291,
		["item_id"] = 27662,
		["items"] = {
			27695,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "美味魔尾鱼",
			["English"] = "Feltail Delight",
			["French"] = "Délice de gangre-queue",
			["German"] = "Teufelsfinne Supreme",
			["Korean"] = "지옥꼬리퉁돔 별미",
			["Mexican"] = "Delicias de colavil",
			["Portuguese"] = "Delícia de Caudavil",
			["Russian"] = "Лакомство из сквернохвоста",
			["Spanish"] = "Delicias de colavil",
			["Taiwanese"] = "美味魔尾魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33292,
		["item_id"] = 27663,
		["items"] = {
			27696,
		},
		["min_skill"] = 310,
		["name"] = {
			["Chinese"] = "烟熏孢子鱼",
			["English"] = "Blackened Sporefish",
			["French"] = "Poisson-spore noirci",
			["German"] = "Schwarzgebratener Sporenfisch",
			["Korean"] = "포자물고기 장작구이",
			["Mexican"] = "Pescado con esporas ennegrecido",
			["Portuguese"] = "Esporoso Esturricado",
			["Russian"] = "Копченый спороус",
			["Spanish"] = "Pescado con esporas ennegrecido",
			["Taiwanese"] = "煙熏孢子魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33293,
		["item_id"] = 27664,
		["items"] = {
			27697,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "烤泥鱼",
			["English"] = "Grilled Mudfish",
			["French"] = "Eperlan grillé",
			["German"] = "Gegrillter Matschflosser",
			["Korean"] = "미꾸라지 구이",
			["Mexican"] = "Pezfango a la parrilla",
			["Portuguese"] = "Muçum Grelhado",
			["Russian"] = "Жареная ильница",
			["Spanish"] = "Pezfango a la parrilla",
			["Taiwanese"] = "烤泥魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33294,
		["item_id"] = 27665,
		["items"] = {
			27698,
		},
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "水煮蓝鱼",
			["English"] = "Poached Bluefish",
			["French"] = "Tassergal poché",
			["German"] = "Gedünstete Blauflosse",
			["Korean"] = "삶은 게르치",
			["Mexican"] = "Pezazul pochado",
			["Portuguese"] = "Azulinho Poché",
			["Russian"] = "Вареный луфарь",
			["Spanish"] = "Pezazul pochado",
			["Taiwanese"] = "水煮藍魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33295,
		["item_id"] = 27666,
		["items"] = {
			27699,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "金色鱼柳",
			["English"] = "Golden Fish Sticks",
			["French"] = "Bâtonnets de poisson doré",
			["German"] = "Goldfischstäbchen",
			["Korean"] = "황금 어묵",
			["Mexican"] = "Palitos de pez dorado",
			["Portuguese"] = "Palitinhos de Peixe Dourado",
			["Russian"] = "Палочки из золотой рыбки",
			["Spanish"] = "Palitos de pez dorado",
			["Taiwanese"] = "金色魚柳",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 33296,
		["item_id"] = 27667,
		["items"] = {
			27700,
		},
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "香辣小龙虾",
			["English"] = "Spicy Crawdad",
			["French"] = "Ecrevisse épicée",
			["German"] = "Würziger Flusskrebs",
			["Korean"] = "매운 가재",
			["Mexican"] = "Cigala picante",
			["Portuguese"] = "Lagostim Picante",
			["Russian"] = "Рак с пряностями",
			["Spanish"] = "Cigala picante",
			["Taiwanese"] = "香辣小龍蝦",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 36210,
		["item_id"] = 30155,
		["items"] = {
			30156,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "蚌柳",
			["English"] = "Clam Bar",
			["French"] = "Bâtonnet de palourdes",
			["German"] = "Muschelriegel",
			["Korean"] = "조개맛살",
			["Mexican"] = "Barrita de almeja",
			["Portuguese"] = "Barrinha de Marisco",
			["Russian"] = "Батончик из мяса моллюска",
			["Spanish"] = "Barrita de almeja",
			["Taiwanese"] = "蚌柳",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 37836,
		["item_id"] = 30816,
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "香料面包",
			["English"] = "Spice Bread",
			["French"] = "Pain épicé",
			["German"] = "Gewürzbrot",
			["Korean"] = "매콤한 빵",
			["Mexican"] = "Pan con especias",
			["Portuguese"] = "Pão de Especiarias",
			["Russian"] = "Хлеб с пряностями",
			["Spanish"] = "Pan con especias",
			["Taiwanese"] = "香料面包",
		},
		["phase"] = 1,
		["trainers"] = {
			["price"] = 10,
			["sources"] = {
				17246,
				4210,
				3026,
				18988,
				19369,
				1355,
				3087,
				5159,
				8306,
				4552,
				18987,
				1699,
				19185,
				16253,
				1382,
				16719,
				18993,
				3067,
				16277,
				5482,
				16676,
				1430,
				3399,
				6286,
			},
		},
	},
	{
		["expansion"] = 2,
		["id"] = 38867,
		["item_id"] = 31672,
		["items"] = {
			31675,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "莫克纳萨肋排",
			["English"] = "Mok'Nathal Shortribs",
			["French"] = "Côtelettes mok'nathal",
			["German"] = "Rippchen der Mok'Nathal",
			["Korean"] = "모크나탈 갈비",
			["Mexican"] = "Costillitas de Mok'Nathal",
			["Portuguese"] = "Costelinhas de Mok'nathal",
			["Russian"] = "Ребрышки из Мок'Натала",
			["Spanish"] = "Costillitas de Mok'Nathal",
			["Taiwanese"] = "莫克納薩肋排",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 38868,
		["item_id"] = 31673,
		["items"] = {
			31674,
		},
		["min_skill"] = 335,
		["name"] = {
			["Chinese"] = "香脆蛇",
			["English"] = "Crunchy Serpent",
			["French"] = "Serpent croustillant",
			["German"] = "Knusperschlange",
			["Korean"] = "바삭바삭 천둥매 튀김",
			["Mexican"] = "Serpiente crujiente",
			["Portuguese"] = "Serpente Crocante",
			["Russian"] = "Поджаристый змей",
			["Spanish"] = "Serpiente crujiente",
			["Taiwanese"] = "香脆蛇",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 42296,
		["item_id"] = 33048,
		["min_skill"] = 320,
		["name"] = {
			["Chinese"] = "炖鲑鱼",
			["English"] = "Stewed Trout",
			["French"] = "Fricassée de truite",
			["German"] = "Gedämpfte Forelle",
			["Korean"] = "송어 매운탕",
			["Mexican"] = "Estofado de trucha",
			["Portuguese"] = "Truta Ensopada",
			["Russian"] = "Тушеная форель",
			["Spanish"] = "Estofado de trucha",
			["Taiwanese"] = "炖鲑魚",
		},
		["phase"] = 4,
		["trainers"] = {
			["price"] = 60000,
			["sources"] = {
				19186,
			}
		}
	},
	{
		["expansion"] = 2,
		["id"] = 42302,
		["item_id"] = 33052,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "渔夫的美味",
			["English"] = "Fisherman's Feast",
			["French"] = "Festin du pêcheur",
			["German"] = "Fischerschmaus",
			["Korean"] = "낚시꾼의 별미",
			["Mexican"] = "Festín de pescador",
			["Portuguese"] = "Banquete do Pescador",
			["Russian"] = "Рыбацкая услада",
			["Spanish"] = "Festín de pescador",
			["Taiwanese"] = "漁夫的美味",
		},
		["phase"] = 4,
		["trainers"] = {
			["price"] = 60000,
			["sources"] = {
				19186,
			}
		}
	},
	{
		["expansion"] = 2,
		["id"] = 42305,
		["item_id"] = 33053,
		["min_skill"] = 350,
		["name"] = {
			["Chinese"] = "黄油鲑鱼",
			["English"] = "Hot Buttered Trout",
			["French"] = "Truite au beurre blanc",
			["German"] = "Heiße Forelle in Butter",
			["Korean"] = "송어 버터 구이",
			["Mexican"] = "Trucha con mantequilla caliente",
			["Portuguese"] = "Truta Grelhada na Manteiga",
			["Russian"] = "Жареная форель",
			["Spanish"] = "Trucha con mantequilla caliente",
			["Taiwanese"] = "黃油鲑魚",
		},
		["phase"] = 4,
		["trainers"] = {
			["price"] = 60000,
			["sources"] = {
				19186,
			}
		}
	},
	{
		["expansion"] = 2,
		["id"] = 43707,
		["item_id"] = 33825,
		["items"] = {
			33870,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "骨鱼汤",
			["English"] = "Skullfish Soup",
			["French"] = "Soupe de poisson-crâne",
			["German"] = "Schädelfischsuppe",
			["Korean"] = "해골물고기 수프",
			["Mexican"] = "Sopa de pez calavera",
			["Portuguese"] = "Sopa de Kranikola",
			["Russian"] = "Суп из рыбы-черепа",
			["Spanish"] = "Sopa de pez calavera",
			["Taiwanese"] = "骨魚湯",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43758,
		["item_id"] = 33866,
		["items"] = {
			33871,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "风暴牛排",
			["English"] = "Stormchops",
			["French"] = "Côtelettes foudroyantes",
			["German"] = "Sturmkoteletts",
			["Korean"] = "번개구이",
			["Mexican"] = "Costillas de truenos",
			["Portuguese"] = "Costeletas Tempestuosas",
			["Russian"] = "Буреветчина",
			["Spanish"] = "Costillas de truenos",
			["Taiwanese"] = "風暴牛排",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43761,
		["item_id"] = 33867,
		["items"] = {
			33869,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "烤血鳞鱼",
			["English"] = "Broiled Bloodfin",
			["French"] = "Aileron-de-sang grillé",
			["German"] = "Gebratene Blutflosse",
			["Korean"] = "피지느러미 구이",
			["Mexican"] = "Sangraleta a la parrilla",
			["Portuguese"] = "Pinassangre Grelhado",
			["Russian"] = "Зажаренный на открытом огне афиохаракс",
			["Spanish"] = "Sangraleta a la parrilla",
			["Taiwanese"] = "烤血鱗魚",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43765,
		["item_id"] = 33872,
		["items"] = {
			33873,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "热辣塔布羊排",
			["English"] = "Spicy Hot Talbuk",
			["French"] = "Talbuk extra piquant",
			["German"] = "Feuriger Würztalbuk",
			["Korean"] = "매콤한 양념 탈부크 구이",
			["Mexican"] = "Talbuk con guindillas",
			["Portuguese"] = "Talbuque Apimentado",
			["Russian"] = "Острый стейк из талбука",
			["Spanish"] = "Talbuk con guindillas",
			["Taiwanese"] = "熱辣塔布羊排",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43772,
		["item_id"] = 33874,
		["items"] = {
			33875,
		},
		["min_skill"] = 300,
		["name"] = {
			["Chinese"] = "金布勒宠物食品",
			["English"] = "Kibler's Bits",
			["French"] = "Croquettes de Kibler",
			["German"] = "Kiblers Häppchen",
			["Korean"] = "키블러의 간식",
			["Mexican"] = "Tapitas de Kibler",
			["Portuguese"] = "Iscas de Kibler",
			["Russian"] = "\"Кит и кот\"",
			["Spanish"] = "Tapitas de Kibler",
			["Taiwanese"] = "金布勒寵物食品",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 43779,
		["item_id"] = 33924,
		["items"] = {
			33925,
		},
		["min_skill"] = 1,
		["name"] = {
			["Chinese"] = "美味巧克力蛋糕",
			["English"] = "Delicious Chocolate Cake",
			["French"] = "Gâteau au chocolat délicieux",
			["German"] = "Köstlicher Schokoladenkuchen",
			["Korean"] = "맛좋은 초콜릿 케이크",
			["Mexican"] = "Pastel de chocolate delicioso",
			["Portuguese"] = "Bolo de Chocolate Delicioso",
			["Russian"] = "Вкусный шоколадный торт",
			["Spanish"] = "Pastel de chocolate delicioso",
			["Taiwanese"] = "美味巧克力蛋糕",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 45022,
		["item_id"] = 34411,
		["items"] = {
			34413,
		},
		["min_skill"] = 325,
		["name"] = {
			["Chinese"] = "苹果热酒",
			["English"] = "Hot Apple Cider",
			["French"] = "Cidre chaud",
			["German"] = "Heißer Apfelwein",
			["Korean"] = "따뜻한 사과맛 탄산수",
			["Mexican"] = "Sidra de manzana caliente",
			["Portuguese"] = "Cidra de Maçã Quente",
			["Russian"] = "Горячий яблочный сидр",
			["Spanish"] = "Sidra de manzana caliente",
			["Taiwanese"] = "蘋果熱酒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 45695,
		["item_id"] = 34832,
		["items"] = {
			34834,
		},
		["min_skill"] = 100,
		["name"] = {
			["Chinese"] = "拉姆瑟船长的特酿啤酒",
			["English"] = "Captain Rumsey's Lager",
			["French"] = "Brune du capitaine Rumsey",
			["German"] = "Kapitän Rumseys Lagerbier",
			["Korean"] = "럼지 선장의 맥주",
			["Mexican"] = "Cerveza del capitán",
			["Portuguese"] = "Lager do Capitão Rumsey",
			["Russian"] = "Светлое пиво капитана Ромси",
			["Spanish"] = "Cerveza del capitán",
			["Taiwanese"] = "拉姆瑟船長的特釀啤酒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 2,
		["id"] = 46684,
		["item_id"] = 35563,
		["items"] = {
			35564,
		},
		["min_skill"] = 250,
		["name"] = {
			["Chinese"] = "熊肉串烧",
			["English"] = "Charred Bear Kabobs",
			["French"] = "Kébab d'ours grillé",
			["German"] = "Verkohlter Bärenkebap",
			["Korean"] = "곰 갈빗살 꼬치구이",
			["Mexican"] = "Kebab de oso carbonizado",
			["Portuguese"] = "Kebab Torrado de Urso",
			["Russian"] = "Кебаб из медвежатины на углях",
			["Spanish"] = "Kebab de oso carbonizado",
			["Taiwanese"] = "熊肉串燒",
		},
		["phase"] = 1,
	},
	{
		["expansion"] = 1,
		["id"] = 46688,
		["item_id"] = 35565,
		["items"] = {
			35566,
		},
		["min_skill"] = 250,
		["name"] = {
			["Chinese"] = "多汁熊肉汉堡",
			["English"] = "Juicy Bear Burger",
			["French"] = "Steak d'ours juteux",
			["German"] = "Saftiger Bärenburger",
			["Korean"] = "맛있는 곰 갈빗살 버거",
			["Mexican"] = "Hamburguesa de oso jugosa",
			["Portuguese"] = "Hamburgurso Suculento",
			["Russian"] = "Сочная котлета из медвежатины",
			["Spanish"] = "Hamburguesa de oso jugosa",
			["Taiwanese"] = "多汁熊排堡",
		},
		["phase"] = 1,
	},
}

for _, skill in ipairs(tbc_skills) do
	table.insert(RR_DATA["skills"]["Cooking"], skill)
end
